src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <externalId>true</externalId>
        <label>AccountID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a self-relationship field used to link SubAccounts(recType) to the respective MembershipAccounts(recType)</description>
        <label>Parent Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Brand Code BC01=Chevron Federal Credit Union, BC02=Spectrum Credit Union</description>
        <label>Reference</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <description>This record type will be used to store all the Membership Accounts</description>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <label>AccountID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <formula>Account_Number__r.RecType__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonAccount__c</fullName>
        <externalId>true</externalId>
        <label>PersonAccount</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Person_ID_Number__c</fullName>
        <formula>PersonID__r.PersonID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Person ID Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/CaseMemberNameChange.cls
public without sharing class CaseMemberNameChange {
    
    		@AuraEnabled 				
			public static List<object> GetMemberNameList(String Caseid)
			{
				Boolean Iseligible = false;
				List<object> listObj = new List<object>(); 
				List<GroupMember> GroupMemberList = new List<GroupMember>();
				user CurrentUser = [Select Id, UserRoleId,Email,ForecastEnabled ,Alias, Managerid  from user where id = :UserInfo.getUserId() LIMIT 1];
				
				
				
				GroupMemberList = [SELECT GroupId,Id,UserOrGroupId, Group.Type FROM GroupMember where  Group.Name='CaseMemberNameChange'];
				
				for(GroupMember gm : GroupMemberList)
				{
					if(gm.UserOrGroupId == CurrentUser.id )
					{
						Iseligible = true;
					}
					
				}
				List<boolean> eligible = new List<boolean>();
				eligible.add(Iseligible);
				listObj.add(eligible);
				List<Person_Account__c> PersonAccountlist = new List<Person_Account__c>();	
				Set<Id> PersonAccountId = new Set<Id>();						
				if(Iseligible == true)
				{
					Case cs = new Case();
					cs = [SELECT AccountId,Account_Number__c, Account_Number__r.Name ,CaseNumber , id, Account_Number__r.id FROM Case where id =:Caseid];
					list<Person_Account__c> paList = new list<Person_Account__c>();
					
				    	/*Account_Details__c accDetails = [Select Parent_Account__c,RecType__c,RecordType.Name from Account_Details__c where Id=:cs.Account_Number__c Limit 1];
				    	List<string> listStringIds = new List<string>();
				    	listStringIds.add(cs.Account_Number__c);
				    	if(accDetails.Parent_Account__c != null)
				    	{
				    		listStringIds.add(accDetails.Parent_Account__c);
				    		List<Account_Details__c> accDetailsList = [Select Parent_Account__c,RecType__c,RecordType.Name from Account_Details__c where Parent_Account__c=:accDetails.Parent_Account__c];
				    		for(Account_Details__c item: accDetailsList )
				    		{
				    			
				    			listStringIds.add(item.id);
				    		}
				    	}
				    	else
					    {
					    	List<Account_Details__c> accDetailsList = [Select Parent_Account__c,RecType__c,RecordType.Name from Account_Details__c where Parent_Account__c=:accDetails.Id];
				    		for(Account_Details__c item: accDetailsList )
				    		{
				    			
				    			listStringIds.add(item.id);
				    		}
					    }*/
				    	paList = [SELECT Id,
				                          Account_Number__c,
				                          PersonId__c,
				                          PersonID__r.Name,
				                          TypeTranslate__c FROM Person_Account__c WHERE Account_Number__r.Name =: cs.Account_Number__r.Name and TypeTranslate__c !=: '0004/Beneficiary'];
				    	
				    	
				    	AggregateResult[] groupedResults
						  = [SELECT 
				                          PersonId__c,
				                          PersonID__r.Name acctName,
				                          TypeTranslate__c FROM Person_Account__c WHERE Account_Number__r.Name =: cs.Account_Number__r.Name  and TypeTranslate__c !=: '0004/Beneficiary' group by PersonId__c,PersonID__r.Name,TypeTranslate__c ];
				    	list<Person_Account__c> paList1 = new list<Person_Account__c>();
				    	for (AggregateResult ar : groupedResults)  {
				    		Person_Account__c item = new Person_Account__c();
				    		item.PersonId__c = (string)ar.get('PersonId__c');
				    		item.PersonID__r = new Account();
				    		item.PersonID__r.Name = (string)ar.get('acctName');
				    		item.TypeTranslate__c = (string)ar.get('TypeTranslate__c');
				    		paList1.add(item);
						}
				    	
				    	//return paList1;
					
					 list<Account> accList = new list<Account>();
					/*Case cs = new Case();
					cs = [SELECT AccountId,Account_Number__c, Account_Number__r.Name ,CaseNumber , id, Account_Number__r.id FROM Case where id =:Caseid];
					List<Account_Details__c> acc = [Select Id,
                      Name,
                      Brand__c,
                      RecType__c,
                      Reference__c, Parent_Account__r.Name,Parent_Account__c,RecordType.Name FROM Account_Details__c Where Id=:cs.Account_Number__c limit 1];
                       list<Person_Account__c> paList = new list<Person_Account__c>();
				         if(acc[0].RecordType.Name == 'Membership'){
				        	if(acc[0].Parent_Account__r.Name != null)
				        	{
				        		string pid;
				        		pid	= acc[0].Parent_Account__c;
				            	paList = [SELECT Id,Account_Number__c, PersonID__c, Account_Number__r.RecType__c,Account_Number__r.Name,PersonID__r.Name,TypeTranslate__c FROM Person_Account__c WHERE Account_Number__c =:acc[0].id or Account_Number__c=:pid];
				        	}
				        	else
				        	{
				        		paList = [SELECT Id,Account_Number__c, PersonID__c, Account_Number__r.RecType__c,Account_Number__r.Name,PersonID__r.Name,TypeTranslate__c FROM Person_Account__c WHERE Account_Number__c =:acc[0].id];
				        	}
				        }
				        else
				        {
				        	string accId1;
				        	if(acc[0].Parent_Account__r.Name != null){
				              accId1 = acc[0].Parent_Account__c;
				              paList = [SELECT Id,
				                             Account_Number__c, 
				                             PersonID__c,
				                             Account_Number__r.RecType__c, 
				                             Account_Number__r.Name,
				                             PersonID__r.Name,
				                             RecType__c,
				                             TypeTranslate__c FROM Person_Account__c WHERE Account_Number__c =:cs.Account_Number__c OR Account_Number__c =:accId1];
				            }else{
				            	paList = [SELECT Id,
				                             Account_Number__c, 
				                             PersonID__c,
				                             Account_Number__r.RecType__c, 
				                             Account_Number__r.Name,
				                             PersonID__r.Name,
				                             RecType__c,
				                             TypeTranslate__c FROM Person_Account__c WHERE Account_Number__c =:cs.Account_Number__c];
				            }
				        }
                    	system.debug('ABC1233##');
				        system.debug('paList##'+paList);
                    	system.debug('ABC##');*/
				         set<String> accountNumberSet = new set<String>();
				        set<Id> accIdset = new set<Id>();
				        set<String> acctypeSet = new set<String>();
				        
				        for(Person_Account__c var: paList1)
				        {
				            accountNumberSet.add(var.PersonID__r.Name);
				            acctypeSet.add(var.Account_Number__r.RecType__c);
				            accIdSet.add(var.PersonID__c);
				        }
				        
        
        			system.debug('accIdset##'+accIdset);
			           accList = [Select Id,Name FROM Account Where Id IN:accIdSet];
                        system.debug('Without Membership##'+accList);
       					   
				        if(!accList.IsEmpty())
						{    
				       	  listObj.add(accList); 	
						}
				}
			            
          			
						
					
				
				
				system.debug('List of Object'+listObj);
				
				return listObj;
									
			/*	if(Iseligible == true)
				{
					Case cs = new Case();
					cs = [SELECT AccountId,Account_Number__c, Account_Number__r.Name ,CaseNumber , id, Account_Number__r.id FROM Case where id =:Caseid];
					
					PersonAccountlist = [SELECT AccountID__c,Account_Number__c,Account_Type__c,Id,PersonAccount__c,PersonID__c, Person_ID_Number__c 
										FROM Person_Account__c where Account_Number__c =: cs.Account_Number__c];
					for(Person_Account__c pa:PersonAccountlist )
					{
						PersonAccountId.add(pa.PersonID__c);
					}
					List<Account> actname = new List<Account>();
					system.debug('PersonAccountId##'+PersonAccountId);
					actname = [Select id, Name from Account where id IN:PersonAccountId ];
					system.debug('actname##'+actname);
					if(!actname.IsEmpty())
					{
						listObj.add(actname);
					}
				}*/
			
			}
			
			@AuraEnabled 				
			public static void UpdateCase(String Caseid, String Memberid)
			{
				Case cs = new Case();
				cs = [SELECT AccountId,Account_Number__c, Account_Number__r.Name ,CaseNumber , id, Account_Number__r.id FROM Case where id =:Caseid];
				cs.AccountId = Memberid;
				update cs;
				
			}
			
}