src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <externalId>true</externalId>
        <label>AccountID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Branch__c</fullName>
        <label>Current Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <label>AccountID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UpdateAccountMemberBranchTest.cls
@isTest 
public class UpdateAccountMemberBranchTest
{
    static testMethod void testMethod1() 
    {
        Account acc = new Account();
        acc.name = 'Test';
        insert acc;
        
        List<Account_Details__c> listAD = new List<Account_Details__c>();
        for(Integer i=0 ;i <200;i++)
        {
            Account_Details__c accDetail = new Account_Details__c();
            accDetail.Name='Number'+i;
            accDetail.Current_Branch__c = 15;
            accDetail.RecType__c = 'ACCT';
            listAD.add(accDetail);
        }
        
        insert listAD;
        
        Person_Account__c PA = new Person_Account__c();
        PA.Account_Number__c = listAD[0].Id;
        PA.AccountID__c = acc.Id;
        
        insert PA;
        
        Test.startTest();

            UpdateAccountMemberBranch  updateBranch = new UpdateAccountMemberBranch ();
            DataBase.executeBatch(updateBranch); 
            
        Test.stopTest();
    }
}