src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used for member needs assessments eligibility</description>
        <label>NA Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEAV_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEAV_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEEM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEEM_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to show if the NA Housing section is considered complete (TRUE) or partial (FALSE)</description>
        <label>NA LEHS Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMD_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMD_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMP_Complete</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_01_CODE__c</fullName>
        <label>Warning 01 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Card</fullName>
        <active>true</active>
        <description>This record type will be used to store all the CARD Information</description>
        <label>Card</label>
    </recordTypes>
    <recordTypes>
        <fullName>Mortgage</fullName>
        <active>true</active>
        <description>This record type will be used to store all the Mortgage Information</description>
        <label>Mortgage</label>
    </recordTypes>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Source__c</fullName>
        <label>Event Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event – Oakland City Center Meet and Greet 12/06/17</fullName>
                </value>
                <value>
                    <fullName>Event – San Francisco Plaza Event 11/30/17</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Contractor Safety Meeting-12/07/17</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Brock New Hire Orientation-01/05/18</fullName>
                </value>
                <value>
                    <fullName>Event-Richmond-Pinole Valley Juniors Fundraiser-01/07/18</fullName>
                </value>
                <value>
                    <fullName>Event-El Paso-Contractor Visit-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-1600 Smith Houston-Lunch and Learn-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Chevron Retiree Luncheon-01/23/18</fullName>
                </value>
                <value>
                    <fullName>Event-Post Oak Houston-Briarpark Atrium Event-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-El Paso-Lobby Event-02/02/18</fullName>
                </value>
                <value>
                    <fullName>Event-Post Oak Houston-Stewart Legacy Event-01/25/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Meet and Greet-01/30/18</fullName>
                </value>
                <value>
                    <fullName>Event-Reston-Open House-01/31/18</fullName>
                </value>
                <value>
                    <fullName>Event-Houston Galleria-Lobby Event-02/07/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Contractor New Hire Orientation-01/19/18</fullName>
                </value>
                <value>
                    <fullName>Event-Covington-Meet and Greet-01/31/18</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_did_you_hear_about_us__c</fullName>
        <label>How did you hear about us?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yahoo Ad</fullName>
                </value>
                <value>
                    <fullName>Google Ad</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Subtype__c</fullName>
        <label>Product Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Mortgage</fullName>
                </value>
                <value>
                    <fullName>2nd Mortgage</fullName>
                </value>
                <value>
                    <fullName>90 Day Note-Unsecured</fullName>
                </value>
                <value>
                    <fullName>ARM 1/1</fullName>
                </value>
                <value>
                    <fullName>ARM 10/1</fullName>
                </value>
                <value>
                    <fullName>ARM 3/1</fullName>
                </value>
                <value>
                    <fullName>ARM 3/3</fullName>
                </value>
                <value>
                    <fullName>ARM 5/1</fullName>
                </value>
                <value>
                    <fullName>ARM 5/5</fullName>
                </value>
                <value>
                    <fullName>ARM 7/1</fullName>
                </value>
                <value>
                    <fullName>ATM Card</fullName>
                </value>
                <value>
                    <fullName>Auto - Liberty</fullName>
                </value>
                <value>
                    <fullName>Auto - New</fullName>
                </value>
                <value>
                    <fullName>Auto Refinance</fullName>
                </value>
                <value>
                    <fullName>Auto -Used</fullName>
                </value>
                <value>
                    <fullName>Balance Transfer</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Bridging</fullName>
                </value>
                <value>
                    <fullName>Business Development SEG</fullName>
                </value>
                <value>
                    <fullName>CFCU Company Guaranteed</fullName>
                </value>
                <value>
                    <fullName>CFCU Disaster Assistance-Level 3</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Credit Card in Repayment</fullName>
                </value>
                <value>
                    <fullName>Credit Cards</fullName>
                </value>
                <value>
                    <fullName>Credit Protection</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Debt Consolidation</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>DPA Interest Only HELOC</fullName>
                </value>
                <value>
                    <fullName>DPA Texan HELOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/ContentDocumentLinkDeleteTest.cls
@isTest
public class ContentDocumentLinkDeleteTest {
    public static testmethod void Test_getData(){
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Penguins',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;  
    	
        List<Account_Details__c> account_details_Obj = new List<Account_Details__c>{
            new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC'),
                new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC'),
                new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'CARD', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC')};
                    
                    
        Insert account_details_Obj;
		
      Lead ld = new Lead ();
      ld.LastName = 'Test';
      ld.Email = 'test@gmail.com';
      ld.Product_Type__c = 'Misc';
      ld.Brand__c = 'Chevron';
      ld.FirstName = 'test';
      ld.LastName = 'New';    
      ld.MiddleName = 'New';
      ld.Description = 'New';
      ld.Salutation = 'MR.';
      ld.Suffix = 'MR'; 
      ld.Status = 'New';
      ld.Phone= '1234567890';
      ld.Email='test@test.com';
      ld.MobilePhone='1234567892';
      ld.How_did_you_hear_about_us__c='Website';
      ld.Event_Source__c='Event-Reston-Open House-04/20/18';
      ld.LeadSource='BDO-Realtor Referral';
      ld.Product_Type__c ='Mortgage';
      ld.Product_Subtype__c='Purchase';
      ld.Street_Address_1__c='Address 1';
      ld.State__c= 'NY';
      ld.Zip_Code__c= '12345';
      ld.City__c='NYC';
      ld.Country__c ='USA';    
      insert ld;
        
      ContentVersion content=new ContentVersion(); 
      content.Title='Header_Picture1'; 
      content.PathOnClient='/' + content.Title + '.jpg'; 
      Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
      content.VersionData=bodyBlob; 
      //content.LinkedEntityId=sub.id;
      content.origin = 'H';
      insert content;  
    
      ContentDocumentLink contentlink=new ContentDocumentLink();
      contentlink.LinkedEntityId=ld.id;
      contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
      contentlink.ShareType = 'V';
      insert contentlink;  
      
      Test.startTest();
      ld.Status = 'Closed - Converted';  
      update ld;		
    		
      Account account_Obj = new Account(LastName = 'BANDATest', FirstName = 'MARIATest', Type = 'null', PersonHasOptedOutOfEmail = false, NA_Eligibility__c = false, NA_LEAV_Complete__c = true, NA_LECF_Complete__c = true, NA_LECP_Complete__c = true, NA_LEEM_Complete__c = true, NA_LEHS_Complete__c = true, NA_LEMD_Complete__c = false, NA_LEMP_Complete__c = false, NA_LEMQ_Complete__c = true, NA_LEOL_Complete__c = true, NA_LEOM_Complete__c = true, NA_LEPT_Complete__c = true, NA_LESB_Complete__c = false, NA_LESF_Complete__c = true, NA_LEWS_Complete__c = true, NA_Opt_Out__c = false, smagicinteract__SMSOptOut__pc = false, et4ae5__HasOptedOutOfMobile__pc = false);
      Insert account_Obj; 
    
    Account_Details__c obj = [select id from Account_Details__c limit 1];
    
    	List<Person_Account__c> person_obj= new List<Person_Account__c>{new Person_Account__c(Account_Number__c = obj.Id, PersonID__c = account_Obj.Id), new Person_Account__c(Account_Number__c = account_details_Obj[1].Id, PersonID__c = account_Obj.Id), new Person_Account__c(Account_Number__c = account_details_Obj[2].Id, PersonID__c = account_Obj.Id)};
		     Insert person_obj;
		     
		Account account_Obj1 = new Account(LastName = 'BANDATest1', FirstName = 'MARIATest1', Type = 'null', PersonHasOptedOutOfEmail = false, NA_Eligibility__c = false, NA_LEAV_Complete__c = true, NA_LECF_Complete__c = true, NA_LECP_Complete__c = true, NA_LEEM_Complete__c = true, NA_LEHS_Complete__c = true, NA_LEMD_Complete__c = false, NA_LEMP_Complete__c = false, NA_LEMQ_Complete__c = true, NA_LEOL_Complete__c = true, NA_LEOM_Complete__c = true, NA_LEPT_Complete__c = true, NA_LESB_Complete__c = false, NA_LESF_Complete__c = true, NA_LEWS_Complete__c = true, NA_Opt_Out__c = false, smagicinteract__SMSOptOut__pc = false, et4ae5__HasOptedOutOfMobile__pc = false);
    Insert account_Obj1; 
    		
		List<Case> case_Obj = new List<Case>{
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj.Id, Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false)
		    
                };                
				    Insert case_Obj;
    	
    	
    Approve_Attachment__c ap = new Approve_Attachment__c();
		ap.Attachment_Name__c = 'test';
		ap.Case_ID__c = case_Obj[0].id;
		insert ap;
		
		ContentDocumentLink cdl = new ContentDocumentLink();
			cdl.ContentDocumentId = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: contentVersion.Id].ContentDocumentId;
			cdl.LinkedEntityId = ap.id;
			cdl.ShareType = 'V';
			insert cdl;
			

		ap.ContentDocumentLinkId__c = cdl.id;
    	update ap;
    	
    	delete cdl;
    	test.stopTest();
    }
}