src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ownership_Log__c.object
<CustomObject>
    <description>Creates a log that is automatically populated each time a case changes ownership.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related Case Number</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Ownership Log</relationshipLabel>
        <relationshipName>Ownership_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <label>Owner</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Sequence</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Ownership Log</label>
    <nameField>
        <displayFormat>COSL{000000000}</displayFormat>
        <label>Ownership Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownership Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Staging/src/main/default/classes/CaseClosedLogTest.cls
@isTest
private class CaseClosedLogTest {

    static testMethod void testMethod1() {
    
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Account acc = new Account(
           RecordTypeID=RecTypeId,
           FirstName='Test FName',
           LastName='Test LName',
           PersonMailingStreet='test@yahoo.com',
           PersonMailingPostalCode='12345',
           PersonMailingCity='SFO',
           PersonEmail='test@yahoo.com',
           PersonHomePhone='1234567',
           PersonMobilePhone='12345678');

        
        insert acc;
        
          Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
        insert accDetails;       
        
    
    
    Case c1 = new Case( Status = 'New' );
  
    c1.Status = 'Open';
    c1.Account_Number__c = accDetails.id;
    c1.ownerid= UserInfo.getUserId();
    test.startTest();
      insert( c1 ); 
      
      c1.Status = 'Closed';
      
      update C1;
      
      List<user> objUser = [select id from User limit 1];
      
      system.debug('objUser---' + objUser);
      c1.OwnerId = objuser[0].id;
      
      update c1; 
       c1.OwnerId = UserInfo.getUserId();
       c1.Status = 'Open';
      
      update C1;
      
      c1.OwnerId = objuser[0].id;
       c1.Status = 'Open';
       update C1;
       
        c1.OwnerId = UserInfo.getUserId();
       c1.Status = 'Closed';
       update C1;
       
        List<Ownership_Log__c> listOwnerShip = [select Id,Case__c,Owner__c,Sequence__c from Ownership_Log__c]; 
        
        System.debug('listOwnerShip---' + listOwnerShip);
        
        test.stopTest();
 
    }
}