src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsMarkDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkRead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkSaved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkSaved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MemberCommentCount__c</fullName>
        <label>MemberCommentCount</label>
        <summaryFilterItems>
            <field>Member_Comment__c.Draft__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Member_Comment__c.Case__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Member_Number__c</fullName>
        <label>Member Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Comment__c.object
<CustomObject>
    <description>Comments intended to be visible to the member</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Member Comments</relationshipLabel>
        <relationshipName>Member_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkRead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if the member has read the comment</description>
        <label>Member Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Member Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Comment__c</fullName>
        <label>Member Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member_Number__c</fullName>
        <formula>Case__r.Account_Number__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Member Number</label>
        <type>Text</type>
    </fields>
    <label>Member Comment</label>
    <nameField>
        <displayFormat>MCOM{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/classes/DigitalBankingAPIForBadgeCount.cls
@RestResource(urlMapping = '/DigitalBankingAPIForBadgeCount/*')
global class DigitalBankingAPIForBadgeCount{
	
    @HttpPOST
    global static Map<String,Integer> getUnreadCaseCount() {
        
        RestRequest req = RestContext.request;
        system.debug('req'+req);
             
        String strMemberNumber = req.params.get('SSN');
        system.debug('strMemberNumber: '+strMemberNumber);
        String FinalAccNum;
        String loanAPI;
        Set<Id> parentcaseId = new Set<Id>();
        Set<string> MemberCommentAccountNumber = new Set<string>();
        
        Map<String,Integer> responseObjList = new Map<String,Integer>();
        
        ACH_To_Episys_API_Details__c api = ACH_To_Episys_API_Details__c.getValues('ProductionURL');
                
        if(api.URL__c != null){
            loanAPI = api.URL__c;
        }
        
        if(strMemberNumber.length() == 9){
           
            HttpRequest req1 = new HttpRequest();
            HttpResponse res1;
            Http http1 = new Http();
            string responseBody1;
            string AuthrorizedAccountString = '';
            
            req1.setEndpoint(loanAPI + '/MemberAuthorization/GetAuthorizedAccounts?ssn=' + strMemberNumber);
            req1.setMethod('GET');
            
            if(!Test.isRunningTest()){                       
                res1 = http1.send(req1);
                responseBody1 = res1.getBody();                
            }
            else{
                responseBody1 = '{"Accounts":"0000000123,0000000256"}';
            }
            
            system.debug('responseBody1: '+responseBody1);
            
            if(responseBody1 != ''){
                map<string, object> jsonParsed = (map<string, object>)JSON.deserializeUntyped(responseBody1);
                system.debug('jsonParsed=='+jsonParsed);
                AuthrorizedAccountString = (string)jsonParsed.get('Accounts');
            }
                
            List<String> lstAccounts = AuthrorizedAccountString.split(',');
            Set<String> setAccounts = new Set<String>(lstAccounts);
            
            system.debug('lstAccounts: '+lstAccounts);    
            
            List<Case> AllCases = [SELECT Id, Account_Number__r.Name FROM case 
                                          where IsMarkDeleted__c = false and IsMarkSaved__c = false and
                                          MemberCommentCount__c > 0 and 
                                          Account_Number__r.Name in :lstAccounts and 
                                          CreatedDate >= LAST_N_MONTHS:18];
            for(integer i =0 ; i < AllCases.size(); i ++)
			{				
				parentcaseId.Add(AllCases[i].Id);
			}
            
            List<Member_Comment__c> AllUnreadCommentsforCase = [SELECT Case__r.Id, CreatedDate,Id,Member_Comment__c,Name, IsRead__c, Member_Number__c FROM Member_Comment__c Where Case__r.Id IN : parentcaseId and draft__c != true and IsRead__c = false order by CreatedDate desc];
			system.debug('AllUnreadCommentsforCase: '+AllUnreadCommentsforCase); 
            
            for(Member_Comment__c mc: AllUnreadCommentsforCase){
                MemberCommentAccountNumber.add(mc.Member_Number__c);
            }
            for(AggregateResult aggRes : [SELECT COUNT(ID) totalunread, Account_Number__r.Name accnum FROM case 
                                          where IsMarkRead__c = false and IsMarkDeleted__c = false and IsMarkSaved__c = false and
                                          MemberCommentCount__c > 0 and 
                                          Account_Number__r.Name in :lstAccounts and 
                                          CreatedDate >= LAST_N_MONTHS:18
                                          GROUP BY Account_Number__r.Name]) {
    			
                string accnum = (string) aggRes.get('accnum');
    			Integer count = (Integer) aggRes.get('totalunread');                                             
                
                
    			responseObjList.put(accnum, count);
            }
            
           /* for(Member_Comment__c mc: AllUnreadCommentsforCase){
                Integer MCCount = 1;
                if(!responseObjList.ContainsKey(mc.Member_Number__c)){
                    responseObjList.put(mc.Member_Number__c, MCCount);
                }                
            }*/
           
        	
            system.debug('responseObjList: '+responseObjList);        	            
        }
        
        return responseObjList;
        
    }   
}