src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CommentsTextforMembersControllerTest.cls
@isTest(SeeAllData=True)
public class CommentsTextforMembersControllerTest {

    static testMethod void testMethod1(){
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Account acc = new Account(
           RecordTypeID=RecTypeId,
           FirstName='Test FName',
           LastName='Test LName',
           PersonMailingStreet='test@yahoo.com',
           PersonMailingPostalCode='12345',
           PersonMailingCity='SFO',
           PersonEmail='test@yahoo.com',
           PersonHomePhone='1234567',
           PersonMobilePhone='12345678');
         
        insert acc;
        
        Account_Details__c accDetails = new Account_Details__c();
           accDetails.Name = 'test name';
           accDetails.RecType__c = 'ACCT';
        insert accDetails;
        
        Person_Account__c pa = new Person_Account__c();
           pa.Account_Number__c = accDetails.Id;
           pa.PersonID__c = acc.Id;
        insert pa;
        
        String RecTypeId2= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        List<Account> acc2 = [Select Id From Account Where RecordTypeID=:RecTypeId2 Limit 1];
        
        
        PageReference pageRef = Page.CommentsTextforMembers;
        Test.setCurrentPage(pageRef);
        CommentsTextforMembersController controller = new CommentsTextforMembersController(new ApexPages.StandardController(acc2[0]));
        controller.isTest = true;
       // CommentsTextforMembersController.warningCodeWrapper wrp=new CommentsTextforMembersController.warningCodeWrapper('test');
        
        controller.mainMethod();
    }
}