src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <description>This field will be used to uniquely identify a Person.</description>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Member_Comment__c.object
<CustomObject>
    <description>Comments intended to be visible to the member</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Case__r.BrandfromAccount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Member Comments</relationshipLabel>
        <relationshipName>Member_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_Comment__c</fullName>
        <label>Member Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member_Communication__c</fullName>
        <label>Member Communication</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Member Comment</label>
    <nameField>
        <displayFormat>MCOM{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SecureEmailSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Chevron_KB__c</fullName>
        <label>Chevron_KB</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>List_of_Allowed_Extensions__c</fullName>
        <label>List of allowed Extensions</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spectrum_KB__c</fullName>
        <label>Spectrum_KB</label>
        <type>Url</type>
    </fields>
    <label>Secure Email Setting</label>
</CustomObject>

Staging/src/main/default/classes/AddAttachemntController.cls
global with sharing   class AddAttachemntController {
	public string UserName {get;set;}
	public string Stylesheet{get;set;}
	public string BrandName {get;set;}
	public string ImgName {get;set;}
	public string Sidebar{get;set;}
	public string CopyRights{get;set;}
	public string Extension {get;set;}
	 public List<selectOption> AccountNames{ get; set; }
	public string parentId {get;set;}
	 public set<String> accountNumberSet {get; set;}
	public List<Attachment> listAttachment{get;set;}
	public string Brand_Help {get;set;}
	public string Responsivecss {get;set;}
	public string parentType {get;set;}
	public string title {get;set;}
	public string SB {get;set;}
	public string SD {get;set;}
	public Attachment[] attachments {
	    get;
	    set;
	}
	public List<FileList> attachmentlist {get;set;}
		
	
	public List<FileList> ConvertAttachemntToFilelist()
	{
		 if (attachments != null)
        {
        	List<FileList> filelists = new List<FileList>();
        	integer j = 0;
            for(j=0; j< attachments.size(); j++ )
            {
                
                    FileList fl = new FileList();
                    fl.filename = attachments[j].Name;
                    fl.downloadurl = 'servlet/servlet.FileDownload?file=' + attachments[j].id ;
                    string ext = '';
                    try
                    { 
                        ext = attachments[j].Name.split('\\.')[1];
                    }
                    catch (Exception ex)
                    {
                    
                    }
                    ext = ext.toLowerCase();
                    if(ext == 'doc' || ext == 'docx'){
                    	ext = 'word';
                    }
                    else if(ext == 'xls' || ext == 'xlsx'){
                    	ext = 'excel';
                    }
                    else if(ext == 'ppt' || ext == 'ppts'){
                    	ext = 'powerpoint';
                    }
                     else if(ext == 'jpg' || ext == 'jpeg' || ext == 'png'|| ext == 'bmp'){
                    	ext = 'jpg';
                    }
                    else if(ext == 'one'){
                    	ext = 'onenote';
                    }
                    
                    fl.fileicon = ext;
                    string displaysize;
                    if(attachments[j].BodyLength != Null){    
	                    if(attachments[j].BodyLength < 1000)
	                    {
	                        displaySize = attachments[j].BodyLength + ' Bytes';
	                        //displaySize = attachments[j].BodyLength + 'KB';
	                        System.debug('displaySize1=='+ displaySize);
	                    }                               
	                    else if(attachments[j].BodyLength > 1000 && attachments[j].BodyLength < 1000000)
	                    {
	                        displaySize = Math.floor(attachments[j].BodyLength/1000) + ' KB';
	                        //displaySize = attachments[j].BodyLength + 'KB';
	                        System.debug('displaySize1=='+ displaySize);
	                    }
	                    else
	                    {
	                        displaySize  = Math.round((attachments[j].BodyLength / 1000000)*10)/10 + ' MB';
	                        //displaySize  = (attachments[j].BodyLength)/100 + 'MB';
	                         System.debug('displaySize2=='+ displaySize);
	                    }
                    }
                    fl.filesize = displaySize;
                    filelists.add(fl);
                
            }
            return filelists;
        }
		return null;
	}	
		public string  entityType {get;set;}
		public string  caseid {get;set;} 
				
	public AddAttachemntController()
	 {
	 	AccountNames = new List<selectOption>();
	    accountNumberSet = new Set<String>();   
	    parentId = ApexPages.currentPage().getParameters().get('parentId');
	    parentType = ApexPages.currentPage().getParameters().get('parentType');
	    SB = ApexPages.currentPage().getParameters().get('SB');
	    SD = ApexPages.currentPage().getParameters().get('SD');
	    entityType = ApexPages.currentPage().getParameters().get('entityType');
	   
	   	
	   
	    if(entityType == null || entityType == '')
	    {
	    	entityType = 'case';
	    }
	    if(entityType == 'case')
	    {
	    	parentType = 'SentMessages';
	    	Case c = [select Subject,CaseNumber from Case where Id =: parentId limit 1];
	    	caseid = c.id;
	    	title = 'Case # ' +  c.CaseNumber + ' - Upload files'; 
	    }
	    else if(entityType == 'notes')
	    {
	    	
	    	
	    	Member_Comment__c n = [select Member_Communication__c,Case__c from Member_Comment__c where ID  =: parentId limit 1];
	    	
	    	Case c = [select id,Subject,CaseNumber from Case where Id =: n.Case__c limit 1];
	    	
	    	title = 'Case # ' +  c.CaseNumber + ' - Upload files for reply'; 
	    	caseid = c.id;
	    }
	    	
	    
	    Attachment[] attachmentsLocal = [
	                    select Id, Name, Description, LastModifiedDate,BodyLength
	                    from Attachment
	                    where ParentId = :parentId
	                    order by Name
	                    ];
	    attachments =    attachmentsLocal;
	    attachmentlist = ConvertAttachemntToFilelist();
    }
    
    public void RefreshAll()
    {
    		
    	    Attachment[] attachmentsLocal = [
	                    select Id, Name, Description, LastModifiedDate,BodyLength
	                    from Attachment
	                    where ParentId = :parentId
	                    order by Name
	                    ];
	                    system.debug('111111');
	    attachments =    attachmentsLocal;
	    attachmentlist = ConvertAttachemntToFilelist();
	    system.debug('111111');
    }
    
	 public PageReference  PageLoad()
       {
        	getCategory();
        	
List <SecureEmailSetting__c> ses = SecureEmailSetting__c.getall().values();
		
        Extension = ses[0].List_of_Allowed_Extensions__c;
        
		CFCUAccount userAccount = new CFCUAccount();
		userAccount.personAccount = new Person_Account__c();
    	string LoggedinUser = UserInfo.getUserId();
        List<User> u = [SELECT Name, ContactId, FederationIdentifier from User Where ID=:LoggedinUser];
        userAccount.CurrentUser = u[0];
        userAccount.fedid = u[0].FederationIdentifier;
        UserName = userAccount.CurrentUser.Name;
        List<contact> c = [SELECT AccountId, FirstName, MiddleName, LastName FROM Contact WHERE Id =:u[0].ContactId];
        	 
        if (c.size()>0)
         {
         	userAccount.userBusinessContact = c[0];
         }
            system.debug('userAccount.fedid...' + userAccount.fedid);
	    userAccount.fedid =  userAccount.Get10DigitFid(userAccount.fedid);
	    List<Person_Account__c> personaccounts =  [SELECT Account_Number__c,Id,Name, PersonID__c FROM Person_Account__c Where Name_Type__c = 0 and Account_Number__r.Name =:userAccount.fedid];
            
            
         if(personaccounts.size()>0)
         {
        	 userAccount.personAccount = personaccounts[0];
             userAccount.AccountId = userAccount.personaccount.PersonID__c;
             userAccount.AccountNumber = userAccount.personaccount.Account_Number__c;
         }
            
        List <Account_Details__c> ad = [Select Brand__c FROM Account_Details__c Where ID = :userAccount.AccountNumber];
        if(ad.size()>0)
        {
        	userAccount.Brand = ad[0].Brand__c;
        }
        	
    
		
		System.Debug('UserAccount:-' + userAccount);
		
            if(userAccount.Brand == 'Chevron')
        	{
        	   ImgName ='logoorig.png';
                Stylesheet= 'message1.css';
                CopyRights ='Chevron Federal Credit Union. All Rights Reserved';
                Sidebar ='SidebarSubmitPage.css';
                Brand_Help = ses[0].Chevron_KB__c;
                Responsivecss ='Responsive_Chevron.css';
        	}
        	else
        	{
        		ImgName = 'spectrum_logo.jpg';
                Stylesheet= 'message1_spectrum.css';
                CopyRights ='Spectrum Credit Union. All Rights Reserved';
                Sidebar ='SidebarSubmitPage.css';
                Brand_Help = ses[0].Spectrum_KB__c;
                Responsivecss ='Responsive_Spectrum.css';
        	}
        	
	        
        	 return null;	
        }
        
        public void RemoveFile()
        {
        
        		string id =  ApexPages.CurrentPage().getParameters().get('id').split('=')[1];
        		
        	  for (integer i = 0; i < attachments.size(); i++)
		        {
		            if (id == attachments[i].id)
		            {
		
		               
		                    delete attachments[i];
		               
		
		
		                attachments.remove(i);
		                
		                break;
		            }
		        }
        	 attachmentlist = ConvertAttachemntToFilelist();
        	
        	
        	 
        }
        
        public List<SelectOption> getCategory()
	{
		
	 	List<SelectOption> options = new List<SelectOption>();
	    Schema.Describefieldresult primaryCategory = Case.Primary_Category__c.getDescribe();
	    	
	        
	  // 	Schema.DescribeFieldResult fieldResult = Schema.sObjectType.cases.fields.Primary_Category__c.getDescribe();
	   	List<Schema.PicklistEntry> ple = primaryCategory.getPicklistValues();
	        
	  	 for( Schema.PicklistEntry f : ple)
		   {
		      options.add(new SelectOption(f.getValue(),f.getLabel()));
		   }       
	    return options;
	}

}