src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a self-relationship field used to link SubAccounts(recType) to the respective MembershipAccounts(recType)</description>
        <label>Parent Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Type_Translate__c</fullName>
        <formula>RIGHT(( TypeTranslate__c ),(LEN( TypeTranslate__c )-5))</formula>
        <label>Split Type Translate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MemberNumberLightningController.cls
public class MemberNumberLightningController{
	
	@AuraEnabled   
    public static List<Person_Account__c> FetchAccounts(string searchText)
    {
    	List<Person_Account__c> accDetails = new List<Person_Account__c>();
        searchText = searchText.trim();
        
        system.debug('searchText::::'+searchText);        
       
        string genQuery = 'SELECT Id, PersonId__r.Name , Split_Type_Translate__c, Account_Number__r.TypeTranslate__c, Name_Type__c, Account_Number__r.ID1__c FROM Person_Account__c WHERE';
        string whereQuery;
        if(searchText != ''){
            if(whereQuery!=NULL){
                whereQuery = whereQuery+ 'AND Account_Number__r.Name LIKE \''+searchText+'\'';
            }else{
                integer i;
                integer membersize = searchText.length();
                for(i=membersize; i<10;i++){
                searchText = '0'+searchText;
              }
                whereQuery = ' (Account_Number__r.Name LIKE \''+searchText+'\' OR Account_Number__r.Parent_Account__r.Name LIKE \''+searchText+'\') AND Split_Type_Translate__c IN(\'Primary\',\'Joint Member\',\'Joint Owner\',\'Power of Attorney\',\'Trustee\',\'Authorized Signer\',\'Representative Payee\',\'Custodian\',\'Responsible Individual\') ORDER BY Name_Type__c ASC NULLS LAST ' ;
            }
        }
        
        if(whereQuery!=NULL){
            string totalQuery = genQuery+whereQuery+'LIMIT 100';
            system.debug('TotalQuery'+totalQuery);
            accDetails = Database.query(totalQuery);          
        }   
        System.debug('Total Query is::::'+accDetails);
        
        return accDetails;
    }
	
}