src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_At_Branch1__c</fullName>
        <formula>Text(Created_At_Branch__c)  &amp;  &apos; &apos;  &amp;  
CASE(Created_At_Branch__c, 
72, &apos;eBranch&apos;,
0, &apos;Head Quarter&apos;,
200, &apos;Spectrum&apos;,
270, &apos;Spectrum&apos;,
299, &apos;Spectrum&apos;,
99, &apos;ATM&apos;,
96, &apos;Consumer Lending&apos;,
24, &apos;CA Bakersfield&apos;,
05, &apos;Brea&apos;,
20, &apos;Camino Media&apos;,
02, &apos;Concord&apos;,
09, &apos;El Segundo&apos;,
206, &apos;Spectrum Pleasant Hill&apos;,
21, &apos;Kern River/ China Grade&apos;,
04, &apos;Richmond&apos;,
03, &apos;San Ramon&apos;,
201, &apos;Spectrum San Francisco&apos;,
29, &apos;Denver&apos;,
06, &apos;Covington&apos;,
203, &apos;Spectrum Frederick Bechtel&apos;,
23, &apos;Pascagoula&apos;,
19, &apos;Aramco&apos;,
17, &apos;Bellaire&apos;,
14, &apos;1600 Smith&apos;,
208, &apos;Spectrum El Paso&apos;,
25, &apos;Post Oak&apos;,
202, &apos;Spectrum Houston Galleria&apos;,
207, &apos;Bountiful&apos;,
28, &apos;Salt Lake City Refinery&apos;,
205, &apos;Spectrum Reston&apos;,
01, &apos;San Francisco&apos;,
22, &apos;West Loop&apos;,
53, &apos;Electronic&apos;,
55, &apos;Inactive, Low Balance, No Loans*&apos;,
56, &apos;Inactive, Low Balance, Chargeoffs&apos;,
57, &apos;Inactive, Low Balance, Bad Address&apos;,
88, &apos;Operation Services&apos;,
93, &apos;Member Services&apos;,
98, &apos;Remote Access&apos;,
204, &apos;Spectrum Westridge Mall&apos;,
253, &apos;Spectrum Electronic&apos;,
255, &apos;Spectrum Inactive, Low Balance, No Loans*&apos;,
256, &apos;Spectrum Inactive, Low Balance, Chargeoffs&apos;,
257, &apos;Spectrum Inactive, Low Balance, Bad Address&apos;,
293, &apos;Spectrum Member Services Branch&apos;,                     
&apos;&apos;)</formula>
        <label>Created At Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Episys_User_ID__c</fullName>
        <label>Episys User ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Mortgage</fullName>
        <active>true</active>
        <description>This record type will be used to store all the Mortgage Information</description>
        <label>Mortgage</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Branch__c</fullName>
        <label>Assigned Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <formula>Text(Assigned_Branch__c) &amp; &apos; &apos; &amp; 
CASE(Assigned_Branch__c, 
96, &apos;Direct Lending&apos;, 
200, &apos;Spectrum&apos;, 
270, &apos;Spectrum&apos;, 
299, &apos;Spectrum&apos;, 
99, &apos;ATM&apos;, 
24, &apos;Bakersfield&apos;, 
05, &apos;Brea&apos;, 
20, &apos;Camino Media&apos;, 
02, &apos;Concord&apos;, 
09, &apos;El Segundo&apos;, 
206, &apos;Pleasant Hill&apos;, 
21, &apos;Kern River/ China Grade&apos;, 
04, &apos;Richmond&apos;, 
03, &apos;San Ramon&apos;, 
201, &apos;Spectrum San Francisco&apos;, 
29, &apos;Denver&apos;, 
06, &apos;Covington&apos;, 
203, &apos;Spectrum Frederick Bechtel&apos;, 
23, &apos;Pascagoula&apos;, 
19, &apos;Aramco&apos;, 
17, &apos;Bellaire&apos;, 
14, &apos;1600 Smith&apos;, 
208, &apos;El Paso&apos;, 
25, &apos;Post Oak&apos;, 
202, &apos;Spectrum Houston Galleria&apos;, 
207, &apos;Bountiful&apos;, 
28, &apos;Salt Lake City Refinery&apos;, 
205, &apos;Spectrum Reston&apos;, 
01, &apos;San Francisco&apos;, 
22, &apos;West Loop&apos;, 
53, &apos;Electronic&apos;, 
55, &apos;Inactive, Low Balance, No Loans*&apos;, 
56, &apos;Inactive, Low Balance, Chargeoffs&apos;, 
57, &apos;Inactive, Low Balance, Bad Address&apos;, 
88, &apos;Operation Services&apos;, 
93, &apos;Member Services&apos;, 
98, &apos;Remote Access&apos;, 
204, &apos;Spectrum Westridge Mall&apos;, 
253, &apos;Spectrum Electronic&apos;, 
255, &apos;Spectrum Inactive, Low Balance, No Loans*&apos;, 
256, &apos;Spectrum Inactive, Low Balance, Chargeoffs&apos;, 
257, &apos;Spectrum Inactive, Low Balance, Bad Address&apos;, 
293, &apos;Spectrum Member Services Branch&apos;, 
&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Branch_of_Lead_creator__c</fullName>
        <label>Branch of Lead creator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01</fullName>
                </value>
                <value>
                    <fullName>02</fullName>
                </value>
                <value>
                    <fullName>03</fullName>
                </value>
                <value>
                    <fullName>04</fullName>
                </value>
                <value>
                    <fullName>05</fullName>
                </value>
                <value>
                    <fullName>06</fullName>
                </value>
                <value>
                    <fullName>208</fullName>
                </value>
                <value>
                    <fullName>09</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>201</fullName>
                </value>
                <value>
                    <fullName>202</fullName>
                </value>
                <value>
                    <fullName>203</fullName>
                </value>
                <value>
                    <fullName>204</fullName>
                </value>
                <value>
                    <fullName>205</fullName>
                </value>
                <value>
                    <fullName>206</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>253</fullName>
                </value>
                <value>
                    <fullName>255</fullName>
                </value>
                <value>
                    <fullName>256</fullName>
                </value>
                <value>
                    <fullName>257</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Episys_User_ID__c</fullName>
        <label>Episys User ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Episys_User__c</fullName>
        <formula>CreatedBy.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Episys User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_did_you_hear_about_us__c</fullName>
        <label>How did you hear about us?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yahoo Ad</fullName>
                </value>
                <value>
                    <fullName>Google Ad</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Branch__c</fullName>
        <label>Member Branch</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mortgage_Loan_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Mortgage Loan Officer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Mortgage_Loan_Officer__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>false</active>
        <businessProcess>Default</businessProcess>
        <description>record type for all the Branch Users</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Mortgage_Loan_Officer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether a given user if a Mortgage Loan Officer</description>
        <label>Mortgage Loan Officer</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
	
	public static boolean hasExecuted = false;
	
	private boolean m_isExecuting = false;
	
	private integer BatchSize = 0;

	public OpportunityTriggerHandler(boolean isExecuting, integer size )
	{
		m_isExecuting =  isExecuting;
		BatchSize = size;
	}
	
	public void OnBeforeInsert(Opportunity[] newOpportunities)
	{
			system.debug('Handler Called###');
		    string uid= UserInfo.getUserId();
		    User usr = [Select id, name, alias from User where id=:uid];
		    List<Episys_User__c> eusr = [SELECT id, alias__c, Assigned_Branch__c,Episys_ID__c, Branch_Name__c,Default__c from Episys_User__c 
		                                    where alias__c=:usr.alias order by Default__c desc]; 
		    Set<ID> accountid = new Set<Id>();
		    Id LoggedinUser = UserInfo.getUserId();
		    Set<Decimal> Episys_User_ID = new Set<Decimal>(); 
		    Set<String> branchnameSet = new Set<String>(); 
		    Set<String> MemAccId = new Set<String>();
		         
		              
		    for(Opportunity opp: newOpportunities)
		     {		     	
			        accountid.Add(opp.accountid);
			        MemAccId.Add(opp.Member_Account__c);
			        
			        if((opp.StageName == 'Closed Lost' || opp.StageName == 'Closed Won'))
			          {
			             opp.closedate = system.today();
			          }
			       
		            if(opp.Member_Type__c == 'Pre Member')
		            {
		            	opp.IsCreatedAsMember__c = false;
		            }  
		            else if(opp.Member_Type__c == 'Member'){
		            	opp.IsCreatedAsMember__c = true;
		            }         
		    }
		    
		    List<Account> accName = [Select Name, Id from Account where Id IN:accountid ];
        	for(Opportunity opp: newOpportunities)
            {
            	for(Account acc: accName)
            	{
                	if(opp.AccountId == acc.id )
                	{
                		opp.Opportunity_Name_Text__c = acc.Name;
                	}
            	}
            }
		    
		   
		    Map<id,String> MemAccMap = new Map<id,string>();
		    for(Account_Details__c ad : [select Id, Created_At_Branch1__c from Account_Details__c where id =:MemAccId AND Created_At_Branch1__c != null]){
		    	MemAccMap.put(ad.Id, ad.Created_At_Branch1__c);
		    }
		    
		   
		    
		    List<Person_Account__c> pa =[select id,Account_Number__c,Account_Number__r.Brand__c,Person_Account__c.PersonID__c ,Account_Number__r.RecType__c
		                            from Person_Account__c where PersonID__c IN : accountid];
		    List<Account> listAccountBrand = [select id,Parent_Lead__c,Parent_Lead__r.Brand__C from account where id in: accountid and Parent_Lead__c != null];
		     system.debug('accountid##'+ accountid);
		    system.debug('pa##'+ pa);
		     system.debug('listAccountBrand##'+ listAccountBrand);
		    for(Opportunity opp: newOpportunities)   
		     {
		               for(Account acc : listAccountBrand)
		                 {
		                            if(acc.id == opp.accountid && acc.Parent_Lead__c != null)
		                            {
		                                if(acc.Parent_Lead__r.Brand__C == 'CFCU'){
		                                    opp.Brand__c = 'Chevron';
		                                }
		                                else{   
		                                    opp.Brand__c = acc.Parent_Lead__r.Brand__C;
		                                }
		                                
		                                break;
		                            }   
		                        
		                 }
		                        
		                        
		                 boolean found = false;
		                 string brand = '';
		                 for(Person_Account__c item : pa)
		                    {
		                             system.debug('PersonID__c##'+ item.PersonID__c);
		                            if(opp.accountid == item.PersonID__c)
		                            {
		                            	 system.debug('RecType__c##'+ item.Account_Number__r.RecType__c);
		                                if(item.Account_Number__r.RecType__c == 'ACCT')
		                                {
		                                    opp.Brand__c = item.Account_Number__r.Brand__c;
		                                    break;
		                                }
		                                else{
		                                		opp.Brand__c = item.Account_Number__r.Brand__c;
		                                		
		                                    /*if(opp.Brand__c == '')
		                                    {
		                                        opp.Brand__c = item.Account_Number__r.Brand__c;
		                                    }*/
		                                }
		                                
		                                
		                            }
		                            
		                     }
		                
		                /* if(brand != '')
		                 {
		                     opp.Brand__c = brand;
		                        
		                 }*/
		                 /* logic to get branch detail from member account detail */
		                 if(opp.Member_Account__c != null && MemAccMap.containsKey(opp.Member_Account__c)){
		                 	
		                 	opp.Member_Branch__c = MemAccMap.get(opp.Member_Account__c);
		                 }
		                 
		                 
		                 
		    
		      }
		      
		      
		      for(Opportunity opp: newOpportunities)
		      {
		      		
		      //	if(opp.Mortgage_Loan_Officer__c == null && opp.Episys_User_ID__c != null)
		      	if(opp.Episys_User_ID__c != null)
		      	{
					Episys_User_ID.Add(opp.Episys_User_ID__c);
		      	}
		                
		      }
		      		
		      system.debug('Episys_User_ID###' + Episys_User_ID);
		      
		      List<Episys_User__c> episysUsers = [SELECT id, alias__c, Assigned_Branch__c,Episys_ID__c, Branch_Name__c,Default__c from Episys_User__c 
		                                    where Episys_ID__c in: Episys_User_ID];
		      Group OppQueue = new Group();   
		      String groupName = '';           
		      List<Group> listQueue = [select id,Name,Email from Group where Type = 'Queue' and (Email like '%lead.com' or Email like '%opportunity.com')];
		          
	           
    		  for(Opportunity opp: newOpportunities)
		      {
		      		system.debug('Above Conditions###');
		      		system.debug('Ownership__c###' + opp.Ownership__c);
		      		/*if(opp.Mortgage_Loan_Officer__c != null && opp.Is_Converted__c == false)
			        {
			        	system.debug('Condition Mortgage Officer###');
			            opp.Ownerid = opp.Mortgage_Loan_Officer__c;
			            opp.User_Owner__c = opp.Mortgage_Loan_Officer__c;
			        	opp.Queue_Owner__c = null;
			        }*/
			        //else if(opp.Ownership__c == 'Auto Assign' && opp.Mortgage_Loan_Officer__c == null && (opp.Opportunity_Source__c == 'Branch Walk in' || opp.Opportunity_Source__c == 'Branch Call')  && opp.Is_Converted__c == false)
			        if(opp.Ownership__c == 'Auto Assign' && (opp.Opportunity_Source__c == 'Branch Walk in' || opp.Opportunity_Source__c == 'Branch Call')  && opp.Is_Converted__c == false)
		      		{
		      			system.debug('opp.Episys_User_ID__c###' + opp.Episys_User_ID__c);
		      			system.debug('episysUsers###' + episysUsers);
		      			groupName = '';
		      			if(episysUsers.size() > 0)
		      			{
			      			for(Episys_User__c episysItem: episysUsers)
			      			{
			      				system.debug('episysItem.Episys_ID__c###' + episysItem.Episys_ID__c);
			      				if(opp.Episys_User_ID__c == episysItem.Episys_ID__c)
			      				{
			      					system.debug('Episys user matched###');
			      					string BranchQueue = episysItem.Branch_Name__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
			      					system.debug('EBranchQueue###' + BranchQueue);
			      					for(Group grp : listQueue)
					      			{
					      				
					      				if(grp.Email.containsIgnoreCase(BranchQueue))
					      				{
					      					groupName = grp.Name;
					      					break;
					      				}
					      				
					      			}
			      				 	if(groupName!=null && groupName!='')
			      				 	{
			      				 		
			      				 		opp.Queue_Owner__c = groupName;	
			      				 		opp.User_Owner__c = null;
			      				 		opp.Ownership__c ='Keep';
			      				 	}
			      				 	else
			      				 	{
                                            system.debug('Condition Product Type###');
					      				 	string ProductType = opp.Product_Type__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
					      				 	system.debug('ProductType###' + ProductType);
											for(Group grp : listQueue)
							      			{
							      				
							      				if(grp.Email.containsIgnoreCase(ProductType))
							      				{
							      					groupName = grp.Name;
							      					break;
							      				}
							      				
							      				
							      			}
							      			system.debug('groupName###' + groupName);
					      				 	if(groupName!=null && groupName!='')
					      				 	{
					      				 		opp.Queue_Owner__c = groupName;	
					      				 		opp.User_Owner__c = null;
					      				 		opp.Ownership__c ='Keep';
					      				 	}
			      				 	}
			      					break;
			      					
			      				}
			      			}
		      			}
		      			else
		      			{
		      					 		   system.debug('Condition Product Type###');
					      				 	string ProductType = opp.Product_Type__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
					      				 	system.debug('ProductType###' + ProductType);
											for(Group grp : listQueue)
							      			{
							      				
							      				if(grp.Email.containsIgnoreCase(ProductType))
							      				{
							      					groupName = grp.Name;
							      					break;
							      				}
							      				
							      				
							      			}
							      			system.debug('groupName###' + groupName);
					      				 	if(groupName!=null && groupName!='')
					      				 	{
					      				 		opp.Queue_Owner__c = groupName;	
					      				 		opp.User_Owner__c = null;
					      				 		opp.Ownership__c ='Keep';
					      				 	}
			      				 	
		      			}
		      			
		      			
		      			
		      		}
                  else if(opp.Ownership__c == 'Auto Assign' && opp.Opportunity_Source__c == 'Event'){
                      		
                           string BranchQueue='';
                           groupname='';
                            if(eusr.size() > 0 && eusr[0].Default__c == true)
                            {
                               BranchQueue = eusr[0].Branch_Name__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
                            }
                            else if(eusr.size() > 0 && eusr[0].Default__c == false){
                                BranchQueue = eusr[0].Branch_Name__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
                            }
                      system.debug('EBranchQueue###' + BranchQueue);
                      if(BranchQueue != null && BranchQueue != ''){
                          for(Group grp : listQueue)
                          { 
                              if(grp.Email.containsIgnoreCase(BranchQueue))
                              {
                                  groupname = grp.Name;
                                  break;
                              }
                              system.debug('groupName###' + groupname);
                          }
                      }
                      if(groupname != null && groupname!=''){
                          //opp.Opportunity_Owner__c = groupnameid;
                          opp.Queue_Owner__c = groupName;	
                          opp.User_Owner__c = null;
                          opp.Ownership__c ='Keep';
                          
                      }
                      else{
                          system.debug('Condition Product Type###');
                          string ProductType = opp.Product_Type__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();                        
                          for(Group grp : listQueue)
                          {
                              if(grp.Email.containsIgnoreCase(ProductType))
                              {
                                  groupname = grp.Name;
                                  break;
                              }
                          }
                          system.debug('groupName###' + groupname);
                          if(groupname!=null && groupname!='')
                          {
                              //Opp.Opportunity_Owner__c = groupnameid;	
                              opp.Queue_Owner__c = groupName;	
                              opp.User_Owner__c = null;
                              opp.Ownership__c ='Keep';
                          }
                      }
                  } 
		      	//	else if(opp.Ownership__c == 'Auto Assign' && opp.Mortgage_Loan_Officer__c == null && (opp.Opportunity_Source__c != 'Branch Walk in' && opp.Opportunity_Source__c != 'Branch Call')  && opp.Is_Converted__c == false)
		      		else if(opp.Ownership__c == 'Auto Assign' && (opp.Opportunity_Source__c != 'Branch Walk in' && opp.Opportunity_Source__c != 'Branch Call')  && opp.Is_Converted__c == false)
		      		{
		      					system.debug('Condition Product Type###');
		      				 	string ProductType = opp.Product_Type__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
		      				 	system.debug('ProductType###' + ProductType);
								for(Group grp : listQueue)
				      			{
				      				
				      				if(grp.Email.containsIgnoreCase(ProductType))
				      				{
				      					groupName = grp.Name;
				      					break;
				      				}
				      				
				      				
				      			}
				      			system.debug('groupName###' + groupName);
		      				 	if(groupName!=null && groupName!='')
		      				 	{
		      				 		opp.Queue_Owner__c = groupName;	
		      				 		opp.User_Owner__c = null;
		      				 		opp.Ownership__c ='Keep';
		      				 	}
		      				 	
		      		}
		      		
		      }	
    		 
    				    
		    
		        	
		        	
		        	
		        	
                        
	}
	
	
	
	public void OnBeforeUpdate(Opportunity[] Opportunities, Map<ID, Opportunity> OpportunityNewMap, Map<ID, Opportunity> OpportunityOldMap)
	{
 system.debug('----------------------------Limit'+Limits.getQueries());
		string uid= UserInfo.getUserId();
		    User usr = [Select id, name, alias from User where id=:uid];
		 /*   List<Episys_User__c> eusr = [SELECT id, alias__c, Assigned_Branch__c,Episys_ID__c, Branch_Name__c,Default__c from Episys_User__c 
		                                    where alias__c=:usr.alias order by Default__c desc];*/ 
		Id LoggedinUser = UserInfo.getUserId();
		Set<Decimal> Episys_User_ID = new Set<Decimal>(); 
		Set<String> branchnameSet = new Set<String>(); 
		Group OppQueue = new Group();   
		String groupName = '';   
		List<Decimal> ListEpisysIds = new List<Decimal>();
		Set<id> QueOppId = new Set<id>();
		for(Opportunity opp: Opportunities)
	    {
	    	if(opp.Queue_Owner__c != null && opp.Queue_Owner__c !=''){
	    		QueOppId.add(opp.id);
	    	}
	    	if(opp.Episys_User_ID__c != null)
	    	{
	    	 ListEpisysIds.add(opp.Episys_User_ID__c);
	    	}
	    }
		
		List<Episys_User__c> euser = [SELECT id,alias__c, Assigned_Branch__c,Episys_ID__c, Branch_Name__c,Default__c 
						from Episys_User__c where Episys_ID__c  in: ListEpisysIds];
	      	
		for(Opportunity opp: Opportunities)
	    {
	    	opp.Branch_of_Lead_creator__c =   '';
	    	for(Episys_User__c episysid : euser)
	    	{
	    		if(episysid.Episys_ID__c == opp.Episys_User_ID__c)
	    		{
	    			 opp.Branch_of_Lead_creator__c =   episysid.Branch_Name__c;
	    			 	Episys_User_ID.Add(opp.Episys_User_ID__c);
	    			 	break;
	    		}
	    	
	    	}
	    }
	      	
	      /*	 if(euser.size() > 0){
			              opp.Branch_of_Lead_creator__c =   euser[0].Branch_Name__c;
			              //opp.Member_Branch__c =   euser[0].Branch_Name__c;
			              
			          }	
			  else
			  {
			  	opp.Branch_of_Lead_creator__c =   '';
			  	//opp.Member_Branch__c =   '';
			  }
		  //  if(opp.Mortgage_Loan_Officer__c == null && opp.Episys_User_ID__c != null)
		  	if(opp.Episys_User_ID__c != null)
		    {
					Episys_User_ID.Add(opp.Episys_User_ID__c);
		    }*/
	                
        
        List<Group> listQueue = [select id,Name,Email from Group where Type = 'Queue' and (Email like '%lead.com' or Email like '%opportunity.com')];
	     List<Episys_User__c> episysUsers = [SELECT id, alias__c, Assigned_Branch__c,Episys_ID__c, Branch_Name__c,Default__c from Episys_User__c 
		                                    where Episys_ID__c in: Episys_User_ID];
		                                    
		/* set<id> setOpp = new Set<id>();
        	  for(Opportunity Opp1 : [select id,Name from Opportunity where Owner.Type = 'Queue' and id IN :QueOppId]){
        	 	
        	 	SetOpp.add(Opp1.id);
        	  }*/
        	  
        	  system.debug('----------------'+QueOppId) ;   
		                                             
       		for(Opportunity opp: Opportunities)
        	{		
                 	Opportunity oldOpp = OpportunityOldMap.get(opp.Id);
                 	 system.debug('-----opp.StageName-----------'+opp.StageName) ;  
                 	if(QueOppId.contains(opp.id) && (opp.StageName == 'Closed Won' || opp.StageName == 'Closed Lost')){
            	 		opp.Adderror('Queue owned opportunities cannot be closed.');
            	 	}
                 	if((oldOpp.StageName == 'Closed Won' || oldOpp.StageName == 'Closed Lost') && opp.Allow_Error__c == false)
            	 	{
            	 		opp.Adderror('Opportunity fields are read only for Closed Opportunity.');
            	 		
            	 	}
            	 	else{
	                if(opp.Is_Converted__c && oldOpp.Opportunity_Source__c != opp.Opportunity_Source__c)
	                {
	                    opp.Adderror('Opportunity Source is read only for Opportunity converted from Lead.');
	                }
	                if(opp.Is_Converted__c && oldOpp.Brand__C != opp.Brand__C)
	                {
	                    opp.Adderror('Brand is read only for Opportunity converted from Lead.');
	                }
	                if(opp.Is_Converted__c && oldOpp.Product_Type__c != opp.Product_Type__c)
	                {
	                    opp.Adderror('Product Type is read only for Opportunity converted from Lead.');
	                }
	                if(opp.Is_Converted__c && oldOpp.Product_Sub__c != opp.Product_Sub__c)
	                {
	                    opp.Adderror('Product Subtype is read only for Opportunity converted from Lead.');
	                }
	                
	                if(oldOpp.How_did_you_hear_about_us__c != opp.How_did_you_hear_about_us__c)
	                {
	                    opp.Adderror('How did you hear about us is read only for Opportunity converted from Lead.');
	                }
	                
	                if(opp.Is_Converted__c && oldOpp.Event_Source__c != opp.Event_Source__c)
	                {
	                    opp.Adderror('Event Source is read only for Opportunity converted from Lead.');
	                }
	                if(oldOpp.closedate != opp.closedate)
	                {
	                     opp.Adderror('Close date is read only');
	                }
	                if(oldOpp.AccountId != opp.AccountId && ((oldOpp.IsMemberOpportunity__c == opp.IsMemberOpportunity__c) && opp.IsMemberOpportunity__c == false && opp.Allow_Error__c == false))
	                {
	                     opp.Adderror('Member name is read only');
	                }
	              
	                if(oldOpp.Name != null && oldOpp.Name !='Name' && oldOpp.Name != opp.Name)
	                {
	                     opp.Adderror('Opportunity Number is read-only');
	                }
	                if((opp.StageName == 'Closed Lost' || opp.StageName == 'Closed Won') && oldOpp.StageName != opp.StageName)
	                {
	                    opp.closedate = system.today();
	                } 

		      /*         if(opp.Is_Converted__c && oldOpp.Member_Branch__c != opp.Member_Branch__c)
		               {
		                 opp.Adderror('Member Branch is read only for Opportunity converted from Lead.');
		               }
		        */      
	              
	               if(oldOpp.Lead_Episys_User_ID__c != opp.Lead_Episys_User_ID__c)
	               {
	                 opp.Adderror('Lead Episys User Id is read only');
	               }
	               
	               if((opp.StageName != 'Closed Lost' && opp.StageName != 'Closed Won') && oldOpp.StageName != opp.StageName)
	                {
	                    opp.closedate = date.ValueOf('2048-12-31');
	                   
	                }
            	 	}
	               if(opp.Allow_Error__c == true)
	               {
	               		opp.Allow_Error__c = false;
	               }
	              
	             
	             /*  if(oldOpp.Mortgage_Loan_Officer__c != opp.Mortgage_Loan_Officer__c && opp.Mortgage_Loan_Officer__c!=null )
	               {
		                 opp.Ownerid = opp.Mortgage_Loan_Officer__c;
		                 opp.User_Owner__c = opp.Mortgage_Loan_Officer__c;
				         opp.Queue_Owner__c = null;
	               }*/	               
	             /*  else if(opp.Ownership__c == 'Auto Assign' && opp.Mortgage_Loan_Officer__c == null &&(opp.Opportunity_Source__c == 'Branch Walk in' || opp.Opportunity_Source__c == 'Branch Call'))
		      		{
		      			groupName = '';
		      			for(Episys_User__c episysItem: episysUsers)
		      			{
		      				
		      				if(opp.Episys_User_ID__c == episysItem.Episys_ID__c)
		      				{
		      					string BranchQueue = episysItem.Branch_Name__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
		      					for(Group grp : listQueue)
				      			{
				      				
				      				if(grp.Email.containsIgnoreCase(BranchQueue))
				      				{
				      					groupName = grp.Name;
				      					break;
				      				}
				      				
				      			}
		      				 	if(groupName!=null || groupName!='')
		      				 	{
		      				 		opp.Queue_Owner__c = groupName;	
		      				 		opp.User_Owner__c = null;
		      				 	}
		      					break;
		      					
		      				}
		      			}
		      		}
		      		
		      		else if(opp.Ownership__c == 'Auto Assign' && opp.Mortgage_Loan_Officer__c == null && (opp.Opportunity_Source__c != 'Branch Walk in' && opp.Opportunity_Source__c != 'Branch Call'))
		      		{
		      				 	groupName = '';
				      		string ProductType = opp.Product_Type__c.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
								for(Group grp : listQueue)
				      			{
				      				
				      				if(grp.Email.containsIgnoreCase(ProductType))
				      				{
				      					groupName = grp.Name;
				      					break;
				      				}
				      				
				      				
				      			}
		      				 	if(groupName!=null || groupName!='')
		      				 	{
		      				 		opp.Queue_Owner__c = groupName;	
		      				 		opp.User_Owner__c = null;
		      				 	}
		      		}*/
        	}
        	
 

    }
	

   
}