src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendRequestToOnBaseControllerTest.cls
@isTest(SeeAllData=True)
public class SendRequestToOnBaseControllerTest {
       
    static testMethod void testMethod1() {
        
        Account_Details__c accDetail = new Account_Details__c();
           accDetail.Name = '0000018249';
           //accDetail.Combined_Account_ID__c = 'test';
        insert accDetail;
        
      //  PageReference pageRef = Page.SendRequestToRTS;
       // Test.setCurrentPage(pageRef);
      //  ApexPages.currentPage().getParameters().put('accNum', accDetail.Name);
        
        Test.startTest();
            Test.setMock(HttpCalloutMock.class, new MockClass());
            SendRequestToOnBaseController controller = new SendRequestToOnBaseController();
        Test.stopTest();     
    } 
}