src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_LEOM_Expired__c</fullName>
        <description>Set a flag used for NA LEOM section expiration</description>
        <formula>IF( (Last_NA_LEOM__c  = null  ||   
      Last_NA_LEOM__c &lt;  NOW() -(1440/1440) ) &amp;&amp; 
      NA_Eligibility__c  = TRUE ,
          true, 
          false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NA LEOM Expired</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>LECF_800_Feedback__c</fullName>
        <label>LECF_800_Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LECF_800__c</fullName>
        <defaultValue>false</defaultValue>
        <label>800 #</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LECF_ATM_Feedback__c</fullName>
        <label>LECF_ATM_Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LECF_ATM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LECF_ATM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LECF_Branch_Feedback__c</fullName>
        <label>LECF_Branch_Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LECF_Branch__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Branch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LECF_Comment__c</fullName>
        <label>LECF_Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LECF_Experience_Improvement_Feedback__c</fullName>
        <description>LECF_Experience_Improvement_Feedback</description>
        <inlineHelpText>LECF_Experience_Improvement_Feedback</inlineHelpText>
        <label>LECF_Experience_Improvement_Feedback</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LECF_Last_Updated_On__c</fullName>
        <label>Provide Feedback Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LECF_Mobile_banking_Feedback__c</fullName>
        <label>LECF_Mobile_banking_Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LECF_Mobile_banking__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile banking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LECF_Online_banking_Feedback__c</fullName>
        <label>LECF_Online_banking_Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LECF_Online_banking__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Online banking</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REC_LECF_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Call Center Extended Hours</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REC_LECF_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sign_up_for_Online</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REC_LECF_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sign_up_for_Mobile</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REC_LECF_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Surcharge Free ATM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REC_LECF_Outcome_1__c</fullName>
        <label>Call Center Extended Hours Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Recommendation_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>REC_LECF_Outcome_2__c</fullName>
        <label>Sign_up_for_Mobile Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Recommendation_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>REC_LECF_Outcome_3__c</fullName>
        <label>Sign_up_for_Online Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Recommendation_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>REC_LECF_Outcome_4__c</fullName>
        <label>Surcharge Free ATM Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Recommendation_Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rec_LEOM_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Recommendation 1 - Life Events - Other Milestones</description>
        <inlineHelpText>Recommendation 1 - Life Events - Other Milestones</inlineHelpText>
        <label>HELOC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RV Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Health Savings Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Personal Line of Credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Student Loans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_6__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CDs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_7__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Money Market</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Na_CurrentFeedbackController.cls
public class Na_CurrentFeedbackController
{

public string script{get;set;}
    public Account AccountC{get;set;}
    public string NA_id {get;set;}
    
    public string accId2 { get; set; }
    public NeedAssessmentController parentController {get;set;}
      public Needs_Assesment__c  lcf_New;
       
       
        public Needs_Assesment__c  getlcf_New(){
       
           setObjects();
        
        return lcf_New;
    }
    public void setlcf_New(Needs_Assesment__c  val){
        lcf_New = val;
    }
    

    public void setObjects(){
        
        accId2 = parentController.account[0].Id;
        list<Needs_Assesment__c> naother = [select id,LECF_Branch_Feedback__c,LECF_Branch__c,LECF_800__c,LECF_800_Feedback__c,
                    LECF_Online_banking_Feedback__c,LECF_Online_banking__c,LECF_ATM__c,LECF_ATM_Feedback__c,LECF_Mobile_banking__c,
                    LECF_Mobile_banking_Feedback__c ,LECF_Comment__c,LECF_Last_Updated_On__c,
                    Rec_LEOM_1__c,Rec_LEOM_2__c,Rec_LEOM_3__c,LECF_Experience_Improvement_Feedback__c,
                    Rec_LEOM_4__c,Rec_LEOM_5__c,Rec_LEOM_6__c,Rec_LEOM_7__c,
                    Rec_LECF_Outcome_1__c,Rec_LECF_Outcome_2__c,Rec_LECF_Outcome_3__c,Rec_LECF_Outcome_4__c,
                    Rec_LECF_1__c,Rec_LECF_2__c,Rec_LECF_3__c,Rec_LECF_4__c
                    from Needs_Assesment__c
                    where member__c =:accId2 ORDER by LastModifiedDate desc];
        if (naother.size() > 0)
        {
            NA_id = naother[0].Id;
            
            if(AccountC.NA_LEOM_Expired__c)
            {
                 lcf_New = new Needs_Assesment__c();
                 lcf_New .ID = NA_id;
                 

            }
            else
            {
                 lcf_New = naother [0];
            }
        }
        else
        {
  
            lcf_New = new Needs_Assesment__c();
            
        }
    }

 

   public void SubmitFeedbackForm()
    {
        /*If(       lcf_New .LECF_Branch_Feedback__c                != null || 
                  lcf_New .LECF_800__c                            != null || 
                  lcf_New .LECF_800_Feedback__c                   != null || 
                  lcf_New .LECF_Branch__c                         != null ||
                  lcf_New .LECF_Online_banking_Feedback__c        != null || 
                  lcf_New .LECF_Online_banking__c                 != null ||         
                  lcf_New .LECF_ATM__c                            != null ||        
                  lcf_New .LECF_ATM_Feedback__c                   != null ||        
                  lcf_New .LECF_Mobile_banking_Feedback__c        != null ||        
                  lcf_New .LECF_Mobile_banking__c                 != null ||   
                  lcf_New.LECF_Experience_Improvement_Feedback__c != null ||     
                  lcf_New .Rec_LEOM_1__c ||
                  lcf_New .Rec_LEOM_2__c || 
                  lcf_New .Rec_LEOM_3__c || 
                  lcf_New .Rec_LEOM_4__c || 
                  lcf_New .Rec_LEOM_5__c ||
                  lcf_New .Rec_LEOM_6__c || 
                  lcf_New .Rec_LEOM_7__c || 
                  lcf_New.Rec_LECF_1__c  || 
                  lcf_New.Rec_LECF_2__c  || 
                  lcf_New.Rec_LECF_3__c  || 
                  lcf_New.Rec_LECF_4__c        )*/           
        {
        
             system.debug('test2 --- ');
            
                 Needs_Assesment__c  nao_tobeinserted = new Needs_Assesment__c  ();
                    nao_tobeinserted.Id = lcf_New .Id;
                    
                    
                     nao_tobeinserted.LECF_Branch_Feedback__c= lcf_New .LECF_Branch_Feedback__c;
                     nao_tobeinserted.LECF_Branch__c= lcf_New .LECF_Branch__c;
                     nao_tobeinserted.LECF_800__c= lcf_New .LECF_800__c;
                     nao_tobeinserted.LECF_800_Feedback__c= lcf_New .LECF_800_Feedback__c;
                     nao_tobeinserted.LECF_Online_banking_Feedback__c= lcf_New .LECF_Online_banking_Feedback__c;
                     nao_tobeinserted.LECF_Online_banking__c= lcf_New .LECF_Online_banking__c;
                     nao_tobeinserted.LECF_ATM__c= lcf_New .LECF_ATM__c;
                     
                     
                     nao_tobeinserted.LECF_ATM_Feedback__c= lcf_New .LECF_ATM_Feedback__c;
                     nao_tobeinserted.LECF_Mobile_banking__c= lcf_New .LECF_Mobile_banking__c;
                     nao_tobeinserted.LECF_Mobile_banking_Feedback__c= lcf_New .LECF_Mobile_banking_Feedback__c;
                                          nao_tobeinserted.LECF_Experience_Improvement_Feedback__c = lcf_New .LECF_Experience_Improvement_Feedback__c;
                  nao_tobeinserted.LECF_Comment__c = lcf_New.LECF_Comment__c ;
                    nao_tobeinserted.Rec_LEOM_2__c= lcf_New .Rec_LEOM_2__c;
                    nao_tobeinserted.Rec_LEOM_3__c= lcf_New .Rec_LEOM_3__c;
                    nao_tobeinserted.Rec_LEOM_4__c= lcf_New .Rec_LEOM_4__c;
                    nao_tobeinserted.Rec_LEOM_5__c= lcf_New .Rec_LEOM_5__c;
                    nao_tobeinserted.Rec_LEOM_6__c= lcf_New .Rec_LEOM_6__c;
                    nao_tobeinserted.Rec_LEOM_7__c= lcf_New .Rec_LEOM_7__c;
                    nao_tobeinserted.Rec_LECF_1__c = lcf_New.Rec_LECF_1__c;
                    nao_tobeinserted.Rec_LECF_2__c = lcf_New.Rec_LECF_2__c;
                    nao_tobeinserted.Rec_LECF_3__c = lcf_New.Rec_LECF_3__c;
                    nao_tobeinserted.Rec_LECF_4__c = lcf_New.Rec_LECF_4__c;
                    if(nao_tobeinserted.Id == null)
                    {
                    nao_tobeinserted.Member__c = accId2 ;
                    }
                    nao_tobeinserted.LECF_Last_Updated_On__c= system.today();
                     script = '1';
             
                     
                        upsert  nao_tobeinserted;
                        

            
    
       }
                RefreshParent();
    }
    
   
    
     public void resetscript()
     {
        script = '';
     }
  
     public void RefreshParent(){
             
        
           
           parentController.RefreshAccount();
         



           parentController.GetCurrentFeedbackTabClass();
     }

}