src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Created_By_User_Alias__c</fullName>
        <label>Created By User Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_User_Text__c</fullName>
        <label>Created By User Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_User__c</fullName>
        <label>Created By User</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecureEmailAddress__c</fullName>
        <description>Account level email address</description>
        <label>Secure Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>WARNING_01_CODE__c</fullName>
        <label>Warning 01 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Episys_Name__c</fullName>
        <label>Episys Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WarningCodeMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Warning_Code_Number__c</fullName>
        <label>Warning Code Number</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warning_Code_Text__c</fullName>
        <label>Warning Code Text</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>WarningCodeMapping</label>
</CustomObject>

src/main/default/classes/AccountDetailsTriggerTest.cls
@isTest
public class AccountDetailsTriggerTest {
    
    static testMethod void testMethod1(){
        
        String uid = UserInfo.getUserId();
        RecordType recordtype =[SELECT Id,Name FROM RecordType WHERE Name='Person Account'];
        User currentUser = [SELECT LocaleSidKey, Alias, LanguageLocaleKey, TimeZoneSidKey, EmailEncodingKey FROM User WHERE Id=:uid];    
        
        Account_Details__c accDetails = new Account_Details__c();
        accDetails.Name = 'test';
        accDetails.SecureEmailAddress__c = 'sample@sample.com';
        accDetails.Created_By_User__c = 1;
        accDetails.RecType__c = 'ACCT';
        accDetails.Created_By_User_Alias__c = currentUser.Alias;
        insert accDetails;
        
        Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'testname';
        eu.Alias__c = currentUser.Alias;
        accDetails.SecureEmailAddress__c = 'sample@sample.com';
        insert eu;

        accDetails.SecureEmailAddress__c = 'sample@sample2.com';
        accDetails.Created_By_User_Text__c = 'testnameUpdate';
        accDetails.Balance__c = 100;
        update accDetails;
        
        WarningCodeMapping__c wm = new WarningCodeMapping__c();
        wm.Name = 'Rec001';
        wm.Warning_Code_Number__c = '001';
        wm.Warning_Code_Text__c = '001-NO BATCH POSTING ALLOWED';
        insert wm;
        
        accDetails.WARNING_01_CODE__c = '001-NO BATCH POSTING ALLOWED...';
        accDetails.SecureEmailAddress__c = 'sample@sample3.com';
        accDetails.Balance__c = 200;
        update accDetails;        

		Account_Details__c accDetails2 = [Select Id,SecureEmailAddress__c from Account_Details__c where Name = 'test' limit 1];
        accDetails2.SecureEmailAddress__c = 'sample@sample3.com';
        update accDetails2;     
        
        Account acc = new Account();
        acc.Owner = currentUser;
        acc.FirstName = 'testname';
        acc.LastName='testname';
        acc.recordtypeid = recordtype.Id;
        acc.PersonID__C ='V554870800';
        acc.PersonEmail ='acctest@test.com';
        insert acc;
        
        Person_Account__c pa = new Person_Account__c();
        pa.Account_Number__c = accDetails.id;
        pa.Name_Type__c = 0;
        pa.PersonID__c = acc.Id;
        insert pa;
        
		Test.startTest();
        UpdateAccountCreatebyEpisysUser c = new UpdateAccountCreatebyEpisysUser();
        Database.executeBatch(c);
        Test.stopTest();
    }
    
    static testMethod void testMethod2(){
        
        String uid = UserInfo.getUserId();
        RecordType recordtype =[SELECT Id,Name FROM RecordType WHERE Name='Person Account'];
        User currentUser = [SELECT LocaleSidKey, Alias, LanguageLocaleKey, TimeZoneSidKey, EmailEncodingKey FROM User WHERE Id=:uid];    
        
        Account_Details__c accDetails = new Account_Details__c();
        accDetails.Name = 'test';
        accDetails.SecureEmailAddress__c = 'sample@sample.com';
        accDetails.Created_By_User__c = 1;
        accDetails.RecType__c = 'SHAR';
        accDetails.Created_By_User_Alias__c = currentUser.Alias;
        insert accDetails;
        
        Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'testname';
        eu.Alias__c = currentUser.Alias;
        accDetails.SecureEmailAddress__c = 'sample@sample.com';
        insert eu;

        accDetails.SecureEmailAddress__c = 'sample@sample2.com';
        accDetails.Created_By_User_Text__c = 'testnameUpdate';
        accDetails.Balance__c = 100;
        update accDetails;
        
        WarningCodeMapping__c wm = new WarningCodeMapping__c();
        wm.Name = 'Rec001';
        wm.Warning_Code_Number__c = '001';
        wm.Warning_Code_Text__c = '001-NO BATCH POSTING ALLOWED';
        insert wm;
        
        accDetails.WARNING_01_CODE__c = '001-NO BATCH POSTING ALLOWED...';
        accDetails.SecureEmailAddress__c = 'sample@sample3.com';
        accDetails.Balance__c = 200;
        update accDetails;        

		Account_Details__c accDetails2 = [Select Id,SecureEmailAddress__c from Account_Details__c where Name = 'test' limit 1];
        accDetails2.SecureEmailAddress__c = 'sample@sample3.com';
        update accDetails2;     
        
        Account acc = new Account();
        acc.Owner = currentUser;
        acc.FirstName = 'testname';
        acc.LastName='testname';
        acc.recordtypeid = recordtype.Id;
        acc.PersonID__C ='V554870800';
        acc.PersonEmail ='acctest@test.com';
        insert acc;
        
        Person_Account__c pa = new Person_Account__c();
        pa.Account_Number__c = accDetails.id;
        pa.Name_Type__c = 0;
        pa.PersonID__c = acc.Id;
        insert pa;
        
		Test.startTest();
        UpdateAccountCreatebyEpisysUser c = new UpdateAccountCreatebyEpisysUser();
        Database.executeBatch(c);
        Test.stopTest();
    }
}