src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_LEOM_Expired__c</fullName>
        <description>Set a flag used for NA LEOM section expiration</description>
        <formula>IF( (Last_NA_LEOM__c  = null  ||   
      Last_NA_LEOM__c &lt;  NOW() -(1440/1440) ) &amp;&amp; 
      NA_Eligibility__c  = TRUE ,
          true, 
          false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NA LEOM Expired</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>LEPT_Comments__c</fullName>
        <label>LEPT_Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LEPT_Convenient_locations__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEPT_Convenient locations</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEPT_Deposit_rates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEPT_Deposit rates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEPT_Financial_Institution__c</fullName>
        <label>LEPT_Financial_Institution</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chevron Federal Credit Union</fullName>
                </value>
                <value>
                    <fullName>Spectrum Credit Union</fullName>
                </value>
                <value>
                    <fullName>Bank of America</fullName>
                </value>
                <value>
                    <fullName>Chase Bank</fullName>
                </value>
                <value>
                    <fullName>Wells Fargo</fullName>
                </value>
                <value>
                    <fullName>Citibank</fullName>
                </value>
                <value>
                    <fullName>US Bank</fullName>
                </value>
                <value>
                    <fullName>Capital One</fullName>
                </value>
                <value>
                    <fullName>Ally</fullName>
                </value>
                <value>
                    <fullName>USAA</fullName>
                </value>
                <value>
                    <fullName>Other Credit Union</fullName>
                </value>
                <value>
                    <fullName>Other Financial Institution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEPT_Have_financial_advisor_there__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEPT_Have financial advisor there</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEPT_Last_Response_Date_For_FI__c</fullName>
        <label>LEPT_Last Response Date for FI</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEPT_Last_Response_Date_for_Comments__c</fullName>
        <label>LEPT_Last Response Date for Comments</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEPT_Last_Updated_On__c</fullName>
        <label>MM Primary Account Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEPT_Loan_rates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEPT_Loan rates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEPT_Online_mobile_apps__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEPT_Online/mobile apps</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEPT_Other__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEPT_Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REC_LEPT_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Checing Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Recommendation 1 - Life Events - Other Milestones</description>
        <inlineHelpText>Recommendation 1 - Life Events - Other Milestones</inlineHelpText>
        <label>HELOC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RV Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Health Savings Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Personal Line of Credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Student Loans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_6__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CDs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_7__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Money Market</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Na_PrimaryTransactionController.cls
public class Na_PrimaryTransactionController
{
    public string script { get; set; }
    public Account AccountC { get; set; }
    public string NA_id { get; set; }

    public string accId2 { get; set; }
    public NeedAssessmentController parentController { get; set; }
    public Needs_Assesment__c lmm_New;


    public Needs_Assesment__c getlmm_New()
    {

        setObjects();

        return lmm_New;
    }
    public void setlmm_New(Needs_Assesment__c val)
    {
        lmm_New = val;
    }


    public void setObjects()
    {

        accId2 = parentController.account[0].Id;

        list<Needs_Assesment__c> naother = [select id, LEPT_Financial_Institution__c , LEPT_Deposit_rates__c, LEPT_Convenient_locations__c , LEPT_Have_financial_advisor_there__c,
                         LEPT_Last_Updated_On__c, LEPT_Loan_rates__c,LEPT_Online_mobile_apps__c,LEPT_Other__c,
                         Rec_LEOM_1__c, Rec_LEOM_2__c, Rec_LEOM_3__c,LEPT_Comments__c,LEPT_Last_Response_Date_For_FI__c,LEPT_Last_Response_Date_for_Comments__c,
                         Rec_LEOM_4__c, Rec_LEOM_5__c, Rec_LEOM_6__c, Rec_LEOM_7__c,REC_LEPT_1__c from Needs_Assesment__c


                           where member__c =:accId2 ORDER by LastModifiedDate desc];

        if (naother.size() > 0)
        {
            NA_id = naother[0].Id;

            if (AccountC.NA_LEOM_Expired__c)
            {
                lmm_New = new Needs_Assesment__c();
                lmm_New.ID = NA_id;


            }
            else
            {
                lmm_New = naother[0];
            }
        }
        else
        {

            lmm_New = new Needs_Assesment__c();

        }
    }




    public void SubmitFeedbackForm()
    {


        if( lmm_New.LEPT_Financial_Institution__c != null || lmm_New.LEPT_Convenient_locations__c != null || lmm_New.LEPT_Have_financial_advisor_there__c != null || lmm_New.LEPT_Loan_rates__c != null || lmm_New.LEPT_Online_mobile_apps__c != null || lmm_New.LEPT_Other__c != null || lmm_New.LEPT_Comments__c != null || lmm_New.Rec_LEOM_1__c || lmm_New.Rec_LEOM_2__c || lmm_New.Rec_LEOM_3__c || lmm_New.Rec_LEOM_4__c || lmm_New.Rec_LEOM_5__c || lmm_New.Rec_LEOM_6__c || lmm_New.Rec_LEOM_7__c)



        {

          

            Needs_Assesment__c nao_tobeinserted = new Needs_Assesment__c();
            nao_tobeinserted.Id = lmm_New.Id;


            nao_tobeinserted.LEPT_Financial_Institution__c = lmm_New.LEPT_Financial_Institution__c;
            nao_tobeinserted.LEPT_Deposit_rates__c = lmm_New.LEPT_Deposit_rates__c;
            nao_tobeinserted.LEPT_Convenient_locations__c = lmm_New.LEPT_Convenient_locations__c;
            nao_tobeinserted.LEPT_Have_financial_advisor_there__c = lmm_New.LEPT_Have_financial_advisor_there__c;            
            nao_tobeinserted.LEPT_Loan_rates__c = lmm_New.LEPT_Loan_rates__c;
            nao_tobeinserted.LEPT_Online_mobile_apps__c = lmm_New.LEPT_Online_mobile_apps__c;
            nao_tobeinserted.LEPT_Other__c = lmm_New.LEPT_Other__c;
            nao_tobeinserted.LEPT_Comments__c = lmm_New.LEPT_Comments__c;
            

            nao_tobeinserted.Rec_LEOM_1__c = lmm_New.Rec_LEOM_1__c;
            nao_tobeinserted.Rec_LEOM_2__c = lmm_New.Rec_LEOM_2__c;
            nao_tobeinserted.Rec_LEOM_3__c = lmm_New.Rec_LEOM_3__c;
            nao_tobeinserted.Rec_LEOM_4__c = lmm_New.Rec_LEOM_4__c;
            nao_tobeinserted.Rec_LEOM_5__c = lmm_New.Rec_LEOM_5__c;
            nao_tobeinserted.Rec_LEOM_6__c = lmm_New.Rec_LEOM_6__c;
            nao_tobeinserted.Rec_LEOM_7__c = lmm_New.Rec_LEOM_7__c;
            
            nao_tobeinserted.Rec_LEPT_1__c = lmm_New.Rec_LEPT_1__c;
            
            

            if (nao_tobeinserted.Id == null)
            {
                nao_tobeinserted.Member__c = accId2;
            }
            nao_tobeinserted.LEPT_Last_Updated_On__c = system.today();
            script = '1';


            upsert nao_tobeinserted;




        }
        RefreshParent();
    }



    public void resetscript()
    {
        script = '';
    }

    public void RefreshParent()
    {



        parentController.RefreshAccount();




        parentController.GetPrimaryTransactionTabClass();
    }




}