src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a self-relationship field used to link SubAccounts(recType) to the respective MembershipAccounts(recType)</description>
        <label>Parent Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Card</fullName>
        <active>true</active>
        <description>This record type will be used to store all the CARD Information</description>
        <label>Card</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/PersonLookUpOnCaseControllerTest.cls
@isTest
public class PersonLookUpOnCaseControllerTest {
    
    static testMethod void testMethod1(){
        
        Account acc = new Account();
        
        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'test';
        insert accDetails;
        
        Person_Account__c pa = new Person_Account__c();
            pa.PersonID__c = acc.Id;
            pa.Account_Number__c = accDetails.Id;
        insert pa;
        
        PageReference pageRef = Page.PersonLookUpOnCase;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('accId', accDetails.Id);        
        PersonLookUpOnCaseController controller = new PersonLookUpOnCaseController(new ApexPages.StandardController(acc)); 
    }
    
    static testMethod void PersonLookUpOnCaseSubAccsTest(){
        
        Account acc = new Account();
        
        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'test';
            accDetails.RecType__c = 'ACCT';
        insert accDetails;
        
        Account_Details__c accDetails1 = new Account_Details__c();
            accDetails1.RecType__c = 'CARD';
            accDetails1.Parent_Account__c = accDetails.Id;
        insert accDetails1;
        
        Person_Account__c pa = new Person_Account__c();
            pa.PersonID__c = acc.Id;
            pa.Account_Number__c = accDetails.Id;
        insert pa;
        
        PageReference pageRef = Page.PersonLookUpOnCaseSubAccs;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('accId', accDetails1.Id);        
        PersonLookUpOnCaseSubAccsController controller = new PersonLookUpOnCaseSubAccsController(new ApexPages.StandardController(acc));        
    }
}