src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_LEOM_Expired__c</fullName>
        <description>Set a flag used for NA LEOM section expiration</description>
        <formula>IF( (Last_NA_LEOM__c  = null  ||   
      Last_NA_LEOM__c &lt;  NOW() -(1440/1440) ) &amp;&amp; 
      NA_Eligibility__c  = TRUE ,
          true, 
          false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NA LEOM Expired</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/NA_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Instituition__c</fullName>
        <label>Financial_Instituition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chevron Federal Credit Union</fullName>
                </value>
                <value>
                    <fullName>Spectrum Credit Union</fullName>
                </value>
                <value>
                    <fullName>Bank of America</fullName>
                </value>
                <value>
                    <fullName>Chase Bank</fullName>
                </value>
                <value>
                    <fullName>Wells Fargo</fullName>
                </value>
                <value>
                    <fullName>Citibank</fullName>
                </value>
                <value>
                    <fullName>US Bank</fullName>
                </value>
                <value>
                    <fullName>Capital One</fullName>
                </value>
                <value>
                    <fullName>Ally</fullName>
                </value>
                <value>
                    <fullName>USAA</fullName>
                </value>
                <value>
                    <fullName>Other Credit Union</fullName>
                </value>
                <value>
                    <fullName>Other Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Spectrum Federal Credit Union</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Needs_Assessment__c</fullName>
        <label>Needs_Assessment</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipLabel>NA_Deposits</relationshipLabel>
        <relationshipName>NA_Deposits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Certificate of Deposit (CD)</fullName>
                </value>
                <value>
                    <fullName>Money Market Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NA_Deposit</label>
    <nameField>
        <label>NA_Deposits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA_Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>LEEM_Comments__c</fullName>
        <label>LEEM_Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LEEM_Deductible_Plan__c</fullName>
        <label>LEEM_Deductible_Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEEM_Health_Savings_Account__c</fullName>
        <label>LEEM_Health_Savings_Account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEEM_Last_Updated_On__c</fullName>
        <label>LEEM_Last_Updated_On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEEM_Money_In_Primary_Account__c</fullName>
        <label>LEEM_Money_In_Primary_Account</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LEEM_Savings_For_Retirement_401__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEEM_Savings_For_Retirement_401</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEEM_Savings_For_Retirement_IRA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEEM_Savings_For_Retirement_IRA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEEM_Savings_For_Retirement_O_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEEM_Savings_For_Retirement_O_Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LEEM_Savings_For_Retirement_O_R_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LEEM_Savings_For_Retirement_O_R_Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REC_LEEM_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>REC_LEEM_1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REC_LEEM_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>REC_LEEM_2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Health Savings Account</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/classes/Na_Earn_MoreController.cls
public class Na_Earn_MoreController
{
public list<NA_Deposit__c> deposits;
public string script{get;set;}

public boolean sizeExceeds {get;set;} 

    public Account AccountC{get;set;}
    public string NA_id {get;set;}
    public integer depositeid { get; set; }
    public string accId2 { get; set; }
    public NeedAssessmentController parentController {get;set;}
      public Needs_Assesment__c  lcf_New;
       
       
        public Needs_Assesment__c  getlcf_New(){
            
       if(lcf_New == null)
       {
        
           setObjects();
       }
       else
       {
       		list<Needs_Assesment__c> naother = [select id,
                    Rec_LEOM_3__c,
                    Rec_LEEM_2__c,
                    Rec_LEEM_1__c
            
                     from Needs_Assesment__c
                    where member__c =:accId2 ORDER by LastModifiedDate desc];
                    
	        if (naother.size() > 0)
	        {
	        	lcf_New.Rec_LEEM_1__c = naother[0].Rec_LEEM_1__c;
	        }     	
       }
        return lcf_New;
    }
    public void setlcf_New(Needs_Assesment__c  val){
        lcf_New = val;
    }
    

    public void setObjects(){
        
        accId2 = parentController.account[0].Id;
        list<Needs_Assesment__c> naother = [select id,LEEM_Health_Savings_Account__c,
                    
                    LEEM_Deductible_Plan__c,
                    
                    LEEM_Comments__c,
                    LEEM_Savings_For_Retirement_O_Account__c,
                    LEEM_Savings_For_Retirement_O_R_Account__c,
                    LEEM_Savings_For_Retirement_IRA__c,
                    LEEM_Savings_For_Retirement_401__c,
                    LEEM_Money_In_Primary_Account__c,
                    LEEM_Last_Updated_On__c,
                    Rec_LEOM_3__c,
                    Rec_LEEM_2__c,
                    Rec_LEEM_1__c
            
                     from Needs_Assesment__c
                    where member__c =:accId2 ORDER by LastModifiedDate desc];
        if (naother.size() > 0)
        {
            NA_id = naother[0].Id;
            
            if(AccountC.NA_LEOM_Expired__c)
            {
                 lcf_New = new Needs_Assesment__c();
                 lcf_New .ID = NA_id;
                 

            }
            else
            {
                 lcf_New = naother [0];
            }
        }
        else
        {
  
            lcf_New = new Needs_Assesment__c();
            
        }
        
         deposits = [select id, Balance__c, Financial_Instituition__c, Needs_Assessment__c, Rate__c, Type__c
                        from NA_Deposit__c where Needs_Assessment__c =: lcf_New.ID];
    }

public list<NA_Deposit__c> Getdeposits()
    {
        
        if (deposits == null)
        {
            deposits = new list<NA_Deposit__c>();
        }


        return deposits;
    }

   public void setdeposits(list<NA_Deposit__c> value)
    {
       
            deposits = value;
       



    }

  public void addDeposit()
    {
        if(deposits.size() == 5)
        {
            sizeExceeds = true;
            return;
        }
        sizeExceeds =false;
        NA_Deposit__c obj = new NA_Deposit__c();
        //obj.Needs_Assessment__c = NA_id;
        deposits.add(obj);

    }
    
    
     public void deletedeposits()
    {
        


        sizeExceeds = false;
        for (integer i = 0; i < deposits.size(); i++)
        {
            if (depositeid == i)
            {

                if (!string.isEmpty(deposits[i].id))
                {
                    delete deposits[i];
                }


                deposits.remove(i);
                
                break;
            }
        }




    }

   public void SubmitEarnMoreForm()
    {
        sizeExceeds = false;
        //If( deposits.size() > 0 || lcf_New.LEEM_Health_Savings_Account__c != null || lcf_New.REC_LEEM_1__c || lcf_New.REC_LEEM_2__c || lcf_New.Rec_LEOM_3__c || lcf_New.LEEM_Deductible_Plan__c != null|| lcf_New.LEEM_Savings_For_Retirement_O_Account__c || lcf_New.LEEM_Savings_For_Retirement_IRA__c || lcf_New.LEEM_Savings_For_Retirement_401__c || lcf_New.LEEM_Money_In_Primary_Account__c != null ) {
        {
            
                    Needs_Assesment__c  nao_tobeinserted = new Needs_Assesment__c  ();
                    nao_tobeinserted.Id = lcf_New .Id;
                    
                    
                     nao_tobeinserted.LEEM_Health_Savings_Account__c= lcf_New .LEEM_Health_Savings_Account__c;
                     
                     nao_tobeinserted.LEEM_Deductible_Plan__c= lcf_New .LEEM_Deductible_Plan__c;
                     
                    nao_tobeinserted.LEEM_Comments__c= lcf_New .LEEM_Comments__c;
                    nao_tobeinserted.LEEM_Savings_For_Retirement_O_Account__c= lcf_New .LEEM_Savings_For_Retirement_O_Account__c;
                    nao_tobeinserted.LEEM_Savings_For_Retirement_O_R_Account__c= lcf_New .LEEM_Savings_For_Retirement_O_R_Account__c;
                    
                    nao_tobeinserted.LEEM_Savings_For_Retirement_IRA__c= lcf_New .LEEM_Savings_For_Retirement_IRA__c;
                    nao_tobeinserted.LEEM_Savings_For_Retirement_401__c= lcf_New .LEEM_Savings_For_Retirement_401__c;
                    nao_tobeinserted.LEEM_Money_In_Primary_Account__c= lcf_New .LEEM_Money_In_Primary_Account__c;
                                          
                    nao_tobeinserted.REC_LEEM_1__c = lcf_New.REC_LEEM_1__c;
                    nao_tobeinserted.REC_LEEM_2__c = lcf_New.REC_LEEM_2__c;
                    nao_tobeinserted.Rec_LEOM_3__c = lcf_New.Rec_LEOM_3__c;
                     
                    if(nao_tobeinserted.Id == null)
                    {
                    nao_tobeinserted.Member__c = accId2 ;
                    }
                    nao_tobeinserted.LEEM_Last_Updated_On__c= system.today();
                    lcf_New.LEEM_Last_Updated_On__c =nao_tobeinserted.LEEM_Last_Updated_On__c;
                    
                        script = '1';
                     
                        upsert  nao_tobeinserted;
                      lcf_New.id = nao_tobeinserted.Id;
                         for (integer i = 0; i < deposits.size(); i++)
                        {
                            if(deposits[i].Needs_Assessment__c  == null)
                            {
                                
                            deposits[i].Needs_Assessment__c = nao_tobeinserted.id;
                            }
                        }

                 upsert deposits;
    
       }
                RefreshParent();
    }
    
   
    
     public void resetscript()
     {
        script = '';
     }
  
     public void RefreshParent(){
             
        
           
           parentController.RefreshAccount();
         



           parentController.GetCurrentFeedbackTabClass();
           
     }
}