src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/GetRelatedAccountsforCase.cls
public class GetRelatedAccountsforCase {
	
	@AuraEnabled 
    public static object GetCaseAccounts(string CaseId){
    	
    	 Case caseDetail = [select status, Attachments_Are_Deleted__c, Account_Number__c from Case where Id =: CaseId];
    	 set<id> accountIds = new set<id>();
    	 List<account_details__c> ListAccountsDetails = new List<account_details__c>(); 
    	 
    	 List<CaseAccountMemberDetail__c> relatedAccountsList = new List<CaseAccountMemberDetail__c>();
    	 
    	 relatedAccountsList= [select id, Case__c, Account_Name__c, MemberAccountid__c from CaseAccountMemberDetail__c where Case__c =:  CaseId and MemberAccountid__c !=: caseDetail.Account_Number__c];
    	 
    	 for(CaseAccountMemberDetail__c camd : relatedAccountsList){
    	 	accountIds.add(camd.MemberAccountid__c);
    	 }
    	 
    	 ListAccountsDetails = [select id, Name,RecordType.Name,Brand__c, TypeTranslate__c, RecType__c from account_details__c where id IN: accountIds];
    	 
    	 return ListAccountsDetails;
    
    }
    
}