src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a self-relationship field used to link SubAccounts(recType) to the respective MembershipAccounts(recType)</description>
        <label>Parent Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/PersonAccount.object
<CustomObject>
    <recordTypes>
        <fullName>PersonAccount</fullName>
        <active>true</active>
        <label>Person Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/PersonNameforSubAccountsController.cls
public class PersonNameforSubAccountsController {
    
    private final Account_Details__c cRec;
    public string accId;
    public string accId1;
    public list<Person_Account__c> paList{get;set;}
    
    public PersonNameforSubAccountsController(ApexPages.StandardController controller){
      //  this.cRec = (Account_Details__c)Controller.getRecord();
        accId = System.currentPageReference().getParameters().get('Id');
        system.debug('Account Id is:::::'+accId);
        if(accId!=NULL || accId!=''){
            personAccounts(accId);    
        }else{
            
        }
    } 
        
        public void personAccounts(string accId){
       
         paList = new list<Person_Account__c>();         
       //  paList = [SELECT Id FROM Person_Account__c WHERE Account_Number__c =:accId];            
       //  System.debug('PersonAccount List is:::'+paList);     
        
         Account_Details__c accDetails = [Select Parent_Account__c from Account_Details__c where Id=:accId Limit 1];          
            if(accDetails.Parent_Account__c != null){
              accId1 = accDetails.Parent_Account__c;
            }else{
             // ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Parent account number not available.'));
            }
 
         paList = [SELECT Id,
                          Account_Number__c,
                          PersonId__c,
                          PersonID__r.Name,
                          TypeTranslate__c FROM Person_Account__c WHERE Account_Number__c =:accId OR Account_Number__c =:accId1];
            
         System.debug('Person AccountList is:::::'+paList); 
      
    }
    }