src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Approve_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <label>Attachment Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_ID__c</fullName>
        <label>Case ID</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Approve_Attachment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approved Attachments</label>
    <nameField>
        <displayFormat>A - {0000}</displayFormat>
        <label>ApproveAttachmentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Canned_Message_Metadata__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Chevron_Footer__c</fullName>
        <label>Chevron Footer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Chevron_Header__c</fullName>
        <label>Chevron Header</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Spectrum_Footer__c</fullName>
        <label>Spectrum Footer</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Spectrum_Header__c</fullName>
        <label>Spectrum Header</label>
        <type>TextArea</type>
    </fields>
    <label>Canned Message Metadata</label>
</CustomObject>

src/objects/Canned_Responses__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
                <value>
                    <fullName>Chevron</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Lookup_Text__c</fullName>
        <label>Primary Lookup Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Lookup_Text__c</fullName>
        <label>Secondary Lookup Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Lookup_Text__c</fullName>
        <label>Tertiary Lookup Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Canned Responses</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>Canned Responses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canned Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <description>This field will be used to uniquely identify a Person.</description>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Member_Comment__c.object
<CustomObject>
    <description>Comments intended to be visible to the member</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Case__r.BrandfromAccount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Member Comments</relationshipLabel>
        <relationshipName>Member_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_Comment__c</fullName>
        <label>Member Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Member Comment</label>
    <nameField>
        <displayFormat>MCOM{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CannedResponsesForCommentTest.cls
@isTest
public class CannedResponsesForCommentTest{

@testSetup static void methodName() 
{
	string fid ='0000999999'  ;    
         String uid = UserInfo.getUserId();
         Profile profile = [SELECT Id,Name FROM Profile where Name ='Customer Community Login User' ];
         RecordType recordtype =[SELECT Id,Name FROM RecordType WHERE Name='Person Account'];
         User currentUser = [SELECT LocaleSidKey, LanguageLocaleKey, TimeZoneSidKey, EmailEncodingKey FROM User WHERE Id=:uid];
         Site communityid = [SELECT Id FROM Site where Name ='customer_messaging_center'];
         SamlSsoConfig samlSsoProviderId = [Select Id from SamlSsoConfig where DeveloperName='DI_SAML' ];
         Boolean Create = true;
         string ids;
         string ids2;
     
          // Creating  Account  
          Account acc = new Account();
          acc.Owner = currentUser;
          acc.FirstName = 'tFName';
          acc.LastName='TLName';
          acc.recordtypeid = recordtype.Id;
          acc.PersonID__C ='V554870800';
          
          acc.PersonEmail ='acctest@test.com';
          
          insert acc;
          
          Contact c = [SELECT Id,AccountId FROM Contact WHERE AccountId=:acc.Id];

            // Creating new user
          User u = new User();
            u.Username = 'testUserName@test.com' ;
            u.FederationIdentifier =fid ;
            u.Email ='test@test.com' ;
            u.FirstName ='tFirstName' ;
            u.LastName ='tLastName' ;
            u.ProfileId = profile.Id;
            u.ContactId = c.Id;
            u.Alias ='tAlias';
           
            u.LocaleSidKey = currentUser.LocaleSidKey;
            u.LanguageLocaleKey = currentUser.LanguageLocaleKey; 
            u.TimeZoneSidKey = currentUser.TimeZoneSidKey; 
            u.EmailEncodingKey = currentUser.EmailEncodingKey;
            insert u;
            
            /*PermissionSet ps = [SELECT Id, Name, Label FROM PermissionSet where label = 'Read permission for member comment'];
            
            PermissionSetAssignment psa = new PermissionSetAssignment(PermissionSetId = ps.ID, AssigneeId = u.id);
            insert psa;   */       
            
           // Creating Account_Details__c
            List<Account_Details__c> Account_Details = new List<Account_Details__c>();
            Account_Details__c ad = new Account_Details__c();
            ad.Name = fid;
            
            Account_Details.add(ad);
            insert Account_Details;
           // Creating  Person_Account__c
            
             Person_Account__c pa = new Person_Account__c();
             pa.Account_Number__c = ad.id;
             pa.Name_Type__c = 0;
             pa.PersonID__c = acc.Id;
             insert pa;
             string view='';
             
            Canned_Message_Metadata__c cannedMessageHeader = new Canned_Message_Metadata__c();
            cannedMessageHeader.Name = 'Metadata';
            cannedMessageHeader.Chevron_Footer__c = 'Thanks, Chevron Support 999-999-9999';
            cannedMessageHeader.Spectrum_Footer__c = 'Thanks, Spectrum Support 999-999-9999';
            cannedMessageHeader.Chevron_Header__c = 'Dear Member,';
            cannedMessageHeader.Spectrum_Header__c = 'Dear Member,';
            insert cannedMessageHeader;
             test.startTest();
             Case cas = new Case();
       
        system.runas(u)
          {
             cas.Subject = 'Test Subject Inquires';
             cas.Description = 'Test Description Inquires';
             cas.Account_Number__c = pa.Account_Number__c;
             cas.AccountID = c.AccountId;
             cas.Primary_Category__c = 'Inquires';
             cas.Status ='Open';
             insert cas;
         }
    
    
   
        List<Attachment> AttachmentLst = new List<Attachment>();
        for(integer i=0 ; i <= 5 ; i++){
            Attachment attach=new Attachment();    
            attach.Name='Unit Test Attachment';
            Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
            attach.body=bodyBlob;
            attach.parentId=cas.id;
            AttachmentLst.add(attach);
        }        
        insert AttachmentLst;
    Approve_Attachment__c ap = new Approve_Attachment__c();
        ap.Attachment_Id__c = AttachmentLst[0].id;
        ap.Case_ID__c = cas.id;      
        insert ap;
        
        Approve_Attachment__c ap2 = new Approve_Attachment__c();
        //ap.name = 'Test123';
        ap2.Attachment_Id__c = AttachmentLst[1].id;
        ap2.Case_ID__c = cas.id;
        insert ap2;
    
    	
        
        

             //List<Canned_Responses__c> Canned = new List<Canned_Responses__c>{};
           
            Canned_Responses__c cr = new Canned_Responses__c();
            cr.Brand__c = 'Chevron';
            cr.Primary_Lookup_Text__c = 'CFCU Contact Information';
            cr.Secondary_Lookup_Text__c = 'Test';
            cr.Active__c = true;
            cr.Tertiary_Lookup_Text__c = 'Test';
            insert cr;
    test.stoptest();
}


    static testmethod void validateStandardController(){
        test.startTest();
		Case cas = [select id from case limit 1];
        
   List<Attachment>     AttachmentLst = [select id from Attachment where parentid =: cas.id];
        
		Canned_Responses__c cr = [select id from Canned_Responses__c limit 1];
		
		 List<Member_Comment__c> memberCommentList= new List<Member_Comment__c>();
            Member_Comment__c memberComment= new Member_Comment__c(Case__c = cas.Id);
            PageReference pageRef = Page.Canned_Responses_For_Member_Comment;
            Test.setCurrentPage(pageRef);
            apexpages.currentpage().getparameters().put('caseId' , cas.id);
            
            
            ApexPages.StandardController sc = new ApexPages.StandardController(memberComment);        
            CannedResponsesForComment crc = new CannedResponsesForComment(sc);      
                 
            List<CannedResponsesForComment.attachmentWrapper> wrapList = crc.wrapperLst;
            for(CannedResponsesForComment.attachmentWrapper obj : wrapList){
                if(obj.attachmentobj.Id==AttachmentLst[2].Id){
                 obj.checkvalue = true;
                }
                if(obj.attachmentobj.Id==AttachmentLst[0].Id){
                 obj.checkvalue = true;
                }
            }
            
           
            crc.MemberDescription = 'Test';
            crc.brand = 'Chevron';
            crc.selectedPrimary =  'CFCU Contact Information';
            crc.selectedSecondary = '0';
            crc.selectedTertiary = '0';
            crc.selectedSecondary = 'Test';
            crc.getItems();
            crc.getPrimary();
            crc.getSecondary();
            crc.getTertiary();
            crc.getTitlesBySearchText();
            crc.savenew();
            crc.selectedTertiary = 'Test';
            crc.selectedTitle = cr.id;
            crc.getSelectedDecription();
            crc.getTitlesByCategories();
            crc.save();
            crc.cancelall();
    test.stopTest();
      }
   
 }