src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Branch1__c</fullName>
        <formula>Text(Current_Branch__c)  &amp;  &apos; &apos;  &amp; CASE(Current_Branch__c, 
72, &apos;eBranch&apos;,
99, &apos;ATM&apos;,
96, &apos;Consumer Lending&apos;,
0, &apos;Head Quarter&apos;,
200, &apos;Spectrum&apos;,
270, &apos;Spectrum&apos;,
24, &apos;CA Bakersfield&apos;, 
05, &apos;Brea&apos;, 
20, &apos;Camino Media&apos;, 
02, &apos;Concord&apos;, 
09, &apos;El Segundo&apos;, 
206, &apos;Spectrum Pleasant Hill&apos;, 
21, &apos;Kern River/ China Grade&apos;, 
04, &apos;Richmond&apos;, 
03, &apos;San Ramon&apos;, 
201, &apos;Spectrum San Francisco&apos;, 
29, &apos;Denver&apos;, 
06, &apos;Covington&apos;, 
203, &apos;Spectrum Frederick Bechtel&apos;, 
23, &apos;Pascagoula&apos;, 
19, &apos;Aramco&apos;, 
17, &apos;Bellaire&apos;, 
14, &apos;1600 Smith&apos;, 
208, &apos;El Paso&apos;, 
08, &apos;El paso&apos;,
25, &apos;Post Oak&apos;, 
202, &apos;Spectrum Houston Galleria&apos;, 
27, &apos;Bountiful&apos;, 
28, &apos;Salt Lake City Refinery&apos;, 
205, &apos;Spectrum Reston&apos;,
01, &apos;San Francisco&apos;, 
22, &apos;West Loop&apos;, 
53, &apos;Electronic&apos;, 
55, &apos;Inactive, Low Balance, No Loans*&apos;, 
56, &apos;Inactive, Low Balance, Chargeoffs&apos;, 
57, &apos;Inactive, Low Balance, Bad Address&apos;, 
88, &apos;Operation Services&apos;, 
93, &apos;Member Services&apos;, 
98, &apos;Remote Access&apos;, 
204, &apos;Spectrum Westridge Mall&apos;, 
253, &apos;Spectrum Electronic&apos;, 
255, &apos;Spectrum Inactive, Low Balance, No Loans*&apos;, 
256, &apos;Spectrum Inactive, Low Balance, Chargeoffs&apos;, 
257, &apos;Spectrum Inactive, Low Balance, Bad Address&apos;, 
293, &apos;Spectrum Member Services Branch&apos;,  
&apos;&apos;)</formula>
        <label>Current Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Episys_User_ID__c</fullName>
        <label>Episys User ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Branch__c</fullName>
        <label>Assigned Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <formula>Text(Assigned_Branch__c) &amp; &apos; &apos; &amp; 
CASE(Assigned_Branch__c, 
96, &apos;Direct Lending&apos;, 
200, &apos;Spectrum&apos;, 
270, &apos;Spectrum&apos;, 
299, &apos;Spectrum&apos;, 
99, &apos;ATM&apos;, 
24, &apos;Bakersfield&apos;, 
05, &apos;Brea&apos;, 
20, &apos;Camino Media&apos;, 
02, &apos;Concord&apos;, 
09, &apos;El Segundo&apos;, 
206, &apos;Pleasant Hill&apos;, 
21, &apos;Kern River/ China Grade&apos;, 
04, &apos;Richmond&apos;, 
03, &apos;San Ramon&apos;, 
201, &apos;Spectrum San Francisco&apos;, 
29, &apos;Denver&apos;, 
06, &apos;Covington&apos;, 
203, &apos;Spectrum Frederick Bechtel&apos;, 
23, &apos;Pascagoula&apos;, 
19, &apos;Aramco&apos;, 
17, &apos;Bellaire&apos;, 
14, &apos;1600 Smith&apos;, 
208, &apos;El Paso&apos;, 
25, &apos;Post Oak&apos;, 
202, &apos;Spectrum Houston Galleria&apos;, 
207, &apos;Bountiful&apos;, 
28, &apos;Salt Lake City Refinery&apos;, 
205, &apos;Spectrum Reston&apos;, 
01, &apos;San Francisco&apos;, 
22, &apos;West Loop&apos;, 
53, &apos;Electronic&apos;, 
55, &apos;Inactive, Low Balance, No Loans*&apos;, 
56, &apos;Inactive, Low Balance, Chargeoffs&apos;, 
57, &apos;Inactive, Low Balance, Bad Address&apos;, 
88, &apos;Operation Services&apos;, 
93, &apos;Member Services&apos;, 
98, &apos;Remote Access&apos;, 
204, &apos;Spectrum Westridge Mall&apos;, 
253, &apos;Spectrum Electronic&apos;, 
255, &apos;Spectrum Inactive, Low Balance, No Loans*&apos;, 
256, &apos;Spectrum Inactive, Low Balance, Chargeoffs&apos;, 
257, &apos;Spectrum Inactive, Low Balance, Bad Address&apos;, 
293, &apos;Spectrum Member Services Branch&apos;, 
&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Episys_Name__c</fullName>
        <label>Episys Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Episys_User_ID__c</fullName>
        <label>Episys User ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Episys_User__c</fullName>
        <formula>CreatedBy.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Episys User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimate_Value__c</fullName>
        <label>Estimate Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Keep__c</fullName>
        <defaultValue>false</defaultValue>
        <description>By pass auto assignment rules and keep ownership of the Lead</description>
        <inlineHelpText>Keep ownership of the Lead and do not allow the assignment rules to route it to a group&apos;s queue.</inlineHelpText>
        <label>Keep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Branch__c</fullName>
        <label>Member Branch</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_2__c</fullName>
        <label>Street Address 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>false</active>
        <businessProcess>Default</businessProcess>
        <description>record type for all the Branch Users</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/main/default/classes/CreateNewLeadController.cls
public class CreateNewLeadController
{
    public string AccountID {get;set;}
    public string MemberAccountID {get;set;}
    
    public string EstimateAmount {get;set;}
    public string LoanAmount {get;set;}
   
    public Lead leadObject {get;set;}
    public string OwnerName {get;set;}
    public string OwnerID {get;set;}
    public string accountName {get;set;}
    public list<SelectOption> ProductTypeList {get;set;}
    public string productTypeClass {get;set;}
    public string brandClass {get;set;}
    public decimal SelectedEpisysUserId {get;set;}
    
    string uid= UserInfo.getUserId();
    public string branchOption { get;set; }
    public list<SelectOption> BranchOptionList{get;set;}
    
     public CreateNewLeadController(ApexPages.StandardController controller){

        AccountID = System.currentPageReference().getParameters().get('accountid');               
        
        /*List<Account> accounts = [SElect owner.alias from Account where ID =: AccountID]  ;
        String Alias=''; 
        if (accounts.size() > 0 )
        {
            Alias = accounts[0].owner.alias;
            
        }
        List<user> usrs = [Select id from user where alias =: Alias];
        if (usrs.size() > 0)
        {
            uid = usrs[0].id;
        }*/
          system.debug('AccountID --- from page ' + accountid);
         
         
         
         User usr = [Select id, name, alias from User where id=:uid];
       List<Episys_User__c> eusr = [SELECT id,
                      alias__c,
                      Assigned_Branch__c from Episys_User__c where alias__c=:usr.alias]; 
         
       
        Schema.DescribeFieldResult statusFieldDescription = Lead.Product_Type__c.getDescribe();
        
        productTypeClass = '';
        brandClass = '';
        list<SelectOption> op = new list<SelectOption>();
        op.add(new SelectOption('-None-','-None-'));
        for (Schema.Picklistentry picklistEntry : statusFieldDescription.getPicklistValues())
        {
            op.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
        }
        ProductTypeList = op;        

        if(AccountID == null)
        {
         
         ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Account not found');
            return;
        }
               
        List<Account> acclist = [Select Id,Name,Alternate_Email__pc,Owner.Name,Owner.ID,Suffix,FirstName,MiddleName,
        LastName,PersonEmail,Residential_City__pc,Residential_Country_Code__pc,Residential_Country__pc,Residential_Extra_Address__pc,
        Residential_State__pc,Residential_Street__pc,Residential_Zipocde__pc,PersonMobilePhone, Home_Phone__pc, Phone  from Account where Id =: AccountID limit 1];
        Account acc = acclist[0];
        if(acc == null)
        {
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Invalid Account');
            ApexPages.addMessage(msgs );
            return;

        }
        leadObject = new Lead();
        leadObject.Person__c = AccountID;
        leadObject.FirstName = acc.FirstName;
        leadObject.LastName = acc.LastName;
        leadObject.MiddleName = acc.MiddleName;
        leadObject.Suffix = acc.Suffix;
        leadObject.Home_Phone__c = acc.Home_Phone__pc;
        leadObject.Street_Address_1__c = acc.Residential_Street__pc;
        //OwnerName =  acc.Owner.Name;
        OwnerName = userinfo.getFirstName() + ' ' + userinfo.getLastName();
        OwnerID = acc.Owner.ID;        
        leadObject.Street_Address_2__c = acc.Residential_Extra_Address__pc;
        leadObject.Country__c = acc.Residential_Country_Code__pc;
        leadObject.State__c = acc.Residential_State__pc;
        leadObject.City__c = acc.Residential_City__pc;
                leadObject.Zip_Code__c = acc.Residential_Zipocde__pc;
         if(MemberAccountID!=NULL){
          leadObject.Member_Branch__c = currentBranch(MemberAccountID); }    
                  BranchOptionList = itemsList();  
          leadObject.Estimate_Value__c = EstimateAmount;
          leadObject.Loan_Amount__c = LoanAmount;    
    }
     //member branch code 
        public ID currentBranch(String memID){           
        List<Account_Details__c> mem_acc = [select id, Current_Branch1__c from Account_Details__c where id=:memID]; 
        if(mem_acc != null){
          return mem_acc[0].id;
         }
        else return '';
        } 
         
    
    
    
    
    public List<SelectOption> ItemsList(){
        User usr = [Select id, name, alias from User where id=:uid];
       List<Episys_User__c> eusr = [SELECT id,
                      alias__c,
                      Assigned_Branch__c,Episys_ID__c, Branch_Name__c,Default__c from Episys_User__c where alias__c=:usr.alias order by Default__c]; 
        
         List<SelectOption> options = new List<SelectOption>();
         /*if(eusr.size()>0){
         BranchOption = eusr[0].Branch_Name__c;
                leadObject.Episys_User_ID__c =  eusr[0].Episys_ID__c;
                } */
         for(Episys_User__c eu : eusr ){
            if(eu.Default__c||(eusr.size()==1))
            {
                BranchOption = eu.Branch_Name__c;
                leadObject.Episys_User_ID__c =  eu.Episys_ID__c;
            }
            
            if(!eu.Default__c&&(eusr.size()!=1))
            {
                BranchOption = eu.Branch_Name__c;
                leadObject.Episys_User_ID__c =  eu.Episys_ID__c;
            }
            options.add(new SelectOption(eu.Branch_Name__c, eu.Branch_Name__c));
         }
                   
        return options;
         }
         
    
    
    public PageReference Save()
    {
        brandClass = '';
        productTypeClass = '';
        if(String.isBlank(leadObject.Product_Type__c) || leadObject.Product_Type__c == '--None--'){
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Product Type: You must enter a value');
            ApexPages.addMessage(msgs);
            productTypeClass = 'error';
            return null;
       }
       if(String.isBlank(leadObject.Brand__c) || leadObject.Brand__c == '--None--'){
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Brand: You must enter a value');
            ApexPages.addMessage(msgs);
            brandClass = 'error';
            return null;
       }
       system.debug('---SelectedEpisysUserId--'+SelectedEpisysUserId);
       //if(SelectedEpisysUserId != null){
        
        
       //}
       productTypeClass = '';
       
       //leadObject.OwnerID = OwnerID;
       Database.DMLOptions dmo=new Database.DMLOptions();
       dmo.assignmentRuleHeader.useDefaultRule= true;

       leadobject.setOptions(dmo);
        
        if(!string.isBlank(MemberAccountID)){
            
         leadObject.Member_Account__c = MemberAccountID;
              
        }
        if(SelectedEpisysUserId != null){
            leadObject.Episys_User_ID__c = SelectedEpisysUserId;
        }     
        /*system.debug('---leadObject--- Ownership ---' + leadObject.Ownership__c);   
       if(leadObject.Ownership__c == 'Assign' || leadObject.Ownership__c == 'Keep'){            
            leadObject.Keep__c = true;
       }*/
       
        
         insert leadObject;
         system.debug('---leadObject--'+leadObject.Episys_User_ID__c);
         system.debug('---leadObject--'+leadObject.id);
         //lead leadlst
         PageReference pageRef = new PageReference('/' + leadObject.id);
            pageRef.setRedirect(true);
            return pageRef;
       
       
        
    }
    
    
    public void SetEpsisUserID()
    {
        
         User usr = [Select id, name, alias from User where id=:uid];
         List<Episys_User__c> eusr = [SELECT id,alias__c, Assigned_Branch__c, Branch_Name__c,Default__c,Episys_Name__c,Episys_ID__c from Episys_User__c where alias__c=:usr.alias order by Default__c]; 
        system.debug('Branch_Name__c----' + eusr + '---');
         for(Episys_User__c eu : eusr ){
            if(BranchOption.trim() ==  eu.Branch_Name__c.trim())
            {
              leadObject.Episys_User_ID__c =  eu.Episys_ID__c;
              SelectedEpisysUserId = eu.Episys_ID__c;
            }
         }
         
         

             
             
    }
        
        

}