src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_01__c</fullName>
        <description>Comment Block 1</description>
        <label>Comment 01</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Brand Code BC01=Chevron Federal Credit Union, BC02=Spectrum Credit Union</description>
        <label>Reference</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Previous_Owner__c</fullName>
        <label>Previous Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OTPSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OTPExpirationSeconds__c</fullName>
        <label>OTP Expiration (Seconds)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OTPSettings</label>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MemberVerificationTest.cls
@isTest
public class MemberVerificationTest {
	
	/*@TestSetup
    public static void setup() {

      Profile[] p1 = [select Id from Profile where Name = 'CFCU Admin' limit 1];
        
        User user1 = new User(alias = 'u1',lastname='test999', languagelocalekey='en_US', 
                              email='User1@avfg.com', emailencodingkey='UTF-8', 
                              localesidkey='en_US', profileId = p1[0].id, timezonesidkey='America/Los_Angeles', 
                              username='test9991'+'@avfg.com');
        
        insert user1;
        
         Case cs = new Case();
           cs.Brand__c = 'Chevron';
           cs.Previous_Owner__c = user1.Id;
           
        insert cs;
        ids1=cs.Id;
        System.debug('ids1==' + ids1);
    }*/
    
    static testMethod void testMethod1(){
    	
    	Id rtId = [SELECT Id FROM RecordType WHERE IsPersonType = TRUE AND SObjectType='Account' LIMIT 1].Id;
		Account acc = new Account();
    	acc.RecordTypeID=rtId;
    	acc.FirstName='Test FName';
        acc.LastName='Test LName';
    	acc.Mobile_Phone__pc = '9169954478';
    	acc.PersonEmail='test@yahoo.com';
    	acc.Home_Phone__pc = '1234567896';
    	acc.Work_Phone__pc = '4785123698';
        //acc.PersonHomePhone='1234567';
        acc.PersonMobilePhone='12345678';
        acc.Alternate_Email__pc = 'test@gmail.com';
        insert acc;
  
        Account_Details__c accDetail = new Account_Details__c();
        accDetail.Name = 'Test123';
        //accDetail.RecType__c = 'ACCT';
        accDetail.Reference__c = 'BC02';
        accDetail.Comment_Block_01__c = 'TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS';
        insert accDetail;
        
        Person_Account__c pa = new Person_Account__c();
        pa.PersonID__c = acc.Id;
        pa.Account_Number__c = accDetail.Id;        
        insert pa;
        
        
        Account acc2 = new Account();
    	acc2.RecordTypeID=rtId;
    	acc2.FirstName='Test FName';
        acc2.LastName='Test LName';
    	acc2.Mobile_Phone__pc = '9169954478';
    	acc2.PersonEmail='test@yahoo.com';
    	acc2.Home_Phone__pc = '1234567896';
    	acc2.Work_Phone__pc = '4785123698';
        //acc2.PersonHomePhone='1234567';
        acc2.PersonMobilePhone='12345678';
        acc2.Alternate_Email__pc = 'test@gmail.com';
        insert acc2;
        
        /*Account_Details__c accDetail2 = new Account_Details__c();
        accDetail2.Name = 'Test';
        accDetail2.RecType__c = 'ACCT';
        accDetail2.Reference__c = 'BC02';
  
        insert accDetail2;*/
        
        Person_Account__c pa2 = new Person_Account__c();
        pa2.PersonID__c = acc2.Id;
        pa.Account_Number__c = accDetail.Id;        
        insert pa2;
   
   	    smagicinteract__SMS_Template__c SM = new smagicinteract__SMS_Template__c();
   	    SM.smagicinteract__Name__c = 'SpectrumSMS';
   	    SM.smagicinteract__Text__c = 'Test';
   	    insert SM;
   	    
   	    OTPSettings__c otp = new OTPSettings__c();
   	    otp.Name = 'Member Verification';
   	    otp.OTPExpirationSeconds__c = 1;
   	    insert otp;
   	     
    	MemberVerification controller = new MemberVerification();
    	controller.accids = new List<string>();   	
    	controller.accids.add(accDetail.id);
    	controller.allRelatedAccounts = new List<string>();
    	controller.allRelatedAccounts.add(acc.id);
    	controller.acc = acc;
    	controller.IsIneligible();
    	string resend = 'true';
    	string fieldName  = 'PersonEmail';
    	ApexPages.currentPage().getParameters().put('fieldName',fieldName);
    	ApexPages.currentPage().getParameters().put('resend',resend);
    	controller.ResendOTP();
        //string x = controller.buttonClass;
        controller.cancelOTP();
        string phone = '1236547896';
        string message = 'Test';
        string Name = 'TestUser';
        List<SelectOption> Xyz = controller.PhoneList_Options;
        List<SelectOption> Abc = controller.EmailsList_Options;
        controller.SendSMS(phone,message,Name);
        
        controller.IsEmail = true;
        controller.verifyOTP();
        controller.DeclineOTP();
        string otpstring = '896542';
        string email = 'test@123.com';
        //controller.SendOTPEmail(otpstring,email);
    }
    
    static testMethod void testMethod2(){
    	
    	Id rtId = [SELECT Id FROM RecordType WHERE IsPersonType = TRUE AND SObjectType='Account' LIMIT 1].Id;
		Account acc = new Account();
    	acc.RecordTypeID=rtId;
    	acc.FirstName='Test FName';
        acc.LastName='Test LName';    	
        insert acc;
  
        Account_Details__c accDetail = new Account_Details__c();
        accDetail.Name = 'Test123';
        accDetail.RecType__c = 'ACCT';
        accDetail.Reference__c = 'BC02';
        //accDetail.Comment_Block_01__c = 'TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS';
        insert accDetail;
        
        Person_Account__c pa = new Person_Account__c();
        pa.PersonID__c = acc.Id;
        pa.Account_Number__c = accDetail.Id;        
        insert pa;
        
        
        Account acc2 = new Account();
    	acc2.RecordTypeID=rtId;
    	acc2.FirstName='Test FName';
        acc2.LastName='Test LName';
        insert acc2;
        
        /*Account_Details__c accDetail2 = new Account_Details__c();
        accDetail2.Name = 'Test';
        accDetail2.RecType__c = 'ACCT';
        accDetail2.Reference__c = 'BC02';
  
        insert accDetail2;*/
        
        Person_Account__c pa2 = new Person_Account__c();
        pa2.PersonID__c = acc2.Id;
        pa.Account_Number__c = accDetail.Id;        
        insert pa2;
   
   	    smagicinteract__SMS_Template__c SM = new smagicinteract__SMS_Template__c();
   	    SM.smagicinteract__Name__c = 'SpectrumSMS';
   	    SM.smagicinteract__Text__c = 'Test';
   	    insert SM;
   	    
   	    OTPSettings__c otp = new OTPSettings__c();
   	    otp.Name = 'Member Verification';
   	    otp.OTPExpirationSeconds__c = 1;
   	    insert otp;
   	     
    	MemberVerification controller = new MemberVerification();
    	controller.accids = new List<string>();   	
    	controller.accids.add(accDetail.id);
    	controller.allRelatedAccounts = new List<string>();
    	controller.allRelatedAccounts.add(acc.id);
    	controller.acc = acc;
    	controller.IsIneligible();
    	string resend = 'true';
    	string fieldName  = 'PersonEmail';
    	ApexPages.currentPage().getParameters().put('fieldName',fieldName);
    	ApexPages.currentPage().getParameters().put('resend',resend);
    	controller.ResendOTP();
        //string x = controller.buttonClass;
        controller.cancelOTP();
        string phone = '1236547896';
        string message = 'Test';
        string Name = 'TestUser';
        List<SelectOption> Xyz = controller.PhoneList_Options;
        List<SelectOption> Abc = controller.EmailsList_Options;
        controller.SendSMS(phone,message,Name);
        
        controller.IsEmail = true;
        controller.verifyOTP();
        controller.DeclineOTP();
        string otpstring = '896542';
        string email = 'test@123.com';
        //controller.SendOTPEmail(otpstring,email);
    }
}