src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaritzCX__ALG_Response_Id__c</fullName>
        <externalId>true</externalId>
        <label>ALG Survey Response Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MaritzCX__ALG_Survey_Id__c</fullName>
        <externalId>true</externalId>
        <label>ALG Survey Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <inlineHelpText>Escalation SLA in hours for a case.  SLA to initiate when the 3 categories are set and will be in effect until the case is closed.</inlineHelpText>
        <label>SLA (Business Hours)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CaseRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Case Record Type based on Categories</description>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teritiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseRecordType</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <description>This field will be used to uniquely identify a Person.</description>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Survey_Case_Codes__c.object
<CustomObject>
    <description>Lookup table for branch/dept codes used to assign to queues</description>
    <fields>
        <fullName>Branch_Dept__c</fullName>
        <label>Branch/Dept</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Survey Case Codes</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Case Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/MaritzCXSurveyResponseTriggerHandlerTest.cls
@isTest
public class MaritzCXSurveyResponseTriggerHandlerTest {
	
    static testMethod void testMaritzCXSurveyResponseAfterInsert() {
        
        Group grp=new Group();
        grp.Name='Lending Survey Queue';
        insert grp;
        
        RecordType recType = [Select Id From RecordType  Where SobjectType = 'Case' and Name = 'Survey Cases'];
        
        CaseRecordType__c caseRecType=new CaseRecordType__c();
        caseRecType.Name='657';
        caseRecType.Primary_Category__c='Surveys';
        caseRecType.Secondary_Category__c='Digital Banking - Survey';
        caseRecType.Teritiary_Category__c='Follow-Up';
        caseRecType.SLA__c=40;
        caseRecType.RecordTypeId__c=recType.Id;
        Insert caseRecType;
        
        List<Account_Details__c> lstAccDetails = TestDataFactory.getAccountDetailsData();
        Insert lstAccDetails;
        
        List<Account> lstAcc= TestDataFactory.getAccountsData();
        Insert lstAcc;
        
        List<Person_Account__c> lstPersons= new List<Person_Account__c>{
            new Person_Account__c(TypeTranslate__c='0000/Primary',Name_Type__c=0,Account_Number__c = lstAccDetails[0].id, PersonID__c = lstAcc[0].Id), 
            new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = lstAccDetails[0].Id, PersonID__c = lstAcc[0].Id), 
            new Person_Account__c(Account_Number__c = lstAccDetails[2].Id, PersonID__c = lstAcc[0].Id)};
                
        Insert lstPersons;
        
        List<Person_Account__c> lstPersons1= 
		new List<Person_Account__c>{new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = lstAccDetails[1].Id, PersonID__c = lstAcc[0].Id), 
		new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = lstAccDetails[2].Id, PersonID__c = lstAcc[1].Id)};
            
		Insert lstPersons1; 
        
        Contact contact1=new Contact();
        contact1.LastName='BANDATest';
        contact1.Email='test@test.com';
        contact1.PersonID__c='V555628874';
        insert contact1;
        
        Survey_Case_Codes__c  surveyCaseCode=new Survey_Case_Codes__c();
        surveyCaseCode.Name='90';
        surveyCaseCode.Branch_Dept__c='RE Lending';
        surveyCaseCode.Primary_Category__c='Surveys';
        surveyCaseCode.Secondary_Category__c='RE Lending';
        surveyCaseCode.Tertiary_Category__c='Other';
        surveyCaseCode.Queue__c='RE Lending Survey Queue';
        
        Insert surveyCaseCode;
        
        MaritzCX__Survey__c maritzSurvey= new MaritzCX__Survey__c();
        maritzSurvey.MaritzCX__ALG_Survey_Id__c=18;
        maritzSurvey.Name='Lending Survey';
        maritzSurvey.MaritzCX__Allegiance_Survey_Response_View_Link__c=true;
        maritzSurvey.MaritzCX__Is_Default_Survey__c=false;
        maritzSurvey.MaritzCX__MCX_Company_Id__c=1082836647;
        
        Insert maritzSurvey;
        
        System.debug('maritzSurvey:'+maritzSurvey.Id);
        MaritzCX__Survey_Response__c objRes=new MaritzCX__Survey_Response__c(); 
 
        objRes.MaritzCX__Account__c=lstAcc[0].Id;
        objRes.MaritzCX__ALG_Response_Id__c=58090; //Unique thus increment by one on every insert
        objRes.MaritzCX__ALG_Survey_Id__c=18;
        objRes.MaritzCX__Key_Metric_5__c=2;
        objRes.MaritzCX__Key_Metric_6__c=4;
        objRes.MaritzCX__Key_Metric_7__c=5;
        objRes.MaritzCX__Metric_1__c=lstAccDetails[0].Name;
        objRes.MaritzCX__Metric_2__c='18';
        objRes.MaritzCX__respondent_email__c= 'test@test.com';
        objRes.MaritzCX__Respondent_State__c='Completed';
        objRes.MaritzCX__Survey_Id__c=maritzSurvey.Id;
        
        Insert objRes;
       
        MaritzCX__Survey__c maritzSurvey1= new MaritzCX__Survey__c();
        maritzSurvey1.MaritzCX__ALG_Survey_Id__c=90;
        maritzSurvey1.Name='Lending Survey';
        maritzSurvey1.MaritzCX__Allegiance_Survey_Response_View_Link__c=true;
        maritzSurvey1.MaritzCX__Is_Default_Survey__c=false;
        maritzSurvey1.MaritzCX__MCX_Company_Id__c=1082836647;
        
        Insert maritzSurvey1;
        
        MaritzCX__Survey_Response__c objRes1=new MaritzCX__Survey_Response__c(); 
 
        objRes1.MaritzCX__Account__c=lstAcc[0].Id;
        objRes1.MaritzCX__ALG_Response_Id__c=58090; 
        objRes1.MaritzCX__ALG_Survey_Id__c=18;
        objRes1.MaritzCX__Key_Metric_5__c=2;
        objRes1.MaritzCX__Key_Metric_6__c=4;
        objRes1.MaritzCX__Key_Metric_7__c=5;
        objRes1.MaritzCX__Metric_1__c=lstAccDetails[0].Name;
        objRes1.MaritzCX__Metric_2__c='90';
        objRes1.MaritzCX__respondent_email__c= 'V555628874';
        objRes1.MaritzCX__Respondent_State__c='Completed';
        objRes1.MaritzCX__Survey_Id__c=maritzSurvey1.Id;
        
        List<MaritzCX__Survey_Response__c> newSurveys=new List<MaritzCX__Survey_Response__c>();
        newSurveys.add(objRes1);
        
        MaritzCXSurveyResponseTriggerHandler objTriggerHandler=new MaritzCXSurveyResponseTriggerHandler();
		//objTriggerHandler.afterInsert(newSurveys);
    }
}