src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Card_Name__c</fullName>
        <label>Card Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Number__c</fullName>
        <label>Loan Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PROPERTY_ADDRESS__c</fullName>
        <label>Property Address</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a self-relationship field used to link SubAccounts(recType) to the respective MembershipAccounts(recType)</description>
        <label>Parent Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <label>Property City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip__c</fullName>
        <label>Property Zip</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <formula>Account_Number__r.Card_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Card Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Split_Type_Translate__c</fullName>
        <formula>RIGHT(( TypeTranslate__c ),(LEN( TypeTranslate__c )-5))</formula>
        <label>Split Type Translate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Staging/src/main/default/classes/MemberNumberController.cls
public class MemberNumberController{ 

public String MembernumberQuery {get;set;}
public Boolean searchMsgDetails {get; set;}
//public List<Account_Details__c> accDetails = new List<Account_Details__c>();
public List<Person_Account__c> accDetails = new List<Person_Account__c>();  
//public Set<Person_Account__c> myset = new Set<Person_Account__c>();
//public List<Person_Account__c> result = new List<Person_Account__c>();
//public set<Id> paIds = new set<Id>();
public String imageURL{get;set;}

    public void searchAccount(){
        
       // accDetails = new List<Account_Details__c>(); 
        accDetails = new List<Person_Account__c>();
        MembernumberQuery = MembernumberQuery.trim();
        
        system.debug('membernumberQuery::::'+membernumberQuery);
        
       // string genQuery = 'SELECT Id, Name, Card_Name__c, Card_Number__c, Loan_Number__c, VIN__c, PROPERTY_ADDRESS__c, Property_City__c, Property_State__c, Property_Zip__c FROM Account_Details__c WHERE';
        string genQuery = 'SELECT PersonId__r.Name , Split_Type_Translate__c, Account_Number__r.TypeTranslate__c, Name_Type__c, Account_Number__r.ID1__c FROM Person_Account__c WHERE';
        string whereQuery;
        if(MembernumberQuery != ''){
            if(whereQuery!=NULL){
                whereQuery = whereQuery+ 'AND Account_Number__r.Name LIKE \''+MembernumberQuery+'\'';
            }else{
                integer i;
                integer membersize = membernumberQuery.length();
                for(i=membersize; i<10;i++){
                membernumberQuery = '0'+membernumberQuery;
              }
                whereQuery = ' (Account_Number__r.Name LIKE \''+MembernumberQuery+'\' OR Account_Number__r.Parent_Account__r.Name LIKE \''+MembernumberQuery+'\') AND Split_Type_Translate__c IN(\'Primary\',\'Joint Member\',\'Joint Owner\',\'Power of Attorney\',\'Trustee\',\'Authorized Signer\',\'Representative Payee\',\'Custodian\',\'Responsible Individual\') ORDER BY Name_Type__c ASC NULLS LAST ' ;
            }
        }
        
        if(whereQuery!=NULL){
            string totalQuery = genQuery+whereQuery+'LIMIT 100';
            system.debug('TotalQuery'+totalQuery);
            accDetails = Database.query(totalQuery);
          //  myset.addAll(accDetails);
          //  result.addAll(myset);
        }   
        System.debug('Total Query is::::'+accDetails);

        //to display some custom message when no related member records found
            if(accDetails == null || accDetails.size()==0)
                searchMsgDetails = true; 
            else
                searchMsgDetails = false;                                             
    }

    //Method to return all the account details records based on user input
  /*  public List<Account_Details__c> getMemberAccountInfo()
    {
        return accDetails;
    } */
    public List<Person_Account__c> getMemberAccountInfo()
    {
        return accDetails;
        
    }
    
    
    //Method to clear all user input values and the related member records
    public void clearAll()
    {
         MembernumberQuery='';
         accDetails.clear();
         searchMsgDetails = false;
    }
   
    public MemberNumberController()
    {        
        imageURL='/servlet/servlet.FileDownload?file=';
        List< document > documentList=[select name from document where Name='CFCU Logo'];
       
        if(documentList.size()>0)
        {
          imageURL=imageURL+documentList[0].id;
        }
 
        // if query appears in URL, execute it
        String urlQuery=ApexPages.currentPage().getParameters().get('query');
       
        if ( (null!=urlQuery) && (0!=urlQuery.length()) ){
              MembernumberQuery=urlQuery;       
  }          
    }
 
}//end class