src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PersonLookUpOnCaseController.cls
public class PersonLookUpOnCaseController {

   // private final Account_Details__c accRec;
    private final Account accRec;
    public string accId {get;set;}
  //  public list<Account_Details__c> accList{get;set;}
    public list<Account> accList{get;set;}
    public list<Person_Account__c> paList{get;set;}
    
    public PersonLookUpOnCaseController(ApexPages.StandardController controller){
       // this.accRec = (Account_Details__c)Controller.getRecord();
        this.accRec = (Account)Controller.getRecord();
        accId = System.currentPageReference().getParameters().get('accId'); 
        personAccounts(accId);
    }
    
    public void personAccounts(string accId){
        paList = new list<Person_Account__c>();
            paList = [SELECT Id,
                             Account_Number__c, 
                             PersonID__c,
                             Account_Number__r.RecType__c, 
                             Account_Number__r.Name,
                             PersonID__r.Name,
                             TypeTranslate__c FROM Person_Account__c WHERE Account_Number__c =:accId];
        accountDetails(paList);
          for(Person_Account__c item : paList)
          {
          	
          	if(item.PersonID__r != null && item.PersonID__r.Name != null)
          	{
          		item.PersonID__r.Name = item.PersonID__r.Name.replace('\'','\\\'');
          	}
          }   
             
    }
    
    public void accountDetails(list<Person_Account__c> paList){
      
        set<String> accountNameSet = new set<String>();
        for(Person_Account__c var: paList){
            accountNameSet.add(var.PersonID__r.Name);
        }
        
        accList = new list<Account>();
        
        accList = [Select Id,
                          Name,
                          Alternate_Email__pc,
                          FirstName,
                          MiddleName,
                          LastName,
                          PersonEmail,
                          Residential_City__pc,
                          Residential_Country_Code__pc,
                          Residential_Country__pc,
                          Residential_Extra_Address__pc,
                          Residential_State__pc,
                          Residential_Street__pc,
                          Residential_Zipocde__pc,
                          PersonHomePhone FROM Account Where Name IN:accountNameSet];
    }
}