src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Last_NA_LEHS__c</fullName>
        <description>The last date that a needs assessment housing section was created for the member.</description>
        <label>Last NA LEHS</label>
        <summarizedField>Needs_Assesment__c.Last_LEHS__c</summarizedField>
        <summaryFilterItems>
            <field>Needs_Assesment__c.Last_LEHS__c</field>
            <operation>notEqual</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Needs_Assesment__c.Member__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Last_NA_LEOM__c</fullName>
        <description>The last date that a needs assessment life events section was created for the member.</description>
        <label>Last NA LEOM</label>
        <summarizedField>Needs_Assesment__c.Last_LEOM__c</summarizedField>
        <summaryForeignKey>Needs_Assesment__c.Member__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NA_Complete__c</fullName>
        <description>Formula flag to indicate that all sections of a member&apos;s active NA are comlplete</description>
        <formula>NA_LEHS_Complete__c  &amp;&amp;  NA_LEOM_Complete__c &amp;&amp; NA_LEWS_Complete__c &amp;&amp; NA_LEMP_Complete__c  &amp;&amp;
NA_LECF_Complete__c  &amp;&amp;  NA_LESF_Complete__c &amp;&amp; NA_LESB_Complete__c &amp;&amp; NA_LECP_Complete__c &amp;&amp;
NA_LEPT_Complete__c &amp;&amp; NA_LEMD_Complete__c &amp;&amp; NA_LEOL_Complete__c &amp;&amp; NA_LEAV_Complete__c &amp;&amp;
NA_LEEM_Complete__c &amp;&amp; NA_LEMQ_Complete__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NA Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used for member needs assessments eligibility</description>
        <label>NA Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEAV_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEAV_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEEM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEEM_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to show if the NA Housing section is considered complete (TRUE) or partial (FALSE)</description>
        <label>NA LEHS Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Expired__c</fullName>
        <formula>IF( ( Last_NA_LEHS__c = null  ||   
      Last_NA_LEHS__c &lt;  NOW() -(1440/1440) ) &amp;&amp; 
      NA_Eligibility__c  = TRUE ,
          true, 
          false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NA LEHS Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMD_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMD_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMQ_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMQ_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOL_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEOL_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA LEOM Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOM_Expired__c</fullName>
        <description>Set a flag used for NA LEOM section expiration</description>
        <formula>IF( (Last_NA_LEOM__c  = null  ||   
      Last_NA_LEOM__c &lt;  NOW() -(1440/1440) ) &amp;&amp; 
      NA_Eligibility__c  = TRUE ,
          true, 
          false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NA LEOM Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEPT_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEPT_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESB_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESB_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEWS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEWS_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out_Date__c</fullName>
        <description>The date 1 year into the future when the member will be able to have needs assessments performed.  The member can choose to opt out of the needs assessments for a period of 1 year.  This value is set by a workflow rule triggered by the NA Opt Out field change.</description>
        <label>NA Opt Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out_Updated__c</fullName>
        <label>NA Opt Out Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, indicates that the member has opted to not participate in needs assessments for the period of 1 year.</description>
        <label>NA Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TYPE__c</fullName>
        <label>Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Loan</fullName>
        <active>true</active>
        <description>This record type will be used to store all the LOAN Information</description>
        <label>Loan</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <description>This field will be used to uniquely identify a Person.</description>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/GracePeriod__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ExpiresInDays__c</fullName>
        <label>ExpiresInDays</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GracePeriod__c</fullName>
        <label>GracePeriod</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GracePeriod</label>
</CustomObject>

src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>LEAV_Last_Updated_On__c</fullName>
        <label>LE Auto/Vehicle Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LECF_Last_Updated_On__c</fullName>
        <label>Provide Feedback Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LECP_Last_Updated_On__c</fullName>
        <label>Contact Preferences Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEEM_Last_Updated_On__c</fullName>
        <label>LEEM_Last_Updated_On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEHS_Last_Updated_On__c</fullName>
        <label>LE Housing Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEMD_Last_Updated_On__c</fullName>
        <label>MM Deposits Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEMP_Last_Updated_On__c</fullName>
        <label>MM Payment/Transfers Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEMQ_Last_Updated_On__c</fullName>
        <label>LEMQ_Last_Updated_On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LEOL_Last_Updated_On__c</fullName>
        <label>LE Other Loans Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEOM_Last_Updated_On__c</fullName>
        <label>LEOM_Last_Updated_On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEPT_Last_Updated_On__c</fullName>
        <label>MM Primary Account Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LESB_Last_Updated_On__c</fullName>
        <label>Shared Branching Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LESF_Last_Updated_On__c</fullName>
        <label>LESF_Last_Updated_On</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEWS_Last_Updated_On__c</fullName>
        <label>MM Withdrawals Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MemberPageMessagesLightningController.cls
public class MemberPageMessagesLightningController {
	
    
    
   
    
   
    
    
    private static boolean IsShowData()
    {
    	
		      //Declaring a Set as we don't want Duplicate Group Ids
			Set<Id> results = new Set<Id>();
			
			///Declaring a Map for Group with Role
			Map<Id,Id> grRoleMap = new Map<Id,Id>();
			
			//Populating the Map with RelatedID(i.e.UserRoledId) as Key
			for(Group gr : [select id,relatedid,name from Group])
			{
				grRoleMap.put(gr.relatedId,gr.id);
			}
			
			//Groups directly associated to user
			Set<Id> groupwithUser = new Set<Id>();
			
			//Populating the Group with User with GroupId we are filtering only  for Group of Type Regular,Role and RoleAndSubordinates
			for(GroupMember  u :[select groupId from GroupMember where UserOrGroupId=:UserInfo.getUserId() and (Group.Type = 'Regular' OR Group.Type='Role' OR Group.Type='RoleAndSubordinates')])
			{
				groupwithUser.add(u.groupId);
			}
			
			//Groups with Role
			for(User  u :[select UserRoleId from User where id=:UserInfo.getUserId()])
			{
				//Checking if the current User Role is part of Map or not
				if(grRoleMap.containsKey(u.UserRoleId))
				{
					results.add(grRoleMap.get(u.UserRoleId));
				}
			}
			//Combining both the Set
			results.addAll(groupwithUser);
			
			//Traversing the whole list of Groups to check any other nested Group
			Map<Id,Id> grMap = new Map<Id,Id>();
			for(GroupMember gr : [select id,UserOrGroupId,Groupid from GroupMember where
			        (Group.Type = 'Regular' OR Group.Type='Role' OR Group.Type='RoleAndSubordinates')])
			{
				grMap.put(gr.UserOrGroupId,gr.Groupid);
			}
			for(Id i :results)
			{
				if(grMap.containsKey(i))
				{
					results.add(grMap.get(i));
				}
			}
			
			
			system.debug('########' + results);
			  
        	boolean ShowData = false;
  		
  		
		list<GroupMember> listNamegroup =	[select group.developerName from GroupMember where UserOrGroupId in: results];
		set<string> listName = new set<string>();
			for(GroupMember i :listNamegroup)
			{
				
					listName.add(i.group.developerName );
				
			}
			
			system.debug('########' + listName);
		   
		      if (listName.contains('NA_Auth')) {
		           ShowData = true;
		      }
		     
		     
		     
		     Set<String> groupNames = new Set<String>();
		   for (GroupMember gm : [select 
		                             group.name,
		                             group.DeveloperName 
		                          from GroupMember 
		                          where UserOrGroupId = :UserInfo.getUserId()]) {
		       groupNames.add(gm.group.DeveloperName);
		   }
			
			system.debug('groupNames---' + groupNames);
		   
		      if (groupNames.contains('NA_Auth')) {
		           ShowData = true;
		      }
		     
		      
		    system.debug('########1111' + results);  
		    return ShowData;
    }
    
    
    private static boolean IsExpired(string actId, Account acc)
    {
    	Needs_Assesment__c objNeedsAssessment;
    	//query Need assesment to feed the NeedAssessment method that needs to be called in the controller
        List<Needs_Assesment__c> na = [select id,LEEM_Last_Updated_On__c, LEMQ_Last_Updated_On__c,LEOM_Last_Updated_On__c,LEAV_Last_Updated_On__c ,LESF_Last_Updated_On__c, LESB_Last_Updated_On__c, LEMD_Last_Updated_On__c, LECP_Last_Updated_On__c, LEHS_Last_Updated_On__c, LEOL_Last_Updated_On__c, LECF_Last_Updated_On__c, LEWS_Last_Updated_On__c, LEMP_Last_Updated_On__c, LEPT_Last_Updated_On__c  from Needs_Assesment__c where Member__c =: actId limit 1];
        if (na.size() > 0)
        {
            objNeedsAssessment = na[0];
        }
        
       boolean Expired = false;
        if (objNeedsAssessment == null)
        {
        	Expired= true;
        	return Expired;
        }
        if(GetTabStatus(objNeedsAssessment.LEHS_Last_Updated_On__c,acc.NA_LEHS_Complete__c, 'Housing', acc ) && 
        GetTabStatus(objNeedsAssessment.LEOM_Last_Updated_On__c,acc.NA_LEOM_Complete__c, 'NA Other Milestones', acc)
        	&& GetTabStatus(objNeedsAssessment.LEWS_Last_Updated_On__c,acc.NA_LEWS_Complete__c, 'Withdrawal', acc) 
        	&& GetTabStatus(objNeedsAssessment.LEMP_Last_Updated_On__c,acc.NA_LEMP_Complete__c, 'Move Your Money', acc)
        	&& GetTabStatus(objNeedsAssessment.LECF_Last_Updated_On__c,acc.NA_LECF_Complete__c, 'Current Feedback', acc) 
        	&& GetTabStatus(objNeedsAssessment.LESF_Last_Updated_On__c,acc.NA_LESF_Complete__c, 'ATM Network', acc)
        	&& GetTabStatusTime(objNeedsAssessment.LESB_Last_Updated_On__c,acc.NA_LESB_Complete__c, 'Shared Branching', acc) 
        	&& GetTabStatus(objNeedsAssessment.LECP_Last_Updated_On__c,acc.NA_LECP_Complete__c, 'Contact Preference', acc)
        	&& GetTabStatus(objNeedsAssessment.LEPT_Last_Updated_On__c,acc.NA_LEPT_Complete__c, 'PrimaryTransaction', acc) 
        	&& GetTabStatus(objNeedsAssessment.LEMD_Last_Updated_On__c,acc.NA_LEMD_Complete__c, 'MakingDeposits', acc)
        	&& GetTabStatus(objNeedsAssessment.LEOL_Last_Updated_On__c,acc.NA_LEOL_Complete__c, 'Other Loan', acc) 
        	&& GetTabStatusTime(objNeedsAssessment.LEAV_Last_Updated_On__c,acc.NA_LEAV_Complete__c, 'Auto Vehicle', acc)
			&& GetTabStatus(objNeedsAssessment.LEEM_Last_Updated_On__c,acc.NA_LEEM_Complete__c, 'Earn More', acc) 
			&& GetTabStatusTime(objNeedsAssessment.LEMQ_Last_Updated_On__c,acc.NA_LEMQ_Complete__c, 'Extend Benifits', acc)
        
        	 )
        {
        	Expired = true; 
        }
        
        return Expired;
    }
    
    
    public static boolean GetTabStatus(Date updatedDate, boolean complete, string due, account acc)
	{
		GracePeriod__c dataHosuing = GracePeriod__c.getValues(due);
		
       integer HousingDuePeriod = integer.valueOf(dataHosuing.ExpiresInDays__c);
		
	    boolean TabExpired = false;
		if (acc.NA_Opt_Out__c)
	    {
	        TabExpired = false;
	    }
		else if(updatedDate == null)
		{
			TabExpired = true;
		}
	    
	    else if (complete && updatedDate != null && updatedDate + HousingDuePeriod < Date.today())
	    {
	        TabExpired = true;
	    }
	 	system.debug('due---' + due);
	 	system.debug('TabExpired---' + TabExpired);
		return TabExpired;

	}
	
	public static boolean GetTabStatusTime(DateTime updatedDate, boolean complete, string due, Account acc)
	{
		GracePeriod__c dataHosuing = GracePeriod__c.getValues(due);
      integer  HousingDuePeriod = integer.valueOf(dataHosuing.ExpiresInDays__c);
		
	    boolean TabExpired = false;
		if (acc.NA_Opt_Out__c)
	    {
	        TabExpired = false;
	    }
		else if(updatedDate == null)
		{
			TabExpired = true;
		}
	    
	    else if (complete && updatedDate != null && updatedDate + HousingDuePeriod < Date.today())
	    {
	        TabExpired = true;
	    }
	 
		return TabExpired;	    

	}
	
	@AuraEnabled
	public static Map<string, string> accountDetails(string actId)
	{
			list<Person_Account__c> paList = new list<Person_Account__c>();
        	paList = [SELECT Id,Account_Number__c,Account_Number__r.RecType__c, Account_Number__r.Name FROM Person_Account__c WHERE PersonID__c =:actId and TypeTranslate__c in ('0001/Joint Member','0000/Primary')];
        	List<Account>	account = [select Id,RecordType.name,BIRTH_DATE__pc,NA_Complete__c,Last_NA_LEHS__c, Last_NA_LEOM__c, NA_LEHS_Complete__c, NA_LEWS_Complete__c, NA_Opt_Out_Updated__c,
                                     NA_LEMP_Complete__c, NA_LECF_Complete__c, NA_LEOM_Complete__c, NA_Opt_Out_Date__c, NA_LESF_Complete__c, NA_LESB_Complete__c,
                                     NA_LEHS_Expired__c, NA_LEOM_Expired__c, NA_Eligibility__c, NA_Opt_Out__c, NA_LECP_Complete__c, NA_LEPT_Complete__c, NA_LEMD_Complete__c,
                                     NA_LEOL_Complete__c,NA_LEAV_Complete__c,NA_LEEM_Complete__c,NA_LEMQ_Complete__c, Member_Verification_OTP_Invalid_Attempt__c from Account where id =: actId limit 1];
        	Map<string, string> m = new Map<string, string>();
        	
        	
        	Boolean PrimaryAccountWithAtleastoneTrust = false;
        	///////////////////////
        	
        	
    
    	 
        
        PrimaryAccountWithAtleastoneTrust = false;
        List<Person_Account__c> paList1 =     [SELECT Id, Account_Number__c, Account_Number__r.RecType__c, Relationship__c, Account_Number__r.TypeTranslate__c, TypeTranslate__c,
                  Account_Number__r.Name FROM Person_Account__c WHERE PersonID__c =: actId and Account_Number__r.RecType__c = 'ACCT'
                                         and(Account_Number__r.TypeTranslate__c != '2-TRUST' or Account_Number__r.TYPE__c != 2) and TypeTranslate__c like '%PRIMARY%' ];


        if (paList1.size() > 0)
        {
            PrimaryAccountWithAtleastoneTrust = true;           
        }
        
		
		system.debug('Before condition--0');
		boolean MemberAbove18 = true;
		if(account[0].BIRTH_DATE__pc != null)
		{
			
			MemberAbove18 =	account[0].BIRTH_DATE__pc.addyears(18) < System.Today();
		}
		boolean IsShowData = IsShowData();
        boolean IsExpired = IsExpired(actId, account[0]);
		m.put('Memberisunder18',string.valueof( MemberAbove18 == false));
		m.put('Memberisnotprimary',string.valueof(MemberAbove18 && PrimaryAccountWithAtleastoneTrust == false));
		system.debug('Memberhaspartiallycompleted condition--1');
		m.put('Memberhaspartiallycompleted', string.valueof(MemberAbove18 == TRUE && PrimaryAccountWithAtleastoneTrust == TRUE && account[0].NA_Opt_Out__c == FALSE && IsExpired == FALSE && account[0].NA_Complete__c == FALSE));
		system.debug('Before condition--1');
		m.put('AMemberAssessmentisdue', string.valueof(MemberAbove18 == TRUE && PrimaryAccountWithAtleastoneTrust == TRUE && account[0].NA_Opt_Out__c == FALSE && IsExpired == True));
		system.debug('Before condition--2');
		m.put('MemberOptOut', string.valueof(account[0].NA_Opt_Out_Date__c != NULL && account[0].NA_Opt_Out_Date__c > system.today()));
        system.debug('Before condition--3');
        	system.debug('account[0].NA_Opt_Out_Date__c' + account[0].NA_Opt_Out_Date__c);
        if(account[0].NA_Opt_Out_Date__c != null)
        {
        	Datetime dtTIme = datetime.newInstance( account[0].NA_Opt_Out_Date__c.year(),account[0].NA_Opt_Out_Date__c.month(),account[0].NA_Opt_Out_Date__c.day(), 0,0,0);
        	
        	string Opt_Out_Date = dtTIme.format('MMMM d ,  yyyy');
        	m.put('Opt_Out_Date',Opt_Out_Date);
        }
        else
        {
        	m.put('Opt_Out_Date','');
        }
        system.debug('Before condition--4');	
        m.put('ShowData',string.valueof(IsShowData));
        
      
        	
        	
        	system.debug('paList...'+paList);
		    set<String> accountNumberSet = new set<String>();
		    set<Id> accIdset = new set<Id>();
		    set<String> acctypeSet = new set<String>();
		    for(Person_Account__c var: paList){
		    	
		        accountNumberSet.add(var.Account_Number__r.Name);
		        acctypeSet.add(var.Account_Number__r.RecType__c);
		        accIdSet.add(var.Account_Number__c);
		    }
		    system.debug('acctypeSet ---  '  + acctypeSet);
		    list<Account_Details__c> accList = new list<Account_Details__c>();
		  boolean  Highpotentialflag = false;
		boolean	Highvalueflag = false;
		    if(acctypeSet.contains('ACCT')){
		        accList = [SELECT Id,Name,RecType__c,High_Value_Flag__c	FROM Account_Details__c WHERE Name IN:accountNumberSet AND High_Value_Flag__c  != null ORDER BY High_Value_Flag__c DESC];
		    	 if(!accList.isEmpty() && accList.size() > 0 ){
    	 		 	
    	 		 		system.debug('accList[0].High_Value_Flag__c ---  '  + accList[0].High_Value_Flag__c );
    	 		 		
    	 		 		for (Account_Details__c acc : accList) {

						  if(acc.High_Value_Flag__c == 1)
						  {
						  	Highpotentialflag = false;
    	 		 			Highvalueflag = true;
    	 		 			break;
						  }
						  else if(acc.High_Value_Flag__c == 2){
	    	 		 			Highpotentialflag = true;
	    	 		 			Highvalueflag = false;
    	 		 		  }						
						}	
    	 		 					    	 				    	 						    	 	
		    	 }
		    
		    }
		   system.debug('accList ---  '  + accList);
		   
		   m.put('Highpotentialflag',string.valueof(Highpotentialflag));
		   m.put('Highvalueflag',string.valueof(Highvalueflag));
		   
		   if(account[0].Member_Verification_OTP_Invalid_Attempt__c == null)
            {
            	 m.put('ShowOTPInvalidAttempt','false');
            	 m.put('OTPNextAttemptValidAfterHours','0');
            }
		   else
		   {
			   Long milliseconds = System.Now().getTime() - account[0].Member_Verification_OTP_Invalid_Attempt__c.getTime() ;
	           Long hours = milliseconds / (1000 * 60 * 60);
	           OTPSettings__c data = OTPSettings__c.getValues('Member Verification');
	           Integer OTPExpiresAfterSeconds = integer.valueOf(data.OTPExpirationSeconds__c);
	            
	            system.debug('hours---' + hours);            
	            Integer OTPNextAttemptValidAfterHours = integer.valueOf(data.OTPNextAttemptValidAfterHours__c);
	            system.debug('OTPNextAttemptValidAfterHours---' + OTPNextAttemptValidAfterHours);
	            if(OTPNextAttemptValidAfterHours > hours){
	                m.put('ShowOTPInvalidAttempt','true');
	                m.put('OTPNextAttemptValidAfterHours', string.valueOf(OTPNextAttemptValidAfterHours));
	            }
	            else
	            {
	            	m.put('ShowOTPInvalidAttempt','false');
	            	m.put('OTPNextAttemptValidAfterHours','0');
	            }
		   }
		   
		   boolean IsShowOTPButton = showData_OTP();
		   m.put('IsShowOTPButton',string.valueOf(IsShowOTPButton));
		    m.put('RecordTypeName',account[0].RecordType.name);
		   return m;
       }
       
       private static boolean showData_OTP(){
   
    	
    		boolean showData1 = false;
		      //Declaring a Set as we don't want Duplicate Group Ids
			Set<Id> results = new Set<Id>();
			
			///Declaring a Map for Group with Role
			Map<Id,Id> grRoleMap = new Map<Id,Id>();
			
			//Populating the Map with RelatedID(i.e.UserRoledId) as Key
			for(Group gr : [select id,relatedid,name from Group])
			{
				grRoleMap.put(gr.relatedId,gr.id);
			}
			
			//Groups directly associated to user
			Set<Id> groupwithUser = new Set<Id>();
			
			//Populating the Group with User with GroupId we are filtering only  for Group of Type Regular,Role and RoleAndSubordinates
			for(GroupMember  u :[select groupId from GroupMember where UserOrGroupId=:UserInfo.getUserId() and (Group.Type = 'Regular' OR Group.Type='Role' OR Group.Type='RoleAndSubordinates')])
			{
				groupwithUser.add(u.groupId);
			}
			
			//Groups with Role
			for(User  u :[select UserRoleId from User where id=:UserInfo.getUserId()])
			{
				//Checking if the current User Role is part of Map or not
				if(grRoleMap.containsKey(u.UserRoleId))
				{
					results.add(grRoleMap.get(u.UserRoleId));
				}
			}
			
			//Combining both the Set
			results.addAll(groupwithUser);
			
			//Traversing the whole list of Groups to check any other nested Group
			Map<Id,Id> grMap = new Map<Id,Id>();
			for(GroupMember gr : [select id,UserOrGroupId,Groupid from GroupMember where
			        (Group.Type = 'Regular' OR Group.Type='Role' OR Group.Type='RoleAndSubordinates')])
			{
				grMap.put(gr.UserOrGroupId,gr.Groupid);
			}
			for(Id i :results)
			{
				if(grMap.containsKey(i))
				{
					results.add(grMap.get(i));
				}
			}
			
			
			system.debug('########' + results);
			  
        	showData1 = false;
  		
  		
		list<GroupMember> listNamegroup =	[select group.developerName from GroupMember where UserOrGroupId in: results];
		set<string> listName = new set<string>();
			for(GroupMember i :listNamegroup)
			{
				
					listName.add(i.group.developerName );
				
			}
			
			system.debug('########' + listName);
		   
		      if (listName.contains('OTP_Auth')) {
		           showData1 = true;
		      }
	     
		     Set<String> groupNames = new Set<String>();
		   for (GroupMember gm : [select 
		                             group.name,
		                             group.DeveloperName 
		                          from GroupMember 
		                          where UserOrGroupId = :UserInfo.getUserId()]) {
		       groupNames.add(gm.group.DeveloperName);
		   }
			
			system.debug('groupNames---' + groupNames);
		   
		      if (groupNames.contains('OTP_Auth')) {
		           showData1 = true;
		      }	     
		      
		    return showData1;   	
    }
}