src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_raw__c</fullName>
        <label>Email</label>
        <length>40</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Card_Name__c</fullName>
        <label>Card Name</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>Status</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Card</fullName>
        <active>true</active>
        <description>This record type will be used to store all the CARD Information</description>
        <label>Card</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Documents__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this button when you want to send additional documents apart from the pre-configured ones through DocuSign.</description>
        <label>Additional Documents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Five_Day_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Five Day Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkRead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkSaved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkSaved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaritzCX__Response_Deleted_From_MaritzCX__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field keeps track of whether the response is available or deleted from the system.</description>
        <label>Response Deleted From MaritzCX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SLATemp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLATemp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
                <value>
                    <fullName>HSA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Staff_Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field to manually escalate a case</description>
        <inlineHelpText>Use this field to manually escalate a case for further assistance</inlineHelpText>
        <label>Staff Escalated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Staging/src/main/default/classes/MasterCardTravelTriggerTest.cls
@isTest
public class MasterCardTravelTriggerTest {
	

		  static testMethod void test1(){
			  Account acc = new Account();
		    	//acc.RecordTypeID=rtId;
		    	acc.FirstName='Test FName';
		        acc.LastName='Test LName';    
		        acc.Mobile_Phone__pc='555-469-3885'; 
		        acc.Email_raw__c='dbhavsar@affirma.com'; 	
		        insert acc;
        
			  	Account_Details__c accDetail = new Account_Details__c();
		        accDetail.Name = '0000147163';
		        accDetail.RecType__c = 'ACCT';
		        accDetail.TypeTranslate__c = '1-PERSONAL';
		        insert accDetail;
		        
		        Account_Details__c accDetail1 = new Account_Details__c();
		        accDetail1.Name = '0000147163';
		        accDetail1.RecType__c = 'CARD';
		        accDetail1.TypeTranslate__c = '15-CHEVRON DEBIT CARD';
		        accDetail1.Status__c = 1;
		        accDetail1.Card_Number__c= '5165967021121165';
		        accDetail1.Card_Name__c = 'MINDY O RIGA';
		        accDetail1.TypeTranslate__c = '15-CHEVRON DEBIT CARD';
		        insert accDetail1;
		        
		        Master_Card_Configurations__c cs = new Master_Card_Configurations__c();	 	
		    	cs.Card_Type__c = '11,12';	
		    	cs.Name = 'ATM'; 
		    	insert cs; 
		    	
		    	Master_Card_Configurations__c cs1 = new Master_Card_Configurations__c();	 	
		    	cs1.Card_Type__c = '13,14,15,18';	
		    	cs1.Name = 'DEBIT'; 
		    	insert cs1;
		    	
		    	Master_Card_Configurations__c cs2 = new Master_Card_Configurations__c();	 	
		    	cs2.Card_Type__c = '16,17';	
		    	cs2.Name = 'HSA'; 
		    	  	
		    	insert cs2;
			  	
			  	List<Case> case_Obj = new List<Case>{
			    new Case(Status = 'In Process',description='Original Desc', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = acc.Id, Account_Number__c = accDetail.Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Card services', Secondary_Category__c = 'ATM/Debit', Tertiary_Category__c = 'Travel notification', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false)	};
		    	
		    	Insert case_Obj;
		    	
			  	Mastercard_Travel__c mcObj = new Mastercard_Travel__c();
			  	mcobj.CardId__c = accDetail1.id;
			  	mcobj.Case__c= case_Obj[0].Id;
			  	mcobj.Country__c= 'India';
			  	mcobj.Departure_Date__c= Date.newInstance(2018, 12, 01);
			  	mcobj.Destination__c= 'International';
			  	mcobj.Email__c='dbhavsar@affirma.com';
			  	mcobj.IsEmailPreferred__c= true;
			  	mcobj.IsPhonePreferred__c=false;
			  	mcobj.Return_Date__c=Date.newInstance(2018, 12, 10);
			  	mcobj.State__c='';
			  	mcobj.Timezone__c='America/Los_Angeles';
			  	mcobj.US_Mobile_Number__c='123456789';
			  	insert mcObj;
			  	
			  	Mastercard_Travel__c mcObj1 = new Mastercard_Travel__c();
			  	mcObj1.CardId__c = accDetail1.id;
			  	mcObj1.Case__c= case_Obj[0].Id;
			  	mcObj1.Country__c= 'Nepal';
			  	mcObj1.Departure_Date__c= Date.newInstance(2018, 12, 21);
			  	mcObj1.Destination__c= 'International';
			  	mcObj1.Email__c='dbhavsar@affirma.com';
			  	mcObj1.IsEmailPreferred__c= true;
			  	mcObj1.IsPhonePreferred__c=false;
			  	mcObj1.Return_Date__c=Date.newInstance(2018, 12, 22);
			  	mcObj1.State__c='';
			  	mcObj1.Timezone__c='America/Los_Angeles';
			  	mcObj1.US_Mobile_Number__c='123456789';
			  	insert mcObj1;
			  	
			  	Mastercard_Travel__c mcObj2 = new Mastercard_Travel__c();
			  	mcObj2.CardId__c = accDetail1.id;
			  	mcObj2.Case__c= case_Obj[0].Id;
			  	mcObj2.Country__c= 'Nepal';
			  	mcObj2.Departure_Date__c= Date.newInstance(2018, 12, 24);
			  	mcObj2.Destination__c= 'International';
			  	mcObj2.Email__c='dbhavsar@affirma.com';
			  	mcObj2.IsEmailPreferred__c= true;
			  	mcObj2.IsPhonePreferred__c=false;
			  	mcObj2.Return_Date__c=Date.newInstance(2018, 12, 25);
			  	mcObj2.State__c='';
			  	mcObj2.Timezone__c='America/Los_Angeles';
			  	mcObj2.US_Mobile_Number__c='123456789';
			  	insert mcObj2;
			  	
			  	
			  //	Mastercard_Travel__c mcObj1 = [select id,Return_Date__c from Mastercard_Travel__c where id =: mcObj.id];
			  	mcObj.Return_Date__c = Date.newInstance(2018, 12, 12);
			  	update mcObj;

			 //// 	mcObj2.Return_Date__c = Date.newInstance(2018, 12, 26);
			  	//update mcObj2;
			  	
			  	
			  	delete mcObj;
			  	
			  	delete mcObj2;
			  	
		  }
    
}