src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_LEOM_Expired__c</fullName>
        <description>Set a flag used for NA LEOM section expiration</description>
        <formula>IF( (Last_NA_LEOM__c  = null  ||   
      Last_NA_LEOM__c &lt;  NOW() -(1440/1440) ) &amp;&amp; 
      NA_Eligibility__c  = TRUE ,
          true, 
          false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NA LEOM Expired</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/NA_Other_Existing_Loans__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Institution__c</fullName>
        <label>Financial  Institution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chevron Federal Credit Union</fullName>
                </value>
                <value>
                    <fullName>Spectrum Credit Union</fullName>
                </value>
                <value>
                    <fullName>Bank of America</fullName>
                </value>
                <value>
                    <fullName>Chase Bank</fullName>
                </value>
                <value>
                    <fullName>Wells Fargo</fullName>
                </value>
                <value>
                    <fullName>Citibank</fullName>
                </value>
                <value>
                    <fullName>US Bank</fullName>
                </value>
                <value>
                    <fullName>Capital One</fullName>
                </value>
                <value>
                    <fullName>Ally</fullName>
                </value>
                <value>
                    <fullName>USAA</fullName>
                </value>
                <value>
                    <fullName>Other Credit Union</fullName>
                </value>
                <value>
                    <fullName>Other Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Spectrum Federal Credit Union</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Needs_Assessment__c</fullName>
        <label>Needs Assessment</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipLabel>NA_Other_Existing_Loans</relationshipLabel>
        <relationshipName>NA_Other_Existing_Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home Equity</fullName>
                </value>
                <value>
                    <fullName>Personal Line of Credit</fullName>
                </value>
                <value>
                    <fullName>RV/Boat</fullName>
                </value>
                <value>
                    <fullName>Student/College</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NA_Other_Existing_Loan</label>
    <nameField>
        <label>Other Loans</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA_Other_Existing_Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>LEOL_Last_Updated_On__c</fullName>
        <label>LE Other Loans Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEOL_Other_Existing_Loans__c</fullName>
        <label>LEOL_Other_Existing_Loans</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Prefer Not To Answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rec_LEOL_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Refinance for Existing Loans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOL_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Rec_LEOL_2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Recommendation 1 - Life Events - Other Milestones</description>
        <inlineHelpText>Recommendation 1 - Life Events - Other Milestones</inlineHelpText>
        <label>HELOC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RV Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Health Savings Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Personal Line of Credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Student Loans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_6__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CDs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_7__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Money Market</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Na_OtherExistingLoans.cls
public class Na_OtherExistingLoans
{
    public string script { get; set; }
    public Account AccountC { get; set; }
    public string NA_id { get; set; }

    public string accId2 { get; set; }
    public NeedAssessmentController parentController { get; set; }
    public Needs_Assesment__c lmm_New;
    public integer loanid { get; set; }
    public list<NA_Other_Existing_Loans__c> otherExistingLoans;
public boolean  firsttime = true;



    public Needs_Assesment__c getlmm_New()
    {
        if(lmm_New == null)
        {
        setObjects();
}
        return lmm_New;
    }
    public void setlmm_New(Needs_Assesment__c val)
    {
        lmm_New = val;
    }



    public void setObjects()
    {

        accId2 = parentController.account[0].Id;

        list<Needs_Assesment__c> naother = [select id,
                        Rec_LEOM_1__c,
                        Rec_LEOM_2__c,
                        Rec_LEOM_3__c,
                        Rec_LEOM_4__c,
                        Rec_LEOM_5__c,
                        Rec_LEOM_6__c,
                        Rec_LEOM_7__c,Rec_LEOL_1__c,Rec_LEOL_2__c,
                        LEOL_Last_Updated_On__c,LEOL_Other_Existing_Loans__c
                         from Needs_Assesment__c
                           where member__c =:accId2 ORDER by LastModifiedDate desc];

        if (naother.size() > 0)
        {
            NA_id = naother[0].Id;

            if (AccountC.NA_LEOM_Expired__c)
            {
                lmm_New = new Needs_Assesment__c();
                lmm_New.ID = NA_id;


            }
            else
            {
                lmm_New = naother[0];
            }
        }
        else
        {

            lmm_New = new Needs_Assesment__c();

        }
        
                otherExistingLoans = [select id, Balance__c, End_Date__c, Financial_Institution__c, Needs_Assessment__c, Rate__c, Type_of_Loan__c 
                        from NA_Other_Existing_Loans__c where Needs_Assessment__c =: lmm_New.ID];
        
                       
    }

    public list<NA_Other_Existing_Loans__c> GetotherExistingLoans()
    {
        if (otherExistingLoans == null)
        {
            otherExistingLoans = new list<NA_Other_Existing_Loans__c>();
        }


        return otherExistingLoans;
    }


    public void setotherExistingLoans(list<NA_Other_Existing_Loans__c> value)
    {
       
            otherExistingLoans = value;
       



    }
    public void addOtherExistingLoan()
    {

        NA_Other_Existing_Loans__c obj = new NA_Other_Existing_Loans__c();
        //obj.Needs_Assessment__c = NA_id;
        otherExistingLoans.add(obj);

    }


    public void deleteOtherExistingLoan()
    {
        system.debug('System-----' + loanid);



        for (integer i = 0; i < otherExistingLoans.size(); i++)
        {
            if (loanid == i)
            {

                if (!string.isEmpty(otherExistingLoans[i].id))
                {
                    delete otherExistingLoans[i];
                }


                otherExistingLoans.remove(i);
                
                break;
            }
        }




    }


    public PageReference SubmitFeedbackForm()
    {

    



            Needs_Assesment__c nao_tobeinserted = new Needs_Assesment__c();
                        nao_tobeinserted.Id = lmm_New.Id;
            nao_tobeinserted.Rec_LEOM_1__c = lmm_New.Rec_LEOM_1__c;
            nao_tobeinserted.Rec_LEOM_2__c = lmm_New.Rec_LEOM_2__c;
            nao_tobeinserted.Rec_LEOM_3__c = lmm_New.Rec_LEOM_3__c;
            nao_tobeinserted.Rec_LEOM_4__c = lmm_New.Rec_LEOM_4__c;
            nao_tobeinserted.Rec_LEOM_5__c = lmm_New.Rec_LEOM_5__c;
            nao_tobeinserted.Rec_LEOM_6__c = lmm_New.Rec_LEOM_6__c;
            nao_tobeinserted.Rec_LEOM_7__c = lmm_New.Rec_LEOM_7__c;
			nao_tobeinserted.REC_LEOL_1__c = lmm_New.REC_LEOL_1__c;
			nao_tobeinserted.REC_LEOL_2__c = lmm_New.REC_LEOL_2__c;
			nao_tobeinserted.LEOL_Other_Existing_Loans__c = lmm_New.LEOL_Other_Existing_Loans__c;


            if (nao_tobeinserted.Id == null)
            {
                nao_tobeinserted.Member__c = accId2;
            }
            nao_tobeinserted.LEOL_Last_Updated_On__c = system.today();
            
            
 			lmm_New.LEOL_Last_Updated_On__c =nao_tobeinserted.LEOL_Last_Updated_On__c;           
            script = '1';

upsert nao_tobeinserted;

            	lmm_New.id = nao_tobeinserted.id;
            
              for (integer i = 0; i < otherExistingLoans.size(); i++)
        				{
        					if(otherExistingLoans[i].Needs_Assessment__c == null)
        					{
        					otherExistingLoans[i].Needs_Assessment__c = nao_tobeinserted.id;
        					}
        				}

            upsert otherExistingLoans;


	
        
        
        
        RefreshParent();
        
        return null;
    }



    public void resetscript()
    {
        script = '';
    }

    public void RefreshParent()
    {



        parentController.RefreshAccount();




        parentController.GetOtherLoanTabClass();
    }




}