src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Created_By_User_Alias__c</fullName>
        <label>Created By User Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UpdateAccountCreatebyEpisysUser.cls
global class UpdateAccountCreatebyEpisysUser implements Database.Batchable<sObject>{

   global Database.QueryLocator start(Database.BatchableContext BC){
      String ACCT = 'ACCT';
      String Query='Select Id,Name, RecType__c, Created_By_User_Alias__c from Account_Details__c order by Name';
      return Database.getQueryLocator(Query);
      
   }

   global void execute(Database.BatchableContext BC, List<Account_Details__c> scope){
     Set<string> ids = new Set<string>();
     Map<Id,string> accountEpisysUser = new Map<Id,string>();
     
     for(Account_Details__c acc : scope)
     {
        ids.add(acc.id);
        accountEpisysUser.put(acc.id,acc.Created_By_User_Alias__c);
     }
        
    AggregateResult[] groupedResults = [SELECT PersonId__c,Account_Number__c, PersonID__r.id,Account_Number__r.RecType__c FROM Person_Account__c WHERE Account_Number__c in: ids group by PersonId__c,PersonID__r.id,Account_Number__c,Account_Number__r.RecType__c];
    
    System.debug('groupedResults' +groupedResults);
    
    Map<string,string> listEpisysUsers = new Map<string,string>();
 
    Set<string> memberFound = new Set<string>(); 
    
    for(AggregateResult item : groupedResults)
    {
        if(((string)item.get('RecType__c')) == 'ACCT'  && !memberFound.contains((string)item.get('PersonId__c')))
        {
            string episysUser = accountEpisysUser.get((string)item.get('Account_Number__c'));
            if(string.isNotBlank(episysUser) && string.isNotEmpty(episysUser))
            {
                memberFound.add((string)item.get('PersonId__c'));
                listEpisysUsers.put((string)item.get('PersonId__c'), episysUser);  
            }
        }
    }
       
    for(AggregateResult item : groupedResults)
    {
        if(((string)item.get('RecType__c')) != 'ACCT' && !memberFound.contains((string)item.get('PersonId__c')))
        {
            string episysUser = accountEpisysUser.get((string)item.get('Account_Number__c'));
            if(string.isNotBlank(episysUser) && string.isNotEmpty(episysUser))
            {
               memberFound.add((string)item.get('PersonId__c'));
            	listEpisysUsers.put((string)item.get('PersonId__c'), episysUser);    
            }
                     
        }
        
    }
    
    List<Account> listMainAccount = [select id,Created_By_Episys_User_Alias__c from Account where Id in: memberFound and Created_By_Episys_User_Alias__c = null];
    List<Episys_User__c> episysUserList = [select id,Name, Alias__c from Episys_User__c];
    Set<String> existingUsers = new Set<String>();
    
    for(Account acc: listMainAccount)
    {
        string memberUser = listEpisysUsers.get(acc.id);
        existingUsers.add(listEpisysUsers.get(acc.id));
        for(Integer i=0;i<episysUserList.size();i++)
        {
            String userAlias = episysUserList[i].Alias__c;
            if (existingUsers.contains(userAlias))
            {
                acc.Created_By_Episys_User_Alias__c = memberUser;
            }
        }
    }
    
    update listMainAccount;
    
    }

   global void finish(Database.BatchableContext BC){
   }
}