src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>(TODAY() -  PersonContact.BIRTH_DATE__c )*24/(365*24)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Alt_Email_Raw__c</fullName>
        <label>Alternate Email</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_raw__c</fullName>
        <label>Email</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Verification_OTP_Invalid_Attempt__c</fullName>
        <label>Member Verification OTP Invalid Attempt</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NA_Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used for member needs assessments eligibility</description>
        <label>NA Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEAV_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEAV_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEEM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEEM_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to show if the NA Housing section is considered complete (TRUE) or partial (FALSE)</description>
        <label>NA LEHS Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Update__c</fullName>
        <label>NA LEHS Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_LEMD_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMD_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMQ_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMQ_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOL_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEOL_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA LEOM Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOM_Update__c</fullName>
        <description>Need Assessment last update field</description>
        <label>NA LEOM Update</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_LEPT_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEPT_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESB_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESB_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEWS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEWS_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out_Date__c</fullName>
        <description>The date 1 year into the future when the member will be able to have needs assessments performed.  The member can choose to opt out of the needs assessments for a period of 1 year.  This value is set by a workflow rule triggered by the NA Opt Out field change.</description>
        <label>NA Opt Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out_Updated__c</fullName>
        <label>NA Opt Out Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, indicates that the member has opted to not participate in needs assessments for the period of 1 year.</description>
        <label>NA Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a self-relationship field used to link SubAccounts(recType) to the respective MembershipAccounts(recType)</description>
        <label>Parent Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TYPE__c</fullName>
        <label>Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <description>This record type will be used to store all the Membership Accounts</description>
        <label>Membership</label>
    </recordTypes>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NA_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Needs_Assessment__c</fullName>
        <label>Needs_Assessment</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipLabel>NA_Deposits</relationshipLabel>
        <relationshipName>NA_Deposits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Certificate of Deposit (CD)</fullName>
                </value>
                <value>
                    <fullName>Money Market Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NA_Deposit</label>
    <nameField>
        <label>NA_Deposits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA_Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NA_Membership_Referral_Questions__c.object
<CustomObject>
    <fields>
        <fullName>Needs_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Needs Assessment</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipLabel>NA_Membership Referral Questions</relationshipLabel>
        <relationshipName>NA_Membership_Referral_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NA_Membership Referral Question</label>
    <nameField>
        <label>Membership Referral Questions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA_Membership Referral Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NA_Other_Existing_Loans__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Needs_Assessment__c</fullName>
        <label>Needs Assessment</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipLabel>NA_Other_Existing_Loans</relationshipLabel>
        <relationshipName>NA_Other_Existing_Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NA_Other_Existing_Loan</label>
    <nameField>
        <label>Other Loans</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA_Other_Existing_Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/Needs_Assesment__c/fields/Rec_Comment_New__c.field-meta.xml
<CustomField>
    <fullName>Rec_Comment_New__c</fullName>
    <label>Rec_Comment_New</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/ConvertPreMemberToMemberBatchClassTest.cls
@isTest
public class ConvertPreMemberToMemberBatchClassTest {
	
    static testmethod void testmethod1() {
	
        RecordType objRecordType = [SELECT Id,Name FROM RecordType WHERE Name='MemberShip'];
        RecordType objRecordType1 = [SELECT Id,Name FROM RecordType WHERE Name='Person Account'];
        RecordType rec1 = [Select Name, Id From RecordType where sObjectType='Account' and isActive=true and Name='Pre Member'];
        
        MemberConversionSetting__c mcs = new MemberConversionSetting__c();
        mcs.Name = 'PrimaryRecord';
        mcs.Manual__c = 10;
        mcs.Automation__c = 8;
        mcs.Unmerge__c = 10;
        mcs.Member_Matching_Cut_off_Date__c = Date.newInstance(2018, 10, 2);
        mcs.Not_matched_Members_cut_off_window__c = 3;
        insert mcs;
            
		Account_Details__c  act = new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE', RecordType = objRecordType);
		Insert act;
		
		Account_Details__c  act1 = new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE', RecordType = objRecordType1, Parent_Account__c = act.Id);
		Insert act1;
		
		
		List<Account> account_Obj = new List<Account>{new Account(LastName = 'Test1', FirstName = 'Test', Type = 'null', Member_Verification_OTP_Invalid_Attempt__c = system.now(), Home_Phone__pc = '123456333390', Mobile_Phone__pc = '258963147852', Work_Phone__pc = '233333232323', Email_raw__c = 'test1@test.com', PersonEmail = 'test1@test.com',Alt_Email_Raw__c ='ab1c@abc.com',  Alternate_Email__pc = 'abc@abc.com')};
		      												
    	Account pact = new Account();
        pact.FirstName = 'Test';
        pact.LastName = 'Test1';
        pact.Email_raw__c = 'test@test.com';
        pact.PersonEmail = 'test1@test.com';
        pact.Home_Phone__pc = '123456333390';
        pact.Work_Phone__pc = '233336232323';
        pact.Mobile_Phone__pc = '258663147852'; 
        pact.RecordtypeId = rec1.Id;
        pact.Residential_Street__pc ='34567';
        pact.BIRTH_DATE__pc = system.Today().addyears(-20);
        pact.NA_Eligibility__c = true;
        pact.NA_Eligibility__c= true;
		pact.NA_LEHS_Complete__c= true;
		pact.NA_LEHS_Update__c= system.Today(); 
		pact.NA_LEOM_Complete__c= true;
		pact.NA_LEOM_Update__c= system.Today();
		pact.NA_Opt_Out__c= false;
		pact.NA_Opt_Out_Date__c= system.Today();
		pact.NA_Opt_Out_Updated__c= system.Today();
		pact.NA_LEAV_Complete__c= true;
		pact.NA_LECF_Complete__c= true;
		pact.NA_LECP_Complete__c= true;
		pact.NA_LEEM_Complete__c= true;
		pact.NA_LEMD_Complete__c= true;
		pact.NA_LEMP_Complete__c= true;
		pact.NA_LEMQ_Complete__c= true;
		pact.NA_LEOL_Complete__c= true;
		pact.NA_LEPT_Complete__c= true;
		pact.NA_LESB_Complete__c= true;
		pact.NA_LESF_Complete__c= true;
		pact.NA_LEWS_Complete__c= true;
        account_Obj.add(pact);
        
        Insert account_Obj;
        
        List<Person_Account__c> person_obj= new List<Person_Account__c>{new Person_Account__c(Account_Number__c = act.Id, PersonID__c = account_Obj[0].Id), new Person_Account__c(Account_Number__c = act1.Id, PersonID__c = account_Obj[1].Id)};
		     Insert person_obj;
        
        
        Test.startTest();
        ConvertPreMemberToMemberBatchClass a = new ConvertPreMemberToMemberBatchClass();
        Database.executeBatch(a);
        Test.stopTest();
      
    }
    static testmethod void testmethod2() {
	
        RecordType objRecordType = [SELECT Id,Name FROM RecordType WHERE Name='MemberShip'];
        RecordType objRecordType1 = [SELECT Id,Name FROM RecordType WHERE Name='Person Account'];
        RecordType rec1 = [Select Name, Id From RecordType where sObjectType='Account' and isActive=true and Name='Pre Member'];
        
        MemberConversionSetting__c mcs = new MemberConversionSetting__c();
        mcs.Name = 'PrimaryRecord';
        mcs.Manual__c = 10;
        mcs.Automation__c = 8;
        mcs.Unmerge__c = 10;
        mcs.Member_Matching_Cut_off_Date__c = Date.newInstance(2018, 10, 2);
        mcs.Not_matched_Members_cut_off_window__c = 3;
        insert mcs;
            
		Account_Details__c  act = new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE', RecordType = objRecordType);
		Insert act;
		
		Account_Details__c  act1 = new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE', RecordType = objRecordType1, Parent_Account__c = act.Id);
		Insert act1;
		
		
		List<Account> account_Obj = new List<Account>{new Account(LastName = 'Test', FirstName = 'Test', Type = 'null', Member_Verification_OTP_Invalid_Attempt__c = system.now(), Home_Phone__pc = '9252066277', Mobile_Phone__pc = '9252066277', Work_Phone__pc = '9252066277', Email_raw__c = 'test1@test.com', PersonEmail = 'test1@test.com',Alt_Email_Raw__c ='ab1c@abc.com',Residential_Street__pc = 'res',Residential_Zipocde__pc = '23456',  Alternate_Email__pc = 'abc@abc.com')};
		      												
    	Account pact = new Account();
        pact.FirstName = 'Test';
        pact.LastName = 'Test1';
        pact.Email_raw__c = 'test@test.com';
        pact.PersonEmail = 'test1@test.com';
        pact.Home_Phone__pc = '9252066277';
        pact.Work_Phone__pc = '9252066277';
        pact.Mobile_Phone__pc = '9252066277'; 
        pact.RecordtypeId = rec1.Id;
        pact.Residential_Street__pc ='res';
        pact.Residential_Zipocde__pc = '23567';
        pact.BIRTH_DATE__pc = system.Today().addyears(-20);
        pact.NA_Eligibility__c = true;
        pact.NA_Eligibility__c= true;
		pact.NA_LEHS_Complete__c= true;
		pact.NA_LEHS_Update__c= system.Today(); 
		pact.NA_LEOM_Complete__c= true;
		pact.NA_LEOM_Update__c= system.Today();
		pact.NA_Opt_Out__c= false;
		pact.NA_Opt_Out_Date__c= system.Today();
		pact.NA_Opt_Out_Updated__c= system.Today();
		pact.NA_LEAV_Complete__c= true;
		pact.NA_LECF_Complete__c= true;
		pact.NA_LECP_Complete__c= true;
		pact.NA_LEEM_Complete__c= true;
		pact.NA_LEMD_Complete__c= true;
		pact.NA_LEMP_Complete__c= true;
		pact.NA_LEMQ_Complete__c= true;
		pact.NA_LEOL_Complete__c= true;
		pact.NA_LEPT_Complete__c= true;
		pact.NA_LESB_Complete__c= true;
		pact.NA_LESF_Complete__c= true;
		pact.NA_LEWS_Complete__c= true;
        account_Obj.add(pact);
        
        Insert account_Obj;
        
        List<Person_Account__c> person_obj= new List<Person_Account__c>{new Person_Account__c(Account_Number__c = act.Id, PersonID__c = account_Obj[0].Id), new Person_Account__c(Account_Number__c = act1.Id, PersonID__c = account_Obj[1].Id)};
		     Insert person_obj;
        
        
        Test.startTest();
        ConvertPreMemberToMemberBatchClass a = new ConvertPreMemberToMemberBatchClass();
        Database.executeBatch(a);
        Test.stopTest();
      
    }
    static testmethod void testmethod3() {
	
        RecordType objRecordType = [SELECT Id,Name FROM RecordType WHERE Name='MemberShip'];
        RecordType objRecordType1 = [SELECT Id,Name FROM RecordType WHERE Name='Person Account'];
        RecordType rec1 = [Select Name, Id From RecordType where sObjectType='Account' and isActive=true and Name='Pre Member'];
        
        MemberConversionSetting__c mcs = new MemberConversionSetting__c();
        mcs.Name = 'PrimaryRecord';
        mcs.Manual__c = 10;
        mcs.Automation__c = 8;
        mcs.Unmerge__c = 10;
        mcs.Member_Matching_Cut_off_Date__c = Date.newInstance(2018, 10, 2);
        mcs.Not_matched_Members_cut_off_window__c = 3;
        insert mcs;
            
		Account_Details__c  act = new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE',TYPE__c = 2, RecordType = objRecordType);
		Insert act;
		
		Account_Details__c  act1 = new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE', RecordType = objRecordType1, Parent_Account__c = act.Id);
		Insert act1;
		
		
		List<Account> account_Obj = new List<Account>{new Account(LastName = 'Test1', FirstName = 'Test', Type = 'null', Member_Verification_OTP_Invalid_Attempt__c = system.now(), Home_Phone__pc = '9252066277', Mobile_Phone__pc = '9252066277', Work_Phone__pc = '9252066277',Residential_Street__pc = 'res',Residential_Zipocde__pc = '23456', Email_raw__c = 'test1@test.com', PersonEmail = 'test1@test.com',Alt_Email_Raw__c ='ab1c@abc.com',  Alternate_Email__pc = 'abc@abc.com')};
		Insert account_Obj;
        
    	Account pact = new Account();
        pact.FirstName = 'Test';
        pact.LastName = 'Test1';
        //pact.Email_raw__c = 'test@test.com';
        //pact.PersonEmail = 'test1@test.com';
        //pact.Home_Phone__pc = '9252066277';
        pact.Work_Phone__pc = '9252066277';
        pact.Mobile_Phone__pc = '9252066277'; 
        pact.RecordtypeId = rec1.Id;
        pact.Residential_Street__pc ='res';
        pact.Residential_Zipocde__pc = '23567';
        pact.BIRTH_DATE__pc = system.Today().addyears(-20);
        pact.NA_Eligibility__c = true;
        pact.NA_Eligibility__c= true;
		pact.NA_LEHS_Complete__c= true;
		pact.NA_LEHS_Update__c= system.Today(); 
		pact.NA_LEOM_Complete__c= true;
		pact.NA_LEOM_Update__c= system.Today();
		pact.NA_Opt_Out__c= false;
		pact.NA_Opt_Out_Date__c= system.Today();
		pact.NA_Opt_Out_Updated__c= system.Today();
		pact.NA_LEAV_Complete__c= true;
		pact.NA_LECF_Complete__c= true;
		pact.NA_LECP_Complete__c= true;
		pact.NA_LEEM_Complete__c= true;
		pact.NA_LEMD_Complete__c= true;
		pact.NA_LEMP_Complete__c= true;
		pact.NA_LEMQ_Complete__c= true;
		pact.NA_LEOL_Complete__c= true;
		pact.NA_LEPT_Complete__c= true;
		pact.NA_LESB_Complete__c= true;
		pact.NA_LESF_Complete__c= true;
		pact.NA_LEWS_Complete__c= true;
        insert pact;
        
        account_Obj.add(pact);
        
        
        
        List<Person_Account__c> person_obj= new List<Person_Account__c>{new Person_Account__c(Account_Number__c = act.Id, TypeTranslate__c = 'PRIMARY', PersonID__c = account_Obj[0].Id), new Person_Account__c(Account_Number__c = act1.Id, PersonID__c = account_Obj[1].Id)};
		Insert person_obj;
        
        /*Task tk = new task();
        tk.Status = 'Open';
        tk.WhoId = pact.id;
        insert tk;*/
        
        
        
        Needs_Assesment__c na = new Needs_Assesment__c();
        na.Member__c = pact.id;
        na.Rec_Comment_New__c = 'test';
        insert na;
        
        NA_Other_Existing_Loans__c nae = new NA_Other_Existing_Loans__c();
        nae.Needs_Assessment__c = na.id;
        nae.Balance__c = 10000.00;
        insert nae;
        
        NA_Membership_Referral_Questions__c nmr = new NA_Membership_Referral_Questions__c();
        nmr.Needs_Assessment__c = na.id;
        nmr.Age__c = '22';
        insert nmr;
        
        NA_Deposit__c nd = new NA_Deposit__c();
        nd.Needs_Assessment__c = na.id;
        nd.Balance__c = 10000;
        insert nd;
        
        Opportunity op = new Opportunity(Name = 'Name', StageName = 'Open',Product_Type__c = 'Misc', CloseDate = system.today(),  Is_Converted__c = true, Opportunity_Source__c = 'Word of mouth', AccountId = pact.id,  Ownership__c = 'Auto Assign', Episys_User_ID__c = 1);
        insert op;
        
        Case cs = new Case();
        cs.AccountId = pact.Id;
        cs.Brand__c = 'Spectrum';
        insert cs;
        
        Test.startTest();
        ConvertPreMemberToMemberBatchClass a = new ConvertPreMemberToMemberBatchClass();
        Database.executeBatch(a);
        ConvertPreMemberToMemberWebservice.Convert();
        ConvertPreMemberToMemberWebservice.CreateCaseForNonMatchedMember();
        Test.stopTest();
      
    }
}