src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>AccountID__c</fullName>
        <externalId>true</externalId>
        <label>AccountID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_User_Alias__c</fullName>
        <label>Created By User Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_User_Text__c</fullName>
        <label>Created By User Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_User__c</fullName>
        <label>Created By User</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OPEN_DATE__c</fullName>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>E-mail Address</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Membership_account_created_date__c</fullName>
        <label>Membership account created date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
                <value>
                    <fullName>Onboarding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Onboarding</fullName>
        <active>true</active>
        <businessProcess>Onboarding</businessProcess>
        <description>Onboarding new accounts (2,2,2)</description>
        <label>Onboarding</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <description>This field will be used to uniquely identify a Person.</description>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>AccountID__c</fullName>
        <label>AccountID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Open_Date__c</fullName>
        <formula>Account_Number__r.OPEN_DATE__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PersonAccountTriggerHandler.cls
public with sharing class PersonAccountTriggerHandler {
   // 
    public static void createCase(map<Id,Person_Account__c> newMap){
        list<Person_Account__c> paList = new list<Person_Account__c>();
        set<Id> personIds = new set<Id>();
        set<Id> accDetailIds = new set<Id>();
        map<Id,Account> personMap = new map<Id,Account>();
        map<Id,Account_Details__c> accDetailMap = new map<Id,Account_Details__c>();
        list<Case> caseList = new list<Case>();
      //  map<double,Id> userMap = new map<double,Id>();
        map<String,Id> userMap1 = new map<String,Id>();
        map<String,Id> userAliasMap = new map<String,Id>();
        
        for(Person_Account__c pa: newMap.values()){
            if(pa.Name_Type__c == 0){
              //CRM-1090 only add person whose open date is within 7 days
              if (pa.Open_Date__c != null && pa.Open_Date__c.daysBetween(date.today()) <= 7)
              {
                System.debug('adding person account with open date..' + pa.Open_Date__c);
                System.debug('adding person account with Account ID..' + pa.AccountID__c);
                  paList.add(pa); 
                  personIds.add(pa.PersonID__c);
                  accDetailIds.add(pa.Account_Number__c);
              }
              else
              {
                System.debug('Not adding person account with open date..' + pa.Open_Date__c);
                System.debug('Not adding person account with Account ID..' + pa.AccountID__c);
                  
              }                
            }
        }
        
        list<Account> personList = [SELECT Id,firstname, Lastname, PersonHomePhone, 
                                    PersonEmail, Residential_Street__pc, Residential_City__pc, 
                                    Residential_State__pc, Residential_Zipocde__pc FROM Account WHERE Id IN: personIds];
        Set<Id> perId = new Set<Id>();
        for(Account pl: personList){
            personMap.put(pl.Id, pl);
            perId.add(pl.Id);
        }
        
        list<Account_Details__c> accDetailList = [SELECT Id, Open_Date__c, Created_By_User__c, OnBoarded__c, Created_By_User_Text__c, Created_By_User_Alias__c FROM Account_Details__c WHERE Id IN: accDetailIds];
        for(Account_Details__c adl: accDetailList){
            accDetailMap.put(adl.Id, adl);
        }
        
        List<Contact> con = [Select Id, Name, AccountId from Contact where Contact.AccountId =:perId];
        Map<Id,Id> conMap = new Map<Id,Id>();
        for(Contact ct : con){
            conMap.put(ct.AccountId, ct.Id);
        }
 
       // Id queueGroupId = [SELECT Id FROM Group WHERE Type='Queue' AND Name= 'Operations-Memberships Queue'].Id;
        Id queueGroupId = [SELECT Id FROM Group WHERE Type='Queue' AND Name= 'eBranch Queue'].Id;
        
        //list<User> userList = [SELECT Id, Name, Alias, IsActive FROM User where IsActive = true];
        
        list<User> userList = [SELECT Id, Name, Alias, IsActive FROM User
                                where (Profile.Name !='Messaging center Customers') and (isActive = True)];

        
        
        for(User u: userList){
            userMap1.put(u.Name.toupperCase(), u.Id);
            userAliasMap.put(u.Alias, u.Id);
        } 
        
        list<User> userList1 = [SELECT Id, Name, Alias, IsActive FROM User where IsActive = false];
        Set<Id> uList = new Set<Id>();
        for(User u : userList1){
            uList.add(u.Id);
        } 

        for(Person_Account__c var: paList){
            
            if(accDetailMap.get(var.Account_Number__c).OnBoarded__c == true){
            Case c = new Case();
                c.RecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Onboarding').getRecordTypeId();
                c.Primary_Category__c = 'Account Maintenance';
                c.Secondary_Category__c = 'OnBoarding';
                c.Tertiary_Category__c = 'None';
                c.Status = 'Open';
                c.Account_Number__c = var.Account_Number__c;
               // c.AccountId = personMap.get(var.PersonID__c).Id;
                c.AccountId = var.PersonID__c;
                if(c.ContactId == NULL){
                    c.ContactId = conMap.get(var.PersonID__c);
                }
                c.First_Name__c = personMap.get(var.PersonID__c).firstname;
                c.Last_Name__c = personMap.get(var.PersonID__c).lastname;
                c.Phone_Number__c = personMap.get(var.PersonID__c).PersonHomePhone;
                c.Email_Address__c = personMap.get(var.PersonID__c).PersonEmail;
                c.Street_Address_1__c = personMap.get(var.PersonID__c).Residential_Street__pc;
                c.City__c = personMap.get(var.PersonID__c).Residential_City__pc;
                c.State__c = personMap.get(var.PersonID__c).Residential_State__pc;
                c.Zip_Code__c = personMap.get(var.PersonID__c).Residential_Zipocde__pc;
                c.Membership_account_created_date__c = accDetailMap.get(var.Account_Number__c).OPEN_DATE__c;
                             
                system.debug('accdetailmap ..' + accDetailMap);
                system.debug('var.accounnumber ' + var.Account_Number__c);
                system.debug('check for user..' + userAliasMap.get(accDetailMap.get(var.Account_Number__c).Created_By_User_Alias__c));
                
                if(userAliasMap.get(accDetailMap.get(var.Account_Number__c).Created_By_User_Alias__c) != null){
                  system.debug('###Inside  assigning owner' + userAliasMap.get(accDetailMap.get(var.Account_Number__c).Created_By_User_Alias__c));
               // if(userMap1.get(accDetailMap.get(var.Account_Number__c).Created_By_User_Text__c) != null){
                    c.OwnerId = userAliasMap.get((accDetailMap.get(var.Account_Number__c).Created_By_User_Alias__c).toupperCase());
                }else if(userAliasMap.get(accDetailMap.get(var.Account_Number__c).Created_By_User_Alias__c) == null || accDetailMap.get(var.Account_Number__c).Created_By_User__c == NULL 
                   || uList != NULL){
                    system.debug('Inside assigning eBranch queue');
                    c.OwnerId = queueGroupId;
                }
            
            caseList.add(c);
        }            
        }
        
        try{
            insert caseList;
            System.debug('Case is:::'+caseList);
        }catch(Exception e){
            System.debug('An error was encountered :'+e);
        }
        for(Account_Details__c ad : accDetailList){
           ad.OnBoarded__c = false;
        }
        update accDetailList;
    }
}