src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a self-relationship field used to link SubAccounts(recType) to the respective MembershipAccounts(recType)</description>
        <label>Parent Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Card</fullName>
        <active>true</active>
        <description>This record type will be used to store all the CARD Information</description>
        <label>Card</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PersonNameforSubAccountsControllerTest.cls
@isTest
public class PersonNameforSubAccountsControllerTest {
    
    static testMethod void testMethod1(){
        
        Account_Details__c accDetails1 = new Account_Details__c();
            accDetails1.RecType__c = 'ACCT';
        insert accDetails1;
        
        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'test';
            accDetails.RecType__c = 'CARD';
            accDetails.Parent_Account__c = accDetails1.Id;
        insert accDetails;
        
        PageReference pageRef = Page.PersonNameforSubAccounts;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('Id', accDetails.Id);        
        PersonNameforSubAccountsController controller = new PersonNameforSubAccountsController(new ApexPages.StandardController(accDetails));
    }

}