src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Employee_Restricted_Access__c</fullName>
        <label>Employee Restricted Access</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>Status</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GetRelatedAccountsforCaseTest.cls
@isTest
public class GetRelatedAccountsforCaseTest {
    static testMethod void testMethod1() {
	 	
	 	Create_SLA__c cl = new Create_SLA__c();
        cl.Status__c = 'Open';
        cl.Name = 'Open';
        cl.hours__c = 8;
        insert cl;
        
        Create_SLA__c cl1 = new Create_SLA__c();
        cl1.Status__c = 'In Process';
        cl1.Name = 'In Process';
        cl1.hours__c = 20;
        insert cl1;
        
        Create_SLA__c cl2 = new Create_SLA__c();
        cl2.Status__c = 'Resolution';
        cl2.Name = 'Resolution';
        cl2.hours__c = 20;
        insert cl2;
        
        Account acobj = new Account();
        acobj.FirstName = 'U';
        acobj.LastName = 'D';
        acobj.BIRTH_DATE__pc = date.parse('04/04/1963');
        acobj.Employee_Restricted_Access__c = 1234;
        acobj.Home_Phone__pc = '9169954478';
        insert acobj;
        
	 	 Account_Details__c accDetails = new Account_Details__c();
        accDetails.Name = '0000123';
        accDetails.RecType__c = 'ACCT';
        insert accDetails;
   
        
        Account_Details__c accDetails1 = new Account_Details__c();
        accDetails1.Name = '0000456';
        accDetails1.RecType__c = 'ACCT';
        insert accDetails1;
   
        Case case1 = new Case();
        case1.Subject = 'Test';
        case1.Description = 'test';
        case1.Accountid = acobj.Id;
        case1.Brand__c ='Spectrum';
        case1.Account_Number__c = accDetails.id;
        insert case1;
        
        CaseAccountMemberDetail__c camd1 = new CaseAccountMemberDetail__c();
        camd1.Account_Name__c = accDetails1.Name;
        camd1.Case__c = case1.id;
        camd1.MemberAccountid__c = accDetails1.Id;
        
        insert camd1;
        
         CaseAccountMemberDetail__c camd2 = new CaseAccountMemberDetail__c();
        camd1.Account_Name__c = accDetails.Name;
        camd1.Case__c = case1.id;
        camd1.MemberAccountid__c = accDetails.Id;
        
        insert camd2;
        
      
         Test.StartTest();

         GetRelatedAccountsforCase.GetCaseAccounts(case1.id);	        
	      
        Test.StopTest();
	    }
    
}