src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used for member needs assessments eligibility</description>
        <label>NA Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEAV_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEAV_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEEM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEEM_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to show if the NA Housing section is considered complete (TRUE) or partial (FALSE)</description>
        <label>NA LEHS Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMD_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMD_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMQ_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMQ_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOL_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEOL_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA LEOM Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEPT_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEPT_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESB_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESB_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEWS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEWS_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, indicates that the member has opted to not participate in needs assessments for the period of 1 year.</description>
        <label>NA Opt Out</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Documents__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this button when you want to send additional documents apart from the pre-configured ones through DocuSign.</description>
        <label>Additional Documents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Five_Day_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Five Day Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkRead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkSaved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkSaved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaritzCX__Response_Deleted_From_MaritzCX__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field keeps track of whether the response is available or deleted from the system.</description>
        <label>Response Deleted From MaritzCX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLATemp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLATemp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Staff_Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field to manually escalate a case</description>
        <inlineHelpText>Use this field to manually escalate a case for further assistance</inlineHelpText>
        <label>Staff Escalated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>et4ae5__HasOptedOutOfMobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>smagicinteract__SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QueueOwnersControllerTest.cls
@isTest
private class QueueOwnersControllerTest{
  @testSetup
  static void setupTestData(){
    test.startTest();
    Account account_Obj = new Account(Name='Saumil',Website = 'null', CreatedDate = Date.ValueOf('2017-12-05 21:21:23'), LastModifiedDate = Date.ValueOf('2017-12-06 00:58:53'), PersonHasOptedOutOfEmail = false, NA_Eligibility__c = false, NA_LEAV_Complete__c = false, NA_LECF_Complete__c = false, NA_LECP_Complete__c = false, NA_LEEM_Complete__c = false, NA_LEHS_Complete__c = false, NA_LEMD_Complete__c = false, NA_LEMP_Complete__c = false, NA_LEMQ_Complete__c = false, NA_LEOL_Complete__c = false, NA_LEOM_Complete__c = false, NA_LEPT_Complete__c = false, NA_LESB_Complete__c = false, NA_LESF_Complete__c = false, NA_LEWS_Complete__c = false, NA_Opt_Out__c = false);
    Insert account_Obj; 
    Contact contact_Obj = new Contact(AccountId = account_Obj.id, LastName = 'DILTZ', MailingCity = ' ', MailingState = ' ', MailingPostalCode =  ' ',MailingCountryCode = 'US', HasOptedOutOfEmail = false, CreatedDate = Date.ValueOf('2017-12-05 21:21:23'),  LastModifiedDate = Date.ValueOf('2017-12-06 00:58:53'), smagicinteract__SMSOptOut__c = false, et4ae5__HasOptedOutOfMobile__c = false);
    Insert contact_Obj; 
    Case case_Obj = new Case(ContactId = contact_Obj.id, AccountId = account_Obj.id,Brand__c='Chevron', IsEscalated = false, CreatedDate = Date.ValueOf('2017-12-05 21:22:05'),  LastModifiedDate = Date.ValueOf('2017-12-05 21:22:06'), Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
    Insert case_Obj; 
    test.stopTest();
  }
  static testMethod void test_GetuserCases_UseCase1(){
    List<Account> account_Obj  =  [SELECT Id,IsDeleted,Fax,AccountNumber,Website,PhotoUrl,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,PersonHasOptedOutOfEmail,NA_Eligibility__c,NA_LEAV_Complete__c,NA_LECF_Complete__c,NA_LECP_Complete__c,NA_LEEM_Complete__c,NA_LEHS_Complete__c,NA_LEMD_Complete__c,NA_LEMP_Complete__c,NA_LEMQ_Complete__c,NA_LEOL_Complete__c,NA_LEOM_Complete__c,NA_LEPT_Complete__c,NA_LESB_Complete__c,NA_LESF_Complete__c,NA_LEWS_Complete__c,NA_Opt_Out__c from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Contact> contact_Obj  =  [SELECT Id,IsDeleted,MasterRecordId,AccountId,LastName,MailingCity,MailingState,MailingPostalCode,MailingCountryCode,HasOptedOutOfEmail,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,smagicinteract__SMSOptOut__c,et4ae5__HasOptedOutOfMobile__c from Contact];
    System.assertEquals(true,contact_Obj.size()>0);
    List<Case> case_Obj  =  [SELECT Id,IsDeleted,CaseNumber,ContactId,AccountId,AssetId,IsEscalated,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,Additional_Documents__c,Staff_Escalated__c,Five_Day_Flag__c,IsMarkDeleted__c,IsMarkRead__c,IsMarkSaved__c,MaritzCX__Response_Deleted_From_MaritzCX__c,SLATemp__c from Case];
    System.assertEquals(true,case_Obj.size()>0);
    QueueOwnersController obj01 = new QueueOwnersController();
    QueueOwnersController.GetuserCases();
  }
  static testMethod void test_saveUserCases_UseCase1(){
    List<Account> account_Obj  =  [SELECT Id,IsDeleted,Fax,AccountNumber,Website,PhotoUrl,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,PersonHasOptedOutOfEmail,NA_Eligibility__c,NA_LEAV_Complete__c,NA_LECF_Complete__c,NA_LECP_Complete__c,NA_LEEM_Complete__c,NA_LEHS_Complete__c,NA_LEMD_Complete__c,NA_LEMP_Complete__c,NA_LEMQ_Complete__c,NA_LEOL_Complete__c,NA_LEOM_Complete__c,NA_LEPT_Complete__c,NA_LESB_Complete__c,NA_LESF_Complete__c,NA_LEWS_Complete__c,NA_Opt_Out__c from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Contact> contact_Obj  =  [SELECT Id,IsDeleted,MasterRecordId,AccountId,LastName,MailingCity,MailingState,MailingPostalCode,MailingCountryCode,HasOptedOutOfEmail,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,smagicinteract__SMSOptOut__c,et4ae5__HasOptedOutOfMobile__c from Contact];
    System.assertEquals(true,contact_Obj.size()>0);
    List<Case> case_Obj  =  [SELECT Id,IsDeleted,OwnerId,CaseNumber,ContactId,AccountId,AssetId,IsEscalated,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,Additional_Documents__c,Staff_Escalated__c,Five_Day_Flag__c,IsMarkDeleted__c,IsMarkRead__c,IsMarkSaved__c,MaritzCX__Response_Deleted_From_MaritzCX__c,SLATemp__c from Case];
    System.assertEquals(true,case_Obj.size()>0);
    QueueOwnersController obj01 = new QueueOwnersController();
    QueueOwnersController.QueueWrapper qw = new QueueOwnersController.QueueWrapper(case_Obj[0]);
    
    qw.selected = true;
    
    List<QueueOwnersController.QueueWrapper> listQueue = new List<QueueOwnersController.QueueWrapper> ();
    
    listQueue.add(qw);
    string dataserialize = JSON.serialize(listQueue);
    
    QueueOwnersController.saveUserCases(dataserialize,case_Obj[0].OwnerId);
  }
 /*  static testMethod void test_QueueOwnersController.QueueWrapper(){
    List<Account> account_Obj  =  [SELECT Id,IsDeleted,Fax,AccountNumber,Website,PhotoUrl,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,PersonHasOptedOutOfEmail,NA_Eligibility__c,NA_LEAV_Complete__c,NA_LECF_Complete__c,NA_LECP_Complete__c,NA_LEEM_Complete__c,NA_LEHS_Complete__c,NA_LEMD_Complete__c,NA_LEMP_Complete__c,NA_LEMQ_Complete__c,NA_LEOL_Complete__c,NA_LEOM_Complete__c,NA_LEPT_Complete__c,NA_LESB_Complete__c,NA_LESF_Complete__c,NA_LEWS_Complete__c,NA_Opt_Out__c,smagicinteract__SMSOptOut__pc,	 from Account];
    System.assertEquals(true,account_Obj.size()>0);
    List<Contact> contact_Obj  =  [SELECT Id,IsDeleted,MasterRecordId,AccountId,LastName,MailingCity,MailingState,MailingPostalCode,MailingStateCode,MailingCountryCode,HasOptedOutOfEmail,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,smagicinteract__SMSOptOut__c,et4ae5__HasOptedOutOfMobile__c from Contact];
    System.assertEquals(true,contact_Obj.size()>0);
    List<Case> case_Obj  =  [SELECT Id,IsDeleted,CaseNumber,ContactId,AccountId,AssetId,IsEscalated,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,Additional_Documents__c,Staff_Escalated__c,Five_Day_Flag__c,IsMarkDeleted__c,IsMarkRead__c,IsMarkSaved__c,MaritzCX__Response_Deleted_From_MaritzCX__c,SLATemp__c from Case];
    System.assertEquals(true,case_Obj.size()>0);
    QueueOwnersController obj01 = new QueueOwnersController();
    QueueOwnersController.QueueWrapper obj31 = new QueueOwnersController.QueueWrapper(new Case());
  }*/
}