src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Created_By_User_Alias__c</fullName>
        <label>Created By User Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateCaseForNonMatchedMemberBatch.cls
global class CreateCaseForNonMatchedMemberBatch implements Database.Batchable<sObject> {
    
 global Database.QueryLocator start(Database.BatchableContext BC){
     MemberConversionSetting__c mcs = MemberConversionSetting__c.getValues('PrimaryRecord');
            Integer Days_Automation =0;
            Days_Automation = (Integer)mcs.Not_matched_Members_cut_off_window__c;   
            Days_Automation = (Days_Automation) ;
          //  datetime LastNDays = system.now().addDays(Days_Automation);
           
            BusinessHours  bh = [SELECT Id, MondayEndTime, MondayStartTime FROM BusinessHours WHERE IsDefault=true];
            integer businessduration = bh.MondayEndTime.hour() - bh.MondayStartTime.hour(); 
            
            integer j = Days_Automation;
            integer hours = Days_Automation * 10 * (-1);
            
            datetime businessdays3 = BusinessHours.addGmt(bh.id, system.now(), 3600000 * hours); 
			Timezone tz = Timezone.getTimeZone('America/Los_Angeles');
			
          				
			//DateTime dt1 = system.Now().addDays(-j);
			DateTime dt1 = businessdays3.addSeconds(tz.getOffset(businessdays3) / 1000);
            
            Datetime dt = BusinessHours.add(bh.id, System.now(), -3600000 * businessduration );
      System.debug('Start method called');
     System.debug('Start query called' +  Database.getQueryLocator('SELECT Id, Owner.Name, FirstName,LastName, Ownerid, Is_Case_Created__c, Created_By_Episys_User_Alias__c FROM Account ' + 
                                      	' where RecordType.Name = \'Person Account\' and IsConverted__c=false and Is_Case_Created__c = false ' +
            					  ' and createddate >= ' + string.valueof(dt1).replace(' ','T') + '.000+0000 and  createddate <= ' + string.valueof(dt).replace(' ','T') + '.000+0000'));
     
		return Database.getQueryLocator('SELECT Id, Owner.Name, FirstName,LastName, Ownerid, Is_Case_Created__c, Created_By_Episys_User_Alias__c FROM Account ' + 
                                      	' where RecordType.Name = \'Person Account\' and IsConverted__c=false and Is_Case_Created__c = false ' +
            					  ' and createddate >= ' + string.valueof(dt1).replace(' ','T') + '.000+0000 and  createddate <= ' + string.valueof(dt).replace(' ','T') + '.000+0000');
    
      
   }
    global void execute(Database.BatchableContext BC, List<Account> acclist){
       system.debug('acclist##' + acclist);
        Set<ID> accountIds = new Set<Id>();
        Set<String> aliaslist = new Set<String>();
        Map<Id, String> accaliasmap = new Map<Id, String>();
     	for(Account s : acclist){
	     	accountIds.add(s.id);
            aliaslist.add(s.Created_By_Episys_User_Alias__c);

	    }
    List<user> listUser =    [select id, Alias from user where alias in : aliaslist];
        
       
        
        
        system.debug('listUser.size()##'+ listUser);
         system.debug('accountIds##'+ accountIds);
        if(accountIds.size() > 0)
        {
           //  List<Case> caselist = new List<Case>(); 
             List<FeedItem> FeedItemlist = new List<FeedItem>(); 
             List<Account> updateacclist = new List<Account>();
             List<Person_Account__c> paList = [SELECT Id,Ownerid, PersonID__c, Account_Number__c,Account_Number__r.Created_By_User_Alias__c FROM Person_Account__c WHERE 
                                                      PersonID__c =: accountIds  Order by Account_Number__r.RecType__c];
            
            Set<string> listUserAlias = new Set<string>();
            
           
            
            
            for(Account acc : acclist)
            {
            	 System.debug('inside');
            	 
            	 // Changes done for MVAN-8 Begin
             /*   Case c = new Case();
                c.Primary_Category__c = 'Account Maintenance';
                c.Secondary_Category__c = 'Pre Member Conversion';
                c.Tertiary_Category__c = 'Failed';
                c.Status ='Open';
                c.accountid = acc.id;
                c.Subject = 'Failed Pre Member Conversion';
                
                for(user u : listUser)
                {
                    if(u.alias == acc.Created_By_Episys_User_Alias__c)
                    {
                        c.ownerid = u.id;
                    }
                }
                            
                */
                
          //   User MarsUser =   [select id, name from user where name ='MARS System'];
			  
                 for(user u : listUser)
                {
                     System.debug('insideuser');
                    if(u.alias == acc.Created_By_Episys_User_Alias__c)
                    {
                        FeedItem post = new FeedItem();
			 			//post.Body = 'Failed Pre Member Conversion';
			 			String fullURL = URL.getSalesforceBaseUrl().toExternalForm()+ '/lightning/n/Pre_Member_Conversion';      
			 			system.debug('fullURL==='+fullURL); 
                        //post.Body = 'Failed Pre Member Conversion. Click here to convert Pre Member: ' + fullURL; 
			 			post.Body = 'Failed Pre Member Conversion for ' + acc.FirstName + ' ' + acc.LastName + ' Click here to convert Pre Member: ' + fullURL; 
			 			post.LinkUrl = fullURL;			 			
			 			post.ParentId = u.id;			 			
                        FeedItemlist.Add(post);
                    }
                    
                }
               
               // FeedItemlist.Add(post);
                acc.Is_Case_Created__c = true;
                updateacclist.add(acc);
                  
            }
	        		
            if(!FeedItemlist.IsEmpty()) insert FeedItemlist;
            System.debug('FeedItemlist##' + FeedItemlist.size());
             System.debug('FeedItemlist##' + FeedItemlist);
            if(!updateacclist.IsEmpty()) update updateacclist;
	       
	        // Changes done for MVAN-8 Ends here		
             
             
        }
        
    }
    
    global void finish(Database.BatchableContext BC){
   }
}