src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_01__c</fullName>
        <description>Comment Block 1</description>
        <label>Comment 01</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_02__c</fullName>
        <label>Comment 02</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_03__c</fullName>
        <label>Comment 03</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_04__c</fullName>
        <label>Comment 04</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_05__c</fullName>
        <label>Comment 05</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_06__c</fullName>
        <label>Comment 06</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_07__c</fullName>
        <label>Comment 07</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_08__c</fullName>
        <label>Comment 08</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_09__c</fullName>
        <label>Comment 09</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_10__c</fullName>
        <label>Comment 10</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_11__c</fullName>
        <label>Comment 11</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_12__c</fullName>
        <label>Comment 12</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_13__c</fullName>
        <label>Comment 13</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_14__c</fullName>
        <label>Comment 14</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_15__c</fullName>
        <label>Comment 15</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_16__c</fullName>
        <label>Comment 16</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_17__c</fullName>
        <label>Comment 17</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_18__c</fullName>
        <label>Comment 18</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_19__c</fullName>
        <label>Comment 19</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_20__c</fullName>
        <label>Comment 20</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_01_CODE__c</fullName>
        <label>Warning 01 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_02_CODE__c</fullName>
        <label>Warning 02 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_03_CODE__c</fullName>
        <label>Warning 03 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_04_CODE__c</fullName>
        <label>Warning 04 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_05_CODE__c</fullName>
        <label>Warning 05 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_06_CODE__c</fullName>
        <label>Warning 06 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_07_CODE__c</fullName>
        <label>Warning 07 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_08_CODE__c</fullName>
        <label>Warning 08 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_09_CODE__c</fullName>
        <label>Warning 09 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_10_CODE__c</fullName>
        <label>Warning 10 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_11_CODE__c</fullName>
        <label>Warning 11 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_12_CODE__c</fullName>
        <label>Warning 12 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_13_CODE__c</fullName>
        <label>Warning 13 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_14_CODE__c</fullName>
        <label>Warning 14 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_15_CODE__c</fullName>
        <label>Warning 15 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_16_CODE__c</fullName>
        <label>Warning 16 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_17_CODE__c</fullName>
        <label>Warning 17 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_18_CODE__c</fullName>
        <label>Warning 18 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_19_CODE__c</fullName>
        <label>Warning 19 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_20_CODE__c</fullName>
        <label>Warning 20 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Additional_Documents__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this button when you want to send additional documents apart from the pre-configured ones through DocuSign.</description>
        <label>Additional Documents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Five_Day_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Five Day Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkRead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkSaved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkSaved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Staff_Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field to manually escalate a case</description>
        <inlineHelpText>Use this field to manually escalate a case for further assistance</inlineHelpText>
        <label>Staff Escalated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Staging/src/main/default/classes/MemberAccount360ViewControllerTest.cls
@isTest
public class MemberAccount360ViewControllerTest {
	
	@testSetup
		  static void setupTestData(){
		    test.startTest();
		    List<Account_Details__c> account_details_Obj = new List<Account_Details__c>{
						    new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC',
WARNING_02_CODE__c='ABC',
WARNING_03_CODE__c='ABC',
WARNING_04_CODE__c='ABC',
WARNING_05_CODE__c='ABC',
WARNING_06_CODE__c='ABC',
WARNING_07_CODE__c='ABC',
WARNING_08_CODE__c='ABC',
WARNING_09_CODE__c='ABC',
WARNING_10_CODE__c='ABC',
WARNING_11_CODE__c='ABC',
WARNING_12_CODE__c='ABC',
WARNING_13_CODE__c='ABC',
WARNING_14_CODE__c='ABC',
WARNING_15_CODE__c='ABC',
WARNING_16_CODE__c='ABC',
WARNING_17_CODE__c='ABC',
WARNING_18_CODE__c='ABC',
WARNING_19_CODE__c='ABC',
WARNING_20_CODE__c='ABC',
Comment_Block_01__c='ABC',
Comment_Block_02__c='ABC',
Comment_Block_03__c='ABC',
Comment_Block_04__c='ABC',
Comment_Block_05__c='ABC',
Comment_Block_06__c='ABC',
Comment_Block_07__c='ABC',
Comment_Block_08__c='ABC',
Comment_Block_09__c='ABC',
Comment_Block_10__c='ABC',
Comment_Block_11__c='ABC',
Comment_Block_12__c='ABC',
Comment_Block_13__c='ABC',
Comment_Block_14__c='ABC',
Comment_Block_15__c='ABC',
Comment_Block_16__c='ABC',
Comment_Block_17__c='ABC',
Comment_Block_18__c='ABC',
Comment_Block_19__c='ABC',
Comment_Block_20__c='ABC'
),
						    new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC',
WARNING_02_CODE__c='ABC',
WARNING_03_CODE__c='ABC',
WARNING_04_CODE__c='ABC',
WARNING_05_CODE__c='ABC',
WARNING_06_CODE__c='ABC',
WARNING_07_CODE__c='ABC',
WARNING_08_CODE__c='ABC',
WARNING_09_CODE__c='ABC',
WARNING_10_CODE__c='ABC',
WARNING_11_CODE__c='ABC',
WARNING_12_CODE__c='ABC',
WARNING_13_CODE__c='ABC',
WARNING_14_CODE__c='ABC',
WARNING_15_CODE__c='ABC',
WARNING_16_CODE__c='ABC',
WARNING_17_CODE__c='ABC',
WARNING_18_CODE__c='ABC',
WARNING_19_CODE__c='ABC',
WARNING_20_CODE__c='ABC',
Comment_Block_01__c='ABC',
Comment_Block_02__c='ABC',
Comment_Block_03__c='ABC',
Comment_Block_04__c='ABC',
Comment_Block_05__c='ABC',
Comment_Block_06__c='ABC',
Comment_Block_07__c='ABC',
Comment_Block_08__c='ABC',
Comment_Block_09__c='ABC',
Comment_Block_10__c='ABC',
Comment_Block_11__c='ABC',
Comment_Block_12__c='ABC',
Comment_Block_13__c='ABC',
Comment_Block_14__c='ABC',
Comment_Block_15__c='ABC',
Comment_Block_16__c='ABC',
Comment_Block_17__c='ABC',
Comment_Block_18__c='ABC',
Comment_Block_19__c='ABC',
Comment_Block_20__c='ABC'
),
						    new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC',
WARNING_02_CODE__c='ABC',
WARNING_03_CODE__c='ABC',
WARNING_04_CODE__c='ABC',
WARNING_05_CODE__c='ABC',
WARNING_06_CODE__c='ABC',
WARNING_07_CODE__c='ABC',
WARNING_08_CODE__c='ABC',
WARNING_09_CODE__c='ABC',
WARNING_10_CODE__c='ABC',
WARNING_11_CODE__c='ABC',
WARNING_12_CODE__c='ABC',
WARNING_13_CODE__c='ABC',
WARNING_14_CODE__c='ABC',
WARNING_15_CODE__c='ABC',
WARNING_16_CODE__c='ABC',
WARNING_17_CODE__c='ABC',
WARNING_18_CODE__c='ABC',
WARNING_19_CODE__c='ABC',
WARNING_20_CODE__c='ABC',
Comment_Block_01__c='ABC',
Comment_Block_02__c='ABC',
Comment_Block_03__c='ABC',
Comment_Block_04__c='ABC',
Comment_Block_05__c='ABC',
Comment_Block_06__c='ABC',
Comment_Block_07__c='ABC',
Comment_Block_08__c='ABC',
Comment_Block_09__c='ABC',
Comment_Block_10__c='ABC',
Comment_Block_11__c='ABC',
Comment_Block_12__c='ABC',
Comment_Block_13__c='ABC',
Comment_Block_14__c='ABC',
Comment_Block_15__c='ABC',
Comment_Block_16__c='ABC',
Comment_Block_17__c='ABC',
Comment_Block_18__c='ABC',
Comment_Block_19__c='ABC',
Comment_Block_20__c='ABC'
)
						};
						

		    Insert account_details_Obj;
		    	Account_Details__c obj = [select id from Account_Details__c limit 1];
		    	
		List<Case> case_Obj = new List<Case>{
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false,  Account_Number__c = obj.Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false,  Account_Number__c = obj.Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false,  Account_Number__c = obj.Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false,  Account_Number__c = obj.Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false,  Account_Number__c = obj.Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false)
                };                
				    Insert case_Obj;
		List<CaseComment> CaseComment_Obj = new List<CaseComment>{		 
						new CaseComment(CommentBody='test', IsPublished = true,ParentId=case_Obj[0].Id),
						new CaseComment(CommentBody='test1', IsPublished = true,ParentId=case_Obj[0].Id),
						new CaseComment(CommentBody='test2', IsPublished = true,ParentId=case_Obj[0].Id),
						new CaseComment(CommentBody='test3', IsPublished = true,ParentId=case_Obj[0].Id),
						
						new CaseComment(CommentBody='test', IsPublished = true,ParentId=case_Obj[1].Id),
						new CaseComment(CommentBody='test1', IsPublished = true,ParentId=case_Obj[1].Id),
						new CaseComment(CommentBody='test2', IsPublished = true,ParentId=case_Obj[1].Id),
						new CaseComment(CommentBody='test3', IsPublished = true,ParentId=case_Obj[1].Id)
							    
						};
			insert CaseComment_Obj;
		    test.stopTest();
  }
 static testMethod void GetAllDataTest() {
 	
 	Account_Details__c obj = [select id from Account_Details__c limit 1];
 	 test.startTest();
 	MemberAccountWrapperFor360ViewController.GetAllData(obj.Id);
 	
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'accList','','','test');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'accList','Name','ASC','08/08/2012');
     
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'cardList','','','test');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'cardList','Name','ASC','08/08/2012');
     
	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'related persons','','','test');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'related persons','TypeTranslate__c','ASC','08/08/2012');
     
	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'active cases','','','test');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'active cases','CaseNumber','ASC','08/08/2012');
     
	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'close cases','','','test');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'close cases','CaseNumber','ASC','08/08/2012');
     
	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'Case Comments','AccountNumberName','Desc','test');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'Case Comments','AccountName','ASC','08/08/2012');
     
	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'Active Tasks','AccountNumberName','Asc','test');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'Active Tasks','AccountName','Asc','08/08/2012');
     
	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'Warning/Comments','accNum','asc','Comments');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'Warning/Comments','tpeTrans','asc','08/08/2012');
	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'Warning/Comments','shareNo','asc','Comments');
 	MemberAccountWrapperFor360ViewController.GetPagingData(obj.Id,1,10,'Warning/Comments','recTpe','asc','08/08/2012');
   
         test.stopTest();  
 	
 }   
}