src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PersonNameController.cls
public class PersonNameController {
    
    private final Account_Details__c cRec;
    public string accId;
    public list<Person_Account__c> paList{get;set;}
    
    public PersonNameController(ApexPages.StandardController controller){
       // this.cRec = (Account_Details__c)Controller.getRecord();
        accId = System.currentPageReference().getParameters().get('Id');
        if(accId != null){
        Account_Details__c objNmae = [select id,Name from Account_Details__c where id=:accId];
        
        system.debug('Account Id is:::::'+accId);
        if(accId!=NULL || accId!=''){
            personAccounts(objNmae.Name);    
        }else{
            
        }
        }
    } 
        
        public void personAccounts(string accId){
       
         paList = new list<Person_Account__c>();
         list<Aggregateresult>   paList2 = new list<Aggregateresult>();
         paList2 = [SELECT 
                          
                          PersonId__c,
                          PersonID__r.Name,
                          TypeTranslate__c FROM Person_Account__c WHERE Account_Number__r.Name =:accId group by   PersonId__c, PersonID__r.Name,TypeTranslate__c];
              for(AggregateResult ar: paList2)
              {
              	Person_Account__c P =  NEW Person_Account__c();
              	
              	p.PersonId__c = (string)ar.get('PersonId__c');
              	P.PersonID__r = NEW Account();
              	P.PersonID__r.nAME =  (string)ar.get('Name');
              	P.TypeTranslate__c =   (string)ar.get('TypeTranslate__c');
              	paList.ADD(P);
              	
              }       
        
                          
         System.debug('Person AccountList is:::::'+paList);         
    }   
    }