src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference__c</fullName>
        <description>Brand Code BC01=Chevron Federal Credit Union, BC02=Spectrum Credit Union</description>
        <label>Reference</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Concatenation of primary, secondary and tertiary categories</description>
        <formula>TEXT( Primary_Category__c ) + &quot; / &quot; + 
TEXT( Secondary_Category__c ) + 
IF(ISPICKVAL(Tertiary_Category__c, &quot;&quot;), NULL, &quot; / &quot;) +
TEXT( Tertiary_Category__c )</formula>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/GetCaseAccounts.cls
public without sharing class GetCaseAccounts {
	
     @AuraEnabled    
    public static List<AccountListSelection> GetAllAccounts(Id caseid)
    {
    			case casedetails = new case();
    			List<AccountListSelection> als = new List<AccountListSelection>();
    			
				casedetails = [Select Id,AccountID,Parentid, Account_Number__c from Case where Id =: caseid limit 1];
				
				List<string> accountNumberSet = new List<string>();
				set<Id> accIdset = new set<Id>();
        		set<String> acctypeSet = new set<String>();
        
				list<Person_Account__c> paList = [SELECT Id,
                             Account_Number__c, Account_Number__r.RecType__c,TypeTranslate__c, Account_Number__r.Name FROM Person_Account__c WHERE PersonID__c =:casedetails.AccountId and (NOT TypeTranslate__c like '%Beneficiary%')];
				 for(Person_Account__c var: paList){
            			accountNumberSet.add(var.Account_Number__r.Name);
            			acctypeSet.add(var.Account_Number__r.RecType__c);
            			accIdSet.add(var.Account_Number__c);
				 }
				
				
				List<Account_Details__c> listAccountDetails = new List<Account_Details__c>();
				
				
				if(acctypeSet.contains('ACCT')){
            listAccountDetails = [SELECT Id,
                              Name,
                              RecType__c,
                              TypeTranslate__c,
                              ID1__c,
                              Balance__c,
                              Reference__c,
                              Brand__c FROM Account_Details__c Where Name IN:accountNumberSet and (RecType__c = 'ACCT' or (RecType__c = 'SHAR' and TypeTranslate__c ='1-PRIMARY SHARE')) ORDER BY Name asc, RecType__c asc];
        }else{
            listAccountDetails = [SELECT Id,
                              Name,
                              RecType__c,
                              TypeTranslate__c,
                              ID1__c,
                              Balance__c,
                              Reference__c,
                              Brand__c  FROM Account_Details__c Where Id IN:accIdSet and (RecType__c = 'ACCT' or (RecType__c = 'SHAR' and TypeTranslate__c ='1-PRIMARY SHARE')) ORDER BY Name asc, RecType__c asc];
        }
				
		 List<CaseAccountMemberDetail__c> camd = new List<CaseAccountMemberDetail__c>();
        camd = [select id,Case__c, MemberAccountid__c,  case__r.CaseNumber,case__r.OwnerId,
        				case__r.Owner.Name , case__r.Status, case__r.Category__c,
        				case__r.Primary_Category__c, case__r.Tertiary_Category__c,case__r.Secondary_Category__c,
        				case__r.Account.Name,
        				Account_Name__c, 
        				case__r.Subject, case__r.Origin,case__r.Parent.CaseNumber, case__r.ClosedDate
        				 from CaseAccountMemberDetail__c where Case__c =: caseid];
			
		        for(Account_Details__c ca : listAccountDetails )
		        {
		        	AccountListSelection objcls = new AccountListSelection();
		          	objcls.accountdetails = ca;
		          	boolean selected = false;
				        for(CaseAccountMemberDetail__c c : camd)
				        {
				         
				          if(ca.id  == c.MemberAccountid__c)
				          {		          	
				            selected = true;
				          }	          
				        }
				        if(selected)
				        {
				        	objcls.isSelected = true;
				        }
				        else
				        {
				        	objcls.isSelected = false;
				        }
				         als.add(objcls);
		        }
		        
		        system.debug('als.size()='+als.size());
		        if(als.size() != 0 && casedetails.Account_Number__c != null){
		         	for(AccountListSelection al: als){
		         		account_details__c tempAccc = (account_details__c)al.accountdetails;
		         		if(tempAccc.id == casedetails.Account_Number__c){
		         			if(al.isSelected == false){
		         				al.isSelected = true;
		         			}
		         		}
		         	}
		        }
				 
				return als;
    }
    
       @AuraEnabled 
    public static void AddAccountsandSave(Id caseid, List<String> accountids)
    {    	
    	system.debug('accountids==' +accountids);
    		case selectedcase = [select id, Account_Number__c from case where id =: caseid];
    		system.debug('selectedcase==' +selectedcase);
    		if(!accountids.contains((string)selectedcase.Account_Number__c)){
    			selectedcase.Account_Number__c = accountids[0];
    		}
    		update selectedcase;
    	    	system.debug('accountids=='+accountids);
    			list<account_details__c> ListAccountsSelected = [select id, Name from account_details__c where id in: accountids];
				
				List<CaseAccountMemberDetail__c> camd = [select id from CaseAccountMemberDetail__c
							where Case__c =: caseid];		
							
				system.debug('camd==='+camd);					
							
			if(camd.size() > 0 ){
				delete camd;
			}	            		
           
           List<CaseAccountMemberDetail__c> CaseAccountMemberDetailList = new List<CaseAccountMemberDetail__c>();
            if(ListAccountsSelected.size() > 0 )
            {
            	for(Account_Details__c ca : ListAccountsSelected)
            	{
            		
            		if(ca.Id != null)
            		{
	            		CaseAccountMemberDetail__c cd = new CaseAccountMemberDetail__c();
	            		cd.Case__c = caseid;
	            		cd.MemberAccountid__c = ca.Id ;
	            		cd.Account_Name__c = ca.Name;
	            		CaseAccountMemberDetailList.add(cd);
            		}
            		
            	}
            }
			
			 If(!CaseAccountMemberDetailList.IsEmpty())
            {
            	insert CaseAccountMemberDetailList;
            }
				
    	
    
    }
    
    public class AccountListSelection
	{
		@AuraEnabled
		public object accountdetails {get;set;}
		@AuraEnabled
		public boolean isSelected {get;set;}
	}
}