src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Member_Verification_OTP_Invalid_Attempt__c</fullName>
        <label>Member Verification OTP Invalid Attempt</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_01__c</fullName>
        <description>Comment Block 1</description>
        <label>Comment 01</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_02__c</fullName>
        <label>Comment 02</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_03__c</fullName>
        <label>Comment 03</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_04__c</fullName>
        <label>Comment 04</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_05__c</fullName>
        <label>Comment 05</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_06__c</fullName>
        <label>Comment 06</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_07__c</fullName>
        <label>Comment 07</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_08__c</fullName>
        <label>Comment 08</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_09__c</fullName>
        <label>Comment 09</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_10__c</fullName>
        <label>Comment 10</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_11__c</fullName>
        <label>Comment 11</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_12__c</fullName>
        <label>Comment 12</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_13__c</fullName>
        <label>Comment 13</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_14__c</fullName>
        <label>Comment 14</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_15__c</fullName>
        <label>Comment 15</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_16__c</fullName>
        <label>Comment 16</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_17__c</fullName>
        <label>Comment 17</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_18__c</fullName>
        <label>Comment 18</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_19__c</fullName>
        <label>Comment 19</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_20__c</fullName>
        <label>Comment 20</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Authenticated_Log__c.object
<CustomObject>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Decision</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OTP_Email__c</fullName>
        <description>OTP Authentication: Email address that the OTP authentication security code was sent to.</description>
        <label>OTP Email</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OTP_Phone__c</fullName>
        <description>OTP Authentication: Phone number that the security code was sent to</description>
        <label>OTP Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonId__c</fullName>
        <label>PersonId</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SalesforceID__c</fullName>
        <label>SalesforceID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Authentication Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Authenticated Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authentication Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OTPSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>OTPExpirationSeconds__c</fullName>
        <label>OTP Expiration (Seconds)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OTPSettings</label>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/MemberVerificationLightningControlleTest.cls
@isTest

private class MemberVerificationLightningControlleTest
{
    //Initial Test Data
    //Add Logic to Create data required
    @testSetup
    static void SetUp(){
        test.StartTest();
        List<Account_Details__c> account_details_Obj = new List<Account_Details__c>{
            new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c ='0100', Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE',
                                   Comment_Block_01__c='ABC',
                                   Comment_Block_02__c='ABC',
                                   Comment_Block_03__c='ABC',
                                   Comment_Block_04__c='TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS',
                                   Comment_Block_05__c='ABC',
                                   Comment_Block_06__c='ABC',
                                   Comment_Block_07__c='ABC',
                                   Comment_Block_08__c='ABC',
                                   Comment_Block_09__c='ABC',
                                   Comment_Block_10__c='ABC',
                                   Comment_Block_11__c='ABC',
                                   Comment_Block_12__c='ABC',
                                   Comment_Block_13__c='ABC',
                                   Comment_Block_14__c='ABC',
                                   Comment_Block_15__c='ABC',
                                   Comment_Block_16__c='TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS',
                                   Comment_Block_17__c='ABC',
                                   Comment_Block_18__c='ABC',
                                   Comment_Block_19__c='ABC',
                                   Comment_Block_20__c='ABC'),
                new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE',
                                       Comment_Block_01__c='TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS',
                                       Comment_Block_02__c='ABC',
                                       Comment_Block_03__c='ABC',
                                       Comment_Block_04__c='ABC',
                                       Comment_Block_05__c='ABC',
                                       Comment_Block_06__c='ABC',
                                       Comment_Block_07__c='ABC',
                                       Comment_Block_08__c='ABC',
                                       Comment_Block_09__c='TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS',
                                       Comment_Block_10__c='ABC',
                                       Comment_Block_11__c='ABC',
                                       Comment_Block_12__c='ABC',
                                       Comment_Block_13__c='ABC',
                                       Comment_Block_14__c='ABC',
                                       Comment_Block_15__c='ABC',
                                       Comment_Block_16__c='ABC',
                                       Comment_Block_17__c='ABC',
                                       Comment_Block_18__c='ABC',
                                       Comment_Block_19__c='ABC',
                                       Comment_Block_20__c='TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS'),
                new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE',
                                       Comment_Block_01__c='ABC',
                                       Comment_Block_02__c='ABC',
                                       Comment_Block_03__c='ABC',
                                       Comment_Block_04__c='ABC',
                                       Comment_Block_05__c='ABC',
                                       Comment_Block_06__c='ABC',
                                       Comment_Block_07__c='ABC',
                                       Comment_Block_08__c='ABC',
                                       Comment_Block_09__c='ABC',
                                       Comment_Block_10__c='TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS',
                                       Comment_Block_11__c='ABC',
                                       Comment_Block_12__c='ABC',
                                       Comment_Block_13__c='ABC',
                                       Comment_Block_14__c='ABC',
                                       Comment_Block_15__c='ABC',
                                       Comment_Block_16__c='ABC',
                                       Comment_Block_17__c='ABC',
                                       Comment_Block_18__c='ABC',
                                       Comment_Block_19__c='TELEPHONE/EMAIL CHANGED WITHIN 60 DAYS',
                                       Comment_Block_20__c='ABC')
                };
                    
                    
                    Insert account_details_Obj;
        
        List<Account> account_Obj = new List<Account>{new Account(LastName = 'BANDATest', FirstName = 'MARIATest', Type = 'null', Member_Verification_OTP_Invalid_Attempt__c = system.now(), Home_Phone__pc = '123456333390', Mobile_Phone__pc = '258963147852', Work_Phone__pc = '233333232323', PersonEmail = 'test@test.com', Alternate_Email__pc = 'abc@abc.com'),
            new Account(LastName = 'BANDATest1', FirstName = 'MARIATest1', Type = 'null', Member_Verification_OTP_Invalid_Attempt__c = system.now(), Home_Phone__pc = '1234563333903', Mobile_Phone__pc = '2589631478524', Work_Phone__pc = '2333332323235', PersonEmail = 'test@test.com1', Alternate_Email__pc = 'abc@abc.com1')};
                Insert account_Obj; 
        
        List<Person_Account__c> person_obj= new List<Person_Account__c>{new Person_Account__c(Account_Number__c = account_details_Obj[0].Id, PersonID__c = account_Obj[0].Id), new Person_Account__c(Account_Number__c = account_details_Obj[1].Id, PersonID__c = account_Obj[0].Id), new Person_Account__c(Account_Number__c = account_details_Obj[2].Id, PersonID__c = account_Obj[0].Id),
            new Person_Account__c(Account_Number__c = account_details_Obj[1].Id, PersonID__c = account_Obj[1].Id), new Person_Account__c(Account_Number__c = account_details_Obj[2].Id, PersonID__c = account_Obj[1].Id)};
                Insert person_obj;
        
        
        OTPSettings__c settings = new OTPSettings__c(Name = 'Member Verification', OTPExpirationSeconds__c = 180);
        Insert settings;
        RecordType rec1 = [Select id, Name, sobjecttype from RecordType where Name='Master Authentication Log'];
        Authenticated_Log__c log = new Authenticated_Log__c();
        log.IVR_GUID__c ='abc-123';
        log.RecordTypeId = rec1.id;
        insert log;
         Account obj_Account = [select Id from Account limit 1];
        string accid = obj_Account.Id;
       RecordType OTPRec = [select Id,Name,SobjectType from RecordType where Name ='OTP Authentication Log' and SobjectType='Authenticated_Log__c' limit 1];
         Authenticated_Log__c log1 = new Authenticated_Log__c();
        log1.IVR_GUID__c ='abc-123';
        log1.RecordTypeId = OTPRec.id;
        log1.CreatedDate = system.today();
        log1.SalesforceID__c = accid;
        insert log1;
        
        test.StopTest();
        
    }
   public static testmethod void GetRelatedAccountsPopulated()
   {
        test.startTest();
       	 List<Account> lstAccount = [select Id from Account limit 1];
       
        MemberOTPVerificationLightningController.GetRelatedAccountsPopulated(lstAccount[0].Id, lstAccount[0]);
        MemberOTPVerificationLightningController.GetAccIdsPopulated(lstAccount[0].Id, lstAccount[0]);
       //MemberOTPVerificationLightningController.SaveNoContactInfoLog(lstAccount[0]);
       
         test.StopTest();
   }
    // Test Method: ListOfEmailsAndPhoneNumbers
    public static testmethod void Test_ListOfEmailsAndPhoneNumbers()
    {
        test.startTest();
       	 List<Account> lstAccount = [select Id from Account limit 1];
       
        MemberVerificationLightningController.ListOfEmailsAndPhoneNumbers(lstAccount[0].Id, true);
         test.StopTest();
       
        
    }
    public static testmethod void Test_ListOfEmailsAndPhoneNumbers_1()
    {
        test.startTest();
       	 List<Account> lstAccount = [select Id from Account limit 1];
       RecordType rec1 = [Select id, Name, sobjecttype from RecordType where Name='Master Authentication Log'];
      List<Authenticated_Log__c> MasterAuthenticationLog = MemberOTPVerificationLightningController.GetDataForMasterAuthenticationLog('abc-123', rec1.id);
        MemberOTPVerificationLightningController.ListOfEmailsAndPhoneNumbers(lstAccount[0].Id, true,'abc-123','abc-123');
         test.StopTest();
        
        
    }
    public static testmethod void Test_ListOfEmailsAndPhoneNumbers2()
    {
       test.startTest();
        List<Account> lstAccount = [select Id from Account limit 2];	
        MemberVerificationLightningController.ListOfEmailsAndPhoneNumbers(lstAccount[1].Id, true);
          test.StopTest();
    
       
    }
     
    
    // Test Method: DeclineOTPAtFirstStep
    public static testmethod void Test_DeclineOTPAtFirstStep()
    {
        Account obj_Account = [select Id from Account limit 1];	
        MemberVerificationLightningController.DeclineOTPAtFirstStep(obj_Account.Id);
        MemberOTPVerificationLightningController.DeclineOTPAtFirstStep(obj_Account.Id,'abc-123', 'abc-123','0000056987');
    }
    public static testmethod void Test_DeclineOTPAtFirstStep1()
    {
        Account obj_Account = [select Id from Account limit 1];	
        
        MemberOTPVerificationLightningController.DeclineOTPAtFirstStep(obj_Account.Id,'abc-1234', 'abc-1234','0000056987');
    }
    // Test Method: GenerateRandomOTP
    public static testmethod void Test_GenerateRandomOTP()
    {
        test.startTest();
        Account obj_Account = [select Id from Account limit 1];
        
        string fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        string brandname = 'Spectrum';
        string resend = '';
        string accid = obj_Account.Id;
        MemberVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid);
       
        
        fieldname = 'Mobile_Phone__pc - ' + obj_Account.Id;
        brandname = 'Chevron';
        MemberVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid);
        
        fieldname = 'Work_Phone__pc - ' + obj_Account.Id;
        brandname = 'Spectrum';
        MemberVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid);
       
        
        fieldname = 'PersonEmail - ' + obj_Account.Id;
        brandname = 'Chevron';
        MemberVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid);
        
        
        fieldname = 'Alternate_Email__pc - ' + obj_Account.Id;
        brandname = 'Chevron';
        MemberVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid);
        
        test.stopTest();
    }
     public static testmethod void Test_GenerateRandomOTP1()
    {
        test.startTest();
        Account obj_Account = [select Id from Account limit 1];
        
        string fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        string brandname = 'Spectrum';
        string resend = '';
        string accid = obj_Account.Id;
       
        MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-123', 'abc-123','0000056987');
        
        fieldname = 'Mobile_Phone__pc - ' + obj_Account.Id;
        brandname = 'Chevron';
        
        MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-123', 'abc-123','0000056987');
        
        fieldname = 'Work_Phone__pc - ' + obj_Account.Id;
        brandname = 'Spectrum';
       
         MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-123', 'abc-123','0000056987');
        
        fieldname = 'PersonEmail - ' + obj_Account.Id;
        brandname = 'Chevron';
       
         MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-123', 'abc-123','0000056987');
        
        fieldname = 'Alternate_Email__pc - ' + obj_Account.Id;
        brandname = 'Chevron';
        
         MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-123', 'abc-123','0000056987');
        test.stopTest();
    }
     public static testmethod void Test_GenerateRandomOTP2()
    {
        test.startTest();
        Account obj_Account = [select Id from Account limit 1];
        
        string fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        string brandname = 'Spectrum';
        string resend = '';
        string accid = obj_Account.Id;
       
        MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-1234', 'abc-1234','0000056987');
        
        fieldname = 'Mobile_Phone__pc - ' + obj_Account.Id;
        brandname = 'Chevron';
        
        MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-1234', 'abc-1234','0000056987');
        
        fieldname = 'Work_Phone__pc - ' + obj_Account.Id;
        brandname = 'Spectrum';
       
         MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-1234', 'abc-1234','0000056987');
        
        fieldname = 'PersonEmail - ' + obj_Account.Id;
        brandname = 'Chevron';
       
         MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-1234', 'abc-1234','0000056987');
        
        fieldname = 'Alternate_Email__pc - ' + obj_Account.Id;
        brandname = 'Chevron';
        
         MemberOTPVerificationLightningController.GenerateRandomOTP(fieldname, brandname, resend, accid,'abc-1234', 'abc-1234','0000056987');
        test.stopTest();
    }
    
    // Test Method: verifyOTP
    public static testmethod void Test_verifyOTP()
    {	
        Account obj_Account = [select Id from Account limit 1];
        string accid = obj_Account.Id;
        string enteredotp = '23456';
        string fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        KeyValuePairModel model1 = new KeyValuePairModel();
        model1.Text = EncryptString('23456');
        model1.Value=  EncryptString(string.valueof(system.now()));
        string model = JSON.serialize(model1);
        
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
        MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-123', 'abc-123','0000056987');
        
        fieldname = 'Mobile_Phone__pc - ' + obj_Account.Id;
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
		MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-123', 'abc-123','0000056987');        
        fieldname = 'Work_Phone__pc - ' + obj_Account.Id;
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
        MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-123', 'abc-123','0000056987');
        fieldname = 'PersonEmail - ' + obj_Account.Id;
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
        MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-123', 'abc-123','0000056987');
        fieldname = 'Alternate_Email__pc - ' + obj_Account.Id;
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
        MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-123', 'abc-123','0000056987');
    }
    public static testmethod void Test_verifyOTP1()
    {	
        Account obj_Account = [select Id from Account limit 1];
        string accid = obj_Account.Id;
        string enteredotp = '23456';
        string fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        KeyValuePairModel model1 = new KeyValuePairModel();
        model1.Text = EncryptString('23456');
        model1.Value=  EncryptString(string.valueof(system.now()));
        string model = JSON.serialize(model1);
        
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
        MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-1234', 'abc-1234','0000056987');
        
        fieldname = 'Mobile_Phone__pc - ' + obj_Account.Id;
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
		MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-1234', 'abc-1234','0000056987');        
        fieldname = 'Work_Phone__pc - ' + obj_Account.Id;
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
        MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-1234', 'abc-1234','0000056987');
        fieldname = 'PersonEmail - ' + obj_Account.Id;
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
        MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-1234', 'abc-1234','0000056987');
        fieldname = 'Alternate_Email__pc - ' + obj_Account.Id;
        MemberVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model);
        MemberOTPVerificationLightningController.verifyOTP(accid, enteredotp, fieldname, model,'abc-1234', 'abc-1234','0000056987');
    }
    // Test Method: CancelOTP
    public static testmethod void Test_CancelOTP()
    {	
        Account obj_Account = [select Id from Account limit 1];
        string accid = obj_Account.Id;
        string fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        
        Test.startTest();
        MemberVerificationLightningController.CancelOTP(accid, fieldname);	
        Test.stopTest();
        
      
        
        fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        MemberVerificationLightningController.CancelOTP(accid, fieldname);	
       
        fieldname = 'Mobile_Phone__pc - ' + obj_Account.Id;	
        MemberVerificationLightningController.CancelOTP(accid, fieldname);	
      
        fieldname = 'Work_Phone__pc - ' + obj_Account.Id;	
        MemberVerificationLightningController.CancelOTP(accid, fieldname);
       
        fieldname = 'PersonEmail - ' + obj_Account.Id;	
        MemberVerificationLightningController.CancelOTP(accid, fieldname);
      
        fieldname = 'Alternate_Email__pc - ' + obj_Account.Id;	
        MemberVerificationLightningController.CancelOTP(accid, fieldname);	
       
    }
    public static testmethod void Test_CancelOTP1()
    {	
        Account obj_Account = [select Id from Account limit 1];
        string accid = obj_Account.Id;
        string fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        
        Test.startTest();
        	 MemberOTPVerificationLightningController.CancelOTP(accid,'abc-123', fieldname, 'abc-123','0000056987');	
        Test.stopTest();
        
       
        
        fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
       
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-123', fieldname, 'abc-123','0000056987');	
        fieldname = 'Mobile_Phone__pc - ' + obj_Account.Id;	
       
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-123', fieldname, 'abc-123','0000056987');	
        fieldname = 'Work_Phone__pc - ' + obj_Account.Id;	
      
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-123', fieldname, 'abc-123','0000056987');	
        fieldname = 'PersonEmail - ' + obj_Account.Id;	
       
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-123', fieldname, 'abc-123','0000056987');	
        fieldname = 'Alternate_Email__pc - ' + obj_Account.Id;	
       
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-123', fieldname, 'abc-123','0000056987');	
    }
    public static testmethod void Test_CancelOTP2()
    {	
        Account obj_Account = [select Id from Account limit 1];
        string accid = obj_Account.Id;
        string fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
        
        Test.startTest();
        	 MemberOTPVerificationLightningController.CancelOTP(accid,'abc-1234', fieldname, 'abc-1234','0000056987');	
        Test.stopTest();
        
       
        
        fieldname = 'Home_Phone__pc - ' + obj_Account.Id;
       
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-1234', fieldname, 'abc-1234','0000056987');	
        fieldname = 'Mobile_Phone__pc - ' + obj_Account.Id;	
       
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-1234', fieldname, 'abc-1234','0000056987');	
        fieldname = 'Work_Phone__pc - ' + obj_Account.Id;	
      
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-1234', fieldname, 'abc-1234','0000056987');	
        fieldname = 'PersonEmail - ' + obj_Account.Id;	
       
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-1234', fieldname, 'abc-1234','0000056987');	
        fieldname = 'Alternate_Email__pc - ' + obj_Account.Id;	
       
        MemberOTPVerificationLightningController.CancelOTP(accid,'abc-1234', fieldname, 'abc-1234','0000056987');	
    }
    public static testmethod void Test_GetOTPLogForReload()
    {	
         Account obj_Account = [select Id from Account limit 1];
        string accid = obj_Account.Id;
        RecordType OTPRec = [select Id,Name,SobjectType from RecordType where Name ='OTP Authentication Log' and SobjectType='Authenticated_Log__c' limit 1];
         Authenticated_Log__c log1 = new Authenticated_Log__c();
        log1.IVR_GUID__c ='abc-123';
        log1.RecordTypeId = OTPRec.id;
        log1.CreatedDate = system.today();
        log1.SalesforceID__c = accid;
        insert log1;
        
        
        List<Authenticated_Log__c> OTPLogData = [SELECT ID, Decision__c, OTP_Email__c,OTP_Phone__c,OTP_Status__c
							 FROM Authenticated_Log__c where SalesforceID__c =:accid and RecordTypeId=: OTPRec.Id and createddate =today];
        Test.startTest();
        MemberOTPVerificationLightningController.GetOTPLogForReload(accid,'abc-123', false, false);
       // MemberOTPVerificationLightningController.GetOTPLogForReload(accid,'abc-123', false, true);
       //  MemberOTPVerificationLightningController.GetOTPLogForReload(accid,'abc-123', true, false);
         Test.stopTest();
    }
    
    
    
    private static string EncryptString(string plaindata)
    {
        Blob cryptoKey = Blob.valueOf('39955410e8b11fa9');
        
        Blob data = Blob.valueOf(plaindata);
        Blob encryptedData = Crypto.encryptWithManagedIV('AES128', cryptoKey , data );
        String b64Data = EncodingUtil.base64Encode(encryptedData);
        
        return b64Data;
    }
}