src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Number__c</fullName>
        <label>Code Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MaritzCX__ALG_Survey_Id__c</fullName>
        <externalId>true</externalId>
        <label>ALG Survey Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaritzCX__Respondent_Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Number__c</fullName>
        <label>Member Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_2__c</fullName>
        <label>Street Address 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>ZipCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CaseRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Case Record Type based on Categories</description>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseRecordType</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <description>This field will be used to uniquely identify a Person.</description>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Survey_Case_Codes__c.object
<CustomObject>
    <description>Lookup table for branch/dept codes used to assign to queues</description>
    <fields>
        <fullName>Branch_Dept__c</fullName>
        <label>Branch/Dept</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue__c</fullName>
        <label>Queue</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Survey Case Codes</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Case Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/MaritzCXSurveyResponseTriggerHandler.cls
public class MaritzCXSurveyResponseTriggerHandler {
    
    public void beforeInsert(List<MaritzCX__Survey_Response__c> newSurveyRes){
        
        //-----STRY0012259 : Make Custom Meta Data and add fields --//
        
        MaritzCX_Response__mdt maritzResMdt = MaritzCX_Response__mdt.getInstance('MaritzCX_Response');
        for(MaritzCX__Survey_Response__c surveyRes : newSurveyRes) {
            surveyRes.MaritzCX__ALG_Survey_Id__c=maritzResMdt.MaritzCX_ALG_Survey_Id__c;
            surveyRes.MaritzCX__Key_Metric_5__c=maritzResMdt.MaritzCX_Key_Metric_5__c;
            surveyRes.MaritzCX__Key_Metric_6__c=maritzResMdt.MaritzCX_Key_Metric_6__c;
            surveyRes.MaritzCX__Key_Metric_7__c=maritzResMdt.MaritzCX_Key_Metric_7__c;
            //surveyRes.MaritzCX__respondent_email__c ='V555628874';
        }
    }
    
    public void afterInsert(List<MaritzCX__Survey_Response__c> newSurveyRes){
        
        System.debug('afterInsert');
        //-----STRY0012259 : Create Maritz Survey Response Case --//
        Set<String> personIds=new Set<String>();
        Set<String> accNums=new Set<String>();
        Set<String> surveyCaseCodes=new Set<String>();
        
        for(MaritzCX__Survey_Response__c surveyRes : newSurveyRes) {
            if(surveyRes.MaritzCX__respondent_email__c!=null){
                personIds.add(surveyRes.MaritzCX__respondent_email__c);
            }
            
            if(surveyRes.MaritzCX__Metric_1__c!=null){
                accNums.add(surveyRes.MaritzCX__Metric_1__c);
            }
            
            if(surveyRes.MaritzCX__Metric_2__c!=null){
                surveyCaseCodes.add(surveyRes.MaritzCX__Metric_2__c);
            }
        }
        
        List<CaseRecordType__c> recTypeList =RecordTypeSelector.getCaseRecordTypeByPrimaryCat('Surveys');
        
        System.debug('recTypeList:'+recTypeList);
        
        Set<String> surveyCodeQueues = new Set<String>();
        Map<String,Survey_Case_Codes__c> surveyCodesMap = new Map<String,Survey_Case_Codes__c>();
        for(Survey_Case_Codes__c caseCode : getSurveyCaseCodes(surveyCaseCodes))
        {
            surveyCodesMap.put(caseCode.Name,caseCode);
            surveyCodeQueues.add(caseCode.Queue__c);
        }
        
        Map<String,Account_Details__c> accDetailsMap = new Map<String,Account_Details__c>();
        for(Account_Details__c accDetail : AccountDetailsSelector.getACCTAccDetails(accNums))
        {
            accDetailsMap.put(accDetail.Name,accDetail);
        }
        
        System.debug('accDetailsMap:'+accDetailsMap);
        
        Map<String,Person_Account__c> personAccByAccNumberMap= new Map<String,Person_Account__c>();
        Map<String,Person_Account__c> personAccByPersonIdMap= new Map<String,Person_Account__c>();
        
        for(Person_Account__c pa : PersonAccountSelector.getACCTPersonAccByNumber(accNums))
        {
            personAccByAccNumberMap.put(pa.Account_Number__r.Name,pa);
            personAccByPersonIdMap.put(pa.PersonId__c,pa);
        }
        
        List<Contact> con = ContactSelector.getPersonContacts(personAccByPersonIdMap.keySet());        
        Map<Id,Id> conMap = new Map<Id,Id>();    
        if(con.size() > 0){
            for(Contact ct : con){
                conMap.put(ct.AccountId, ct.Id);
            }
        }
        
        System.debug('conMap:'+conMap);
        
        Map<String,Group> queueMap = new Map<String,Group>();
        for(Group g : [SELECT Id, Name FROM Group WHERE Name =:surveyCodeQueues]){
            queueMap.put(g.Name, g);
        }
        
        System.debug('queueMap:'+queueMap);
        
        Map<String,String> surveyResCaseMap=new Map<String,String>();
        for(MaritzCX__Survey_Response__c surveyRes : newSurveyRes) {
            Survey_Case_Codes__c surveyCode=surveyCodesMap.get(surveyRes.MaritzCX__Metric_2__c);
            if(surveyCode!=null) {
                System.debug('surveyCode:'+surveyCode);
                system.debug('case creation is started');
                Case case1=new Case();
                case1.Subject= surveyCode.Branch_Dept__c+' Alert'+' :'+surveyCode.Name+':'+surveyRes.MaritzCX__Metric_1__c;
                case1.Origin='MaritzCX';
                case1.Code_Number__c=surveyCode.Name;
                case1.Branch_Region__c='Member Services';
                Account_Details__c accDetail=accDetailsMap.get(surveyRes.MaritzCX__Metric_1__c);
                if(accDetail!=null) {
                    case1.Account_Number__c=accDetail.Id;
                    case1.Member_Number__c=accDetail.Name;
                }
                
                Person_Account__c pa=personAccByAccNumberMap.get(surveyRes.MaritzCX__Metric_1__c);
                if(pa!=null) 
                {
                    case1.AccountId = pa.PersonId__c;
                    case1.ContactId = conMap.get(pa.PersonId__c);
                    case1.Last_Name__c = pa.PersonId__r.LastName;
                    case1.Middle_Name__c = pa.PersonId__r.MiddleName;
                    case1.Street_Address_1__c = pa.PersonId__r.Residential_Street__pc;
                    case1.Street_Address_2__c = pa.PersonId__r.Residential_Extra_Address__pc;
                    case1.City__c = pa.PersonId__r.Residential_City__pc;
                    case1.State__c = pa.PersonId__r.Residential_State__pc;
                    case1.Country__c = pa.PersonId__r.Residential_Country__pc;
                    case1.Zip_Code__c = pa.PersonId__r.Residential_Zipocde__pc;
                }
                
                case1.Primary_Category__c = surveyCode.Primary_Category__c;
                case1.Secondary_Category__c = surveyCode.Secondary_Category__c;
                case1.Tertiary_Category__c = surveyCode.Tertiary_Category__c; 
                
                if(recTypeList.size() >0 ) {
                    case1.RecordTypeId = recTypeList[0].RecordTypeId__c;
                }
                
                Group queue=queueMap.get(surveyCode.Queue__c);
                if(queue!=null) {
                    case1.OwnerId = queue.Id;
                }
                
                insert case1;
                
                surveyResCaseMap.put(surveyRes.Id,case1.Id);
                
              
            } 
            
            List<MaritzCX__Survey_Response__c> resToUpdate=new List<MaritzCX__Survey_Response__c>();
            for(MaritzCX__Survey_Response__c res:getSurveyResponses(surveyResCaseMap.keySet())) {
                res.MaritzCX__Case_Id__c=surveyResCaseMap.get(res.Id);
                resToUpdate.add(res);
            }
            
            if(resToUpdate.size()>0) {
                update resToUpdate;
            }
        }
    }
    
    private static List<MaritzCX__Survey_Response__c> getSurveyResponses(Set<String> ids) 
    {
        return [SELECT Id,Name FROM MaritzCX__Survey_Response__c 
                WHERE Id=:ids];
    }
    
    private static List<Survey_Case_Codes__c> getSurveyCaseCodes(Set<String> codes) 
    {
        return [SELECT Name,Branch_Dept__c,Primary_Category__c, Secondary_Category__c, 
                Tertiary_Category__c, Queue__c 
                FROM Survey_Case_Codes__c 
                WHERE Name =:codes];
    }
}