src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used for member needs assessments eligibility</description>
        <label>NA Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEAV_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEAV_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEEM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEEM_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to show if the NA Housing section is considered complete (TRUE) or partial (FALSE)</description>
        <label>NA LEHS Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMD_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMD_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMQ_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMQ_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOL_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEOL_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA LEOM Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEPT_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEPT_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESB_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESB_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEWS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEWS_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, indicates that the member has opted to not participate in needs assessments for the period of 1 year.</description>
        <label>NA Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>Status</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SolarLoanTest.cls
@isTest
private class SolarLoanTest{
  @testSetup
  static void setupTestData(){
   
     List<Account_Details__c> account_details_Obj = new List<Account_Details__c>{
                new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', 
                Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE')};
    
     insert account_details_Obj;
    
     List<Account_Details__c> account_details_Obj1 = new List<Account_Details__c>{
                new Account_Details__c(Name = '0000123456', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', 
                Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE')};
    
     insert account_details_Obj1;
    
    
     Account account_Obj = new Account(LastName = 'BANDATest', FirstName = 'MARIATest', Type = 'null', PersonHasOptedOutOfEmail = false, 
              NA_Eligibility__c = false, NA_LEAV_Complete__c = true, NA_LECF_Complete__c = true, NA_LECP_Complete__c = true, NA_LEEM_Complete__c = true, NA_LEHS_Complete__c = true, 
              NA_LEMD_Complete__c = false, NA_LEMP_Complete__c = false, NA_LEMQ_Complete__c = true, NA_LEOL_Complete__c = true, NA_LEOM_Complete__c = true, NA_LEPT_Complete__c = true, 
              NA_LESB_Complete__c = false, NA_LESF_Complete__c = true, NA_LEWS_Complete__c = true, NA_Opt_Out__c = false);
     Insert account_Obj; 
    
     List<Person_Account__c> person_obj= new List<Person_Account__c>{
     						   new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = account_details_Obj[0].id, PersonID__c = account_Obj.Id)};
     insert person_obj;
      
     List<Person_Account__c> person_obj1= new List<Person_Account__c>{
     						   new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = account_details_Obj1[0].id, PersonID__c = account_Obj.Id)};
     insert person_obj1;
    
     List<Solar_Loans__c> SolarLoan_Obj = new List<Solar_Loans__c>{
        new Solar_Loans__c(Member_Number__c = '0000265418', Status__c = 'Completed', Brand__c = 'Spectrum', Primary_First_Name__c = 'Tania', Primary_Last_Name__c = 'Cabrera')};
     Insert SolarLoan_Obj;
     
     List<SolarLoan_Document__c> SolarLoanDocList = new List<SolarLoan_Document__c>{
         new SolarLoan_Document__c(Name = 'Test Document', Solar_Loans__c = SolarLoan_Obj[0].id)};      
     insert SolarLoanDocList;
           
     test.startTest();
     ContentVersion objAt = new ContentVersion(Title = 'Test Document',PathOnClient = 'TestDocument.pdf',VersionData = Blob.valueOf('Test Content'), IsMajorVersion = true);
     Insert objAt;
      
     
     List<ContentDocument> cdList = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
   	
     List<ContentDocumentLink> ListCDL = new List<ContentDocumentLink>{
     	new ContentDocumentLink (ContentDocumentId = cdList[0].id, LinkedEntityId = SolarLoan_Obj[0].Id)};
     insert ListCDL;
      
     test.stopTest();
  }
  static testMethod void test_GetCaseAttachments_UseCase1(){
    
    test.startTest();  
  	List<Solar_Loans__c> listSolarLoan  =  [SELECT Id from Solar_Loans__c limit 1];
  	List<ContentDocument> cdList = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument limit 1];
    List<SolarLoan_Document__c> SolarLoanDocList = [SELECT id from SolarLoan_Document__c limit 1];  
      
  	List<SolarLoanDocumentAPI.SolarLoanDocumentAPIResopnse> listApiResponse = SolarLoanDocumentAPI.getSolarLoanDocuemnts();
  	RestRequest req = new RestRequest();
  	req.requestURI = '/services/apexrest/SolarLoanDocumentAPI';
      
  	req.requestBody = blob.valueof(listApiResponse[1].AttachmentID /*+ ',' + listApiResponse[1].AttachmentID*/);
  	req.httpMethod = 'post';
  	RestContext.request = req;
 	SolarLoanDocumentAPI.updateSolarLoanDocuemnts();
  	
	SolarLoan_Document_Settings__c docSetting1 = new SolarLoan_Document_Settings__c();
  	docSetting1.Days__c = 120;
  	docSetting1.Name = 'Completed';
  	insert docSetting1;
  	
  	SolarLoan_Document_Settings__c docSetting2 = new SolarLoan_Document_Settings__c();
  	docSetting2.Days__c = 120;
  	docSetting2.Name = 'Declined';
  	insert docSetting2;
  	
  	SolarLoan_Document_Settings__c docSetting3 = new SolarLoan_Document_Settings__c();
  	docSetting3.Days__c = 120;
  	docSetting3.Name = 'Expired';
  	insert docSetting3;
  	
  	SolarLoanDocumentDeleteAttachments obj = new SolarLoanDocumentDeleteAttachments();
  	obj.execute(null);
  
  	test.stopTest();
 
  }
  
}