src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used for member needs assessments eligibility</description>
        <label>NA Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEAV_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEAV_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEEM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEEM_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to show if the NA Housing section is considered complete (TRUE) or partial (FALSE)</description>
        <label>NA LEHS Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMD_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMD_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMQ_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMQ_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOL_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEOL_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA LEOM Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEPT_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEPT_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESB_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESB_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEWS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEWS_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, indicates that the member has opted to not participate in needs assessments for the period of 1 year.</description>
        <label>NA Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_01__c</fullName>
        <description>Comment Block 1</description>
        <label>Comment 01</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_02__c</fullName>
        <label>Comment 02</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_03__c</fullName>
        <label>Comment 03</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_04__c</fullName>
        <label>Comment 04</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_05__c</fullName>
        <label>Comment 05</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_06__c</fullName>
        <label>Comment 06</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_07__c</fullName>
        <label>Comment 07</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_08__c</fullName>
        <label>Comment 08</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_09__c</fullName>
        <label>Comment 09</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_10__c</fullName>
        <label>Comment 10</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_11__c</fullName>
        <label>Comment 11</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_12__c</fullName>
        <label>Comment 12</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_13__c</fullName>
        <label>Comment 13</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_14__c</fullName>
        <label>Comment 14</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_15__c</fullName>
        <label>Comment 15</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_16__c</fullName>
        <label>Comment 16</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_17__c</fullName>
        <label>Comment 17</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_18__c</fullName>
        <label>Comment 18</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_19__c</fullName>
        <label>Comment 19</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comment_Block_20__c</fullName>
        <label>Comment 20</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_01_CODE__c</fullName>
        <label>Warning 01 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_02_CODE__c</fullName>
        <label>Warning 02 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_03_CODE__c</fullName>
        <label>Warning 03 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_04_CODE__c</fullName>
        <label>Warning 04 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_05_CODE__c</fullName>
        <label>Warning 05 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_06_CODE__c</fullName>
        <label>Warning 06 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_07_CODE__c</fullName>
        <label>Warning 07 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_08_CODE__c</fullName>
        <label>Warning 08 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_09_CODE__c</fullName>
        <label>Warning 09 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_10_CODE__c</fullName>
        <label>Warning 10 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_11_CODE__c</fullName>
        <label>Warning 11 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_12_CODE__c</fullName>
        <label>Warning 12 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_13_CODE__c</fullName>
        <label>Warning 13 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_14_CODE__c</fullName>
        <label>Warning 14 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_15_CODE__c</fullName>
        <label>Warning 15 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_16_CODE__c</fullName>
        <label>Warning 16 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_17_CODE__c</fullName>
        <label>Warning 17 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_18_CODE__c</fullName>
        <label>Warning 18 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_19_CODE__c</fullName>
        <label>Warning 19 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WARNING_20_CODE__c</fullName>
        <label>Warning 20 Code</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Card</fullName>
        <active>true</active>
        <description>This record type will be used to store all the CARD Information</description>
        <label>Card</label>
    </recordTypes>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/Member360ViewLightningControllerTest.cls
@isTest
private class Member360ViewLightningControllerTest {

    @testSetup
	static void setupTestData(){
		
    	ACH_To_Episys_API_Details__c api = new ACH_To_Episys_API_Details__c();
        api.URL__c = 'https://symxapi.chevronfcu.org/devclient';
        api.Name = 'ProductionURL';
        insert api;
        
		List<Account_Details__c> account_details_Obj = new List<Account_Details__c>{
						new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC',
                        WARNING_02_CODE__c='ABC',
                        WARNING_03_CODE__c='ABC',
                        WARNING_04_CODE__c='ABC',
                        WARNING_05_CODE__c='ABC',
                        WARNING_06_CODE__c='ABC',
                        WARNING_07_CODE__c='ABC',
                        WARNING_08_CODE__c='ABC',
                        WARNING_09_CODE__c='ABC',
                        WARNING_10_CODE__c='ABC',
                        WARNING_11_CODE__c='ABC',
                        WARNING_12_CODE__c='ABC',
                        WARNING_13_CODE__c='ABC',
                        WARNING_14_CODE__c='ABC',
                        WARNING_15_CODE__c='ABC',
                        WARNING_16_CODE__c='ABC',
                        WARNING_17_CODE__c='ABC',
                        WARNING_18_CODE__c='ABC',
                        WARNING_19_CODE__c='ABC',
                        WARNING_20_CODE__c='ABC',
                        Comment_Block_01__c='ABC',
                        Comment_Block_02__c='ABC',
                        Comment_Block_03__c='ABC',
                        Comment_Block_04__c='ABC',
                        Comment_Block_05__c='ABC',
                        Comment_Block_06__c='ABC',
                        Comment_Block_07__c='ABC',
                        Comment_Block_08__c='ABC',
                        Comment_Block_09__c='ABC',
                        Comment_Block_10__c='ABC',
                        Comment_Block_11__c='ABC',
                        Comment_Block_12__c='ABC',
                        Comment_Block_13__c='ABC',
                        Comment_Block_14__c='ABC',
                        Comment_Block_15__c='ABC',
                        Comment_Block_16__c='ABC',
                        Comment_Block_17__c='ABC',
                        Comment_Block_18__c='ABC',
                        Comment_Block_19__c='ABC',
                        Comment_Block_20__c='ABC'
                        ),
						
                        new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'SHAR', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC',
                        WARNING_02_CODE__c='ABC',
                        WARNING_03_CODE__c='ABC',
                        WARNING_04_CODE__c='ABC',
                        WARNING_05_CODE__c='ABC',
                        WARNING_06_CODE__c='ABC',
                        WARNING_07_CODE__c='ABC',
                        WARNING_08_CODE__c='ABC',
                        WARNING_09_CODE__c='ABC',
                        WARNING_10_CODE__c='ABC',
                        WARNING_11_CODE__c='ABC',
                        WARNING_12_CODE__c='ABC',
                        WARNING_13_CODE__c='ABC',
                        WARNING_14_CODE__c='ABC',
                        WARNING_15_CODE__c='ABC',
                        WARNING_16_CODE__c='ABC',
                        WARNING_17_CODE__c='ABC',
                        WARNING_18_CODE__c='ABC',
                        WARNING_19_CODE__c='ABC',
                        WARNING_20_CODE__c='ABC',
                        Comment_Block_01__c='ABC',
                        Comment_Block_02__c='ABC',
                        Comment_Block_03__c='ABC',
                        Comment_Block_04__c='ABC',
                        Comment_Block_05__c='ABC',
                        Comment_Block_06__c='ABC',
                        Comment_Block_07__c='ABC',
                        Comment_Block_08__c='ABC',
                        Comment_Block_09__c='ABC',
                        Comment_Block_10__c='ABC',
                        Comment_Block_11__c='ABC',
                        Comment_Block_12__c='ABC',
                        Comment_Block_13__c='ABC',
                        Comment_Block_14__c='ABC',
                        Comment_Block_15__c='ABC',
                        Comment_Block_16__c='ABC',
                        Comment_Block_17__c='ABC',
                        Comment_Block_18__c='ABC',
                        Comment_Block_19__c='ABC',
                        Comment_Block_20__c='ABC'
                        ),
                        
                        new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'CARD', TypeTranslate__c = '1-PRIMARY SHARE',WARNING_01_CODE__c='ABC',
                        WARNING_02_CODE__c='ABC',
                        WARNING_03_CODE__c='ABC',
                        WARNING_04_CODE__c='ABC',
                        WARNING_05_CODE__c='ABC',
                        WARNING_06_CODE__c='ABC',
                        WARNING_07_CODE__c='ABC',
                        WARNING_08_CODE__c='ABC',
                        WARNING_09_CODE__c='ABC',
                        WARNING_10_CODE__c='ABC',
                        WARNING_11_CODE__c='ABC',
                        WARNING_12_CODE__c='ABC',
                        WARNING_13_CODE__c='ABC',
                        WARNING_14_CODE__c='ABC',
                        WARNING_15_CODE__c='ABC',
                        WARNING_16_CODE__c='ABC',
                        WARNING_17_CODE__c='ABC',
                        WARNING_18_CODE__c='ABC',
                        WARNING_19_CODE__c='ABC',
                        WARNING_20_CODE__c='ABC',
                        Comment_Block_01__c='ABC',
                        Comment_Block_02__c='ABC',
                        Comment_Block_03__c='ABC',
                        Comment_Block_04__c='ABC',
                        Comment_Block_05__c='ABC',
                        Comment_Block_06__c='ABC',
                        Comment_Block_07__c='ABC',
                        Comment_Block_08__c='ABC',
                        Comment_Block_09__c='ABC',
                        Comment_Block_10__c='ABC',
                        Comment_Block_11__c='ABC',
                        Comment_Block_12__c='ABC',
                        Comment_Block_13__c='ABC',
                        Comment_Block_14__c='ABC',
                        Comment_Block_15__c='ABC',
                        Comment_Block_16__c='ABC',
                        Comment_Block_17__c='ABC',
                        Comment_Block_18__c='ABC',
                        Comment_Block_19__c='ABC',
                        Comment_Block_20__c='ABC'
                        )
            };
						

	Insert account_details_Obj;
		    
	Account account_Obj = new Account(LastName = 'BANDATest', FirstName = 'MARIATest', Type = 'null', PersonHasOptedOutOfEmail = false, NA_Eligibility__c = false, NA_LEAV_Complete__c = true, NA_LECF_Complete__c = true, NA_LECP_Complete__c = true, NA_LEEM_Complete__c = true, NA_LEHS_Complete__c = true, NA_LEMD_Complete__c = false, NA_LEMP_Complete__c = false, NA_LEMQ_Complete__c = true, NA_LEOL_Complete__c = true, NA_LEOM_Complete__c = true, NA_LEPT_Complete__c = true, NA_LESB_Complete__c = false, NA_LESF_Complete__c = true, NA_LEWS_Complete__c = true, NA_Opt_Out__c = false, smagicinteract__SMSOptOut__pc = false, et4ae5__HasOptedOutOfMobile__pc = false);
    Insert account_Obj; 
    
    Account_Details__c obj = [select id from Account_Details__c where id =: account_details_Obj[0].id];
    
    List<Person_Account__c> person_obj= new List<Person_Account__c>{
            new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = account_details_Obj[0].id, PersonID__c = account_Obj.Id), 
            new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = account_details_Obj[0].Id, PersonID__c = account_Obj.Id), 
            new Person_Account__c(Account_Number__c = account_details_Obj[2].Id, PersonID__c = account_Obj.Id)};
    Insert person_obj;
		     
	Account account_Obj1 = new Account(LastName = 'BANDATest1', FirstName = 'MARIATest1', Type = 'null', PersonHasOptedOutOfEmail = false, NA_Eligibility__c = false, NA_LEAV_Complete__c = true, NA_LECF_Complete__c = true, NA_LECP_Complete__c = true, NA_LEEM_Complete__c = true, NA_LEHS_Complete__c = true, NA_LEMD_Complete__c = false, NA_LEMP_Complete__c = false, NA_LEMQ_Complete__c = true, NA_LEOL_Complete__c = true, NA_LEOM_Complete__c = true, NA_LEPT_Complete__c = true, NA_LESB_Complete__c = false, NA_LESF_Complete__c = true, NA_LEWS_Complete__c = true, NA_Opt_Out__c = false, smagicinteract__SMSOptOut__pc = false, et4ae5__HasOptedOutOfMobile__pc = false);
    Insert account_Obj1;      
	List<Person_Account__c> person_obj1= 
		new List<Person_Account__c>{new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = account_details_Obj[1].Id, PersonID__c = account_Obj.Id), 
		new Person_Account__c(TypeTranslate__c='0000/Primary',Account_Number__c = account_details_Obj[2].Id, PersonID__c = account_Obj1.Id)};
	Insert person_obj1; 	
		    	
	List<Case> case_Obj = new List<Case>{
        new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj.Id, Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
        new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj.Id, Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj.Id, Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false,AccountId = account_Obj.Id,  Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false)		    
    };                     
           
        
         /*CaseAccountMemberDetail__c camd2 = new CaseAccountMemberDetail__c();
        camd1.Account_Name__c = account_details_Obj[1].Name;
        camd1.Case__c = case_Obj[0].id;
        camd1.MemberAccountid__c = account_details_Obj[1].Id;
        
        insert camd2;*/
             /* List<Case> case_Obj = new List<Case>();
              
              Case cs1 = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj.Id, Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
              Case cs2 = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj.Id, Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
              Case cs3 = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj.Id, Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
              Case cs4 = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false,AccountId = account_Obj.Id,  Account_Number__c = account_details_Obj[0].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
              
              case_Obj.Add(cs1);
              case_Obj.Add(cs2);
              case_Obj.Add(cs3);
              case_Obj.Add(cs4);*/
                         
			  Insert case_Obj;
              
              /*    CaseAccountMemberDetail__c camd1 = new CaseAccountMemberDetail__c();
                camd1.Account_Name__c = account_details_Obj[1].Name;
                camd1.Case__c = case_Obj[0].id;
                camd1.MemberAccountid__c = account_details_Obj[1].Id;
                
                insert camd1;*/
              
		List<CaseComment> CaseComment_Obj = new List<CaseComment>{		 
						new CaseComment(CommentBody='test', IsPublished = true,ParentId=case_Obj[0].Id),
						new CaseComment(CommentBody='test1', IsPublished = true,ParentId=case_Obj[0].Id),
						new CaseComment(CommentBody='test2', IsPublished = true,ParentId=case_Obj[0].Id),
						new CaseComment(CommentBody='test3', IsPublished = true,ParentId=case_Obj[0].Id),
						
						new CaseComment(CommentBody='test', IsPublished = true,ParentId=case_Obj[1].Id),
						new CaseComment(CommentBody='test1', IsPublished = true,ParentId=case_Obj[1].Id)
						
							    
						};
              
            /*  List<CaseComment> CaseComment_Obj = new List<CaseComment>();
              
              CaseComment cm1 = new CaseComment(CommentBody='test', IsPublished = true,ParentId=case_Obj[0].Id);
              CaseComment cm2 = new CaseComment(CommentBody='test1', IsPublished = true,ParentId=case_Obj[0].Id);
			  CaseComment cm3 =	new CaseComment(CommentBody='test2', IsPublished = true,ParentId=case_Obj[0].Id);
			  CaseComment cm4 =	new CaseComment(CommentBody='test3', IsPublished = true,ParentId=case_Obj[0].Id);
			  CaseComment cm5 =	new CaseComment(CommentBody='test', IsPublished = true,ParentId=case_Obj[1].Id);
			  CaseComment cm6 =	new CaseComment(CommentBody='test1', IsPublished = true,ParentId=case_Obj[1].Id);
              CaseComment_Obj.Add(cm1);
              CaseComment_Obj.Add(cm2);
              CaseComment_Obj.Add(cm3);
              CaseComment_Obj.Add(cm4);
              CaseComment_Obj.Add(cm5);
              CaseComment_Obj.Add(cm6);
              */
                            TEst.starttest();
			insert CaseComment_Obj;
	
			List<Task> task_Obj = new List<Task>{		 
						new Task(Subject='test', Description='Description',Status = 'Open',WhatId=case_Obj[0].Id),
						new Task(Subject='test1', Description='Description',Status = 'Open',WhatId=case_Obj[0].Id),
						new Task(Subject='test2', Description='Description',Status = 'Open',WhatId=case_Obj[0].Id),
						new Task(Subject='test3', Description='Description',Status = 'Open',WhatId=case_Obj[0].Id),
						
						new Task(Subject='test', Description='Description',Status = 'Open',WhatId=case_Obj[1].Id),
						new Task(Subject='test1', Description='Description',Status = 'Open',WhatId=case_Obj[1].Id)
						
							    
						};
             /* List<Task> task_Obj = new List<Task>();
              Task t1 = new Task(Subject='test', Description='Description',Status = 'Open',WhatId=case_Obj[0].Id);
              Task t2 = new Task(Subject='test1', Description='Description',Status = 'Open',WhatId=case_Obj[0].Id);
			  Task t3 = new Task(Subject='test2', Description='Description',Status = 'Open',WhatId=case_Obj[0].Id);
			  Task t4 =	new Task(Subject='test3', Description='Description',Status = 'Open',WhatId=case_Obj[0].Id);
			  Task t5 =	new Task(Subject='test', Description='Description',Status = 'Open',WhatId=case_Obj[1].Id);
			  Task t6 =	new Task(Subject='test1', Description='Description',Status = 'Open',WhatId=case_Obj[1].Id);
              task_Obj.Add(t1);
              task_Obj.Add(t2);
              task_Obj.Add(t3);
              task_Obj.Add(t4);
              task_Obj.Add(t5);
              task_Obj.Add(t6);*/
			  insert task_Obj;
			
		/*	
			
			List<Case> case_Obj1 = new List<Case>{
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj1.Id, Account_Number__c = account_details_Obj[1].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj1.Id, Account_Number__c = account_details_Obj[1].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj1.Id, Account_Number__c = account_details_Obj[1].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false),
		    new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj1.Id,  Account_Number__c = account_details_Obj[1].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false)
		    
                };   
            */  
        /*   List<Case> case_Obj1 = new List<Case>();
          Case cs5 = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj1.Id, Account_Number__c = account_details_Obj[1].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
		  Case cs6 = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj1.Id, Account_Number__c = account_details_Obj[1].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
		  Case cs7 = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj1.Id, Account_Number__c = account_details_Obj[1].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
		  Case cs8 = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj1.Id,  Account_Number__c = account_details_Obj[1].Id, Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold', MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);

         case_Obj1.Add(cs5);
         case_Obj1.Add(cs6);
         case_Obj1.Add(cs7);
         case_Obj1.Add(cs8);
           */   
	/*	 Insert case_Obj1;
		List<CaseComment> CaseComment_Obj1 = new List<CaseComment>{		 
						new CaseComment(CommentBody='test', IsPublished = true,ParentId=case_Obj1[0].Id),
						new CaseComment(CommentBody='test1', IsPublished = true,ParentId=case_Obj1[0].Id),
						new CaseComment(CommentBody='test2', IsPublished = true,ParentId=case_Obj1[0].Id),
						new CaseComment(CommentBody='test3', IsPublished = true,ParentId=case_Obj1[0].Id),
						
						new CaseComment(CommentBody='test', IsPublished = true,ParentId=case_Obj1[1].Id),
						new CaseComment(CommentBody='test1', IsPublished = true,ParentId=case_Obj1[1].Id)
						
							    
						};
			insert CaseComment_Obj1;
			
			List<Task> task_Obj1 = new List<Task>{		 
						new Task(Subject='test', Description='Description',Status = 'Open',WhatId=case_Obj1[0].Id),
						new Task(Subject='test1', Description='Description',Status = 'Open',WhatId=case_Obj1[0].Id),
						new Task(Subject='test2', Description='Description',Status = 'Open',WhatId=case_Obj1[0].Id),
						new Task(Subject='test3', Description='Description',Status = 'Open',WhatId=case_Obj1[0].Id),
						
						new Task(Subject='test', Description='Description',Status = 'Open',WhatId=case_Obj1[1].Id),
						new Task(Subject='test1', Description='Description',Status = 'Open',WhatId=case_Obj1[1].Id)
						
							    
						};
			insert task_Obj1;*/
			TEst.stoptest();	
		    
  }
 static testMethod void GetAllDataTest() {
 	TEst.starttest();
 	List<Account> obj = [select id from Account limit 2];
 	Memeber360ViewLightningController.GetAllData(obj[0].Id);
 	Memeber360ViewLightningController.GetAllData(obj[1].Id);
 TEst.stoptest();
 }   
 
 static testmethod void GetAccountPaggingDataTest()
 {
 	TEst.starttest();
 	List<Account> obj = [select Id from Account limit 2];
 	
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'accList','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'accList','Name','ASC','08/08/2012');
     
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'cardList','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'cardList','Name','ASC','08/08/2012');
 	
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'related persons','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'related persons','TypeTranslate__c','ASC','08/08/2012');
 	
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'accList','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'accList','Name','ASC','08/08/2012');
     
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'cardList','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'cardList','Name','ASC','08/08/2012');
 	
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'related persons','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'related persons','TypeTranslate__c','ASC','08/08/2012');
    	TEst.stoptest();
 }
 
  static testmethod void GetCasesPaggingDataTest()
  {
  	Test.starttest();
  	List<Account> obj = [select Id from Account limit 2];
  		
  	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'active cases','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'active cases','CaseNumber','ASC','08/08/2012');
     
	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'close cases','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'close cases','CaseNumber','ASC','08/08/2012');
     
	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'Case Comments','AccountNumberName','Desc','test');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'Case Comments','AccountName','ASC','08/08/2012');
 	
 	
 	//Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'active cases','','','test');
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'active cases','CaseNumber','ASC','08/08/2012');
     
	//Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'close cases','','','test');
 	//Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'close cases','CaseNumber','ASC','08/08/2012');
     
	//Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'Case Comments','AccountNumberName','Desc','test');
	TEst.stoptest();

  }
  
  static testmethod void GetTasksPaggingDataTest()
  {
  	TEst.starttest();
  	List<Account> obj = [select Id from Account limit 2];
  	
  	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'Active Tasks','AccountNumberName','Asc','test');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'Active Tasks','AccountName','Asc','08/08/2012');
 	
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'Active Tasks','AccountNumberName','Asc','test');
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'Active Tasks','AccountName','Asc','08/08/2012');
 	
 		Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'Case Comments','AccountName','ASC','08/08/2012');
 		TEst.stoptest();
  }
  
  static testmethod void GetWarningCommentsPaggingDataTest()
  {
  	  	TEst.starttest();
  	List<Account> obj = [select Id from Account limit 2];
  	
  	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'Warning/Comments','accNum','asc','Comments');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'Warning/Comments','tpeTrans','asc','08/08/2012');
	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'Warning/Comments','shareNo','asc','Comments');
 	Memeber360ViewLightningController.GetPagingData(obj[0].Id,1,10,'Warning/Comments','recTpe','asc','08/08/2012');
 	
 	
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'Warning/Comments','accNum','asc','Comments');
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'Warning/Comments','tpeTrans','asc','08/08/2012');
	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'Warning/Comments','shareNo','asc','Comments');
 	Memeber360ViewLightningController.GetPagingData(obj[1].Id,1,10,'Warning/Comments','recTpe','asc','08/08/2012');
 	TEst.stoptest();
  }
}