src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>Status</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Approve_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <label>Attachment Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_ID__c</fullName>
        <label>Case ID</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Approve_Attachment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Approved Attachments</label>
    <nameField>
        <displayFormat>A - {0000}</displayFormat>
        <label>ApproveAttachmentID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approved Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <description>This field will be used to uniquely identify a Person.</description>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ShareDocumentControllerTest.cls
@isTest
Public class ShareDocumentControllerTest{

     public static testMethod void checkAttachmentTest(){
       
         Create_SLA__c cl = new Create_SLA__c();
         cl.Status__c = 'Open';
         cl.Name = 'Open';
         cl.hours__c = 8;
         insert cl;
         
         Create_SLA__c cl1 = new Create_SLA__c();
         cl1.Status__c = 'In Process';
         cl1.Name = 'In Process';
         cl1.hours__c = 20;
         insert cl1;
         
         Create_SLA__c cl2 = new Create_SLA__c();
         cl2.Status__c = 'Resolution';
         cl2.Name = 'Resolution';
         cl2.hours__c = 200;
         insert cl2;
         
        string fid ='0000999999' ;    
        String uid = UserInfo.getUserId();
        User currentUser = [SELECT LocaleSidKey, LanguageLocaleKey, TimeZoneSidKey, EmailEncodingKey FROM User WHERE Id=:uid];
        RecordType recordtype =[SELECT Id,Name FROM RecordType WHERE Name='Person Account'];
        
        List<Account_Details__c> Account_Details = new List<Account_Details__c>();
        Account_Details__c ad = new Account_Details__c();
        ad.Name = fid;        
        Account_Details.add(ad);
        insert Account_Details;
        
        List<Account> accounts = new List<Account>();
        Account acc = new Account();
        acc.Owner = currentUser;
        acc.FirstName = 'tFName';
        acc.LastName='TLName';
        acc.recordtypeid = recordtype.Id;
        acc.PersonID__C ='V554870800';       
        acc.PersonEmail ='acctest@test.com';      
        accounts.add(acc);
        insert accounts;
        
        Case cas = new Case();
        //List<Contact> contact = [SELECT AccountId, FirstName, LastName FROM Contact WHERE Id =:contactid];
        cas.Subject = 'TestCaseSubject';
        cas.Description = 'TestCaseSubject';
        cas.Account_Number__c = ad.id;
        cas.AccountID = acc.id;
        cas.Primary_Category__c = 'Online Banking';
        cas.Status ='Open';
        insert cas;
        
        List<Attachment> AttachmentLst = new List<Attachment>();
        for(integer i=0 ; i <= 5 ; i++){
            Attachment attach=new Attachment();    
            attach.Name='Unit Test Attachment';
            Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
            attach.body=bodyBlob;
            attach.parentId=cas.id;
            AttachmentLst.add(attach);
        }        
        insert AttachmentLst;
        
        Approve_Attachment__c ap = new Approve_Attachment__c();
        ap.Attachment_Id__c = AttachmentLst[0].id;
        ap.Case_ID__c = cas.id;      
        insert ap;
        
        Approve_Attachment__c ap2 = new Approve_Attachment__c();
        //ap.name = 'Test123';
        ap2.Attachment_Id__c = AttachmentLst[1].id;
        ap2.Case_ID__c = cas.id;
        insert ap2;
        
        apexpages.currentpage().getparameters().put('caseId' , cas.id);
        
        ShareDocumentController controller = new ShareDocumentController();
        
         List<ShareDocumentController.attachmentWrapper> wrapList = controller.wrapperLst;
         for(ShareDocumentController.attachmentWrapper obj : wrapList){
             if(obj.attachmentobj.Id==AttachmentLst[2].Id){
                 obj.checkvalue = true;
             }
             if(obj.attachmentobj.Id==AttachmentLst[0].Id){
                 obj.checkvalue = false;
             }
         }
        controller.ShareAttchment();      
        controller.cancelall();
        
     
              
     }
     
 }