src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_User__c</fullName>
        <label>Created By User</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SecureEmailAddress__c</fullName>
        <description>Account level email address</description>
        <label>Secure Email Address</label>
        <type>Email</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Branch__c</fullName>
        <label>Assigned Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Episys_Name__c</fullName>
        <label>Episys Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Episys_User__c</fullName>
        <formula>CreatedBy.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Episys User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/main/default/classes/CreateNewLeadControllerTest.cls
@isTest
public class CreateNewLeadControllerTest
{
    static testmethod void testmethod1(){
         String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Account acc = new Account(
            RecordTypeID=RecTypeId,
            FirstName='Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678');
   
        insert acc;
        
        Episys_User__c euc = new Episys_User__c();
        String uid = UserInfo.getUserId();
        User usr = [Select id, name, alias from User where id=:uid]; 
        euc.Alias__c =  usr.alias;
        euc.Assigned_Branch__c = 105;
        euc.Default__c = true;
        euc.Episys_ID__c = 1111;
        euc.Episys_Name__c = 'Test';

        insert euc;
        
        Account_Details__c accDetails = new Account_Details__c();
        accDetails.Name = 'test';
        accDetails.SecureEmailAddress__c = 'sample@sample.com';
        accDetails.Created_By_User__c = 1;
        accDetails.RecType__c = 'ACCT';
        insert accDetails;
        
        PageReference pageRef = Page.CreateNewLead;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('accountid', acc.id);
        Lead l = new Lead();
        CreateNewLeadController controller = new CreateNewLeadController(new ApexPages.StandardController(l));     
        controller.save();       
        controller.leadObject.Product_Type__c = 'Cards';
        controller.save();
        controller.leadObject.Brand__c = 'CFCU';
        controller.SetEpsisUserID();
        controller.currentBranch(accDetails.id);
        controller.save();
    }
}