src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_Eligibility__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag used for member needs assessments eligibility</description>
        <label>NA Eligibility</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEAV_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEAV_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LECP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LECP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEEM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEEM_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEHS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicator to show if the NA Housing section is considered complete (TRUE) or partial (FALSE)</description>
        <label>NA LEHS Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMD_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMD_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMP_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMP_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEMQ_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEMQ_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOL_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEOL_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEOM_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA LEOM Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEPT_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEPT_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESB_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESB_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LESF_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LESF_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_LEWS_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NA_LEWS_Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NA_Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, indicates that the member has opted to not participate in needs assessments for the period of 1 year.</description>
        <label>NA Opt Out</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <description>This record type will be used to store all the Membership Accounts</description>
        <label>Membership</label>
    </recordTypes>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Additional_Documents__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this button when you want to send additional documents apart from the pre-configured ones through DocuSign.</description>
        <label>Additional Documents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Five_Day_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Five Day Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkRead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkSaved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkSaved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaritzCX__Response_Deleted_From_MaritzCX__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field keeps track of whether the response is available or deleted from the system.</description>
        <label>Response Deleted From MaritzCX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SLATemp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SLATemp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Staff_Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Use this field to manually escalate a case</description>
        <inlineHelpText>Use this field to manually escalate a case for further assistance</inlineHelpText>
        <label>Staff Escalated</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>et4ae5__HasOptedOutOfMobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>smagicinteract__SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Web_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key_Part_2__c</fullName>
        <description>concatenate part2</description>
        <label>Key Part 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Key_Part_3__c</fullName>
        <label>Key Part 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Key_Part_4__c</fullName>
        <label>Key Part 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebAddress__c</fullName>
        <label>WebAddress</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>key__c</fullName>
        <description>key to be encoded</description>
        <label>key</label>
        <type>TextArea</type>
    </fields>
    <label>WebService Settings</label>
</CustomObject>

src/classes/DocumentsLightningControllerTest.cls
@isTest
global class DocumentsLightningControllerTest{
  @testSetup
  static void setupTestData(){
   
    Account account_Obj = new Account(Name='Saumil',Website = 'null', CreatedDate = Date.ValueOf('2017-12-05 21:21:23'), LastModifiedDate = Date.ValueOf('2017-12-06 00:58:53'), PersonHasOptedOutOfEmail = false, NA_Eligibility__c = false, NA_LEAV_Complete__c = false, NA_LECF_Complete__c = false, NA_LECP_Complete__c = false, NA_LEEM_Complete__c = false, NA_LEHS_Complete__c = false, NA_LEMD_Complete__c = false, NA_LEMP_Complete__c = false, NA_LEMQ_Complete__c = false, NA_LEOL_Complete__c = false, NA_LEOM_Complete__c = false, NA_LEPT_Complete__c = false, NA_LESB_Complete__c = false, NA_LESF_Complete__c = false, NA_LEWS_Complete__c = false, NA_Opt_Out__c = false);
    Insert account_Obj; 
    Contact contact_Obj = new Contact(AccountId = account_Obj.id, LastName = 'DILTZ', MailingCity = ' ', MailingState = ' ', MailingPostalCode =  ' ',MailingCountryCode = 'US', HasOptedOutOfEmail = false, CreatedDate = Date.ValueOf('2017-12-05 21:21:23'),  LastModifiedDate = Date.ValueOf('2017-12-06 00:58:53'), smagicinteract__SMSOptOut__c = false, et4ae5__HasOptedOutOfMobile__c = false);
    Insert contact_Obj; 
    Case case_Obj = new Case(ContactId = contact_Obj.id, AccountId = account_Obj.id,Brand__c='Chevron', IsEscalated = false, CreatedDate = Date.ValueOf('2017-12-05 21:22:05'),  LastModifiedDate = Date.ValueOf('2017-12-05 21:22:06'), Additional_Documents__c = false, Staff_Escalated__c = false, Five_Day_Flag__c = false, IsMarkDeleted__c = false, IsMarkRead__c = false, IsMarkSaved__c = false, MaritzCX__Response_Deleted_From_MaritzCX__c = false, SLATemp__c = false);
    Insert case_Obj; 
      RecordType objRecordType = [SELECT Id,Name FROM RecordType WHERE Name='MemberShip'];
	
		Account_Details__c  act = new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE', RecordType = objRecordType);
		Insert act;
      Web_Settings__c websettings = new Web_Settings__c();
      websettings.Name = 'DEV';
      websettings.WebAddress__c = 'ps://sfrtsqa.chevronfcu.org/api/';
      websettings.Origin__c = 'ChevronTest';
      websettings.key__c = 'MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAJsB384Iu09cQdn8AeUBEJrG9tQ2HRWv6E81GmJ2qFLJNAJkIjMQ+f8RBK1QcVNsc1ouH+40DM+MjdlonBMFHFjZpNhIj7gpERlN7sgArSeP2VXwYjCCyZJ28vh8L7M6Le6GEVhbZ/dH88Ed2SmV5FXU0PcCsPo99kZwqm2oaVGfAgMBAAECgYEAmsS4TePyAj8/kQNKcPkrNx9';
      websettings.Key_Part_2__c = 'J/IE7cRf+gHepLH8FegNjZq/MZeihdMftP49+V6mFU5mSUCiwUdspFtaYX3VO4um0QCu61VmrtKmSKp2AVezPurHGh9NIIp4o/QAbc9G0JSUHDmb4veWyvAeK6qdogDL7tfs31NATGsQY7Uy4LCECQQDR8Bp/pqTDYKi42AUwVRHt/lM2TdBw9GY+IAo58OQY/G7O7gJkwUPeXZO/ycImphFlGUQvhaY7M20HOM62C/abAkEAvQRnBwpXT7bMu8';
      websettings.Key_Part_3__c = '8OnkmUikgl2ku8F/ebxhqDD0ZyL7s2qW3HnQSLM3Bk4XfKA2z/FSRoUyOA7GYyYP6goWA/TQJAId9JhzsN7nAUCO7ht3CiWfHk3ygi73afYHqu67ZQNy/TeROx0yvTlXcntZQJ/U5iFBvFgp1fusGLX9TslTbM7QJARXJrpDORdtFUEaD23wNr1w7BEZ6H4kpwam3tP1yDsbPYVpHmKHO17VVbS1fm2jFe21bAGePOh4zY77g+LmyddQJAF1v1u';
      websettings.Key_Part_4__c = 'Q+hCQCio58IvM6FtdIDeDk7wFxM0KNn1LkLdo24Kz8DRlR2OcxGYFj+YCcBh9Jby70VsntypGzzh0jxBg==';
      Insert websettings;
  
  }
  static testMethod void test_GetAllData_UseCase1(){
  	 test.startTest();
  	   Test.setMock(HttpCalloutMock.class, new CreateDocumentsResponseGenerator ());
    Account_Details__c account_Obj  =  [SELECT Id from Account_Details__c Limit 1];
    DocumentsLightningController.GetAllData(account_Obj.Id);
      test.stopTest();
  }
  
  
  
  
  
  
 
  
  
  
}