src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>NA_LEOM_Expired__c</fullName>
        <description>Set a flag used for NA LEOM section expiration</description>
        <formula>IF( (Last_NA_LEOM__c  = null  ||   
      Last_NA_LEOM__c &lt;  NOW() -(1440/1440) ) &amp;&amp; 
      NA_Eligibility__c  = TRUE ,
          true, 
          false
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NA LEOM Expired</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Do_you_Rent_or_Own__c</fullName>
        <description>This fields stores the value of &quot;Do you own or rent your home?&quot; on the &quot;Housing&quot; tab.</description>
        <inlineHelpText>Do you own or rent your home?</inlineHelpText>
        <label>LEHS Rent or Own</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Own</fullName>
                </value>
                <value>
                    <fullName>Own - Paid Off</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>Prefer Not To Answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LEHS_Current_Balance__c</fullName>
        <inlineHelpText>If own, what is your current balance?</inlineHelpText>
        <label>LEHS Current Balance</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>LEHS_Current_Lender__c</fullName>
        <description>This field stores the value of &quot;If own, who is your current lender?&quot; on the &quot;Housing&quot; tab.</description>
        <inlineHelpText>If own, who is your current mortgage lender?</inlineHelpText>
        <label>LEHS Current Lender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_LEHS_Current_Lender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_End_Date__c</fullName>
        <inlineHelpText>If own, what is the end date of the mortgage?</inlineHelpText>
        <label>LEHS End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEHS_End_Year__c</fullName>
        <label>LEHS_End_Year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LEHS_Have_Realtor__c</fullName>
        <inlineHelpText>If planning to purchase a house, do you have a realtor?</inlineHelpText>
        <label>LEHS Have Realtor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Last_Updated_On__c</fullName>
        <label>LE Housing Last Updated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEHS_Planning_to_Purchase__c</fullName>
        <inlineHelpText>Are you planning to purchase a house?</inlineHelpText>
        <label>LEHS Planning to Purchase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Purchase_When__c</fullName>
        <inlineHelpText>If planning to purchase a house, when?</inlineHelpText>
        <label>LEHS Purchase When</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Rate__c</fullName>
        <inlineHelpText>If own, what is your current rate?</inlineHelpText>
        <label>LEHS Current Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LEHS_Type_of_Mortgage__c</fullName>
        <label>LEHS_Type_of_Mortgage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30 Year Fixed</fullName>
                </value>
                <value>
                    <fullName>20 Year Fixed</fullName>
                </value>
                <value>
                    <fullName>15 Year Fixed</fullName>
                </value>
                <value>
                    <fullName>7/1 ARM 30 Year</fullName>
                </value>
                <value>
                    <fullName>7/1 ARM 15 Year</fullName>
                </value>
                <value>
                    <fullName>5/1 ARM 30 Year</fullName>
                </value>
                <value>
                    <fullName>5/1 ARM 15 Year</fullName>
                </value>
                <value>
                    <fullName>HELOC 10/15 (10 year draw/15 year repayment)</fullName>
                </value>
                <value>
                    <fullName>Fixed Rate 2nd 15 year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rec_LEHS_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Recommendation 1 - Life Events - Housing</description>
        <inlineHelpText>Recommendation 1 - Life Events - Housing</inlineHelpText>
        <label>Mortgages (Purchase or Refinance)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEHS_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Opportunity to recommend a realtor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_1__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Recommendation 1 - Life Events - Other Milestones</description>
        <inlineHelpText>Recommendation 1 - Life Events - Other Milestones</inlineHelpText>
        <label>HELOC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RV Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_3__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Health Savings Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_4__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Personal Line of Credit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_5__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Student Loans</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_6__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CDs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Rec_LEOM_7__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Money Market</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Na_HousingController.cls
public class Na_HousingController
{
    public Na_HousingController(){
    
    }
    public string script{get;set;}
    public Account AccountC{get;set;}
    public string NA_id {get;set;}
        
    public string accId2 { get; set; }
    public NeedAssessmentController parentController {get;set;}
    
    

    Needs_Assesment__c  lnah_New;
    
    public Needs_Assesment__c  getnah_New(){
      
           setObjects();
      
        return lnah_New;
    }
    public void setnah_new(Needs_Assesment__c  val){
        lnah_New = val;
    }
    
       
     public List<SelectOption> getdynamiclist() {
        List<SelectOption> options = new List<SelectOption>();
        
        options.add(new SelectOption('0','--None--'));
        for (Integer i = System.Today().year() + 1; i < System.Today().year() + 31; i++) 
        {
          options.add(new SelectOption(string.valueof(i),string.valueof(i)));
    }

        return options;
    }
    
    
    public void setObjects(){
        
        accId2 = parentController.account[0].Id;
        list<Needs_Assesment__c> naother = [select id,LEHS_Last_Updated_On__c  ,LEHS_Type_of_Mortgage__c  ,Do_you_Rent_or_Own__c,LEHS_Current_Lender__c,LEHS_End_Year__c,
                    LEHS_Rate__c,LEHS_Comment__c,LEHS_Current_Balance__c,LEHS_Planning_to_Purchase__c,LEHS_Purchase_When__c,
                    LEHS_Have_Realtor__c,Rec_LEOM_1__c,Rec_LEOM_2__c,Rec_LEOM_3__c,Rec_LEOM_4__c,Rec_LEOM_5__c,
                    Rec_LEOM_6__c,Rec_LEOM_7__c,Rec_LEHS_1__c,Rec_LEHS_2__c from Needs_Assesment__c where member__c =:accId2 ORDER by LastModifiedDate desc];
        if (naother.size() > 0)
        {
            NA_id = naother[0].Id;
            
            if(AccountC.NA_LEOM_Expired__c)
            {
                 lnah_New= new Needs_Assesment__c();
                 lnah_New.ID = NA_id;
                 

            }
            else
            {
                 lnah_New= naother [0];
            }
        }
        else
        {
  
            lnah_New= new Needs_Assesment__c();
            
        }
        if(lnah_New.LEHS_End_Year__c == null)
        {
        	lnah_New.LEHS_End_Year__c = 0;
        }
    }
    
    
      
    public void SubmitHousingForm()
    {

     
        //If(lnah_New.Do_you_Rent_or_Own__c != null || lnah_New.LEHS_Current_Lender__c != null || lnah_New.LEHS_Rate__c!= null || lnah_New.LEHS_Current_Balance__c != null || lnah_New.LEHS_End_Date__c != null || lnah_New.LEHS_Planning_to_Purchase__c != null || lnah_New.LEHS_Purchase_When__c != null || lnah_New.LEHS_Have_Realtor__c!= null || lnah_New.Rec_LEOM_1__c|| lnah_New.Rec_LEOM_2__c|| lnah_New.Rec_LEOM_3__c|| lnah_New.Rec_LEOM_4__c|| lnah_New.Rec_LEOM_5__c|| lnah_New.Rec_LEOM_6__c|| lnah_New.Rec_LEOM_7__c || lnah_New.Rec_LEHS_1__c || lnah_New.Rec_LEHS_2__c)
                
        {
            
                 Needs_Assesment__c  nah_tobeinserted = new Needs_Assesment__c  ();
                 nah_tobeinserted .Id = lnah_New.Id;
                    nah_tobeinserted .Do_you_Rent_or_Own__c = lnah_New.Do_you_Rent_or_Own__c ;
                    nah_tobeinserted .LEHS_Current_Lender__c = lnah_New.LEHS_Current_Lender__c ;
                    nah_tobeinserted .LEHS_Rate__c= lnah_New.LEHS_Rate__c;
                    nah_tobeinserted .LEHS_Current_Balance__c = lnah_New.LEHS_Current_Balance__c ;
                    //nah_tobeinserted .LEHS_End_Date__c = lnah_New.LEHS_End_Date__c ;
                    nah_tobeinserted .LEHS_Planning_to_Purchase__c = lnah_New.LEHS_Planning_to_Purchase__c ;
                    nah_tobeinserted .LEHS_Purchase_When__c = lnah_New.LEHS_Purchase_When__c ;
                    


                    nah_tobeinserted .LEHS_Have_Realtor__c= lnah_New.LEHS_Have_Realtor__c;
                    
                    nah_tobeinserted .Rec_LEOM_1__c= lnah_New.Rec_LEOM_1__c;
                    nah_tobeinserted .Rec_LEOM_2__c= lnah_New.Rec_LEOM_2__c;
                    nah_tobeinserted .Rec_LEOM_3__c= lnah_New.Rec_LEOM_3__c;
                    nah_tobeinserted .Rec_LEOM_4__c= lnah_New.Rec_LEOM_4__c;
                    nah_tobeinserted .Rec_LEOM_5__c= lnah_New.Rec_LEOM_5__c;
                    nah_tobeinserted .Rec_LEOM_6__c= lnah_New.Rec_LEOM_6__c;
                    nah_tobeinserted .Rec_LEOM_7__c= lnah_New.Rec_LEOM_7__c;
                    nah_tobeinserted.Rec_LEHS_1__c = lnah_New.Rec_LEHS_1__c;
                    nah_tobeinserted.Rec_LEHS_2__c = lnah_New.Rec_LEHS_2__c;
                    if(lnah_New.LEHS_End_Year__c == 0)
                    {
                    	
                    nah_tobeinserted .LEHS_End_Year__c = null;
                    }
                    else
                    {
                    	
                    nah_tobeinserted .LEHS_End_Year__c = lnah_New.LEHS_End_Year__c ;	
                    }
                    nah_tobeinserted .LEHS_Type_of_Mortgage__c = lnah_New.LEHS_Type_of_Mortgage__c ;
                    
                    
                    nah_tobeinserted.LEHS_Comment__c = lnah_New.LEHS_Comment__c;
                    if(nah_tobeinserted.Id == null)
                    {
                        nah_tobeinserted.Member__c = accId2 ;
                    }
                    
                    nah_tobeinserted.LEHS_Last_Updated_On__c     = system.today();
                    
                    
                    
                   script = '1';
                    upsert  nah_tobeinserted;
                        
                        
                        
            
    
       }
                RefreshParent();
    }
         public void resetscript()
     {
        script = '';
     }
   
    
    
    
      public void RefreshParent(){
             
        
         
           parentController.RefreshAccount();
         parentController.GetHousingTabClass();
     }
    

}