src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Current_Branch1__c</fullName>
        <formula>Text(Current_Branch__c)  &amp;  &apos; &apos;  &amp; CASE(Current_Branch__c, 
72, &apos;eBranch&apos;,
99, &apos;ATM&apos;,
96, &apos;Consumer Lending&apos;,
0, &apos;Head Quarter&apos;,
200, &apos;Spectrum&apos;,
270, &apos;Spectrum&apos;,
24, &apos;CA Bakersfield&apos;, 
05, &apos;Brea&apos;, 
20, &apos;Camino Media&apos;, 
02, &apos;Concord&apos;, 
09, &apos;El Segundo&apos;, 
206, &apos;Spectrum Pleasant Hill&apos;, 
21, &apos;Kern River/ China Grade&apos;, 
04, &apos;Richmond&apos;, 
03, &apos;San Ramon&apos;, 
201, &apos;Spectrum San Francisco&apos;, 
29, &apos;Denver&apos;, 
06, &apos;Covington&apos;, 
203, &apos;Spectrum Frederick Bechtel&apos;, 
23, &apos;Pascagoula&apos;, 
19, &apos;Aramco&apos;, 
17, &apos;Bellaire&apos;, 
14, &apos;1600 Smith&apos;, 
208, &apos;El Paso&apos;, 
08, &apos;El paso&apos;,
25, &apos;Post Oak&apos;, 
202, &apos;Spectrum Houston Galleria&apos;, 
27, &apos;Bountiful&apos;, 
28, &apos;Salt Lake City Refinery&apos;, 
205, &apos;Spectrum Reston&apos;,
01, &apos;San Francisco&apos;, 
22, &apos;West Loop&apos;, 
53, &apos;Electronic&apos;, 
55, &apos;Inactive, Low Balance, No Loans*&apos;, 
56, &apos;Inactive, Low Balance, Chargeoffs&apos;, 
57, &apos;Inactive, Low Balance, Bad Address&apos;, 
88, &apos;Operation Services&apos;, 
93, &apos;Member Services&apos;, 
98, &apos;Remote Access&apos;, 
204, &apos;Spectrum Westridge Mall&apos;, 
253, &apos;Spectrum Electronic&apos;, 
255, &apos;Spectrum Inactive, Low Balance, No Loans*&apos;, 
256, &apos;Spectrum Inactive, Low Balance, Chargeoffs&apos;, 
257, &apos;Spectrum Inactive, Low Balance, Bad Address&apos;, 
293, &apos;Spectrum Member Services Branch&apos;,  
&apos;&apos;)</formula>
        <label>Current Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UpdateAccountMemberBranch.cls
global class UpdateAccountMemberBranch implements Database.Batchable<sObject>{

   global Database.QueryLocator start(Database.BatchableContext BC){
      String ACCT = 'ACCT';
      String Query='Select Id, RecType__c, Current_Branch1__c from Account_Details__c where RecType__C =:ACCT';
      return Database.getQueryLocator(Query);
   }

   global void execute(Database.BatchableContext BC, List<Account_Details__c> scope){
     List<string> ids = new List<string>();
     Map<Id,string> accountMemberBranch = new Map<Id,string>();
     
     for(Account_Details__c acc : scope)
     {
        ids.add(acc.id);
        accountMemberBranch.put(acc.id,acc.Current_Branch1__c);
     }

    List<Person_Account__C> listPA = [select id,Account_Number__c,PersonId__c from Person_Account__C where Account_Number__c in : ids];
    
    Map<string,string> listMemberBranch = new Map<string,string>();
    List<string> listMembers = new List<string>();
     
    for(Person_Account__C item : listPA)
    {
        listMembers.add(item.PersonId__c);
        
    }
    
    List<Person_Account__C> listAccMember = [select id,PersonId__c,Account_Number__c from Person_Account__C where PersonId__c in: listMembers and Account_Number__r.RecType__c = 'ACCT'];
    
    Set<string> memberFound = new Set<string>(); 
    
    for(Person_Account__C item : listAccMember)
    {
        if(!memberFound.contains(item.Id))
        {
            string branch = accountMemberBranch.get(item.Account_Number__c);
            memberFound.add(item.PersonId__c);
            listMemberBranch.put(item.PersonId__c, branch);
        }
        
    }
    
    List<Account> listMainAccount = [select id,Member_Branch__c from Account where Id in: memberFound];
    List<Valid_Branch__c> branchList = [select id,Name from Valid_Branch__c];
    Set<String> existingBranch = new Set<String>();
    
    for(Account acc: listMainAccount)
    {
        string memberBranch = listMemberBranch.get(acc.id);
        existingBranch.add(listMemberBranch.get(acc.id));
        for(Integer i=0;i<branchList.size();i++)
        {
            String branchName = branchList[i].Name;
            
            if (existingBranch.contains(branchName))
            {
                acc.Member_Branch__c = memberBranch;
            }
        }
    }
    
    update listMainAccount;
    
    }

   global void finish(Database.BatchableContext BC){
   }
}