src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Employee_Restricted_Access__c</fullName>
        <label>Employee Restricted Access</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/GetCaseAccountsTest.cls
@isTest
public class GetCaseAccountsTest {
	
	static testMethod void testMethod1() {
		
		List<String> accountids = new List<String>();
	 Account acobj = new Account();
        acobj.FirstName = 'U';
        acobj.LastName = 'D';
        acobj.BIRTH_DATE__pc = date.parse('04/04/1963');
        acobj.Employee_Restricted_Access__c = 1234;
        acobj.Home_Phone__pc = '9169954478';
        insert acobj;
        
        Account_Details__c accDetails = new Account_Details__c();
        accDetails.Name = '0000123';
        accDetails.RecType__c = 'ACCT';
        insert accDetails;
        accountids.add(accDetails.Id);
        
        Account_Details__c accDetails1 = new Account_Details__c();
        accDetails1.Name = '0000456';
        accDetails1.RecType__c = 'ACCT';
        insert accDetails1;
         accountids.add(accDetails1.Id);
        
        Case case1 = new Case();
        case1.Subject = 'Test';
        case1.Description = 'test';
        case1.Accountid = acobj.Id;
        case1.Brand__c ='Spectrum';
        case1.Account_Number__c = accDetails.id;
        insert case1;
        
       CaseAccountMemberDetail__c camd = new CaseAccountMemberDetail__c();
       camd.case__c = case1.id;
       camd.Account_Name__c = accDetails.Name;
       camd.MemberAccountid__c = accDetails.Id;
       insert camd;
       
        CaseAccountMemberDetail__c camd1 = new CaseAccountMemberDetail__c();
       camd1.case__c = case1.id;
       camd1.Account_Name__c = accDetails1.Name;
       camd1.MemberAccountid__c = accDetails1.Id;
       insert camd1;
       
        Person_Account__c pa = new Person_Account__c();
        pa.PersonID__c = acobj.Id;
        pa.Account_Number__c = accDetails.Id;        
        insert pa;
        
        Person_Account__c pa1 = new Person_Account__c();
        pa1.PersonID__c = acobj.Id;
        pa1.Account_Number__c = accDetails1.Id;        
        insert pa1;
        
         Test.StartTest();

         GetCaseAccounts.GetAllAccounts(case1.id);	     
         GetCaseAccounts.AddAccountsandSave(case1.id, accountids);   
	      
        Test.StopTest();
	    }
    
}