src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email_raw__c</fullName>
        <label>Email</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_User__c</fullName>
        <label>Created By User</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SecureEmailAddress__c</fullName>
        <description>Account level email address</description>
        <label>Secure Email Address</label>
        <type>Email</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Card</fullName>
        <active>true</active>
        <description>This record type will be used to store all the CARD Information</description>
        <label>Card</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_did_you_hear_about_us__c</fullName>
        <label>How did you hear about us?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yahoo Ad</fullName>
                </value>
                <value>
                    <fullName>Google Ad</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>No Product Available</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>No Prospect/Mbr Deciding</fullName>
                </value>
                <value>
                    <fullName>App Online</fullName>
                </value>
                <value>
                    <fullName>App Completed</fullName>
                </value>
                <value>
                    <fullName>Follow Up Required</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Poor Referral</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Appointment Set Branch</fullName>
                </value>
                <value>
                    <fullName>Appointment Set Phone</fullName>
                </value>
                <value>
                    <fullName>Additional Follow-up Required</fullName>
                </value>
                <value>
                    <fullName>Contact Attempted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>false</active>
        <businessProcess>Default</businessProcess>
        <description>record type for all the Branch Users</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/DataFactoryTestClass.cls
@isTest
public class DataFactoryTestClass {

    public static Account createAccount(Boolean doInsert, string firstName, string lastName, string email, string personalEmail) {
		Account acc = new Account(FirstName = firstName, LastName =lastName, Email_raw__c=email,PersonEmail = personalEmail  );
		if(doInsert) {
			insert acc;
		}
		return acc;
	}
	public static Account createAccountWithRecordType(Boolean doInsert, string name, string email, id recordTypeId) {
		Account acc = new Account(Name = name, Email_raw__c=email, RecordTypeID =recordTypeId);
		if(doInsert) {
			insert acc;
		}
		return acc;
	}
    public static Lead createLead(string fName, string lName, string status) {
		Group   listQueue = [select id,Name,Email from Group where Type = 'Queue' and (Email like '%lead.com') limit 1];
        Lead ld = new Lead (LastName = lName ,Product_Type__c = 'Card', Sub_Status__c = 'No Response',Brand__c = 'CFCU',FirstName = fName ,MiddleName = 'New', Description = 'New',Product_Amount__c =3.00,
        Salutation = 'MR.',Suffix = 'MR',Status = status ,Phone= '1234567890',Email='test@test.com',MobilePhone='1234567892',How_did_you_hear_about_us__c='Website',
        LeadSource='BDO-Realtor Referral' , Ownership__c='Queue', OwnerId = listQueue.Id, Street_Address_1__c='Address 1',State__c= 'NY',Zip_Code__c= '12345',City__c='NYC',Country__c ='USA');
        insert ld;
		return ld;
	}
    public static Opportunity createOpportunitywithMemberAccount(string Stagename) {
		Account_Details__c accDetail = new Account_Details__c();
        accDetail.Name = 'test';
        accDetail.SecureEmailAddress__c = 'sample@sample.com';
        accDetail.Created_By_User__c = 1;
        insert accDetail;
        
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Account acc = new Account(
        RecordTypeID=RecTypeId,
        FirstName='Test FName',
        LastName='Test LName',
        PersonMailingStreet='test@yahoo.com',
        PersonMailingPostalCode='12345',
        PersonMailingCity='SFO',
        PersonEmail='test@yahoo.com',
        PersonHomePhone='1234567',
        PersonMobilePhone='12345678');
        
        insert acc;
        
        Person_Account__c pa = new Person_Account__c();
        pa.PersonID__c = acc.Id;
        pa.Name_Type__c = 0;
        pa.Account_Number__c = accDetail.Id;
        insert pa;
        Opportunity opp;
        if(Stagename != 'Outreach'){
             opp = new Opportunity(Name = 'Name', member_account__c = accDetail.id,  StageName = Stagename ,  Product_Amount__c =2.00, Product_Type__c = 'Misc',CloseDate = system.today(), Opportunity_Source__c = 'Branch Call', AccountId =acc.id);
        }
        else{
            	 opp = new Opportunity(Name = 'Name', member_account__c = accDetail.id,  StageName = Stagename , Sub_Status__c ='1st attempt', Product_Amount__c =2.00, Product_Type__c = 'Misc',CloseDate = system.today(), Opportunity_Source__c = 'Branch Call', AccountId =acc.id);
            }
			insert opp;
		
		return opp;
	}
   
    public static Opportunity createOpportunitywithSLA(string Stagename) {
		Account_Details__c accDetail = new Account_Details__c();
        accDetail.Name = 'test';
        accDetail.SecureEmailAddress__c = 'sample@sample.com';
        accDetail.Created_By_User__c = 1;
        insert accDetail;
        
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Account acc = new Account(
        RecordTypeID=RecTypeId,
        FirstName='Test FName',
        LastName='Test LName',
        PersonMailingStreet='test@yahoo.com',
        PersonMailingPostalCode='12345',
        PersonMailingCity='SFO',
        PersonEmail='test@yahoo.com',
        PersonHomePhone='1234567',
        PersonMobilePhone='12345678');
        
        insert acc;
        
        Person_Account__c pa = new Person_Account__c();
        pa.PersonID__c = acc.Id;
        pa.Name_Type__c = 0;
        pa.Account_Number__c = accDetail.Id;
        insert pa;
        Opportunity opp;
        if(Stagename != 'Outreach'){
             opp = new Opportunity(Name = 'Name', Hour_Spent_New_Status__c = 1.00 , Hour_Spent_Outreach_Status__c = 1.00, Hour_Spent_Considering_Status__c = 1.00, Hour_Spent_Analyzing_Needs_Status__c = 1.00, Hour_Spent_Fulfillment_Status__c = 1.00, member_account__c = accDetail.id,  StageName = Stagename ,  Product_Amount__c =2.00, Product_Type__c = 'Misc',CloseDate = system.today(), Opportunity_Source__c = 'Branch Call', AccountId =acc.id);
        }
        else{
            	 opp = new Opportunity(Name = 'Name',Hour_Spent_New_Status__c = 1.00 , Hour_Spent_Outreach_Status__c = 1.00, Hour_Spent_Considering_Status__c = 1.00, Hour_Spent_Analyzing_Needs_Status__c = 1.00, Hour_Spent_Fulfillment_Status__c = 1.00, member_account__c = accDetail.id,  StageName = Stagename , Sub_Status__c ='1st attempt', Product_Amount__c =2.00, Product_Type__c = 'Misc',CloseDate = system.today(), Opportunity_Source__c = 'Branch Call', AccountId =acc.id);
            }
			insert opp;
		
		return opp;
	}
}