src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Correspondence_Date__c</fullName>
        <label>Correspondence Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Created_At_Branch1__c</fullName>
        <formula>Text(Created_At_Branch__c)  &amp;  &apos; &apos;  &amp;  
CASE(Created_At_Branch__c, 
72, &apos;eBranch&apos;,
0, &apos;Head Quarter&apos;,
200, &apos;Spectrum&apos;,
270, &apos;Spectrum&apos;,
299, &apos;Spectrum&apos;,
99, &apos;ATM&apos;,
96, &apos;Consumer Lending&apos;,
24, &apos;CA Bakersfield&apos;,
05, &apos;Brea&apos;,
20, &apos;Camino Media&apos;,
02, &apos;Concord&apos;,
09, &apos;El Segundo&apos;,
206, &apos;Spectrum Pleasant Hill&apos;,
21, &apos;Kern River/ China Grade&apos;,
04, &apos;Richmond&apos;,
03, &apos;San Ramon&apos;,
201, &apos;Spectrum San Francisco&apos;,
29, &apos;Denver&apos;,
06, &apos;Covington&apos;,
203, &apos;Spectrum Frederick Bechtel&apos;,
23, &apos;Pascagoula&apos;,
19, &apos;Aramco&apos;,
17, &apos;Bellaire&apos;,
14, &apos;1600 Smith&apos;,
208, &apos;Spectrum El Paso&apos;,
25, &apos;Post Oak&apos;,
202, &apos;Spectrum Houston Galleria&apos;,
207, &apos;Bountiful&apos;,
28, &apos;Salt Lake City Refinery&apos;,
205, &apos;Spectrum Reston&apos;,
01, &apos;San Francisco&apos;,
22, &apos;West Loop&apos;,
53, &apos;Electronic&apos;,
55, &apos;Inactive, Low Balance, No Loans*&apos;,
56, &apos;Inactive, Low Balance, Chargeoffs&apos;,
57, &apos;Inactive, Low Balance, Bad Address&apos;,
88, &apos;Operation Services&apos;,
93, &apos;Member Services&apos;,
98, &apos;Remote Access&apos;,
204, &apos;Spectrum Westridge Mall&apos;,
253, &apos;Spectrum Electronic&apos;,
255, &apos;Spectrum Inactive, Low Balance, No Loans*&apos;,
256, &apos;Spectrum Inactive, Low Balance, Chargeoffs&apos;,
257, &apos;Spectrum Inactive, Low Balance, Bad Address&apos;,
293, &apos;Spectrum Member Services Branch&apos;,                     
&apos;&apos;)</formula>
        <label>Created At Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_At_Branch__c</fullName>
        <label>Created At Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_Branch1__c</fullName>
        <formula>Text(Current_Branch__c)  &amp;  &apos; &apos;  &amp; CASE(Current_Branch__c, 
72, &apos;eBranch&apos;,
99, &apos;ATM&apos;,
96, &apos;Consumer Lending&apos;,
0, &apos;Head Quarter&apos;,
200, &apos;Spectrum&apos;,
270, &apos;Spectrum&apos;,
24, &apos;CA Bakersfield&apos;, 
05, &apos;Brea&apos;, 
20, &apos;Camino Media&apos;, 
02, &apos;Concord&apos;, 
09, &apos;El Segundo&apos;, 
206, &apos;Spectrum Pleasant Hill&apos;, 
21, &apos;Kern River/ China Grade&apos;, 
04, &apos;Richmond&apos;, 
03, &apos;San Ramon&apos;, 
201, &apos;Spectrum San Francisco&apos;, 
29, &apos;Denver&apos;, 
06, &apos;Covington&apos;, 
203, &apos;Spectrum Frederick Bechtel&apos;, 
23, &apos;Pascagoula&apos;, 
19, &apos;Aramco&apos;, 
17, &apos;Bellaire&apos;, 
14, &apos;1600 Smith&apos;, 
208, &apos;El Paso&apos;, 
08, &apos;El paso&apos;,
25, &apos;Post Oak&apos;, 
202, &apos;Spectrum Houston Galleria&apos;, 
27, &apos;Bountiful&apos;, 
28, &apos;Salt Lake City Refinery&apos;, 
205, &apos;Spectrum Reston&apos;,
01, &apos;San Francisco&apos;, 
22, &apos;West Loop&apos;, 
53, &apos;Electronic&apos;, 
55, &apos;Inactive, Low Balance, No Loans*&apos;, 
56, &apos;Inactive, Low Balance, Chargeoffs&apos;, 
57, &apos;Inactive, Low Balance, Bad Address&apos;, 
88, &apos;Operation Services&apos;, 
93, &apos;Member Services&apos;, 
98, &apos;Remote Access&apos;, 
204, &apos;Spectrum Westridge Mall&apos;, 
253, &apos;Spectrum Electronic&apos;, 
255, &apos;Spectrum Inactive, Low Balance, No Loans*&apos;, 
256, &apos;Spectrum Inactive, Low Balance, Chargeoffs&apos;, 
257, &apos;Spectrum Inactive, Low Balance, Bad Address&apos;, 
293, &apos;Spectrum Member Services Branch&apos;,  
&apos;&apos;)</formula>
        <label>Current Branch</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Branch__c</fullName>
        <label>Current Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a self-relationship field used to link SubAccounts(recType) to the respective MembershipAccounts(recType)</description>
        <label>Parent Account</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Membership</fullName>
        <active>true</active>
        <description>This record type will be used to store all the Membership Accounts</description>
        <label>Membership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Branch__c</fullName>
        <label>Assigned Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Branch_Name__c</fullName>
        <formula>Text(Assigned_Branch__c) &amp; &apos; &apos; &amp; 
CASE(Assigned_Branch__c, 
96, &apos;Direct Lending&apos;, 
200, &apos;Spectrum&apos;, 
270, &apos;Spectrum&apos;, 
299, &apos;Spectrum&apos;, 
99, &apos;ATM&apos;, 
24, &apos;Bakersfield&apos;, 
05, &apos;Brea&apos;, 
20, &apos;Camino Media&apos;, 
02, &apos;Concord&apos;, 
09, &apos;El Segundo&apos;, 
206, &apos;Pleasant Hill&apos;, 
21, &apos;Kern River/ China Grade&apos;, 
04, &apos;Richmond&apos;, 
03, &apos;San Ramon&apos;, 
201, &apos;Spectrum San Francisco&apos;, 
29, &apos;Denver&apos;, 
06, &apos;Covington&apos;, 
203, &apos;Spectrum Frederick Bechtel&apos;, 
23, &apos;Pascagoula&apos;, 
19, &apos;Aramco&apos;, 
17, &apos;Bellaire&apos;, 
14, &apos;1600 Smith&apos;, 
208, &apos;El Paso&apos;, 
25, &apos;Post Oak&apos;, 
202, &apos;Spectrum Houston Galleria&apos;, 
207, &apos;Bountiful&apos;, 
28, &apos;Salt Lake City Refinery&apos;, 
205, &apos;Spectrum Reston&apos;, 
01, &apos;San Francisco&apos;, 
22, &apos;West Loop&apos;, 
53, &apos;Electronic&apos;, 
55, &apos;Inactive, Low Balance, No Loans*&apos;, 
56, &apos;Inactive, Low Balance, Chargeoffs&apos;, 
57, &apos;Inactive, Low Balance, Bad Address&apos;, 
88, &apos;Operation Services&apos;, 
93, &apos;Member Services&apos;, 
98, &apos;Remote Access&apos;, 
204, &apos;Spectrum Westridge Mall&apos;, 
253, &apos;Spectrum Electronic&apos;, 
255, &apos;Spectrum Inactive, Low Balance, No Loans*&apos;, 
256, &apos;Spectrum Inactive, Low Balance, Chargeoffs&apos;, 
257, &apos;Spectrum Inactive, Low Balance, Bad Address&apos;, 
293, &apos;Spectrum Member Services Branch&apos;, 
&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Branch Name</label>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/main/default/classes/ImpendingDormancyCreateOpportunityBatch.cls
global class ImpendingDormancyCreateOpportunityBatch implements Database.Batchable<sObject>, Database.Stateful{
     global set<Id> AccountId;
     
    global map<string, string> accountset;
    global List<Opportunity> OpportunityList;
    global List<Account_Details__c> MemberAccountmap;
   
       global ImpendingDormancyCreateOpportunityBatch(){
            accountset = new  map<string, string> ();
            OpportunityList = new List<opportunity>();
            MemberAccountmap = new List<Account_Details__c>();
        //  ListMemberAccount = new string();
       }
    
     global Database.QueryLocator start(Database.BatchableContext BC){
         Triggered_Opportunity_Configurations__c cs = Triggered_Opportunity_Configurations__c.getValues('Primary Record');
        Integer Inactivity_Days =0, Dormant_Days=0;
        Inactivity_Days = (Integer)cs.Impending_Dormancy_Inactivity_Days__c*(-1);       
        date LastNDays = system.today().addDays(Inactivity_Days);
        
        Dormant_Days = (Integer)cs.Impending_Dormancy_Dormant_Days__c*(-1);     
        date LastNDormantDays = system.today().addDays(Dormant_Days);
         
      
      return Database.getQueryLocator('select id,Parent_Account__c,Activity_Date__c,RecType__C,Correspondence_Date__c , Assigned_Branch1__c, Created_At_Branch1__c, Current_Branch1__c, Assigned_Branch__c, Created_At_Branch__c, Current_Branch__c from Account_Details__c where (((Activity_Date__c = null or Activity_Date__c <=' + string.valueof(LastNDays).replace(' 00:00:00','') + ') and (Correspondence_Date__c =null or Correspondence_Date__c <= ' + string.valueof(LastNDays).replace(' 00:00:00','')  + '))' +
                                        ' and ((Activity_Date__c = null or Activity_Date__c > '+ string.valueof(LastNDormantDays).replace(' 00:00:00','') +') or (Correspondence_Date__c =null or Correspondence_Date__c > ' + string.valueof(LastNDormantDays).replace(' 00:00:00','') + '))) and DormancyOppCreated__c = false');
   }
    
    global void execute(Database.BatchableContext BC, List<Account_Details__c> acclist){
        system.debug('Test');
        map<id,string> branchMap = new map<id,string>();
        Set<id> listParentAccounts = new Set<id>();
        Map<id,id> mapParentAccounts = new Map<id,id>();
        List<group> queues = [select id, name, DeveloperName from group where type='queue'];
        map<string, string> episysUserBranch = new map<string, string>();
        
        List<Episys_User__c> EpisysUser = [select Assigned_Branch__c, Branch_Name__c from Episys_User__c where Assigned_Branch__c <> null];
        for(Episys_User__c eu:EpisysUser){
            episysUserBranch.put(string.valueOf(eu.Assigned_Branch__c).replace('.0',''), eu.Branch_Name__c);
            
        }
        
        List<Group> listQueue = [select id,Name,Email from Group where Type = 'Queue'];
        
        

        for(Account_Details__c item : acclist)
        {
            string Assignedbranch ='';
            string CreatedAtBranch ='';
            string Currentbranch ='';
            string finalqueue='';           
            system.debug('item=='+ item.id);
            
            if(item.Assigned_Branch__c != null){
                Assignedbranch = episysUserBranch.get(string.valueOf(item.Assigned_Branch__c).replace('.0','')); 
                finalqueue = checkifPhysicalBranch(Assignedbranch, listQueue);                          
            }
            if(item.Created_At_Branch__c != null && finalqueue == ''){
                CreatedAtBranch = episysUserBranch.get(string.valueOf(item.Created_At_Branch__c).replace('.0',''));     
                finalqueue = checkifPhysicalBranch(CreatedAtBranch, listQueue);
            }
            if(item.Current_Branch__c != null && finalqueue == ''){
                Currentbranch = episysUserBranch.get(string.valueOf(item.Current_Branch__c).replace('.0','')); 
                finalqueue = checkifPhysicalBranch(Currentbranch, listQueue);
            }
            //branch=branch.replaceAll('branch', '').trim().replaceAll(' ', '_');
            if(string.isNotBlank(finalqueue) && string.isNotEmpty(finalqueue))
            {
                
                    branchMap.put(item.id, finalqueue);
                    if(item.Parent_Account__c == null && !listParentAccounts.contains(item.id))
                    {
                        listParentAccounts.add(item.Id);
                              mapParentAccounts.put(item.id,item.Id);
                    }
                    else if(!listParentAccounts.contains(item.Parent_Account__c))
                    {
                        listParentAccounts.add(item.Parent_Account__c);
                        mapParentAccounts.put(item.id,item.Parent_Account__c);
                    }
                    
            }   
        }
        system.debug('branchMap###' + branchMap);
        List<Id> MemberWithOpp = new List<string>();
        List<Person_Account__c> listPA = [SELECT Id,Account_Number__c,PersonId__c,PersonId__r.DormancyOppCreated__c
                                            FROM Person_Account__c where Account_Number__c in: listParentAccounts and TypeTranslate__c = '0000/Primary' ];
        Map<string, string> mapParentIdAccountId = new  Map<string, string>();
        for(Person_Account__c pa : listPA)
        {
            mapParentIdAccountId.put(pa.Account_Number__c,pa.PersonId__c);
            
            if(pa.PersonId__r.DormancyOppCreated__c == true && !MemberWithOpp.contains(pa.PersonId__c))
            {
                MemberWithOpp.add(pa.PersonId__c);
            }
        }
        
        
        string ListMemberAccount ='';
        system.debug('accountset==='+accountset);
        List<Opportunity> listopptoCreate = new List<Opportunity>();
        set<Id> accountIds = new set<Id>();
        for(Account_Details__c item : acclist)
        {
             string parentAccount =  mapParentAccounts.get(item.id);
             string member = mapParentIdAccountId.get(parentAccount);
             string queuename = branchMap.get(item.id);
             if(string.isNotBlank(queuename) && string.isNotEmpty(queuename)) {
                system.debug('Member Not Found');               
                if (!accountset.containsKey(member) && !MemberWithOpp.contains(member)) {
                    system.debug('Member Not Found1');
                    if(member != null && string.isNotBlank(member) && string.isNotEmpty(member))
                    { 
                        system.debug('Member Not Found2');
                        ListMemberAccount = accountset.get(member);
                        if(ListMemberAccount != null && string.isNotBlank(ListMemberAccount) && string.isNotEmpty(ListMemberAccount)){
                            ListMemberAccount = ListMemberAccount + ',' + item.Id;
                        }
                        else
                        {
                          ListMemberAccount = item.Id;
                        }
                        accountset.put(member, ListMemberAccount);
                        
                        Opportunity opp = new Opportunity();
                        opp.Member_Account__c = item.id;
                        opp.StageName = 'New';
                        opp.AccountId = member;
                       
                        opp.Opportunity_Source__c = 'Member Intelligence';
                        opp.Product_Type__c = 'Accounts/Shares';
                        opp.Product_Sub__c = 'Membership';
                        opp.Queue_Owner__c = queuename;
                        
                        List<date> datelist = new List<date>();
                        if(item.Activity_Date__c != null)
                            datelist.add(item.Activity_Date__c);
                        if(item.Correspondence_Date__c != null)
                             datelist.add(item.Correspondence_Date__c);
                        date Futuredate, maxDate;  
                        if(datelist.size()==2){
                            datelist.sort();                
                            maxDate = datelist.get(datelist.size()-1);
                            Futuredate = maxDate.adddays(365);
                        }
                        else if(datelist.size()==1){                        
                            maxDate = datelist.get(0);
                            Futuredate = maxDate.adddays(365);
                        }

                        opp.Future_Date__c = Futuredate;
                        opp.Name = 'Test';
                        opp.CloseDate = system.today();
                        opp.Description = '(INSTRUCTIONS) \r\n TRIGGERED OPPORTUNITY \r\n Inform the member of their impending dormancy and review their options with them.';
                        opp.isTriggeredOpportunity__c =true;                
                        OpportunityList.add(opp);        
                     }           
                       
                   }
                   else{    
                    ListMemberAccount = accountset.get(member);
                      if(ListMemberAccount != null && string.isNotBlank(ListMemberAccount) && string.isNotEmpty(ListMemberAccount)){
                            ListMemberAccount = ListMemberAccount + ',' + item.Id; 
                        }
                        else
                        {
                            ListMemberAccount = item.Id;
                        }   
                         accountset.put(member, ListMemberAccount); 
                         
                         system.debug('ListMemberAccount###' + ListMemberAccount);
                         system.debug('member###' + member);
                         system.debug('item.Id###' + item.Id);
                         system.debug('accountset###' + accountset);
                         
                   }
                MemberAccountmap.add(item);
            }
        }
       
    }
     global void finish(Database.BatchableContext BC){
                
        
        system.debug('accountmap###' + accountset);
         system.debug('OpportunityList###' + OpportunityList);
         system.debug('MemberAccountmap###' + MemberAccountmap);
         
        map<id, string> MemberAccountList = new map<id, string>();
        
        List<Account> accounts = [select id, DormancyOppCreated__c,DormancyMemberAccounts__c from Account where id in: accountset.keySet()];
                for (Account acc : accounts){
                    acc.DormancyOppCreated__c=true;
                    
                    if(string.isnotBlank(acc.DormancyMemberAccounts__c) && string.isnotEmpty(acc.DormancyMemberAccounts__c))
                    {
                        acc.DormancyMemberAccounts__c = acc.DormancyMemberAccounts__c + ','  + accountset.get(acc.id); 
                    }
                    else
                    {
                        acc.DormancyMemberAccounts__c =  accountset.get(acc.id);
                    }
                }
                for (Account_Details__c acc1 : MemberAccountmap){
                    acc1.DormancyOppCreated__c=true;
                }
                
                update accounts;
                update MemberAccountmap;
                
                
                insert OpportunityList;

   }
   
   public static string checkifPhysicalBranch(string branchname, List<Group> listQueue){
        String groupName = ''; 
        system.debug('branchname==='+branchname);
        if(branchname != '' && branchname != null){
            string BranchQueue = branchname.replace(' ', '_').replace('-','_').replace('/','_').toLowerCase();
        
        for(Group grp : listQueue)
                     {
                        if(grp.Email != null && grp.Email.containsIgnoreCase(BranchQueue)){
                                            groupName = grp.Name;
                                            break;
                            }
                                        
                       }
        }
        
        return groupName;
                        
   }
}