src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Authenticated_Log__c.object
<CustomObject>
    <fields>
        <fullName>PersonId__c</fullName>
        <label>PersonId</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Authentication Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Authenticated Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authentication Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/OOWAccountNumber.cls
public with sharing class OOWAccountNumber {
    
     @AuraEnabled
    public static string GetAccountNumber(string accdetailid, string sobjecttype)
    {
    	system.debug('sobjecttype##'+ sobjecttype);
         string AccountNumber;
        if(sobjecttype == 'Account_Details__c')
        {
            Account_Details__c accdetailList = [select id, Name from Account_Details__c where id=:accdetailid];
                       
            AccountNumber = accdetailList.Name ;
        } 
        else
        {
            Person_Account__c p = [SELECT Id, Account_Number__c,  PersonID__c, Account_Number__r.RecType__c, TypeTranslate__c, Account_Number__r.Name
                FROM Person_Account__c where PersonID__c =:accdetailid and Account_Number__r.RecType__c ='ACCT' limit 1];
            AccountNumber = p.Account_Number__r.Name;
        }
           return Accountnumber;                  
       
    }
    
    @AuraEnabled
    public static void SaveLogData(string status, string MemberNumber, string reason, string notes)
    {
    	RecordType rec = [select Id,Name,SobjectType from RecordType where Name ='OOW Execution Log' and SobjectType='Authenticated_Log__c'];
    	
    	Authenticated_Log__c log = new Authenticated_Log__c();
    	log.RecordTypeId= rec.id;
    	log.OOW_Status__c = status;
    	log.OOW_Member_Number__c = MemberNumber;
    	log.OOW_Reason__c = reason;
    	log.OOW_Notes__c = notes;
    	
    	insert log;
    	
    	system.debug('log##'+ log);
    	
    }
}