src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PersonID__c</fullName>
        <externalId>true</externalId>
        <label>PersonID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, IF(Reference__c == &apos;BC02&apos;, &apos;Spectrum&apos;, &apos;Chevron&apos;))</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseComments__c</fullName>
        <label>CaseComments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CaseRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Case Record Type based on Categories</description>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teritiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseRecordType</label>
</CustomObject>

src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Person</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>IF(Account_Number__r.Reference__c == &apos;BC01&apos;, &apos;Chevron&apos;, &apos;Spectrum&apos;)</formula>
        <label>Brand</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PersonID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Person Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Person_Account</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SetRecordTypeAccountDetailsCtrlTest.cls
@isTest
public class SetRecordTypeAccountDetailsCtrlTest {
    
    static testmethod void testmethod1(){
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Account acc = new Account(
           RecordTypeID=RecTypeId,
           FirstName='Test FName',
           LastName='Test LName',
           PersonMailingStreet='test@yahoo.com',
           PersonMailingPostalCode='12345',
           PersonMailingCity='SFO',
           PersonEmail='test@yahoo.com',
           PersonHomePhone='1234567',
           PersonMobilePhone='12345678');
         
        insert acc;
        
        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
        insert accDetails; 
        
        Person_Account__c pa = new Person_Account__c();
            pa.Account_Number__c = accDetails.Id;
            pa.PersonID__c = acc.Id;
        insert pa;

        RecordType recTpe = [Select Id, Name from RecordType where SobjectType='Case' AND Name = 'Account Servicing' Limit 1];
 
        CaseRecordType__c crt = new CaseRecordType__c();
        crt.RecordTypeId__c = recTpe.Id;
        crt.Primary_Category__c = 'test1';
        crt.Secondary_Category__c = 'test2';
        crt.Teritiary_Category__c = 'test3';
        crt.Name = '000';
        insert crt; 
        
        Case cRec = new Case();
           cRec.Brand__c = 'CFCU';
           cRec.CaseComments__c = 'test comments';
        insert cRec;
        
        CaseComment cc = new CaseComment();
           cc.ParentId = cRec.Id;
        insert cc;
        
        test.starttest();
        PageReference pageRef = Page.SetRecordTypeAccountDetails;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('firstPage', 'true');
        ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
        SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec)); 
        
        controller.accountName = accDetails.Id;        
        controller.personId = acc.Id;
        controller.pcOptions();
        controller.pcValue = 'test1';
        controller.scOptions();
        controller.scValue = 'test2';
        controller.tcOptions();
        controller.tcValue = 'test3';
        controller.change();
        controller.nextPage();
        controller.process();
         test.stoptest();
    }
    
    static testmethod void testmethod2(){

        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
        insert accDetails;
        
        Case cRec = new Case();
        
        PageReference pageRef = Page.SetRecordTypeAccountDetails;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('firstPage', 'true');
        ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
        SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec));       
        controller.accountName = accDetails.Id;
        controller.pcValue = 'test1';
        controller.scOptions();        
        controller.process1();
        System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Secondary Category') ;
    }
    
    static testMethod void testMethod3(){

        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
        insert accDetails;
       
       Case cRec = new Case();
       
       PageReference pageRef = Page.SetRecordTypeAccountDetails;
       Test.setCurrentPage(pageRef);
       ApexPages.currentPage().getParameters().put('firstPage', 'true');
       ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
       SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec)); 
       controller.accountName = accDetails.Id;
       controller.pcValue = 'test1';
       controller.scOptions();
       controller.scValue = 'test2';
       controller.tcOptions();
       controller.process1();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Tertiary Category');
    } 
    
    static testMethod void testMethod4(){

        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
        insert accDetails;
       
       Case cRec = new Case();
       
       PageReference pageRef = Page.SetRecordTypeAccountDetails;
       Test.setCurrentPage(pageRef);
       ApexPages.currentPage().getParameters().put('firstPage', 'true');
       ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
       SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec));       
       controller.accountName = accDetails.Id;
       controller.pcOptions();
       controller.process1();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Primary Category');        
    } 
    
    static testMethod void testMethod5(){
        
       Account_Details__c accDetails = new Account_Details__c();
           accDetails.Name = 'testname';
       insert accDetails;  
        
       Case cRec = new Case();
       
       PageReference pageRef = Page.SetRecordTypeAccountDetails;
       Test.setCurrentPage(pageRef);
       ApexPages.currentPage().getParameters().put('firstPage', 'true');
       ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
       SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec));        
       controller.process1();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Member');       
    } 
    
    static testmethod void testmethod6(){

        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
        insert accDetails; 

        Case cRec = new Case();
        
        PageReference pageRef = Page.SetRecordTypeAccountDetails;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('firstPage', 'true');
        ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
        SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec));        
        controller.accountName = accDetails.Id;
        controller.pcValue = 'test1';
        controller.scOptions();        
        controller.nextPage();
        System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Secondary Category') ;
    }
    
    static testMethod void testMethod7(){
       Account_Details__c accDetails = new Account_Details__c();
           accDetails.Name = 'testname';
       insert accDetails; 
       
       Case cRec = new Case();
       
       PageReference pageRef = Page.SetRecordTypeAccountDetails;
       Test.setCurrentPage(pageRef);
       ApexPages.currentPage().getParameters().put('firstPage', 'true');
       ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
       SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec));         
       controller.nextPage();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Member');       
    }
    
     static testMethod void testMethod8(){

       Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
       insert accDetails; 
       
       Case cRec = new Case();
       
       PageReference pageRef = Page.SetRecordTypeAccountDetails;
       Test.setCurrentPage(pageRef);
       ApexPages.currentPage().getParameters().put('firstPage', 'true');
       ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
       SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec));         
       controller.accountName = accDetails.Id;
       controller.pcOptions();
       controller.nextPage();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Primary Category');      
    }
    
    static testMethod void testMethod9(){

       Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
       insert accDetails; 
       
       Case cRec = new Case();
              
       PageReference pageRef = Page.SetRecordTypeAccountDetails;
       Test.setCurrentPage(pageRef);
       ApexPages.currentPage().getParameters().put('firstPage', 'true');
       ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
       SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec)); 
       controller.accountName = accDetails.Id;
       controller.pcValue = 'test1';
       controller.scOptions();
       controller.scValue = 'test2';
       controller.tcOptions();
       controller.nextPage();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Tertiary Category');
    } 
    
    static testmethod void testmethod10(){
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Account acc = new Account(
           RecordTypeID=RecTypeId,
           FirstName='Test FName',
           LastName='Test LName',
           PersonMailingStreet='test@yahoo.com',
           PersonMailingPostalCode='12345',
           PersonMailingCity='SFO',
           PersonEmail='test@yahoo.com',
           PersonHomePhone='1234567',
           PersonMobilePhone='12345678');
         
        insert acc;
        
        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
        insert accDetails; 
        
        Person_Account__c pa = new Person_Account__c();
            pa.Account_Number__c = accDetails.Id;
            pa.PersonID__c = acc.Id;
        insert pa;

        RecordType recTpe = [Select Id, Name from RecordType where SobjectType='Case' AND Name = 'Account Servicing' Limit 1];
 
        CaseRecordType__c crt = new CaseRecordType__c();
        crt.RecordTypeId__c = recTpe.Id;
        crt.Primary_Category__c = 'test1';
        crt.Secondary_Category__c = 'test2';
        crt.Teritiary_Category__c = 'test3';
        crt.Name = '000';
        insert crt; 
        
        Case cRec = new Case();
           cRec.Brand__c = 'CFCU';
           cRec.CaseComments__c = 'test comments';
        insert cRec;
        
        CaseComment cc = new CaseComment();
           cc.ParentId = cRec.Id;
        insert cc;
        
         test.starttest();
        PageReference pageRef = Page.SetRecordTypeAccountDetails;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('firstPage', 'true');
        ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
        SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec));  
        
        controller.accountName = accDetails.Id;        
        controller.personId = acc.Id;
        controller.pcOptions();
        controller.pcValue = 'test1';
        controller.scOptions();
        controller.scValue = 'test2';
        controller.tcOptions();
        controller.tcValue = 'test3';
        controller.process1();
         test.stoptest();
    }
    
    static testMethod void testMethod11(){
        String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Account acc = new Account(
           RecordTypeID=RecTypeId,
           FirstName='Test FName',
           LastName='Test LName',
           PersonMailingStreet='test@yahoo.com',
           PersonMailingPostalCode='12345',
           PersonMailingCity='SFO',
           PersonEmail='test@yahoo.com',
           PersonHomePhone='1234567',
           PersonMobilePhone='12345678');
         
        insert acc;
        
        Account_Details__c accDetails = new Account_Details__c();
            accDetails.Name = 'testname';
        insert accDetails;       

        RecordType recTpe = [Select Id, Name from RecordType where SobjectType='Case' AND Name = 'Account Servicing' Limit 1];
 
        CaseRecordType__c crt = new CaseRecordType__c();
        crt.RecordTypeId__c = recTpe.Id;
        crt.Primary_Category__c = 'test1';
        crt.Secondary_Category__c = 'test2';
        crt.Teritiary_Category__c = 'test3';
        crt.Name = '000';
        insert crt; 
        
        Case cRec = new Case();
        
        PageReference pageRef = Page.SetRecordTypeAccountDetails;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('firstPage', 'true');
        ApexPages.currentPage().getParameters().put('acctId', accDetails.Id);        
        SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(cRec)); 
        
        controller.doCancel();
    }
    
    static testMethod void testMethod12(){
        
        Case c = new Case();
           c.Brand__c = 'CFCU';
        insert c;

        PageReference pageRef = Page.InputFilePage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('caseId', c.Id); 
        SetRecordTypeAccountDetailsController controller = new SetRecordTypeAccountDetailsController(new ApexPages.StandardController(c));
    }
}