src/objects/Account_Details__c.object
<CustomObject>
    <description>This Object will be used to store all the MemberShip Account as well as Sub-Account related information.</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Combined_Account_ID__c</fullName>
        <label>Combined_Account_ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID1__c</fullName>
        <label>Share ID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Onboarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Onboarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecType__c</fullName>
        <label>RecType</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>Status</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Account Type / Share Type</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <label>Member Account</label>
    <nameField>
        <label>Account Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Member Account</pluralLabel>
    <recordTypes>
        <fullName>Share</fullName>
        <active>true</active>
        <description>This record type will be used to store all the SHARE Information</description>
        <label>Share</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
                <value>
                    <fullName>Extended Check Hold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CloseCaseControllerTest.cls
@isTest
private class CloseCaseControllerTest {
 	
 	@testSetup
	static void setupTestData(){
		Create_SLA__c cl = new Create_SLA__c();
        cl.Status__c = 'Open';
        cl.Name = 'Open';
        cl.hours__c = 8;
        insert cl;
        
        Create_SLA__c cl1 = new Create_SLA__c();
        cl1.Status__c = 'In Process';
        cl1.Name = 'In Process';
        cl1.hours__c = 20;
        insert cl1;
        
        Create_SLA__c cl2 = new Create_SLA__c();
        cl2.Status__c = 'Resolution';
        cl2.Name = 'Resolution';
        cl2.hours__c = 20;
        insert cl2;
        
        test.startTest();
		Account account_Obj = new Account(LastName = 'BANDATest', FirstName = 'MARIATest', Type = 'null', PersonHasOptedOutOfEmail = false);
    	Insert account_Obj; 
    	Account_Details__c act_details_obj = new Account_Details__c(Name = '0000147163', Balance__c = 0.00, Combined_Account_ID__c = '0000147163S0100P0100', ID1__c = '0100', Onboarded__c = true, RecType__c = 'ACCT', TypeTranslate__c = '1-PRIMARY SHARE');
    	Insert act_details_obj;
    	Case case_obj = new Case(Status = 'In Process', Origin = null, Subject = 'Test', ClosedDate = null, IsEscalated = false, AccountId = account_Obj.Id, Account_Number__c = act_details_obj.Id, Primary_Category__c = 'Account Maintenance', Secondary_Category__c = 'Account Services', Tertiary_Category__c = 'Extended Check Hold');
    	Insert case_obj;
    	test.stopTest();
	}

    static testMethod void myUnitTest() {
        Case case_obj = [select Id from case limit 1];
        CloseCaseController.FetchCaseData(case_obj.Id);        
        CloseCaseController.closeCaseSave(case_obj.Id,'Open','test', 'test Comments');
    }
}