src/objects/AllNotes__c.object
<CustomObject>
    <description>Legacy notes from Episys</description>
    <fields>
        <fullName>Created_By_User_Text__c</fullName>
        <label>Created By</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_User__c</fullName>
        <label>Created By User</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NoteID__c</fullName>
        <externalId>true</externalId>
        <label>Note ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>All Notes</label>
    <nameField>
        <displayFormat>AllNote-{000000000}</displayFormat>
        <label>Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>All Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Episys_Name__c</fullName>
        <label>Episys Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/AllNotesTriggerTest.cls
@isTest
public class AllNotesTriggerTest {

    static testMethod void testMethod1(){
        
        Episys_User__c eu = new Episys_User__c();
             eu.Episys_ID__c = 1;
             eu.Episys_Name__c = 'test';
        insert eu;
        
        AllNotes__c nts = new AllNotes__c();
             nts.NoteID__c = 'test1';
             nts.Created_By_User__c = 1;
        insert nts;
        
        nts.Created_By_User_Text__c = 'test';
        update nts;             
    }
}