src/objects/Authenticated_Log__c.object
<CustomObject>
    <fields>
        <fullName>Decision__c</fullName>
        <label>Decision</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesforceID__c</fullName>
        <label>SalesforceID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Authentication Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Authenticated Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Authentication Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/AuthenitcationLogsController.cls
public class AuthenitcationLogsController
{
	public string accId {get;set;}
	public List<Authenticated_Log__c>	logs {get;set;}
	
  public AuthenitcationLogsController(ApexPages.StandardController controller){
      Account accRec = (Account)Controller.getRecord();
      accId = accRec.Id;
      
     logs = [select Id,CreatedBy.Name,Decision__c,CreatedDate from Authenticated_Log__c where SalesforceID__c =: accId 
     	and decision__C in ('OTP - No Contact Info','OTP – Not Eligible','OTP – Code not provided','OTP – Code Expired','OTP – Code Failed','Not Authenticated')
     	order by CreatedDate desc
     limit 3];
    }
}