src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Episys_User_ID__c</fullName>
        <label>Episys User ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_Source__c</fullName>
        <label>Event Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event – Oakland City Center Meet and Greet 12/06/17</fullName>
                </value>
                <value>
                    <fullName>Event – San Francisco Plaza Event 11/30/17</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Contractor Safety Meeting-12/07/17</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Brock New Hire Orientation-01/05/18</fullName>
                </value>
                <value>
                    <fullName>Event-Richmond-Pinole Valley Juniors Fundraiser-01/07/18</fullName>
                </value>
                <value>
                    <fullName>Event-El Paso-Contractor Visit-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-1600 Smith Houston-Lunch and Learn-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Chevron Retiree Luncheon-01/23/18</fullName>
                </value>
                <value>
                    <fullName>Event-Post Oak Houston-Briarpark Atrium Event-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-El Paso-Lobby Event-02/02/18</fullName>
                </value>
                <value>
                    <fullName>Event-Post Oak Houston-Stewart Legacy Event-01/25/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Meet and Greet-01/30/18</fullName>
                </value>
                <value>
                    <fullName>Event-Reston-Open House-01/31/18</fullName>
                </value>
                <value>
                    <fullName>Event-Houston Galleria-Lobby Event-02/07/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Contractor New Hire Orientation-01/19/18</fullName>
                </value>
                <value>
                    <fullName>Event-Covington-Meet and Greet-01/31/18</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_did_you_hear_about_us__c</fullName>
        <label>How did you hear about us?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yahoo Ad</fullName>
                </value>
                <value>
                    <fullName>Google Ad</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>No Product Available</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>No Prospect/Mbr Deciding</fullName>
                </value>
                <value>
                    <fullName>App Online</fullName>
                </value>
                <value>
                    <fullName>App Completed</fullName>
                </value>
                <value>
                    <fullName>Follow Up Required</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Poor Referral</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Appointment Set Branch</fullName>
                </value>
                <value>
                    <fullName>Appointment Set Phone</fullName>
                </value>
                <value>
                    <fullName>Additional Follow-up Required</fullName>
                </value>
                <value>
                    <fullName>Contact Attempted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/OpportunityOwnerAssignmentTest.cls
@isTest
private class OpportunityOwnerAssignmentTest {

	@testSetup
	static void SetUp(){
		test.StartTest();
		
		Group	listQueue = [select id,Name,Email from Group where Type = 'Queue' and (Email like '%lead.com') limit 1];
		Account account_Obj = new Account(PersonHomePhone='', PersonHasOptedOutOfEmail = false, Name = 'MARIA BANDA');
		Insert account_Obj; 
		
    	 Lead ld = new Lead (LastName = 'Test',Product_Type__c = 'Card',Brand__c = 'CFCU',FirstName = 'test',MiddleName = 'New', Description = 'New', Ownerid = listQueue.Id,
    						Salutation = 'MR.',Suffix = 'MR',Status = 'New',Phone= '1234567890',Email='test@test.com',MobilePhone='1234567892',How_did_you_hear_about_us__c='Website',Event_Source__c='Event-Reston-Open House-04/20/18',
   							 LeadSource='BDO-Realtor Referral' , Ownership__c='Queue', Street_Address_1__c='Address 1',State__c= 'NY',Zip_Code__c= '12345',City__c='NYC',Country__c ='USA');
    	insert ld; 	
      
      Opportunity op = new Opportunity(Name = 'Name', StageName = 'Open', CloseDate = system.today(),  Is_Converted__c = true, Queue_Assigned_Id__c= listQueue.Id,  Opportunity_Source__c = 'Word of mouth', AccountId = account_Obj.id,  Ownership__c = 'Auto Assign', Episys_User_ID__c = 1);
       insert op;
      
      Opportunity op1 = new Opportunity(Name = 'Name', StageName = 'Open', CloseDate = system.today(),  Is_Converted__c = true, Queue_Assigned_Id__c= listQueue.Id,  Opportunity_Source__c = 'Word of mouth', AccountId = account_Obj.id,  Ownership__c = 'Keep', Episys_User_ID__c = 1);
      insert op1;
	
	Opportunity op2 = new Opportunity(Name = 'Name', StageName = 'Closed Lost', Sub_Status__c ='Declined' , CloseDate = system.today(),  Is_Converted__c = true, Queue_Assigned_Id__c= listQueue.Id,  Opportunity_Source__c = 'Word of mouth', AccountId = account_Obj.id,  Ownership__c = 'Keep', Episys_User_ID__c = 1);
      insert op2;
		
		test.StopTest();
	}
	
	static testMethod void changeCaseOwnershipTest() {
       
        
        Lead l = [Select id, Status,Ownership__c, LeadSource,Product_Type__c,Episys_User_ID__c from Lead limit 1];
        Opportunity o = [Select id,  Ownership__c,Queue_Owner__c,User_Owner__c,Queue_Assigned_Id__c from Opportunity where Ownership__c = 'Auto Assign' limit 1 ];
         Opportunity o1 = [Select id,  Ownership__c,Queue_Owner__c,User_Owner__c,Queue_Assigned_Id__c from Opportunity where Ownership__c = 'Keep' limit 1];
      //    Opportunity o2 = [Select id,  Ownership__c,Queue_Owner__c,User_Owner__c,Queue_Assigned_Id__c from Opportunity where Ownership__c = 'Queue' limit 1];
        
       List<Group> g = OpportunityOwnerAssignment.GetQueueName('Opportunity');
       List<Group> g1 = OpportunityOwnerAssignment.GetQueueName('Lead');
       OpportunityOwnerAssignment.OpportunityChangeOwner(o,o.Id);
       OpportunityOwnerAssignment.OpportunityChangeOwner(o1,o.Id);
       OpportunityOwnerAssignment.OpportunityChangeOwner(o1,l.Id);
        
    }
    
    static testMethod void GetStatusTest()
    {
    	 Opportunity o = [Select id,  Ownership__c,Queue_Owner__c,User_Owner__c,Queue_Assigned_Id__c from Opportunity where Ownership__c = 'Auto Assign' limit 1 ];
    	OpportunityOwnerAssignment.GetStatus('Opportunity', o.id );
    	 Opportunity o1 = [Select id,  Ownership__c,Queue_Owner__c,User_Owner__c,Queue_Assigned_Id__c from Opportunity where StageName = 'Closed Lost' limit 1 ];
    	OpportunityOwnerAssignment.GetStatus('Opportunity', o1.id );
    	
    }
    
}