src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseComments__c</fullName>
        <label>CaseComments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Future_Date__c</fullName>
        <label>Future Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LTK__c</fullName>
        <label>Ticket #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ownership__c</fullName>
        <label>Ownership</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Keep</fullName>
                </value>
                <value>
                    <fullName>Auto Assign</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Assign</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
                <value>
                    <fullName>EPS Research</fullName>
                </value>
                <value>
                    <fullName>Loan Payment</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Transfers Between Memberships</fullName>
                </value>
                <value>
                    <fullName>Transfers Between Sub-Accounts</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Loan Payment</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CaseRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Case Record Type based on Categories</description>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type_Name__c</fullName>
        <label>Record Type Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teritiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseRecordType</label>
</CustomObject>

src/main/default/classes/SetRecordTypeStandAloneCaseController.cls
public class SetRecordTypeStandAloneCaseController {

    private final Case cRec;
    
    public string selectedPrimary{ get;set; }
    
        public list<SelectOption> SearchResult{get;set;}
    public list<SelectOption> pcOptionList{get;set;}
    public string pcValue { get;set; }
    public list<SelectOption> scOptionList{get;set;}
    public string scValue { get;set; }
    public list<SelectOption> tcOptionList{get;set;}
    public string tcValue { get;set; }
    public Blob file {get;set;} 
    public String fileName{get;set;} 
    public List<Attachment> allFileList {get; set;}
    public string caseId {get;set;}
    public Boolean b1{get;set;}
    public Boolean bool{get;set;}
    public integer commentLimit = 4000;
      public String searchText{get;set;}

       
    public SetRecordTypeStandAloneCaseController(ApexPages.StandardController controller){
        bool = false;
        this.cRec = (Case)Controller.getRecord();
        caseId = System.currentPageReference().getParameters().get('caseId');                
        pcOptionList = pcOptions();      
    }
    
    public void change()
    {
        if(b1 == true)
        
        {
            bool = true;
        }
        else
        {
            bool = false;
        }
    }
 
    public List<SelectOption> pcOptions() {
    
    Schema.DescribeFieldResult statusFieldDescription = Case.Primary_Category__c.getDescribe();
        System.debug('Getting description:::'+ statusFieldDescription);
        list<SelectOption> op = new list<SelectOption>();
        op.add(new SelectOption('-None-','-None-'));
        for (Schema.Picklistentry picklistEntry : statusFieldDescription.getPicklistValues())
        {
            op.add(new SelectOption(pickListEntry.getValue(),pickListEntry.getLabel()));
        }
        return op;
    }
    
    public void scOptions() {
    
        list<CaseRecordType__c> scList = [SELECT Id,
                                                 Primary_Category__c,
                                                 Secondary_Category__c FROM CaseRecordType__c WHERE Primary_Category__c =:pcValue];
        set<String> scSet = new set<String>();
        scList.sort();
        for(CaseRecordType__c var: scList){
            scSet.add(var.Secondary_Category__c);
        }                                       
        scOptionList = new list<SelectOption>();
        scOptionList.add(new SelectOption('-None-','-None-'));
        for (String sc : scSet)
        {
            if(sc!='None'){
                scOptionList.add(new SelectOption(sc,sc));
            }
        }
        tcOptionList = new list<SelectOption>();
            tcOptionList.add(new SelectOption('-None-','-None-'));

    }
    
   
    
    public void SearchTertiary(){
   
            pcOptionList = new list<SelectOption>();
            pcOptionList .add(new SelectOption('-None-','-None-'));
             scOptionList = new list<SelectOption>();
            scOptionList .add(new SelectOption('-None-','-None-'));
                        String newSearchText = '%'+searchText+'%';
            list<CaseRecordType__c> tcList = [SELECT Id,
                                                Primary_Category__c,Secondary_Category__c, Teritiary_Category__c FROM CaseRecordType__c WHERE Teritiary_Category__c like :newSearchText or 
                                                Primary_Category__c like :newSearchText or Secondary_Category__c like :newSearchText ];
        List<String> str = new List<String>();

        for(CaseRecordType__c tcr: tcList){
            str.add(tcr.Primary_Category__c + ' / ' + tcr.Secondary_Category__c + ' / ' + tcr.Teritiary_Category__c);
        }

         SearchResult = new list<SelectOption>();
         for (String tc : str){
            if(tc!='None'){
                SearchResult.add(new SelectOption(tc,tc));
            }
        }
      
        
        scOptionList = new list<SelectOption>();
        tcOptionList = new list<SelectOption>();
         tcOptionList.add(new SelectOption('-None-','-None-'));
         scOptionList.add(new SelectOption('-None-','-None-'));
                 pcOptionList = pcOptions();   
          scValue = '-None-';
        pcValue = '-None-';
        tcValue = '-None-';


    }
    
    public void tcOptions() {


        list<CaseRecordType__c> tcList = [SELECT Id,
                                                 Primary_Category__c,
                                                 Secondary_Category__c,
                                                 Teritiary_Category__c FROM CaseRecordType__c WHERE Secondary_Category__c =:scValue];
        List<String> str = new List<String>();
        tcList.sort();
        for(CaseRecordType__c tcr: tcList){
            str.add(tcr.Teritiary_Category__c);
        }
        tcOptionList = new list<SelectOption>();
        tcOptionList.add(new SelectOption('-None-','-None-'));
        for (String tc : str){
            if(tc!='None'){
                tcOptionList.add(new SelectOption(tc,tc));
            }
        }
    }   
    
    public void ChangeCategories()
    {
  if(!string.isBlank( searchText))
       {
           List<String> splits = selectedPrimary.split(' / ');
           pcValue  = splits[0];
           scOptions() ;
           scValue = splits[1];
          tcOptions() ;
                     tcValue = splits[2];
                     }
    }
    
    public pageReference nextPage(){

        boolean categorySelected = false;
       

         if((pcValue == NULL || pcValue == '-None-')){ // && !categorySelected){
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Primary Category');
            ApexPages.addMessage(msgs);
            return null;
        } 
        else if((scValue == NULL || scValue == '-None-')){ // && !categorySelected){
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Secondary Category');
            ApexPages.addMessage(msgs);
            return null;
        } 
        else if((tcValue == NULL || tcValue == '-None-' && scValue != 'Transfers Between Sub-Accounts' && scValue != 'Transfers Between Memberships'
                 && scValue != 'Check By Phone' && scValue != 'Loan Payment' && scValue != 'Check Withdrawal to Self'
                 && scValue != 'Credit Card Payment' && scValue != 'Check Withdrawal to Third Party' && scValue != 'Other')) // && !categorySelected) 
      
         {
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Tertiary Category');
            ApexPages.addMessage(msgs);
            return null;
        } 
        
         else if((cRec.CaseComments__c != NULL && cRec.CaseComments__c.length() > commentLimit ) ) {
                ApexPages.Message msgs3 = new ApexPages.Message(ApexPages.Severity.ERROR, 'Case Comments must be less than ' + commentLimit + ' characters. [' + cRec.CaseComments__c.length() + ']');
                ApexPages.addMessage(msgs3); 
                return null;
            }
           else if (categorySelected) //!categorySelected)
           {
            ApexPages.Message msgs3 = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select atleast one cateory');
                ApexPages.addMessage(msgs3); 
                return null;
           }
        else{
           if(tcValue == '-None-'){
                tcValue = 'None';
            } 
    
        list<CaseRecordType__c> scList = [SELECT Id,
                                                 Primary_Category__c,
                                                 Secondary_Category__c,
                                                 Teritiary_Category__c,
                                                 Record_Type_Name__c,
                                                 RecordTypeId__c FROM CaseRecordType__c WHERE Primary_Category__c =:pcValue AND Secondary_Category__c=:scValue
                                                                                                                            AND Teritiary_Category__c=:tcValue LIMIT 1];
        AssignmentRule AR = new AssignmentRule(); 
        AR = [SELECT Id FROM AssignmentRule WHERE SobjectType = 'Case' AND Active = True LIMIT 1];
            
        Database.DMLOptions dmlOpts = new Database.DMLOptions(); 
                dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;   
       
        Case cs = new case();
            cs.setOptions(dmlOpts);
            for(CaseRecordType__c crt : scList){
            cs.RecordTypeId = scList[0].RecordTypeId__c;
            cs.Primary_Category__c = scList[0].Primary_Category__c;
            cs.Secondary_Category__c = scList[0].Secondary_Category__c;
            cs.Tertiary_Category__c = scList[0].Teritiary_Category__c; }
           // cs.Brand__c = cRec.Brand__c;
            cs.Brand__c = 'CFCU';
          //  cs.Account_Number__c = cRec.Account_Number__c;
          //  cs.AccountId = cRec.AccountId;
            cs.Status = cRec.Status;
            cs.Subject = cRec.Subject;
            cs.LTK__c = cRec.LTK__c;
            cs.CaseComments__c = cRec.CaseComments__c;
            cs.Ownership__c = cRec.Ownership__c;
            if(cs.Ownership__c == 'Assign'){
            cs.OwnerId = cRec.OwnerId;
            }
       cs.Future_Date__c = cRec.Future_Date__c;

       
         try{ 
           insert cs;
           if(Test.isRunningTest()){
               Integer x=1/0;
            }
           }catch (exception e)  { 
           ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select appropriate values for all the fields.');
           ApexPages.addMessage(msgs); 
          }
            if(cs.CaseComments__c != null){
            CaseComment cc = new CaseComment();
              cc.ParentId = cs.Id;
              cc.CommentBody = cs.CaseComments__c;              
              
            insert cc;
            }
            

            
        PageReference pg1 = new PageReference('/apex/InputFilePage?caseId='+cs.Id);
        pg1.setRedirect(true);
        
        return pg1;      
       }
       
       
               
     }
    
    public pageReference doCancel(){
        pageReference page = new pageReference('/500/o');
        page.setRedirect(true);
        return page;
    }
    
    public pageReference process1(){
         boolean categorySelected = false;
        if(selectedPrimary != NULL && selectedPrimary != '') {
            categorySelected = true;
        }
         if((pcValue == NULL || pcValue == '-None-')){
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Primary Category');
            ApexPages.addMessage(msgs);
            return null;
        } 
        else if((scValue == NULL || scValue == '-None-')){
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Secondary Category');
            ApexPages.addMessage(msgs);
            return null;
        } 
        else if((tcValue == NULL || tcValue == '-None-' && scValue != 'Transfers Between Sub-Accounts' && scValue != 'Transfers Between Memberships'
                 && scValue != 'Check By Phone' && scValue != 'Loan Payment' && scValue != 'Check Withdrawal to Self'
                 && scValue != 'Credit Card Payment' && scValue != 'Check Withdrawal to Third Party' && scValue != 'Other')) 
       /*  else if(tcValue == NULL || tcValue == '-None-' && scValue != 'Death Claims' && scValue != 'EPS Research')*/
           {
            ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select Tertiary Category');
            ApexPages.addMessage(msgs);
            return null;
            
           } 
         else if(cRec.CaseComments__c != NULL && cRec.CaseComments__c.length() > commentLimit ) {
                ApexPages.Message msgs3 = new ApexPages.Message(ApexPages.Severity.ERROR, 'Case Comments must be less than ' + commentLimit + ' characters. [' + cRec.CaseComments__c.length() + ']');
                ApexPages.addMessage(msgs3); 
                return null;
            }           
     
     
        else{
           if(tcValue == '-None-'){
                tcValue = 'None';
            } 
 
            
        list<CaseRecordType__c> scList ;            
            
                    scList =  [SELECT Id,
                                                 Primary_Category__c,
                                                 Secondary_Category__c,
                                                 Teritiary_Category__c,
                                                 Record_Type_Name__c,
                                                 RecordTypeId__c FROM CaseRecordType__c WHERE Primary_Category__c =:pcValue AND Secondary_Category__c=:scValue
                                                                                                                            AND Teritiary_Category__c=:tcValue LIMIT 1];
                
        AssignmentRule AR = new AssignmentRule(); 
        AR = [SELECT Id FROM AssignmentRule WHERE SobjectType = 'Case' AND Active = True LIMIT 1];
            
        Database.DMLOptions dmlOpts = new Database.DMLOptions(); 
                dmlOpts.assignmentRuleHeader.assignmentRuleId= AR.id;   
       
        Case cs = new case();
            cs.setOptions(dmlOpts);
            for(CaseRecordType__c crt : scList){
            cs.RecordTypeId = scList[0].RecordTypeId__c;
            cs.Primary_Category__c = scList[0].Primary_Category__c;
            cs.Secondary_Category__c = scList[0].Secondary_Category__c;
            cs.Tertiary_Category__c = scList[0].Teritiary_Category__c; }
           // cs.Brand__c = cRec.Brand__c;
            cs.Brand__c = 'CFCU';
          //  cs.Account_Number__c = cRec.Account_Number__c;
          //  cs.AccountId = cRec.AccountId;
            cs.Status = cRec.Status;
            cs.Description = cRec.Description;
            cs.Subject = cRec.Subject;
            cs.LTK__c = cRec.LTK__c;
            cs.CaseComments__c = cRec.CaseComments__c;
            cs.Ownership__c = cRec.Ownership__c;
            if(cs.Ownership__c == 'Assign'){
            cs.OwnerId = cRec.OwnerId;
            }        
       cs.Future_Date__c = cRec.Future_Date__c;
         try{ 
           insert cs;
           if(Test.isRunningTest()){
               Integer x=1/0;
            }
           }catch (exception e)  { 
              
           ApexPages.Message msgs = new ApexPages.Message(ApexPages.Severity.ERROR, 'Please select appropriate values for all the fields.');
           ApexPages.addMessage(msgs); 
          }
            
            if(cs.CaseComments__c != null){
            CaseComment cc = new CaseComment();
              cc.ParentId = cs.Id;
              cc.CommentBody = cs.CaseComments__c;
                          
              
            insert cc;
            }
                 
        list<Case> co = [select Id from Case order by CreatedDate desc limit 1];  
        PageReference pg = new PageReference('/'+co[0].Id);
        pg.setRedirect(true);
        return pg;
       }        
     }
    
     public pageReference process(){
                 
            Attachment a = new Attachment();
              if(file != null){ 
                a.Name= fileName;
                a.Body= file;
                a.ParentId= caseId;
                //a.CreatedById = UserInfo.getUserId();          
            insert a;
           }
            file = null;                  
                     
        PageReference pg = new PageReference('/'+caseId);
        pg.setRedirect(true);
        return pg;            
    }
   }