src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Number</label>
        <referenceTo>Account_Details__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Device_Type__c</fullName>
        <label>Device Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsMarkRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsMarkRead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LTK__c</fullName>
        <label>Ticket #</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Member_Comment__c.object
<CustomObject>
    <description>Comments intended to be visible to the member</description>
    <fields>
        <fullName>Brand__c</fullName>
        <formula>Case__r.BrandfromAccount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Creator_Email__c</fullName>
        <label>Case Creator Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Member Comments</relationshipLabel>
        <relationshipName>Member_Comments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Device_Type__c</fullName>
        <label>Device Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsMarkRead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to capture if the member has read the comment</description>
        <label>Member Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Member Read</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Comment__c</fullName>
        <label>Member Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Member_Communication__c</fullName>
        <label>Member Communication</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Member_Email__c</fullName>
        <label>Secure Email Address</label>
        <type>Email</type>
    </fields>
    <label>Member Comment</label>
    <nameField>
        <displayFormat>MCOM{000000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CloneController.cls
public class CloneController{
    public string Id {get;set;}
    public boolean Description {get;set;}
    public boolean LTK {get;set;}
    public boolean Status {get;set;}
    public boolean Device_Type {get;set;}
    public boolean Subject  {get;set;}
    public boolean Category  {get;set;}
    public boolean MemberComment {get;set;}
    public boolean CaseComment {get;set;}
    public boolean Attachment {get;set;}
                
   public CloneController(ApexPages.StandardController controller){
        Subject   = false;
        Description = false;
        LTK = false;
        Status = false;
        Device_Type = false;
        Category = false;
        MemberComment = false;
        CaseComment = false;
        Attachment = false;
        ID = ApexPages.currentPage().getParameters().get('id');

    }
    

public pagereference CloneCase() {


      List<case> listc = [select Subject,Description,OwnerID,Status,LTK__c,Device_Type__c,
                                 AccountID,Account_Number__c,Brand__c, 
                                 Primary_Category__c,Tertiary_Category__c,Secondary_Category__c 
                            from Case 
                           where ID = :Id];
      
      Case c = new Case();
      
      c.AccountID = listc[0].AccountID;
      c.OwnerID= listc[0].OwnerID;
      C.Brand__c = listc[0].Brand__c;
      c.Account_Number__c = listc[0].Account_Number__c;
      if(subject)
      {
          c.Subject = listc[0].Subject;
      }
      if(Description )
      {
          c.Description= listc[0].Description;
      }      
      if(Status)
      {
          c.Status= listc[0].Status;
      }
      if(LTK)
      {
          c.LTK__c= listc[0].LTK__c;
      }
      if(Device_Type)
      {
          c.Device_Type__c = listc[0].Device_Type__c;
      }
      if(Category)
      {
          c.Primary_Category__c= listc[0].Primary_Category__c;
          c.Secondary_Category__c= listc[0].Secondary_Category__c;
          c.Tertiary_Category__c= listc[0].Tertiary_Category__c;
      }
      
      

      insert c;
      if(MemberComment )
      {
          List<Member_Comment__c> listComment = [
          select Draft__c,Case_Creator_Email__c,Device_Type__c,IsRead__c,Status__c,Member_Comment__c,
                 Member_Communication__c,Member_Email__c,IsMarkRead__c 
            from Member_Comment__c 
           where Case__c= :Id];

            for (Member_Comment__c i : listComment ) {
                 Member_Comment__c obj = new Member_Comment__c();
                obj.Case__c = c.Id;
                obj.Case_Creator_Email__c = i.Case_Creator_Email__c;
                obj.Status__c = i.Status__c;
                obj.Member_Comment__c= i.Member_Comment__c;
                obj.Member_Communication__c= i.Member_Communication__c;
                obj.Member_Email__c= i.Member_Email__c;
                obj.IsMarkRead__c = i.IsMarkRead__c ;
                obj.Device_Type__c = i.Device_Type__c;
                obj.IsRead__c = i.IsRead__c;
                obj.Draft__c = i.Draft__c;
                insert obj;
                 CopyAttachment(i.Id, obj.Id);
            }

        }
        if(CaseComment)
        {
            List<CaseComment> listCaseComment =         [Select Id, ParentId, IsPublished, CommentBody, CreatedById, CreatedDate, SystemModstamp, LastModifiedDate, LastModifiedById, IsDeleted From CaseComment where ParentId = :Id and IsDeleted = false];

              for (CaseComment l : listCaseComment ) {
                 CaseComment com = new CaseComment ();
                 com.ParentId = c.Id;
                 com.IsPublished = l.IsPublished;
                 com.CommentBody= l.CommentBody;
    
    
                       insert com;
                 
                   CopyAttachment(l.Id, com.Id);
                 
              }

             
        }
        
        if(Attachment)
        {
           CopyAttachment(Id, c.Id);
        }

        
        
      

//      String baseUrl = System.URL.getSalesforceBaseUrl().toExternalForm() + "/" +  c.Id;
      pagereference redirect = new PageReference('/'  + c.id);
      redirect.setRedirect(true);

     return redirect;
    }
    
    public void CopyAttachment(string Old_Id, string New_Id)
    {
         List<Attachment> listAttachment =  new          List<Attachment>();
       listAttachment = [SELECT   Id,Name,Body,ContentType,Description,OwnerId,ParentId FROM Attachment where ParentId = :Old_Id];
        List<Attachment> listAttachmentNew = new List<Attachment>();
      

      
        for (Attachment a : listAttachment ) {
             Attachment att = new Attachment();
             att.ParentId = New_Id;
             att.Body= a.Body;
             att.ContentType= a.ContentType;
             att.Description= a.Description;
             att.OwnerId = a.OwnerId;

             att.Name = a.Name;
         

             listAttachmentNew.add(att);
          }

        insert listAttachmentNew ;
    }
}