src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Branch__c</fullName>
        <label>Assigned Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Episys_Name__c</fullName>
        <label>Episys Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Episys_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used with the &quot;LeadTrigger2 - Episys User ID&quot; trigger to bulk update existing records</description>
        <label>Episys Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Episys_User_ID__c</fullName>
        <label>Episys User ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Episys_User__c</fullName>
        <formula>CreatedBy.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Episys User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Event_Source__c</fullName>
        <label>Event Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event – Oakland City Center Meet and Greet 12/06/17</fullName>
                </value>
                <value>
                    <fullName>Event – San Francisco Plaza Event 11/30/17</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Contractor Safety Meeting-12/07/17</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Brock New Hire Orientation-01/05/18</fullName>
                </value>
                <value>
                    <fullName>Event-Richmond-Pinole Valley Juniors Fundraiser-01/07/18</fullName>
                </value>
                <value>
                    <fullName>Event-El Paso-Contractor Visit-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-1600 Smith Houston-Lunch and Learn-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Chevron Retiree Luncheon-01/23/18</fullName>
                </value>
                <value>
                    <fullName>Event-Post Oak Houston-Briarpark Atrium Event-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-El Paso-Lobby Event-02/02/18</fullName>
                </value>
                <value>
                    <fullName>Event-Post Oak Houston-Stewart Legacy Event-01/25/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Meet and Greet-01/30/18</fullName>
                </value>
                <value>
                    <fullName>Event-Reston-Open House-01/31/18</fullName>
                </value>
                <value>
                    <fullName>Event-Houston Galleria-Lobby Event-02/07/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Contractor New Hire Orientation-01/19/18</fullName>
                </value>
                <value>
                    <fullName>Event-Covington-Meet and Greet-01/31/18</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>I_m_interested_in__c</fullName>
        <label>I&apos;m interested in</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Keep__c</fullName>
        <defaultValue>false</defaultValue>
        <description>By pass auto assignment rules and keep ownership of the Lead</description>
        <inlineHelpText>Keep ownership of the Lead and do not allow the assignment rules to route it to a group&apos;s queue.</inlineHelpText>
        <label>Keep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_Required_old__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership Required Old</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Sub Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Not Interested</fullName>
                </value>
                <value>
                    <fullName>No Product Available</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>No Prospect/Mbr Deciding</fullName>
                </value>
                <value>
                    <fullName>App Online</fullName>
                </value>
                <value>
                    <fullName>App Completed</fullName>
                </value>
                <value>
                    <fullName>Follow Up Required</fullName>
                </value>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Poor Referral</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Appointment Set Branch</fullName>
                </value>
                <value>
                    <fullName>Appointment Set Phone</fullName>
                </value>
                <value>
                    <fullName>Additional Follow-up Required</fullName>
                </value>
                <value>
                    <fullName>Contact Attempted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>et4ae5__HasOptedOutOfMobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>smagicinteract__SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>temp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>temp</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>false</active>
        <businessProcess>Default</businessProcess>
        <description>record type for all the Branch Users</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/main/default/classes/LeadBusinessHoursTest.cls
@istest
public with sharing class LeadBusinessHoursTest {
	@istest
    static void testMethod1(){
        RecordType recTpe = [Select Id, Name from RecordType where Name='Brand Details' Limit 1];
        Group g1 = new Group(Name='Branch 14 - 1600 Smith Queue', type='Queue');
        insert g1;
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, 
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                temp__c = false, Episys_User_ID__c= 1,LeadSource = 'Other', Product_Type__c ='Cards',
                                Brand__c ='Chevron');
       insert newlead;
        
       newlead.Brand__c = 'Spectrum';
       update newlead;
    }
    @istest
    static void testMethod2(){
        RecordType recTpe = [Select Id, Name from RecordType where Name='Brand Details' Limit 1];
        Group g1 = new Group(Name='Branch 14 - 1600 Smith Queue', type='Queue');
        insert g1;
        
        string uid = UserInfo.getUserId();
        User usr = [Select id, name, alias
                    from User
                    where id = :uid];
        
        Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'test';
        eu.Assigned_Branch__c =14;
        eu.alias__c = usr.alias;
        eu.Default__c = true;
        insert eu;
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                I_m_interested_in__c = 'Xpress Form - Web',temp__c = false, Episys_User_ID__c= 1,
                                LeadSource = 'Xpress Form - Web', Product_Type__c ='Cards',
                                Brand__c ='Chevron');
       insert newlead;
        
       newlead.Brand__c = 'Spectrum';
       update newlead;
    }
    @istest
    static void testMethod3(){
        RecordType recType = [Select Id, Name from RecordType where Name='Company Lead' and sObjectType='Lead' Limit 1];
        Group g1 = new Group(Name='Branch 14 - 1600 Smith Queue', type='Queue');
        insert g1;
        
        Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'test';
        eu.Assigned_Branch__c =14;
        insert eu;
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false,recordtypeid = recType.id,                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                I_m_interested_in__c = 'Xpress Form - Web',temp__c = false, Episys_User_ID__c= 1,
                                LeadSource = 'Xpress Form - Web', Product_Type__c ='Cards',
                                Brand__c ='Chevron');
       insert newlead;
        
       newlead.Status = 'Outreach';
       newlead.Sub_Status__c ='No Response'; 
       update newlead;
    }
    
    @istest
    static void testMethod4(){
        RecordType recType = [Select Id, Name from RecordType where Name='Company Lead' and sObjectType='Lead' Limit 1];
        Group g1 = new Group(Name='Branch 14 - 1600 Smith Queue', type='Queue');
        insert g1;
        
        Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'test';
        eu.Assigned_Branch__c =14;
        insert eu;
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false,
                                recordtypeid = recType.id,                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                I_m_interested_in__c = 'Xpress Form - Web',temp__c = false, Episys_User_ID__c= 1,
                                LeadSource = 'Refer a Member - Web', Product_Type__c ='Cards',
                                Brand__c ='Chevron', Referring_Member_Email__c = 'Leadtest@test.com',
                                Referring_Member_FirstName__c = 'testFN', Referring_Member_LastName__c = 'testLN');
        
       insert newlead;
       Account matchingAccounts = new Account(FirstName = 'testFN', LastName = 'testLN', PersonEmail='Leadtest@test.com');
       insert matchingAccounts;                                                        
       
    }
    @istest
    static void testMethod5(){
        RecordType recTpe = [Select Id, Name from RecordType where Name='Brand Details' Limit 1];
        Group g1 = new Group(Name='Branch 14 - 1600 Smith Queue', type='Queue');
        insert g1;
        
        string uid = UserInfo.getUserId();
        User usr = [Select id, name, alias
                    from User
                    where id = :uid];
        
        Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'test';
        eu.Assigned_Branch__c =14;
        eu.alias__c = usr.alias;
        eu.Default__c = true;
        insert eu;
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                I_m_interested_in__c = 'Xpress Form - Web',temp__c = false, 
                                LeadSource = 'Xpress Form - Web', Product_Type__c ='Cards',
                                Brand__c ='Chevron');
       insert newlead;
        
       
    }
    @istest
    static void testMethod6(){
        RecordType recTpe = [Select Id, Name from RecordType where Name='Company Lead' Limit 1];
        Group g1 = new Group(Name='Branch 14 - 1600 Smith Queue', type='Queue');
        insert g1;
        
        string uid = UserInfo.getUserId();
        User usr = [Select id, name, alias
                    from User
                    where id = :uid];
        
        Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'test';
        eu.Assigned_Branch__c =14;
        eu.alias__c = usr.alias; 
        eu.Default__c = true;
        insert eu;
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Xpress Form - Web',temp__c = false, 
                                LeadSource = 'Event', Product_Type__c ='Cards',
                                Brand__c ='Chevron', Event_Source__c ='Advantage Credit');
       insert newlead;
        
       
    }
    @istest
    static void testMethod7(){
        RecordType recTpe = [Select Id, Name from RecordType where Name='Company Lead' Limit 1];
        Group g1 = new Group(Name='Real Estate', type='Queue');
        insert g1;
        
        string uid = UserInfo.getUserId();
        User usr = [Select id, name, alias
                    from User
                    where id = :uid];
        
        Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'test';
        eu.Assigned_Branch__c =14;
        eu.alias__c = usr.alias; 
        eu.Default__c = true;
        insert eu;
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Home Loan Help Desk',temp__c = false, 
                                LeadSource = 'Real Estate help desk', Product_Type__c ='Cards',
                                Brand__c ='Chevron');
       insert newlead;
       Datetime dt = LeadTriggerService.getTimeStampFieldValue('New', newlead );
       boolean flag = LeadTriggerService.getOtherFieldsAreNull('New', newlead );
        LeadTriggerService.updateTimeStampOnOpp('New',newlead, 2.00, true);
       LeadTriggerService.updateTimeStampOnOpp('New',newlead, 2.00, false); 
    }
     @istest
    static void LeadOutreachTest(){
        
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'Outreach', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Home Loan Help Desk',temp__c = false, Sub_Status__c ='No Response',
                                LeadSource = 'Real Estate help desk', Product_Type__c ='Cards',
                                Brand__c ='Chevron');
       insert newlead;
       Datetime dt = LeadTriggerService.getTimeStampFieldValue('Outreach', newlead );
       boolean flag = LeadTriggerService.getOtherFieldsAreNull('Outreach', newlead );
       LeadTriggerService.updateTimeStampOnOpp('Outreach',newlead, 2.00, true);
       LeadTriggerService.updateTimeStampOnOpp('Outreach',newlead, 2.00, false); 
    }
    @istest
    static void LeadConsideringTest(){
        
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'Considering', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Home Loan Help Desk',temp__c = false, 
                                LeadSource = 'Real Estate help desk', Product_Type__c ='Cards',
                                Brand__c ='Chevron');
       insert newlead;
       Datetime dt = LeadTriggerService.getTimeStampFieldValue('Considering', newlead );
	   boolean flag = LeadTriggerService.getOtherFieldsAreNull('Considering', newlead );	
       LeadTriggerService.updateTimeStampOnOpp('Considering',newlead, 2.00, true);
       LeadTriggerService.updateTimeStampOnOpp('Considering',newlead, 2.00, false); 
    }
    @istest
    static void LeadAnalyzingNeedsTest(){
        
        
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'Analyzing Needs', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Home Loan Help Desk',temp__c = false, 
                                LeadSource = 'Real Estate help desk', Product_Type__c ='Cards',
                                Brand__c ='Chevron',Product_Amount__c = 2.00);
       insert newlead;
       Datetime dt = LeadTriggerService.getTimeStampFieldValue('Analyzing Needs', newlead );
       boolean flag = LeadTriggerService.getOtherFieldsAreNull('Analyzing Needs', newlead );	
       LeadTriggerService.updateTimeStampOnOpp('Analyzing Needs',newlead, 2.00, true);
       LeadTriggerService.updateTimeStampOnOpp('Analyzing Needs',newlead, 2.00, false);  
    }
    
    @istest
    static void getTimeDifferenceTest(){
        LeadTriggerService.getTimeDifference(Datetime.now());
    }
   
    @istest
    static void slaLeadTest(){
        List<Lead> leadInsertList = new List<Lead>();
        Map<String, Sla_Manager__mdt> slaManagerMap = Sla_Manager__mdt.getAll();
        for(string key: slaManagerMap.keySet()){
            if(slaManagerMap.get(key).Object_Name__c == 'Lead'){
                Lead l = new Lead();
                l.LastName = 'Test';
                l.Status = slaManagerMap.get(key).StageName__c;
                if(slaManagerMap.get(key).StageName__c =='Outreach'){
                    l.Sub_Status__c ='No Response';
                }
                l.Product_Amount__c =2.00;
                if(slaManagerMap.get(key).Event_Source__c != null && slaManagerMap.get(key).Event_Source__c!= ''){
                	l.Event_Source__c = slaManagerMap.get(key).Event_Source__c;
                }else{
                    l.Event_Source__c ='Advantage Credit';
                }
                String[] source = slaManagerMap.get(key).Opportunity_Source__c.split(',');
                l.LeadSource =source[0];
                if(slaManagerMap.get(key).Product_Type__c != null && slaManagerMap.get(key).Product_Type__c != ''){
                l.Product_Type__c = slaManagerMap.get(key).Product_Type__c;
                }else{
                    l.Product_Type__c = 'Cards';
                }
                leadInsertList.add(l);
                
        	}
            
        }
        insert leadInsertList;
        List<Lead> updateLeadList = new List<Lead>();
        for(Lead l : leadInsertList ){
            if(l.Status == 'New'){
                l.Status = 'Outreach';
                l.Sub_Status__c ='No Response';
            }
            else if(l.Status =='Outreach')
            {
                l.Status = 'New';
            }
            else if(l.Status =='Considering'){
                l.Status = 'Analyzing Needs';
            }
            else if(l.Status == 'Analyzing Needs'){
                l.Status = 'Considering'; 
            }
            else{l.Status = 'New'; }
            updateLeadList.add(l);
        }
        update updateLeadList;
    }
     @istest
    static void slaLeadTest2(){
        List<Lead> leadInsertList = new List<Lead>();
        Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Home Loan Help Desk',temp__c = false, 
                                LeadSource = 'Real Estate help desk', Product_Type__c ='Cards',
                                Brand__c ='Chevron', sla__c= 2.00,Product_Amount__c = 2.00);
       Lead newlead1 = new Lead(LastName = 'LastName268', Status = 'Outreach', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Home Loan Help Desk',temp__c = false, Sub_Status__c ='No Response',
                                LeadSource = 'Real Estate help desk', Product_Type__c ='Cards',
                                Brand__c ='Chevron', sla__c= 3.00,Product_Amount__c = 2.00);
        Lead newlead2 = new Lead(LastName = 'LastName268', Status = 'Considering', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Home Loan Help Desk',temp__c = false, 
                                LeadSource = 'Real Estate help desk', Product_Type__c ='Cards',
                                Brand__c ='Chevron' , sla__c= 3.00, Product_Amount__c = 2.00);
        Lead newlead3 = new Lead(LastName = 'LastName268', Status = 'Analyzing Needs', HasOptedOutOfEmail = false, 
                                
                                IsConverted = false, IsUnreadByOwner = false, smagicinteract__SMSOptOut__c = false,
                                Escalated__c = false, Membership_Required_old__c = false, Keep__c = false,
                                et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,Episys_User_ID__c= 1,
                                I_m_interested_in__c = 'Home Loan Help Desk',temp__c = false, 
                                LeadSource = 'Real Estate help desk', Product_Type__c ='Cards',
                                Brand__c ='Chevron',Product_Amount__c = 2.00 , sla__c= 3.00);
       leadInsertList.add(newlead);
       leadInsertList.add(newlead1);
       leadInsertList.add(newlead2);
       leadInsertList.add(newlead3);
       insert leadInsertList;
        List<Lead> updateLeadList = new List<Lead>();
        for(Lead l : leadInsertList ){
            if(l.Status == 'New'){
                l.Status = 'Outreach';
                l.Sub_Status__c ='No Response';
            }
            else if(l.Status =='Outreach')
            {
                l.Status = 'New';
            }
            else if(l.Status =='Considering'){
                l.Status = 'Analyzing Needs';
            }
            else if(l.Status == 'Analyzing Needs'){
                l.Status = 'Considering'; 
            }
            else{l.Status = 'New'; }
            updateLeadList.add(l);
        }
        update updateLeadList;
    }
}