src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CaseComments__c</fullName>
        <label>CaseComments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CaseRecordType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Case Record Type based on Categories</description>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>RecordTypeId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Teritiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>CaseRecordType</label>
</CustomObject>

src/classes/SetRecordTypeStandAloneCaseCtrlTest.cls
@isTest
public class SetRecordTypeStandAloneCaseCtrlTest {

    static testmethod void testmethod1(){

        RecordType recTpe = [Select Id, Name from RecordType where SobjectType='Case' AND Name = 'Account Servicing' Limit 1];
  
        CaseRecordType__c crt = new CaseRecordType__c();
        crt.RecordTypeId__c = recTpe.Id;
        crt.Primary_Category__c = 'test1';
        crt.Secondary_Category__c = 'test2';
        crt.Teritiary_Category__c = 'test3';
        crt.Name = '000';
        insert crt; 
      test.startTest();
        Case cRec = new Case();
           cRec.Brand__c = 'CFCU';
           cRec.CaseComments__c = 'test comments';
        insert cRec;
        
        CaseComment cc = new CaseComment();
           cc.ParentId = cRec.Id;
        insert cc;
        
        PageReference pageRef = Page.SetRecordTypeStandAloneCase;
        Test.setCurrentPage(pageRef);      
        SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec)); 

        //controller.pcOptions();
        //controller.pcValue = 'test1';
//        controller.scOptions();
       // controller.scValue = 'test2';
       // controller.tcOptions();
       // controller.tcValue = 'test3';
       // controller.change();
       // controller.nextPage();
         
        Attachment attach=new Attachment();    
        attach.Name='Unit Test Attachment';
        Blob file = Blob.valueOf('Unit Test Attachment Body');
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attach.body=bodyBlob;
        attach.parentId= cRec.id;
        insert attach;
        controller.process();
        test.stopTest();
    }
   
    
  /*  static testmethod void testmethod2(){
        
        Case cRec = new Case();
        
        PageReference pageRef = Page.SetRecordTypeStandAloneCase;
        Test.setCurrentPage(pageRef);     
        SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec));       

        controller.pcValue = 'test1';
       
        controller.scOptions();        
        controller.process1();
        System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Secondary Category') ;
    }
    */
   /* static testMethod void testMethod3(){

       Case cRec = new Case();
       
       PageReference pageRef = Page.SetRecordTypeStandAloneCase;
       Test.setCurrentPage(pageRef);       
       SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec)); 

       controller.pcValue = 'test1';
       controller.scOptions();
       controller.scValue = 'test2';
       controller.tcOptions();
       controller.process1();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Tertiary Category');
    } */
    
   /* static testMethod void testMethod4(){

       Case cRec = new Case();
       
       PageReference pageRef = Page.SetRecordTypeStandAloneCase;
       Test.setCurrentPage(pageRef);        
       SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec));       

       controller.pcOptions();
       controller.process1();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Primary Category');        
    } 
    */
    static testmethod void testmethod6(){

        Case cRec = new Case();
        
        PageReference pageRef = Page.SetRecordTypeStandAloneCase;
        Test.setCurrentPage(pageRef);       
        SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec));        

        controller.pcValue = 'test1';
        controller.scOptions();        
        controller.nextPage();
        System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Secondary Category') ;
    }
    
     static testMethod void testMethod8(){

       Case cRec = new Case();
       
       PageReference pageRef = Page.SetRecordTypeStandAloneCase;
       Test.setCurrentPage(pageRef);        
       SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec));         

       controller.pcOptions();
       controller.nextPage();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Primary Category');      
    }
    
    static testMethod void testMethod9(){

       Case cRec = new Case();
              
       PageReference pageRef = Page.SetRecordTypeStandAloneCase;
       Test.setCurrentPage(pageRef);       
       SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec)); 
        
       controller.pcValue = 'test1';
       controller.scOptions();
       controller.scValue = 'test2';
       controller.tcOptions();
       controller.nextPage();
       System.assertEquals(ApexPages.getMessages()[0].getSummary(), 'Please select Tertiary Category');
    } 
    
    static testmethod void testmethod10(){

        List<RecordType> recTpe = [Select Id, Name from RecordType where SobjectType='Case' AND Name = 'Account Servicing'];
        if(recTpe.size()>0){
        CaseRecordType__c crt = new CaseRecordType__c();
        crt.RecordTypeId__c = recTpe[0].Id;
        crt.Primary_Category__c = 'test1';
        crt.Secondary_Category__c = 'test2';
        crt.Teritiary_Category__c = 'test3';
        crt.Name = '000';
        insert crt; 
        }
        test.startTest();
        Case cRec = new Case();
           cRec.Brand__c = 'CFCU';
           cRec.CaseComments__c = 'test comments';
        insert cRec;
        
        CaseComment cc = new CaseComment();
           cc.ParentId = cRec.Id;
        insert cc;
        
        PageReference pageRef = Page.SetRecordTypeStandAloneCase;
        Test.setCurrentPage(pageRef);     
        SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec));  
      
        controller.pcOptions();
        controller.pcValue = 'test1';
        controller.scOptions();
        controller.scValue = 'test2';
        controller.tcOptions();
        controller.tcValue = 'test3';
        //controller.process1();
        
        controller.pcOptions();
        controller.pcValue = '-None-';
        controller.scOptions();
        controller.scValue = '-None-';
        controller.tcOptions();
        controller.tcValue = '-None-';
        controller.process1();
        test.stopTest();
    }
    
    static testMethod void testMethod11(){

        RecordType recTpe = [Select Id, Name from RecordType where SobjectType='Case' AND Name = 'Account Servicing' Limit 1];
 
        CaseRecordType__c crt = new CaseRecordType__c();
        crt.RecordTypeId__c = recTpe.Id;
        crt.Primary_Category__c = 'test1';
        crt.Secondary_Category__c = 'test2';
        crt.Teritiary_Category__c = 'test3';
        crt.Name = '000';
        insert crt; 
        
        Case cRec = new Case();
        
        PageReference pageRef = Page.SetRecordTypeStandAloneCase;
        Test.setCurrentPage(pageRef);      
        SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(cRec)); 
        
        controller.doCancel();
    }
    
    static testMethod void testMethod12(){
        
        Case c = new Case();
           c.Brand__c = 'CFCU';
        insert c;

        PageReference pageRef = Page.InputFilePage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('caseId', c.Id); 
        SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(c));
    }
    
    static testMethod void TestMethodSearchTertiary()
    {
    	Case c = new Case();
        c.Brand__c = 'CFCU';
        insert c;
    	SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(c));
    	controller.SearchTertiary();
    	
    
    }
    
    static testMethod void TestMethodChangeCategories()
    {
    	 RecordType recTpe = [Select Id, Name from RecordType where SobjectType='Case' AND Name = 'Account Servicing' Limit 1];
 
        CaseRecordType__c crt = new CaseRecordType__c();
        crt.RecordTypeId__c = recTpe.Id;
        crt.Primary_Category__c = 'test1';
        crt.Secondary_Category__c = 'test2';
        crt.Teritiary_Category__c = 'test3';
        crt.Name = '000';
        insert crt; 
    	Case c = new Case();
        c.Brand__c = 'CFCU';
        insert c;
    	SetRecordTypeStandAloneCaseController controller = new SetRecordTypeStandAloneCaseController(new ApexPages.StandardController(c));
    	controller.pcOptions();
        controller.pcValue = 'test1';
        controller.scOptions();
        controller.scValue = 'test2';
        controller.tcOptions();
        controller.tcValue = 'test3';
        controller.change();
        controller.nextPage();
        controller.process1();
    	//controller.ChangeCategories();
    
    }
}