src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Source__c</fullName>
        <label>Event Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Event – Oakland City Center Meet and Greet 12/06/17</fullName>
                </value>
                <value>
                    <fullName>Event – San Francisco Plaza Event 11/30/17</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Contractor Safety Meeting-12/07/17</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Brock New Hire Orientation-01/05/18</fullName>
                </value>
                <value>
                    <fullName>Event-Richmond-Pinole Valley Juniors Fundraiser-01/07/18</fullName>
                </value>
                <value>
                    <fullName>Event-El Paso-Contractor Visit-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-1600 Smith Houston-Lunch and Learn-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Chevron Retiree Luncheon-01/23/18</fullName>
                </value>
                <value>
                    <fullName>Event-Post Oak Houston-Briarpark Atrium Event-01/24/18</fullName>
                </value>
                <value>
                    <fullName>Event-El Paso-Lobby Event-02/02/18</fullName>
                </value>
                <value>
                    <fullName>Event-Post Oak Houston-Stewart Legacy Event-01/25/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Meet and Greet-01/30/18</fullName>
                </value>
                <value>
                    <fullName>Event-Reston-Open House-01/31/18</fullName>
                </value>
                <value>
                    <fullName>Event-Houston Galleria-Lobby Event-02/07/18</fullName>
                </value>
                <value>
                    <fullName>Event-Pascagoula-Contractor New Hire Orientation-01/19/18</fullName>
                </value>
                <value>
                    <fullName>Event-Covington-Meet and Greet-01/31/18</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>How_did_you_hear_about_us__c</fullName>
        <label>How did you hear about us?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yahoo Ad</fullName>
                </value>
                <value>
                    <fullName>Google Ad</fullName>
                </value>
                <value>
                    <fullName>LinkedIn</fullName>
                </value>
                <value>
                    <fullName>Facebook</fullName>
                </value>
                <value>
                    <fullName>Twitter</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Subtype__c</fullName>
        <label>Product Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Mortgage</fullName>
                </value>
                <value>
                    <fullName>2nd Mortgage</fullName>
                </value>
                <value>
                    <fullName>90 Day Note-Unsecured</fullName>
                </value>
                <value>
                    <fullName>ARM 1/1</fullName>
                </value>
                <value>
                    <fullName>ARM 10/1</fullName>
                </value>
                <value>
                    <fullName>ARM 3/1</fullName>
                </value>
                <value>
                    <fullName>ARM 3/3</fullName>
                </value>
                <value>
                    <fullName>ARM 5/1</fullName>
                </value>
                <value>
                    <fullName>ARM 5/5</fullName>
                </value>
                <value>
                    <fullName>ARM 7/1</fullName>
                </value>
                <value>
                    <fullName>ATM Card</fullName>
                </value>
                <value>
                    <fullName>Auto - Liberty</fullName>
                </value>
                <value>
                    <fullName>Auto - New</fullName>
                </value>
                <value>
                    <fullName>Auto Refinance</fullName>
                </value>
                <value>
                    <fullName>Auto -Used</fullName>
                </value>
                <value>
                    <fullName>Balance Transfer</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Bridging</fullName>
                </value>
                <value>
                    <fullName>Business Development SEG</fullName>
                </value>
                <value>
                    <fullName>CFCU Company Guaranteed</fullName>
                </value>
                <value>
                    <fullName>CFCU Disaster Assistance-Level 3</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Credit Card in Repayment</fullName>
                </value>
                <value>
                    <fullName>Credit Cards</fullName>
                </value>
                <value>
                    <fullName>Credit Protection</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Debt Consolidation</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>DPA Interest Only HELOC</fullName>
                </value>
                <value>
                    <fullName>DPA Texan HELOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/main/default/classes/ConvertLeadControllerTest.cls
@isTest 
private class ConvertLeadControllerTest{
   
  static testmethod void setupTestData(){
      
      Amount_On_Lead_Opportunity__c mcs = new Amount_On_Lead_Opportunity__c();
      RecordType rec1 = [Select Name, Id From RecordType where sObjectType='Account' and isActive=true and Name='Pre Member'];      
      
      mcs.Amount__c = 264000.00;
      mcs.Product_Sub_Type__c = 'Purchase';
      mcs.Product_Type__c = 'Mortgage';
      mcs.Name = 'Mortgage-Purchase';
      insert mcs;

      
      
      Lead ld = new Lead ();
      ld.LastName = 'Test';
      ld.Email = 'test@gmail.com';
      ld.Product_Type__c = 'Misc';
      ld.Brand__c = 'Chevron';
      ld.FirstName = 'test';
      ld.LastName = 'New';    
      ld.MiddleName = 'New';
      ld.Description = 'New';
      ld.Salutation = 'MR.';
      ld.Suffix = 'MR'; 
      ld.Status = 'New';
      ld.Phone= '1234567890';
      ld.Email='test@test.com';
      ld.MobilePhone='1234567892';
      ld.How_did_you_hear_about_us__c='Website';
      ld.Event_Source__c='Event-Reston-Open House-04/20/18';
      ld.LeadSource='BDO-Realtor Referral';
      ld.Product_Type__c ='Mortgage';
      ld.Product_Subtype__c='Purchase';
      ld.Street_Address_1__c='Address 1';
      ld.State__c= 'NY';
      ld.Zip_Code__c= '12345';
      ld.City__c='NYC';
      ld.Country__c ='USA';    
      insert ld;
 		
      Account pact = new Account();
      pact.FirstName = 'Test';
      pact.LastName = 'Test1';
      pact.PersonEmail = 'test@test.com';
      pact.RecordtypeId = rec1.Id;
      pact.Residential_Street__pc ='11';
      pact.Home_Phone__pc ='011-11111';
      insert pact;
      opportunity opp = new Opportunity();
      opp.Accountid = pact.id;
      opp.Name = 'Name';
      opp.StageName = 'Closed Won';
      opp.CloseDate = system.today();
      opp.Is_Converted__c = true;
      opp.DESCRIPTION = 'DESCRIPTION';
      opp.Opportunity_Source__c = 'Campaign Outreach';
      
      insert opp;
      
      ContentVersion content=new ContentVersion(); 
      content.Title='Header_Picture1'; 
      content.PathOnClient='/' + content.Title + '.jpg'; 
      Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
      content.VersionData=bodyBlob; 
      //content.LinkedEntityId=sub.id;
      content.origin = 'H';
      insert content;
      
      ContentDocumentLink contentlink=new ContentDocumentLink();
      contentlink.LinkedEntityId=ld.id;
      contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
      contentlink.ShareType = 'V';
      test.starttest();
      insert contentlink;
      
      Note testNote = new Note();
      testNote.Title = 'Test Account Note';
      testNote.Body = 'Test Account Note Body.';
      testNote.ParentId = ld.Id;
      
      insert testNote;
 	
      Event e = new Event();
      e.WhoId = ld.id;
      e.StartDateTime = system.today();
      e.EndDateTime = system.today()+5;
      insert e;
      
      Task t = new Task();
      t.WhoId = ld.id;
      insert t;
      
      //ConvertLeadController clc = new ConvertLeadController();
      ConvertLeadController.ConvertLead(ld.id);
      ConvertLeadController.Baseurl();
      ConvertLeadController.AttachActivity(opp, ld);  
    
  }
}