src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ShowMessageForSecureEmailTest.cls
@isTest
public class ShowMessageForSecureEmailTest{

    @IsTest 
  
       public static void UnitTest()
      {
           Case cs = new Case();
              cs.Brand__c = 'CFCU';
              cs.SecureEmail__c ='';
            insert cs;
            
            Case cs1 = new Case();
              cs1.Brand__c = 'CFCU';
              cs1.SecureEmail__c ='test@test.com';
            insert cs1;
            
            ShowMessageForSecureEmail scs = new ShowMessageForSecureEmail(new ApexPages.StandardController(cs));
            
      }
 }