src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Category__c</fullName>
        <label>Primary Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Asset Recovery</fullName>
                </value>
                <value>
                    <fullName>Card Services</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Disaster Relief</fullName>
                </value>
                <value>
                    <fullName>Hurricane Harvey Relief</fullName>
                </value>
                <value>
                    <fullName>Inquiries</fullName>
                </value>
                <value>
                    <fullName>Lending</fullName>
                </value>
                <value>
                    <fullName>Loan Servicing</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Mobile Banking</fullName>
                </value>
                <value>
                    <fullName>Online Banking</fullName>
                </value>
                <value>
                    <fullName>Shared Branching</fullName>
                </value>
                <value>
                    <fullName>Vehicle Titling</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Category__c</fullName>
        <label>Secondary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Primary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A|P2P</fullName>
                </value>
                <value>
                    <fullName>Access</fullName>
                </value>
                <value>
                    <fullName>Access Mobile</fullName>
                </value>
                <value>
                    <fullName>Account Maintenance</fullName>
                </value>
                <value>
                    <fullName>Account Services</fullName>
                </value>
                <value>
                    <fullName>Address/Contact Updates</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>ATM</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Cards</fullName>
                </value>
                <value>
                    <fullName>Bill_Pay</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Branch Research</fullName>
                </value>
                <value>
                    <fullName>California Fires</fullName>
                </value>
                <value>
                    <fullName>Call Center Research</fullName>
                </value>
                <value>
                    <fullName>Check By Phone</fullName>
                </value>
                <value>
                    <fullName>Checks</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Self</fullName>
                </value>
                <value>
                    <fullName>Check Withdrawal to Third Party</fullName>
                </value>
                <value>
                    <fullName>Close Account</fullName>
                </value>
                <value>
                    <fullName>Compliance</fullName>
                </value>
                <value>
                    <fullName>Consumer</fullName>
                </value>
                <value>
                    <fullName>Consumer Loan</fullName>
                </value>
                <value>
                    <fullName>Consumer Loans</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Credit Card Payment</fullName>
                </value>
                <value>
                    <fullName>Death Claims</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Deposits/Shares</fullName>
                </value>
                <value>
                    <fullName>DMV</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tertiary_Category__c</fullName>
        <label>Tertiary Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Secondary_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A2A/P2P</fullName>
                </value>
                <value>
                    <fullName>A2A Inquiry</fullName>
                </value>
                <value>
                    <fullName>A2A Other</fullName>
                </value>
                <value>
                    <fullName>A2A System Issue</fullName>
                </value>
                <value>
                    <fullName>Account Balance</fullName>
                </value>
                <value>
                    <fullName>ACH - Authorization for Debit</fullName>
                </value>
                <value>
                    <fullName>ACH Maintenance</fullName>
                </value>
                <value>
                    <fullName>ACH Payoff Request</fullName>
                </value>
                <value>
                    <fullName>ACH Stop Payment</fullName>
                </value>
                <value>
                    <fullName>Activate</fullName>
                </value>
                <value>
                    <fullName>AD&amp;D</fullName>
                </value>
                <value>
                    <fullName>Add a Name</fullName>
                </value>
                <value>
                    <fullName>Address &amp; Contact Info</fullName>
                </value>
                <value>
                    <fullName>Address and Contact Information Change</fullName>
                </value>
                <value>
                    <fullName>Address Change</fullName>
                </value>
                <value>
                    <fullName>Amendments</fullName>
                </value>
                <value>
                    <fullName>Application Inquiries</fullName>
                </value>
                <value>
                    <fullName>Application Issues</fullName>
                </value>
                <value>
                    <fullName>Application Request</fullName>
                </value>
                <value>
                    <fullName>Application Status</fullName>
                </value>
                <value>
                    <fullName>Arbitration Opt Out Letters</fullName>
                </value>
                <value>
                    <fullName>ATM/Debit Card Inquiry</fullName>
                </value>
                <value>
                    <fullName>ATM Locations</fullName>
                </value>
                <value>
                    <fullName>Authorization For Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Authorization for Auto Transfer</fullName>
                </value>
                <value>
                    <fullName>Authorization to release</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfer Form</fullName>
                </value>
                <value>
                    <fullName>Automatic Transfers</fullName>
                </value>
                <value>
                    <fullName>Auto Payment</fullName>
                </value>
                <value>
                    <fullName>Dispute</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/UpdateCaseCategoryControllerTest.cls
@isTest
public class UpdateCaseCategoryControllerTest {
static testMethod void testMethod1(){
    list<Case> caselist = new List<Case>();
    		Case cs = new Case();
           cs.Brand__c = 'CFCU';
           cs.Primary_Category__c = 'Shared Branching';
    		cs.Secondary_Category__c ='Servicing'	;
    		cs.Tertiary_Category__c = 'Dispute';
        caselist.add(cs);
    	Case cs1 = new Case();
           cs1.Brand__c = 'CFCU';
           cs1.Primary_Category__c = '-None-';
    	caselist.add(cs1);
    	Case cs2 = new Case();
           cs2.Brand__c = 'CFCU';
           cs2.Primary_Category__c = '';
    	caselist.add(cs2);
    	Case cs3 = new Case();
           cs3.Brand__c = 'CFCU';
           cs3.Primary_Category__c = 'Shared Branching';
    		cs3.Secondary_Category__c ='-None-'	;	
    	caselist.add(cs3);
    	insert caselist;
   Map<string,object> casemap = UpdateCaseCategoriesController.getData(cs.id);
    Map<string,object> casemap1 = UpdateCaseCategoriesController.saveCategories(cs);
     Map<string,object> casemap2 = UpdateCaseCategoriesController.saveCategories(cs1);
      Map<string,object> casemap11 = UpdateCaseCategoriesController.saveCategories(cs2);
      Map<string,object> casemap12 = UpdateCaseCategoriesController.saveCategories(cs3);
    //Map<String, Map<String, List<String>>> casemap2 = UpdateCaseCategoriesController.getPicklistValues('Shared Branching');
    Map<String,List<String>> casemap3 =  UpdateCaseCategoriesController.getDependentOptionsImpl('case', 'Primary_Category__c', 'Secondary_Category__c');
    List<KeyValuePairModel> caselist3 = UpdateCaseCategoriesController.getscOptions('Shared Branching');
    List<KeyValuePairModel> caselist1 =  UpdateCaseCategoriesController.pcOptions();
    List<KeyValuePairModel> caselist2 =  UpdateCaseCategoriesController.gettcOptions('Servicing');
}
}