src/objects/Brand__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Brand</label>
</CustomObject>

src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Branch__c</fullName>
        <label>Assigned Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Episys_Name__c</fullName>
        <label>Episys Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <label>Brand</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CFCU</fullName>
                </value>
                <value>
                    <fullName>Spectrum</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Episys_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used with the &quot;LeadTrigger2 - Episys User ID&quot; trigger to bulk update existing records</description>
        <label>Episys Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Episys_User_ID__c</fullName>
        <label>Episys User ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Episys_User__c</fullName>
        <formula>CreatedBy.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Episys User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Keep__c</fullName>
        <defaultValue>false</defaultValue>
        <description>By pass auto assignment rules and keep ownership of the Lead</description>
        <inlineHelpText>Keep ownership of the Lead and do not allow the assignment rules to route it to a group&apos;s queue.</inlineHelpText>
        <label>Keep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_Required_old__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership Required Old</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Subtype__c</fullName>
        <label>Product Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Product_Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1st Mortgage</fullName>
                </value>
                <value>
                    <fullName>2nd Mortgage</fullName>
                </value>
                <value>
                    <fullName>90 Day Note-Unsecured</fullName>
                </value>
                <value>
                    <fullName>ARM 1/1</fullName>
                </value>
                <value>
                    <fullName>ARM 10/1</fullName>
                </value>
                <value>
                    <fullName>ARM 3/1</fullName>
                </value>
                <value>
                    <fullName>ARM 3/3</fullName>
                </value>
                <value>
                    <fullName>ARM 5/1</fullName>
                </value>
                <value>
                    <fullName>ARM 5/5</fullName>
                </value>
                <value>
                    <fullName>ARM 7/1</fullName>
                </value>
                <value>
                    <fullName>ATM Card</fullName>
                </value>
                <value>
                    <fullName>Auto - Liberty</fullName>
                </value>
                <value>
                    <fullName>Auto - New</fullName>
                </value>
                <value>
                    <fullName>Auto Refinance</fullName>
                </value>
                <value>
                    <fullName>Auto -Used</fullName>
                </value>
                <value>
                    <fullName>Balance Transfer</fullName>
                </value>
                <value>
                    <fullName>Bill Pay</fullName>
                </value>
                <value>
                    <fullName>Bridging</fullName>
                </value>
                <value>
                    <fullName>Business Development SEG</fullName>
                </value>
                <value>
                    <fullName>CFCU Company Guaranteed</fullName>
                </value>
                <value>
                    <fullName>CFCU Disaster Assistance-Level 3</fullName>
                </value>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Credit Card in Repayment</fullName>
                </value>
                <value>
                    <fullName>Credit Cards</fullName>
                </value>
                <value>
                    <fullName>Credit Protection</fullName>
                </value>
                <value>
                    <fullName>Debit Card</fullName>
                </value>
                <value>
                    <fullName>Debt Consolidation</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>DPA Interest Only HELOC</fullName>
                </value>
                <value>
                    <fullName>DPA Texan HELOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>et4ae5__HasOptedOutOfMobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>smagicinteract__SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>temp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>temp</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>false</active>
        <businessProcess>Default</businessProcess>
        <description>record type for all the Branch Users</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/main/default/classes/CreateLeadControllerTest.cls
@isTest
private class CreateLeadControllerTest{
  	@testSetup
	static void setupTestData(){
    	
        test.startTest();
    	Group g1 = new Group(Name='Branch 14 - 1600 Smith Queue', type='Queue');
        insert g1;
  		Episys_User__c eu = new Episys_User__c();
        eu.Episys_ID__c = 1;
        eu.Episys_Name__c = 'test';
        eu.Assigned_Branch__c =14;
        insert eu;
            
    	Lead ld = new Lead(LastName = 'LastName268', Status = 'New',Brand__c = 'CFCU', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, CreatedDate = DateTime.now(), //CreatedById = acc.id,
                       LastModifiedDate = DateTime.now(), smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, 
                       et4ae5__HasOptedOutOfMobile__c = false, Episys_User_ID__c =1, Product_Type__c ='Cards', Product_Subtype__c ='Credit Cards',Episys_Flag__c = false, temp__c = false, LeadSource='PTM');
    	Insert ld; 
    	test.stopTest();
  }
	
    static testMethod void test_FetchLeedData(){
   		test.startTest();
    	String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Lead led = new Lead(Brand__c = 'CFCU',LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, CreatedDate = DateTime.now(), //CreatedById = acc.id,
                       LastModifiedDate = DateTime.now(), smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, 
                       et4ae5__HasOptedOutOfMobile__c = false, Episys_User_ID__c =1, Product_Type__c ='Cards', Product_Subtype__c ='Credit Cards',Episys_Flag__c = false, temp__c = false, LeadSource='PTM');
 
        
        Account acc = new Account(
            RecordTypeID=RecTypeId,
            FirstName='Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678');
    	insert acc;
     	PageReference pageRef = Page.CreateNewLead;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('accountid', acc.id);
    	String uid = UserInfo.getUserId();
        User usr = [Select id, name, alias from User where id=:uid]; 
        
        Episys_User__c euc = new Episys_User__c();
        euc.Alias__c =  usr.alias;
        euc.Assigned_Branch__c = 105;
        euc.Default__c = true;
        euc.Episys_ID__c = 1111;
        euc.Episys_Name__c = 'Test';
	    insert euc;
        
      	Lead l = new Lead();
        CreateNewLeadController controller = new CreateNewLeadController(new ApexPages.StandardController(l)); 
        
        controller.save();       
        controller.leadObject.Product_Type__c = 'Cards';
        controller.save();
        controller.leadObject.Brand__c = 'CFCU';

        controller.SetEpsisUserID();
        
       	controller.save();
	
        List<Lead> ld  =  [SELECT LastName,Status,HasOptedOutOfEmail,IsConverted,IsUnreadByOwner,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,smagicinteract__SMSOptOut__c,Escalated__c,Membership_Required_old__c,Keep__c,et4ae5__HasOptedOutOfMobile__c,Episys_Flag__c,temp__c from Lead];
        System.assertEquals(true,ld.size()>0);
        CreateLeadController obj01 = new CreateLeadController();
        lead leadObj = CreateLeadController.FetchLeedData(acc.id);
        CreateLeadController.LeadInsertUpdate(led,acc.id);
       	test.stopTest();

  	}
  
	static testMethod void test_getDependentOptionsImpl(){
    	List<Lead> ld  =  [SELECT LastName,Status,HasOptedOutOfEmail,IsConverted,IsUnreadByOwner,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,smagicinteract__SMSOptOut__c,Escalated__c,Membership_Required_old__c,Keep__c,et4ae5__HasOptedOutOfMobile__c,Episys_Flag__c,temp__c from Lead];
    	System.assertEquals(true,ld.size()>0);
    	CreateLeadController obj01 = new CreateLeadController();
    	CreateLeadController.getDependentOptionsImpl('test data','test data','test data');
  	}
    
  	static testMethod void test_getMemberAccounts(){
    	List<Lead> ld  =  [SELECT LastName,Status,HasOptedOutOfEmail,IsConverted,IsUnreadByOwner,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,smagicinteract__SMSOptOut__c,Escalated__c,Membership_Required_old__c,Keep__c,et4ae5__HasOptedOutOfMobile__c,Episys_Flag__c,temp__c from Lead];
    	System.assertEquals(true,ld.size()>0);
    	CreateLeadController obj01 = new CreateLeadController();
    	CreateLeadController.getMemberAccounts('test data');
  	}
    
  	static testMethod void test_getEpsysDetails(){
    	List<Lead> ld  =  [SELECT LastName,Status,HasOptedOutOfEmail,IsConverted,IsUnreadByOwner,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,smagicinteract__SMSOptOut__c,Escalated__c,Membership_Required_old__c,Keep__c,et4ae5__HasOptedOutOfMobile__c,Episys_Flag__c,temp__c from Lead];
    	System.assertEquals(true,ld.size()>0);
    	CreateLeadController obj01 = new CreateLeadController();
    	CreateLeadController.getEpsysDetails();
  	}
    
    static testMethod void test_FetchLeedData1(){
   		test.startTest();
    	String RecTypeId= [select Id from RecordType where (Name='Person Account') and (SobjectType='Account')].Id;
        
        Lead led = new Lead(Brand__c = 'CFCU',LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, CreatedDate = DateTime.now(), //CreatedById = acc.id,
                       LastModifiedDate = DateTime.now(), smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, 
                       et4ae5__HasOptedOutOfMobile__c = false, Episys_User_ID__c =1, Product_Type__c ='Cards', Product_Subtype__c ='Credit Cards',Episys_Flag__c = false, temp__c = false, LeadSource='PTM');
 
        
        Account acc = new Account(
            RecordTypeID=RecTypeId,
            FirstName='Test FName',
            LastName='Test LName',
            PersonMailingStreet='test@yahoo.com',
            PersonMailingPostalCode='12345',
            PersonMailingCity='SFO',
            PersonEmail='test@yahoo.com',
            PersonHomePhone='1234567',
            PersonMobilePhone='12345678');
    	insert acc;
     	PageReference pageRef = Page.CreateNewLead;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('accountid', acc.id);
    	String uid = UserInfo.getUserId();
        User usr = [Select id, name, alias from User where id=:uid]; 
        
        Episys_User__c euc = new Episys_User__c();
        euc.Alias__c =  usr.alias;
        euc.Assigned_Branch__c = 105;
        euc.Default__c = true;
        euc.Episys_ID__c = 1111;
        euc.Episys_Name__c = 'Test';
	    insert euc;
        
        Episys_User__c euc1 = new Episys_User__c();
        euc1.Alias__c =  usr.alias;
        euc1.Assigned_Branch__c = 106;
        euc1.Default__c = true;
        euc1.Episys_ID__c = 8147;
        euc1.Episys_Name__c = 'Test RJ';
	    insert euc1;
        
      	Lead l = new Lead();
        CreateNewLeadController controller = new CreateNewLeadController(new ApexPages.StandardController(l)); 
        
        controller.save();       
        controller.leadObject.Product_Type__c = 'Cards';
        controller.save();
        controller.leadObject.Brand__c = 'CFCU';

        controller.SetEpsisUserID();
        
       	controller.save();
	
        List<Lead> ld  =  [SELECT LastName,Status,HasOptedOutOfEmail,IsConverted,IsUnreadByOwner,CreatedDate,CreatedById,LastModifiedDate,LastModifiedById,smagicinteract__SMSOptOut__c,Escalated__c,Membership_Required_old__c,Keep__c,et4ae5__HasOptedOutOfMobile__c,Episys_Flag__c,temp__c from Lead];
        System.assertEquals(true,ld.size()>0);
        CreateLeadController obj01 = new CreateLeadController();
        lead leadObj = CreateLeadController.FetchLeedData(acc.id);
        CreateLeadController.LeadInsertUpdate(led,acc.id);
       	test.stopTest();

  	}
}