src/objects/Canned_Responses__c.object
<CustomObject>
    <fields>
        <fullName>Primary_Lookup_Text__c</fullName>
        <label>Primary Lookup Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Secondary_Lookup_Text__c</fullName>
        <label>Secondary Lookup Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tertiary_Lookup_Text__c</fullName>
        <label>Tertiary Lookup Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Canned Responses</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>Canned Responses Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Canned Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRExtnControllerTest.cls
@isTest
public class CRExtnControllerTest{
    
    public static testMethod void CRExtnControllerMethodTest(){
        
        List<Canned_Responses__c> crLst = new List<Canned_Responses__c>();
        Canned_Responses__c cr = new Canned_Responses__c();        
            cr.Primary_Lookup_Text__c  = 'Test';
            cr.Secondary_Lookup_Text__c = 'Test';
            cr.Tertiary_Lookup_Text__c = 'Test';
            crLst.add(cr);
            insert crLst;
    
        ApexPages.StandardController sc = new ApexPages.StandardController(cr);
        CRExtnController controller = new CRExtnController(sc);
    }
}