src/objects/CFCU_Mastercard_Alerts__c.object
<CustomObject>
    <description>masterCard Alerts</description>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Number__c</fullName>
        <label>Member Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>MasterCard Alerts</label>
    <nameField>
        <displayFormat>MCA{00000000}</displayFormat>
        <label>Mastercard_Alerts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MasterCard Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CardDetailsTest.cls
@isTest
public class CardDetailsTest {
	  static testMethod void testMethod1(){
	  	  PageReference pageRef = Page.MasterCardAlerts;
	  	   Test.setCurrentPage(pageRef);       
	  	    ApexPages.currentPage().getParameters().put('card', 'ABC');
        ApexPages.currentPage().getParameters().put('account', '1111');  
	  	 CFCU_Mastercard_Alerts__c obj = new CFCU_Mastercard_Alerts__c();
	  	 obj.Member_Number__c = 'ABC';
	  	 obj.Card_Number__c = '1111';
	  	 CardDetails controller = new CardDetails(new ApexPages.StandardController(obj)); 
	  	List<CFCU_Mastercard_Alerts__c> accList = 	controller.accList; 
	  
	  }
}