src/objects/CFCU_Mastercard_Alerts__c.object
<CustomObject>
    <description>masterCard Alerts</description>
    <fields>
        <fullName>Card_Number__c</fullName>
        <label>Card Number</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Number__c</fullName>
        <label>Member Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OdsKey__c</fullName>
        <label>OdsKey</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>emailAddress__c</fullName>
        <label>emailAddress</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>merchantname__c</fullName>
        <label>merchantname</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>transAmount__c</fullName>
        <label>transAmount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>transAmtAlert__c</fullName>
        <label>transAmtAlert</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>transCountry__c</fullName>
        <description>Country where transaction originated</description>
        <label>transCountry</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>MasterCard Alerts</label>
    <nameField>
        <displayFormat>MCA{00000000}</displayFormat>
        <label>Mastercard_Alerts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MasterCard Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CardDetails.cls
public class CardDetails{
    
    
    
    
    
    public List<CFCU_Mastercard_Alerts__c> accList{    get {

                            List<AggregateResult> countResult =[select Count(Id) from CFCU_Mastercard_Alerts__c  where Card_Number__c =: card and Member_Number__c =: account ];
                         integer count = (Integer)  countResult [0].get('expr0');
                        
                            TotalPages  = count / PageSize  ;
                         if(TotalPages  * PageSize  < count )
                         {
                         TotalPages   = TotalPages   + 1;
                         }
                         integer offsetNumber = ((PageSize ) * (CurrentPageNumber - 1) );
                         
                            List<CFCU_Mastercard_Alerts__c>   accList1=[select OdsKey__c,transCountry__c,emailAddress__c,FirstName__c,LastName__c,merchantname__c,Card_Number__c,Name,Member_Number__c,transAmount__c, transAmtAlert__c from CFCU_Mastercard_Alerts__c where Card_Number__c =: card and Member_Number__c =: account order by CreatedDate,Card_Number__c  limit:PageSize  offset: offsetNumber];
                          
                          return accList1;    
                        }
    set;}
    
    
  
    
    public integer CurrentPageNumber {get;set;}
    
    public string card {get;set;}
    public string account {get;set;}
    

    
    public integer PageSize {get;set;}
    
        public integer TotalPages {get;set;}

     public CardDetails(ApexPages.StandardController crt)
    {
         CurrentPageNumber = 1;
         PageSize  = 20;
         card =    ApexPages.currentPage().getParameters().get('card');
         account=    ApexPages.currentPage().getParameters().get('account');

    }
    



}