src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Branch__c</fullName>
        <label>Assigned Branch</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Episys_Name__c</fullName>
        <label>Episys Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Episys_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used with the &quot;LeadTrigger2 - Episys User ID&quot; trigger to bulk update existing records</description>
        <label>Episys Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Episys_User_ID__c</fullName>
        <label>Episys User ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Episys_User__c</fullName>
        <formula>CreatedBy.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Episys User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Keep__c</fullName>
        <defaultValue>false</defaultValue>
        <description>By pass auto assignment rules and keep ownership of the Lead</description>
        <inlineHelpText>Keep ownership of the Lead and do not allow the assignment rules to route it to a group&apos;s queue.</inlineHelpText>
        <label>Keep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_Required_old__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership Required Old</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Accounts/Shares</fullName>
                </value>
                <value>
                    <fullName>Cards</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Insurance</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Mortgage</fullName>
                </value>
                <value>
                    <fullName>Vehicle Lending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>et4ae5__HasOptedOutOfMobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>smagicinteract__SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>temp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>temp</label>
        <type>Checkbox</type>
    </fields>
    <recordTypes>
        <fullName>Branch</fullName>
        <active>false</active>
        <businessProcess>Default</businessProcess>
        <description>record type for all the Branch Users</description>
        <label>Branch</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/OpenHours__c.object
<CustomObject>
    <fields>
        <fullName>LeadId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadId</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Open_Lead_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Open Hours</label>
    <nameField>
        <label>OpenLeadHours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LeadBusinessHoursTriggerTest.cls
@isTest
public class LeadBusinessHoursTriggerTest {
	static testMethod void LeadBusinessHoursTriggerTest(){
		test.StartTest();
		 	
		
      
    	Group g1 = new Group(Name='Branch 14 - 1600 Smith Queue', type='Queue');
            insert g1;
        
      /*  Lead_Queue__c lq = new Lead_Queue__c();
        lq.Episys_User_Branch_Name__c = '14 1600 Smith';
        lq.Lead_Queue_Name__c = 'Branch 14 - 1600 Smith Queue';
        insert lq;*/
        
         Episys_User__c eu = new Episys_User__c();
             eu.Episys_ID__c = 1;
             eu.Episys_Name__c = 'test';
             eu.Assigned_Branch__c =14;
        insert eu;
            
            
              Lead newlead = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, 
                       smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                temp__c = false, Episys_User_ID__c= 1,LeadSource = 'Other', Product_Type__c ='Cards');
         Lead newlead1 = new Lead(LastName = 'LastName268', Status = 'New', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, 
                       smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                temp__c = false, Episys_User_ID__c= 1,LeadSource = 'Branch Walk in', Product_Type__c ='Cards');
        Lead newlead2 = new Lead(LastName = 'LastName269', Status = 'Prospect Considering', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, 
                       smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                temp__c = false, Episys_User_ID__c= 1,LeadSource = 'Branch Walk in', Product_Type__c ='Cards');
         Lead newlead3 = new Lead(LastName = 'LastName268', Status = 'Prospect Considering', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, 
                       smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                temp__c = false, Episys_User_ID__c= 1033,LeadSource = 'Branch Walk in', Product_Type__c ='Cards');
         Lead newlead4 = new Lead(LastName = 'LastName270', Status = 'Closed - Converted', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, 
                       smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false,
                                temp__c = false, Episys_User_ID__c= 1033, LeadSource = 'Branch Walk in', Product_Type__c ='Cards');
        
    	Insert newlead; 
        Insert newlead1;
        Insert newlead2;
        Insert newlead3;
        Insert newlead4;
        try{
	        newlead4.LastName = 'Test'  ;
	        Update newlead4;
	        system.assert(true,'Lead fields are read only for Closed Leads.');
        }
        catch(Exception e)
        {
        String message = e.getMessage();
         system.assert(message.contains('Lead fields are read only for Closed Leads.'), 'message=' + message);

        }
    	OpenHours__c olc = new OpenHours__c();
    	olc.leadid__c = newlead.id;
    	Insert olc; 
		
		OpenLeadBusinessHours ol = new OpenLeadBusinessHours();
		ol.execute(null);
		
		test.StopTest();		
	}
}