src/objects/Episys_User__c.object
<CustomObject>
    <fields>
        <fullName>Alias__c</fullName>
        <label>Alias</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Episys_ID__c</fullName>
        <externalId>true</externalId>
        <label>Episys ID</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Episys User</label>
    <nameField>
        <displayFormat>EU-{0000}</displayFormat>
        <label>Episys User Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episys Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/AddressChangeController.cls
public class AddressChangeController {
	
	    
   // ---------------------Get data to pass in Address Change Flow..................//       	
@AuraEnabled
    public static Map<string, string> GetAllData(string accid)
    {
		 string FlowURL;
         Map<string,string> strMap = new  Map<string,string>();
         string source;
         boolean SendEmail=false;
        
        // --------------------- Get Flow URL from Custom Settings..................//   
        AddressChangeConfigurations__c acc = AddressChangeConfigurations__c.getValues('Primary');
		
		if(acc.FlowURL__c != null){
			FlowURL = acc.FlowURL__c;			
		}
		
		Account acct = [SELECT id, Name, SSN_TIN_Encrypted__pc from Account where id =: accid limit 1];
		       
        strMap.put('FlowURL',FlowURL);
        strMap.put('UserId',UserInfo.getUserId());
        strMap.put('MemberName',acct.Name);
        strMap.put('SSN',acct.SSN_TIN_Encrypted__pc);

        User currentUser = [SELECT id,alias from user where Id =: UserInfo.getUserId()];
        List<Episys_User__c> EpisysUser = [SELECT id,Alias__c,Episys_ID__c from Episys_User__c where Alias__c =: currentUser.alias limit 1];
        if(EpisysUser.size() > 0){
            strMap.put('EpisysId',String.Valueof(EpisysUser[0].Episys_ID__c));
        }
        else{
            strMap.put('EpisysId','');
        }

        return strMap; 
    }
            	
   
    
}