src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Open_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Open Hours</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>OpenHours__c.LeadId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OpenHours__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/OpenHours__c.object
<CustomObject>
    <fields>
        <fullName>LeadId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadId</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Open_Lead_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Hours__c</fullName>
        <label>Open Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Open Hours</label>
    <nameField>
        <label>OpenLeadHours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpenLeadHours__c.object
<CustomObject>
    <fields>
        <fullName>LeadId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadId</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Open Lead Hours</relationshipLabel>
        <relationshipName>Open_Lead_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Hours__c</fullName>
        <label>Open Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Open Lead Hours</label>
    <nameField>
        <label>OpenLeadHours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Lead Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/classes/UpdateLeadBusinessHours.cls
global class UpdateLeadBusinessHours  implements Database.Batchable<sObject>  {
	
	global datetime startdate {get;set;}
	global datetime enddate {get;set;}
	
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator('select Id, status, CreatedDate, LastModifiedDate from Lead where CreatedDate >= ' + string.valueof(startdate).replace(' ','T') + '.000+0000 and  CreatedDate <= ' + string.valueof(enddate).replace(' ','T') + '.000+0000  '); 
    }
   
    global void execute(Database.BatchableContext BC,list<Lead> Leads)
    {
       List<OpenHours__c> openHours = new List<OpenHours__c>();

		businessHours bhours = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
		string bh = bhours.id;
		
		for(Lead lead: Leads){
			OpenHours__c obj = new OpenHours__c();
		    obj.LeadId__c = lead.Id;
		    Long hours = 0;
		    
		    if(lead.status == 'Closed')
		    {
		        hours = BusinessHours.diff(bh,lead.CreatedDate , lead.LastModifiedDate);        
		    }   
		    else {
		         hours = BusinessHours.diff(bh,lead.CreatedDate , system.now());        
		    }
		    obj.Open_Hours__c = hours/3600000;
		    openHours.add(obj);    
		}
		insert openHours;
	/*	
		    list<string> bIds = new List<string>();
		   for(OpenLeadHours__c item : openHours ){
		   		bIds.add(item.id);
		   }
		    
		    
		List<OpenLeadHours__c> leadhours = [select Id, LeadId__c from OpenLeadHours__c where id in: bIds ];
		List<Lead> lstLeads = new List<Lead>();
		for(OpenLeadHours__c h : leadhours){
		    Lead objLead = new Lead();
		    objLead.Id = h.LeadId__c;
		    objLead.BusinessHours__c = h.Id;
		    lstLeads.add(objLead);
		}
		update lstLeads;*/ 
    }
 
    global void finish(Database.BatchableContext BC)
    {
     
    }
}