src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Open_Hours__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Open Hours</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Id</field>
                <operation>equals</operation>
                <valueField>OpenHours__c.LeadId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>OpenHours__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/OpenHours__c.object
<CustomObject>
    <fields>
        <fullName>LeadId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadId</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Open_Lead_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Hours__c</fullName>
        <label>Open Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Open Hours</label>
    <nameField>
        <label>OpenLeadHours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpenLeadBusinessHours.cls
public class OpenLeadBusinessHours implements Schedulable 
{ 
    public void execute(SchedulableContext sc) 
    { 
      List<OpenHours__c>  listLead = [select Id,CreatedDate,Leadid__r.CreatedDate,Leadid__r.Status 
      		from OpenHours__c where Leadid__r.Status != 'Closed' Order by CreatedDAte DESC];
      businessHours   businessHours1 = [SELECT Id FROM BusinessHours WHERE IsDefault=true];
      
      for(OpenHours__c leaditem : listLead)
      {  
          
              if(leaditem.leadid__C != null)
              {
	              string bh = businessHours1.id;
	              Long hours = BusinessHours.diff(bh,leaditem.Leadid__r.CreatedDate , system.now());  
	             
	              leaditem.Open_Hours__c = hours/3600000;
              }                     
          
      }
      update listLead;
    } 
}