src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Episys_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used with the &quot;LeadTrigger2 - Episys User ID&quot; trigger to bulk update existing records</description>
        <label>Episys Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Escalated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Escalated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Keep__c</fullName>
        <defaultValue>false</defaultValue>
        <description>By pass auto assignment rules and keep ownership of the Lead</description>
        <inlineHelpText>Keep ownership of the Lead and do not allow the assignment rules to route it to a group&apos;s queue.</inlineHelpText>
        <label>Keep</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Membership_Required_old__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Membership Required Old</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>et4ae5__HasOptedOutOfMobile__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mobile Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>smagicinteract__SMSOptOut__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SMS Opt Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>temp__c</fullName>
        <defaultValue>false</defaultValue>
        <label>temp</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Staging/src/main/default/classes/UpdateLeadBusinessHoursTest.cls
@isTest
public class UpdateLeadBusinessHoursTest
{	
	static testMethod void UpdateLeadBusinessHoursTest1(){
		test.StartTest();
		
		Lead newlead = new Lead(LastName = 'LastName268', Status = 'Open', HasOptedOutOfEmail = false, IsConverted = false, IsUnreadByOwner = false, 
                       smagicinteract__SMSOptOut__c = false, Escalated__c = false, Membership_Required_old__c = false, Keep__c = false, et4ae5__HasOptedOutOfMobile__c = false, Episys_Flag__c = false, temp__c = false);
    	Insert newlead; 
    	system.debug('lstLeads1===' + newlead);
        
    	UpdateLeadBusinessHours obj = new UpdateLeadBusinessHours();
        obj.startdate = system.now().adddays(-10);
        obj.enddate = system.now().adddays(1);
    	
        
    	Database.executeBatch(obj,1000);
		
		test.StopTest();		
	}		
}