src/objects/NA_Deposit__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Financial_Instituition__c</fullName>
        <label>Financial_Instituition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chevron Federal Credit Union</fullName>
                </value>
                <value>
                    <fullName>Spectrum Credit Union</fullName>
                </value>
                <value>
                    <fullName>Bank of America</fullName>
                </value>
                <value>
                    <fullName>Chase Bank</fullName>
                </value>
                <value>
                    <fullName>Wells Fargo</fullName>
                </value>
                <value>
                    <fullName>Citibank</fullName>
                </value>
                <value>
                    <fullName>US Bank</fullName>
                </value>
                <value>
                    <fullName>Capital One</fullName>
                </value>
                <value>
                    <fullName>Ally</fullName>
                </value>
                <value>
                    <fullName>USAA</fullName>
                </value>
                <value>
                    <fullName>Other Credit Union</fullName>
                </value>
                <value>
                    <fullName>Other Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Spectrum Federal Credit Union</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Needs_Assessment__c</fullName>
        <label>Needs_Assessment</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipLabel>NA_Deposits</relationshipLabel>
        <relationshipName>NA_Deposits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checking</fullName>
                </value>
                <value>
                    <fullName>Savings</fullName>
                </value>
                <value>
                    <fullName>Certificate of Deposit (CD)</fullName>
                </value>
                <value>
                    <fullName>Money Market Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NA_Deposit</label>
    <nameField>
        <label>NA_Deposits Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA_Deposits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/NA_Membership_Referral_Questions__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <label>Age</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Needs_Assessment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Needs Assessment</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipLabel>NA_Membership Referral Questions</relationshipLabel>
        <relationshipName>NA_Membership_Referral_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Want_to_Refer_Membership__c</fullName>
        <label>Want to Refer Membership</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Prefer Not to Answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NA_Membership Referral Question</label>
    <nameField>
        <label>Membership Referral Questions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA_Membership Referral Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/NA_Other_Existing_Loans__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financial_Institution__c</fullName>
        <label>Financial  Institution</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chevron Federal Credit Union</fullName>
                </value>
                <value>
                    <fullName>Spectrum Credit Union</fullName>
                </value>
                <value>
                    <fullName>Bank of America</fullName>
                </value>
                <value>
                    <fullName>Chase Bank</fullName>
                </value>
                <value>
                    <fullName>Wells Fargo</fullName>
                </value>
                <value>
                    <fullName>Citibank</fullName>
                </value>
                <value>
                    <fullName>US Bank</fullName>
                </value>
                <value>
                    <fullName>Capital One</fullName>
                </value>
                <value>
                    <fullName>Ally</fullName>
                </value>
                <value>
                    <fullName>USAA</fullName>
                </value>
                <value>
                    <fullName>Other Credit Union</fullName>
                </value>
                <value>
                    <fullName>Other Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Spectrum Federal Credit Union</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Needs_Assessment__c</fullName>
        <label>Needs Assessment</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipLabel>NA_Other_Existing_Loans</relationshipLabel>
        <relationshipName>NA_Other_Existing_Loans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Type_of_Loan__c</fullName>
        <label>Type of Loan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home Equity</fullName>
                </value>
                <value>
                    <fullName>Personal Line of Credit</fullName>
                </value>
                <value>
                    <fullName>RV/Boat</fullName>
                </value>
                <value>
                    <fullName>Student/College</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>NA_Other_Existing_Loan</label>
    <nameField>
        <label>Other Loans</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NA_Other_Existing_Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Staging/src/main/default/classes/CollectionsInLightningCls.cls
public class CollectionsInLightningCls 
{
	@AuraEnabled
	public static Map<String, Map<String, List<String>>> getPicklistValues(String objpicklistFieldsMap)
	{
        System.Debug('objpicklistFieldsMap Value' + objpicklistFieldsMap);
		Map<String, List<String>> objPickmap = (Map<String, List<String>>)JSON.deserialize(objpicklistFieldsMap, Map<String, List<String>>.class);
		system.debug('objpickmap ' + objPickmap);
		 
		Map<String, Map<String, List<String>>> objFieldPicklistMap = new Map<String, Map<String, List<String>>>();
		List<String> sobjectslist = new List<String>(objPickmap.keySet());
		Schema.DescribeSobjectResult[] results = Schema.describeSObjects(sobjectslist);
		Map<String, List<String>> fieldOptionsMap;
		system.debug('results---' + results);
		for(Schema.DescribeSObjectResult result : results)
		{
			fieldOptionsMap = new Map<String, List<String>>();
			 system.debug('result123---' + result);
			Schema.sObjectType objType = result.getSObjectType();
			 
			Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
			map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap();
			List<String> objFieldlist = objPickmap.get(result.getName());
			system.debug('objname ' + result.getName());
			system.debug('list of fields ' + objFieldlist);
			for(String fld : objFieldlist)
			{
				system.debug('fields ' + fld);
				List<String > allOpts = new list<String>();
				list<Schema.PicklistEntry> values =
				fieldMap.get(fld).getDescribe().getPickListValues();
				 
				for (Schema.PicklistEntry a : values)
				{
					allOpts.add(a.getValue());
				}
				fieldOptionsMap.put(fld, allOpts);
			}
			
			objFieldPicklistMap.put(result.getName(), fieldOptionsMap);
		}
		return objFieldPicklistMap;
	}
	
	@AuraEnabled
	public static list<NA_Other_Existing_Loans__c> getExistingLoans(String AssessmentId)
	{
		list<NA_Other_Existing_Loans__c> otherExistingLoans = new list<NA_Other_Existing_Loans__c>();
		otherExistingLoans = [select id, Balance__c, End_Date__c, Financial_Institution__c, Needs_Assessment__c, Rate__c, Type_of_Loan__c 
                        from NA_Other_Existing_Loans__c where Needs_Assessment__c =: AssessmentId];
                        
		return otherExistingLoans;		
	}
	
	@AuraEnabled
	public static list<NA_Membership_Referral_Questions__c> getMembershipLoans(String AssessmentId)
	{
		list<NA_Membership_Referral_Questions__c> loans = new list<NA_Membership_Referral_Questions__c>();
		loans = [select id, Age__c, Name__c, Needs_Assessment__c, Want_to_Refer_Membership__c 
                        from NA_Membership_Referral_Questions__c where Needs_Assessment__c =: AssessmentId];
                        
		return loans;		
	}
	
	@AuraEnabled
	public static list<NA_Deposit__c> GetDepositData(String AssessmentId)
	{
		list<NA_Deposit__c> deposits = new list<NA_Deposit__c>();
		deposits = [select id, Balance__c, Financial_Instituition__c, Needs_Assessment__c, Rate__c, Type__c 
                        from NA_Deposit__c where Needs_Assessment__c =: AssessmentId];
                        
		return deposits;		
	}
	
    
	@AuraEnabled    
	public static Map<String, List<KeyValuePairModelInt>> getYearPickList()
	{   
        Map<String, List<KeyValuePairModelInt>> options = new Map<String, List<KeyValuePairModelInt>>();
        KeyValuePairModelInt pair = new KeyValuePairModelInt();
        List<KeyValuePairModelInt> lstPair = new List<KeyValuePairModelInt>();
		pair.Text = '--None--';
		pair.Value = 0;
		        
        lstPair.add(pair);
        
        for (Integer i = System.Today().year() + 1; i < System.Today().year() + 31; i++) 
        {
            pair = new KeyValuePairModelInt();
            pair.Text = string.valueof(i);
            pair.Value = i;
            lstPair.add(pair);            
    	}
        options.put('data', lstPair);
        return options;		
	}
	
	    
	public class KeyValuePairModelInt
	{
		@AuraEnabled    
		public string Text {get;set;}
		@AuraEnabled    
		public Integer Value {get;set;}
		
	} 
}