src/objects/NA_Housing__c.object
<CustomObject>
    <description>Needs Assessment Section - Housing</description>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <inlineHelpText>If own, what is your current balance?</inlineHelpText>
        <label>Current Balance</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <inlineHelpText>If own, who is your current mortgage lender?</inlineHelpText>
        <label>Current Lender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Asked</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Declined to Answer</fullName>
                </value>
                <value>
                    <fullName>Lender A</fullName>
                </value>
                <value>
                    <fullName>Lender B</fullName>
                </value>
                <value>
                    <fullName>Lender C</fullName>
                </value>
                <value>
                    <fullName>Lender D</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Rate__c</fullName>
        <inlineHelpText>If own, what is your current rate?</inlineHelpText>
        <label>Current Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>If own, what is the end date of the mortgage?</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NA__c</fullName>
        <label>NA</label>
        <referenceTo>Needs_Assesment__c</referenceTo>
        <relationshipName>Needs_Assessment_Sections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>NA Life Events Housing</label>
    <nameField>
        <displayFormat>NAS01{000000000}</displayFormat>
        <label>Section Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NA Life Events Housing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Staging/src/main/default/classes/naHousingExtension.cls
public class naHousingExtension {
    
     NA_Housing__c nhs5;
    Needs_Assesment__c nas = new Needs_Assesment__c();
    
    public string firstPage {get;set;}
     public string accId {get;set;}
    NA_Housing__c nah = new NA_Housing__c();
     public  list<NA_Housing__c> nahouse = new list<NA_Housing__c>(); 
   
     public naHousingExtension(ApexPages.StandardController crt){
        nhs5 = (NA_Housing__c)crt.getRecord();
         
        firstPage = System.currentPageReference().getParameters().get('firstPage'); 
        if(firstPage == 'True'){
            accId = System.currentPageReference().getParameters().get('acctId');
        }
          accId = System.currentPageReference().getParameters().get('acctId');
           System.debug('accId is::::'+accId); 
         
         System.debug('current page is::::'+firstPage); 
    }
    
    
    
    public NA_Housing__c getnah(){
         NA_Housing__c nhs1 = new NA_Housing__c();
        firstPage = System.currentPageReference().getParameters().get('firstPage'); 
        if(firstPage == 'True'){
            accId = System.currentPageReference().getParameters().get('acctId');
        }
           
        list<Needs_Assesment__c> naList = new list<Needs_Assesment__c>();
        naList = [select id, member__c from Needs_Assesment__c where member__r.id=:'0017A00000Nxdfk'];
       
         System.debug('accid  check:::'+accId);
        
        set<String> naIdSet = new set<String>();
        
        if(naList.size()>0){
        
         for(Needs_Assesment__c var: naList){
           naIdSet.add(var.id);
        }
        
         nahouse = [select id, Current_Balance__c, Current_Rate__c, End_Date__c, Current_Lender__c, NA__c,  LastModifiedDate from NA_Housing__c where NA__r.id =:naIdSet ORDER by LastModifiedDate desc];
        
            
        nah.NA__c = nahouse[0].Id;
        nah.Current_Balance__c = nahouse[0].Current_Balance__c;
        nah = nahouse[0];
        }
        return nah;   
         
    }
}