src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>LEAV_AnticipateFinance__c</fullName>
        <label>LEAV_AnticipateFinance</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Prefer Not to Answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEAV_ContactPreferences__c</fullName>
        <label>LEAV_ContactPreferences</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>LEAV_CurrentBalance__c</fullName>
        <label>LEAV_CurrentBalance</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LEAV_CurrentLoanProvider__c</fullName>
        <description>This field stores the value of &quot;If yes, Who is your current auto/vehicle loan provider?	&quot; on the &quot;Auto/Vehicle&quot; tab.</description>
        <label>LEAV_CurrentLoanProvider</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chevron Federal Credit Union</fullName>
                </value>
                <value>
                    <fullName>Spectrum Credit Union</fullName>
                </value>
                <value>
                    <fullName>Bank of America</fullName>
                </value>
                <value>
                    <fullName>Chase Bank</fullName>
                </value>
                <value>
                    <fullName>Wells Fargo</fullName>
                </value>
                <value>
                    <fullName>Citibank</fullName>
                </value>
                <value>
                    <fullName>US Bank</fullName>
                </value>
                <value>
                    <fullName>Capital One</fullName>
                </value>
                <value>
                    <fullName>Ally</fullName>
                </value>
                <value>
                    <fullName>USAA</fullName>
                </value>
                <value>
                    <fullName>Other Credit Union</fullName>
                </value>
                <value>
                    <fullName>Other Financial Institution</fullName>
                </value>
                <value>
                    <fullName>Dealer/Manufacturer</fullName>
                </value>
                <value>
                    <fullName>Spectrum Federal Credit Union</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEAV_CurrentRate__c</fullName>
        <label>LEAV_CurrentRate</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LEAV_Current__c</fullName>
        <label>LEAV_Current</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Prefer Not to Answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEAV_EndDateLoan__c</fullName>
        <label>LEAV_EndDateLoan</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEAV_Last_Updated_On__c</fullName>
        <label>LE Auto/Vehicle Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LEAV_PlanDate__c</fullName>
        <label>LEAV_PlanDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LEAV_PlanningToBuy__c</fullName>
        <label>LEAV_PlanningToBuy</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Prefer Not to Answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REC_LEAV_1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Loan</label>
        <type>Checkbox</type>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Staging/src/main/default/classes/NA_AutoVehicleController.cls
public class NA_AutoVehicleController
{
    public NA_AutoVehicleController(){
    
    }

    public string script{get;set;}
    public Account AccountC{get;set;}
    
    public string NA_id {get;set;}
    public string accId2 { get; set; }

    public NeedAssessmentController parentController {get;set;}

    
    //public Needs_Assesment__c ExpiredValue {get;set;}

    Needs_Assesment__c  lnao_New;
    
     public Needs_Assesment__c  getlnao_New(){
         
     
           setObjects();
     
        
        return lnao_New;
    }
    
    
   
    public void setlnao_New(Needs_Assesment__c  val){
        lnao_New = val;
    }
    

    public void setObjects(){
        
        
        
        //IsExpired = false;    
        accId2 = AccountC.Id;
       
        list<Needs_Assesment__c> naother = [select id,LEAV_AnticipateFinance__c,    
                                            LEAV_ContactPreferences__c,
                                            LEAV_Current__c,
                                            LEAV_CurrentBalance__c,
                                            LEAV_CurrentLoanProvider__c,
                                            LEAV_CurrentRate__c,
                                            LEAV_EndDateLoan__c,
                                            LEAV_PlanDate__c,
                                            LEAV_PlanningToBuy__c,
                                            LEAV_Last_Updated_On__c,
                                            REC_LEAV_1__c 
                                            from Needs_Assesment__c where 
                                            member__c =:accId2 ORDER by LastModifiedDate desc];
        if (naother.size() > 0)
        {
            NA_id = naother[0].Id;
            lnao_New = naother [0];

        }
        else
        {
  
            lnao_New = new Needs_Assesment__c();
            //ExpiredValue = new Needs_Assesment__c();
        }
    }
    
    
    
    
 
    public void SubmitAutoVehicleForm()
    {

     
        //If(lnao_New.LEAV_AnticipateFinance__c != null || lnao_New.LEAV_ContactPreferences__c != null || lnao_New.LEAV_Current__c != null ||     lnao_New.LEAV_CurrentBalance__c != null || lnao_New.LEAV_CurrentLoanProvider__c != null || lnao_New.LEAV_CurrentLoanProvider__c != null || lnao_New.LEAV_CurrentRate__c != null || lnao_New.LEAV_EndDateLoan__c != null || lnao_New.LEAV_PlanDate__c != null || lnao_New.LEAV_PlanningToBuy__c != null || lnao_New.REC_LEAV_1__c != null   )
                
        {
            
                 Needs_Assesment__c  nao_tobeinserted = new Needs_Assesment__c  ();
                                     nao_tobeinserted.Id = lnao_New.Id;
                    
                    nao_tobeinserted.LEAV_AnticipateFinance__c = lnao_New .LEAV_AnticipateFinance__c;
                    nao_tobeinserted.LEAV_ContactPreferences__c = lnao_New.LEAV_ContactPreferences__c;
                    
                    nao_tobeinserted.LEAV_Current__c = lnao_New .LEAV_Current__c;
                    nao_tobeinserted.LEAV_CurrentBalance__c = lnao_New.LEAV_CurrentBalance__c;
                    nao_tobeinserted.LEAV_CurrentLoanProvider__c = lnao_New.LEAV_CurrentLoanProvider__c;
                    nao_tobeinserted.LEAV_CurrentRate__c = lnao_New.LEAV_CurrentRate__c;
                    nao_tobeinserted.LEAV_EndDateLoan__c = lnao_New.LEAV_EndDateLoan__c;
                    
                    nao_tobeinserted.LEAV_PlanDate__c = lnao_New.LEAV_PlanDate__c;
                    nao_tobeinserted.LEAV_PlanningToBuy__c = lnao_New.LEAV_PlanningToBuy__c;
                    nao_tobeinserted.REC_LEAV_1__c = lnao_New.REC_LEAV_1__c;
                    
                    

                    if(nao_tobeinserted.Id == null)
                    {
                    nao_tobeinserted.Member__c = accId2 ;
                    }
                    nao_tobeinserted.LEAV_Last_Updated_On__c  = system.today();
                   
                        upsert  nao_tobeinserted;
                        
                        script = '1';
            
    
       }
                RefreshParent();
    }
    
   
    
     public void resetscript()
     {
        script = '';
     }
  
     public void RefreshParent(){
             
        
           
           parentController.RefreshAccount();
         


           parentController.GetAutoVehicleTabClass();
     }
    
   }