src/objects/Needs_Assesment__c.object
<CustomObject>
    <fields>
        <fullName>College_Plan__c</fullName>
        <label>College Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Plan</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>College_Timeframe__c</fullName>
        <label>College Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>College__c</fullName>
        <label>College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Do_you_Rent_or_Own__c</fullName>
        <description>This fields stores the value of &quot;Do you own or rent your home?&quot; on the &quot;Housing&quot; tab.</description>
        <inlineHelpText>Do you own or rent your home?</inlineHelpText>
        <label>LEHS Rent or Own</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Own</fullName>
                </value>
                <value>
                    <fullName>Own - Paid Off</fullName>
                </value>
                <value>
                    <fullName>Rent</fullName>
                </value>
                <value>
                    <fullName>Prefer Not To Answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Home_Improvement_Plan__c</fullName>
        <label>Home Improvement Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Plan</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Home_Improvement_Timeframe__c</fullName>
        <label>Home Improvement Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Home_Improvement__c</fullName>
        <label>Home Improvement</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Current_Lender__c</fullName>
        <description>This field stores the value of &quot;If own, who is your current lender?&quot; on the &quot;Housing&quot; tab.</description>
        <inlineHelpText>If own, who is your current mortgage lender?</inlineHelpText>
        <label>LEHS Current Lender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_LEHS_Current_Lender</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Have_Realtor__c</fullName>
        <inlineHelpText>If planning to purchase a house, do you have a realtor?</inlineHelpText>
        <label>LEHS Have Realtor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Planning_to_Purchase__c</fullName>
        <inlineHelpText>Are you planning to purchase a house?</inlineHelpText>
        <label>LEHS Planning to Purchase</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Purchase_When__c</fullName>
        <inlineHelpText>If planning to purchase a house, when?</inlineHelpText>
        <label>LEHS Purchase When</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>LEHS_Type_of_Mortgage__c</fullName>
        <label>LEHS_Type_of_Mortgage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>30 Year Fixed</fullName>
                </value>
                <value>
                    <fullName>20 Year Fixed</fullName>
                </value>
                <value>
                    <fullName>15 Year Fixed</fullName>
                </value>
                <value>
                    <fullName>7/1 ARM 30 Year</fullName>
                </value>
                <value>
                    <fullName>7/1 ARM 15 Year</fullName>
                </value>
                <value>
                    <fullName>5/1 ARM 30 Year</fullName>
                </value>
                <value>
                    <fullName>5/1 ARM 15 Year</fullName>
                </value>
                <value>
                    <fullName>HELOC 10/15 (10 year draw/15 year repayment)</fullName>
                </value>
                <value>
                    <fullName>Fixed Rate 2nd 15 year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Life_Events_Plan__c</fullName>
        <label>Life Events Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Plan</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Life_Events_Timeframe__c</fullName>
        <label>Life Events Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Life_Events__c</fullName>
        <label>Life Events</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical_Plan__c</fullName>
        <label>Medical Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Plan</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical_Timeframe__c</fullName>
        <label>Medical Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Medical__c</fullName>
        <label>Medical</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Needs_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other_Plan__c</fullName>
        <label>Other Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Plan</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Timeframe__c</fullName>
        <label>Other Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <label>Other</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_RV_Boat_Plan__c</fullName>
        <label>Purchase RV/Boat Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Plan</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_RV_Boat_Timeframe__c</fullName>
        <label>Purchase RV/Boat Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Purchase_RV_Boat__c</fullName>
        <label>Purchase RV/Boat</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retirement_New__c</fullName>
        <label>Retirement_New</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Already Retired</fullName>
                </value>
                <value>
                    <fullName>Prefer Not to Answer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retirement_Plan__c</fullName>
        <label>Retirement Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Plan</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retirement_Timeframe__c</fullName>
        <label>Retirement Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Travel_Plan__c</fullName>
        <label>Travel Plan</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Plan</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Travel_Timeframe__c</fullName>
        <label>Travel Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Timeframe</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Travel__c</fullName>
        <label>Travel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>NA_Interest</valueSetName>
        </valueSet>
    </fields>
    <label>Member Connect</label>
    <nameField>
        <displayFormat>NA{000000000}</displayFormat>
        <label>Assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Member Connect</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CollectionsInLightningClsTest.cls
@isTest

private class CollectionsInLightningClsTest
{
	
	static void SetUp(){
		test.StartTest();
	}

	static void TearDown(){
		test.StopTest();
	}
	
	// Test Method: getPicklistValues
	public static testmethod void Test_getPicklistValues(){
		SetUp();
		string objpicklistfieldsmap = '';
		// TODO : Change following Assert Statement
		Account acc = new Account(
           //RecordTypeID=RecTypeId,
           FirstName='Test FName',
           LastName='Test LName',
           PersonMailingStreet='test@yahoo.com',
           PersonMailingPostalCode='12345',
           PersonMailingCity='SFO',
           PersonEmail='test@yahoo.com',
           PersonHomePhone='1234567',
           PersonMobilePhone='12345678');
         
        insert acc;
		Needs_Assesment__c NC;
        NC = new Needs_Assesment__c();
        
		NC.Home_Improvement__c = 'Prefer Not to Answer';
        NC.Home_Improvement_Timeframe__c='3-6 months';
        NC.Home_Improvement_Plan__c= 'Finance';
        NC.College__c= 'Yes';
        NC.College_Timeframe__c= '3-6 months';
        NC.College_Plan__c='Both';
        NC.Medical__c='Prefer Not to Answer';
        NC.Medical_Timeframe__c='3-6 months';
        NC.Medical_Plan__c='Both';
        NC.Purchase_RV_Boat__c='Yes';
        NC.Purchase_RV_Boat_Timeframe__c='3-6 months';
        NC.Purchase_RV_Boat_Plan__c='Savings';
        NC.Retirement_New__c='Yes';
        NC.Retirement_Timeframe__c='3-6 months';
        NC.Retirement_Plan__c='Savings';
        NC.Travel__c= 'Yes';
        NC.Travel_Timeframe__c='3-6 months';
        NC.Travel_Plan__c='Savings';
        NC.Life_Events__c='Prefer Not to Answer';
        NC.Life_Events_Timeframe__c='3-6 months';
        NC.Life_Events_Plan__c='Finance';
        NC.Other__c='Yes';
        NC.Other_Timeframe__c='3-6 months';
        NC.Other_Plan__c= 'Savings';   
        NC.Member__c =  acc.Id;
        insert NC;
        
        CollectionsInLightningCls.getPicklistValues('{"Needs_Assesment__c":["Do_you_Rent_or_Own__c","LEHS_Current_Lender__c","LEHS_Type_of_Mortgage__c","LEHS_Planning_to_Purchase__c","LEHS_Purchase_When__c","LEHS_Have_Realtor__c"]}');
	//	System.Assert(CollectionsInLightningCls.getPicklistValues(objpicklistfieldsmap) != null);
		TearDown();
	}
	// Test Method: getExistingLoans
	public static testmethod void Test_getExistingLoans(){
		SetUp();
		string assessmentid = '';
		// TODO : Change following Assert Statement
		System.Assert(CollectionsInLightningCls.getExistingLoans(assessmentid) != null);
		TearDown();
	}
	// Test Method: getMembershipLoans
	public static testmethod void Test_getMembershipLoans(){
		SetUp();
		string assessmentid = '';
		// TODO : Change following Assert Statement
		System.Assert(CollectionsInLightningCls.getMembershipLoans(assessmentid) != null);
		TearDown();
	}
	// Test Method: GetDepositData
	public static testmethod void Test_GetDepositData(){
		SetUp();
		string assessmentid = '';
		// TODO : Change following Assert Statement
		System.Assert(CollectionsInLightningCls.GetDepositData(assessmentid) != null);
		TearDown();
	}
	// Test Method: getYearPickList
	public static testmethod void Test_getYearPickList(){
		SetUp();
		// TODO : Change following Assert Statement
		System.Assert(CollectionsInLightningCls.getYearPickList() != null);
		TearDown();
	}
}