src/objects/OpenHours__c.object
<CustomObject>
    <fields>
        <fullName>LeadId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadId</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Open_Lead_Hours</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Open_Hours__c</fullName>
        <label>Open Hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Open Hours</label>
    <nameField>
        <label>OpenLeadHours Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Staging/src/main/default/classes/LeadBusinessHoursController.cls
public class LeadBusinessHoursController {
	
		public static String LeadId {get; set;}
		public static OpenHours__c LeadHours {get; set;}
		
		
		public LeadBusinessHoursController(ApexPages.StandardController controller) {
			LeadId = ApexPages.CurrentPage().getparameters().get('id');
			LeadHours = new OpenHours__c();
			LeadHours = [select Id, Open_Hours__c from OpenHours__c where leadId__c =: LeadId limit 1];			
		}		
		
		 @AuraEnabled 
		 public static OpenHours__c GetLeadHours(string LeadId){
		 	LeadHours = new OpenHours__c();
			LeadHours = [select Id, Open_Hours__c from OpenHours__c where leadId__c =: LeadId limit 1];	
			return LeadHours;
		 }
}