src/objects/Person_Account__c.object
<CustomObject>
    <fields>
        <fullName>Name_Type__c</fullName>
        <label>Name Type</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TypeTranslate__c</fullName>
        <label>Relationship</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Person Account</label>
    <nameField>
        <displayFormat>PA-{00000000}</displayFormat>
        <label>Person Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Person Account</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MemberNumberLightningControllerTest.cls
@isTest
private class MemberNumberLightningControllerTest
{
	
	public static testmethod void Test_FetchAccounts(){
		test.StartTest();
		
		Person_Account__c person_account_Obj = new Person_Account__c(CreatedDate = DateTime.now(), LastModifiedDate = DateTime.now(), Name_Type__c = 21, TypeTranslate__c = '001/Primary');
    	Insert person_account_Obj; 
				
		System.Assert(MemberNumberLightningController.FetchAccounts('0000147163') != null);
		test.StopTest();
	}
}