src/objects/Web_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key_Part_2__c</fullName>
        <description>concatenate part2</description>
        <label>Key Part 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Key_Part_3__c</fullName>
        <label>Key Part 3</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Key_Part_4__c</fullName>
        <label>Key Part 4</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WebAddress__c</fullName>
        <label>WebAddress</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>key__c</fullName>
        <description>key to be encoded</description>
        <label>key</label>
        <type>TextArea</type>
    </fields>
    <label>WebService Settings</label>
</CustomObject>

src/classes/Helper.cls
public  class Helper {
  
  public List<Web_Settings__c> WebServiceSetting; 
  
  public Helper()
  {
    WebServiceSetting = Web_Settings__c.getall().values();
  }

public string WebServiceURL 
{
   get
  {
    return WebServiceSetting[0].WebAddress__c;
    
  }
}
public string WebServiceClientOrigin 
{
   get
  {
    return WebServiceSetting[0].Origin__c;
    
  }
}
    
public string WebServiceClientkey 
{
   get
  {
    return WebServiceSetting[0].key__c;
    
  }
} 
    
public string WebServiceClientKeyPart2 
{
   get
  {
    return WebServiceSetting[0].Key_Part_2__c;
    
  }
}
    
public string WebServiceClientKeyPart3 
{
   get
  {
    return WebServiceSetting[0].Key_Part_3__c;
    
  }
}  
    
public string WebServiceClientKeyPart4 
{
   get
  {
    return WebServiceSetting[0].Key_Part_4__c;
    
  }
} 
    
}